### ISSUE TITLE
Incremental backup in local folder

### ISSUE THREAD

**Issue by alindt** [OfflineIMAP/offlineimap#10]
There really should be a way to tell offlineimap to backup to the local repository in an incremental way, no local message deletion whatsoever.

There are real use cases in which all one wants to do is to backup the messages from the server and just keep them locally even if they are deleted on the server (low disk space on server, small quotas, etc.)

Maybe a companion "incremental = true" to the "readonly = true" repository option?

**Comment by nicolas33** [comment]
There is a better feature request in duplicata #47, IMO. Closing this one.
