### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by blurmonk** [OfflineIMAP/offlineimap#103]
Hi

I have started getting bizarre errors like this. This stuff was working just fine couple days ago. I am not sure if any of the Debian updates messed up some python stuff

Folder .Trash [acc:xxxxxxxxxx]:
 ERROR: ERROR in syncfolder for xxxxxxx folder .Trash: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/accounts.py", line 407, in syncfolder
    statusfolder.cachemessagelist()
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/LocalStatusSQLite.py", line 187, in cachemessagelist
    labels = set([lb.strip() for lb in row[3].split(',') if len(lb.strip()) > 0])
AttributeError: 'NoneType' object has no attribute 'split'

-----------
'NoneType' object has no attribute 'split'
ERROR: ERROR in syncfolder for xxxxxxx folder Trash: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/accounts.py", line 407, in syncfolder
    statusfolder.cachemessagelist()
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/LocalStatusSQLite.py", line 187, in cachemessagelist
    labels = set([lb.strip() for lb in row[3].split(',') if len(lb.strip()) > 0])
AttributeError: 'NoneType' object has no attribute 'split'

-------------------

This is the script I am using in case it is related
import re, os
import subprocess
import sys
import offlineimap

def mailpasswd(acct):
    acct = os.path.basename(acct)
    path = "/home/xxxxx/.xxxx/%s.gpg" % acct
    args = ["gpg", "--use-agent", "-d", path]

    try:
        p=subprocess.check_output(args).strip()
        return p
    except subprocess.CalledProcessError:
        return ""

-------------------------

Debian 3.13.0-rc2
Python 2.7.3 
[GCC 4.7.2] on linux2

OI 6.5.6.1-devel (6.5.5 had the same issue)

**Comment by buster** [comment]
I dont think this is fixed, i get this error:

```
  File "/home/buster/sources/offlineimap/offlineimap/accounts.py", line 430, in syncfolder
    statusfolder.cachemessagelist()
  File "/home/buster/sources/offlineimap/offlineimap/folder/LocalStatusSQLite.py", line 206, in cachemessagelist
    labels = set([lb.strip() for lb in row[3].split(',') if len(lb.strip()) > 0])
AttributeError: 'NoneType' object has no attribute 'split'
```

So, i think this line tries to access a non-existing row[3]:

https://github.com/OfflineIMAP/offlineimap/commit/7df765cfdb4096a33f35bf709db6820a6c2c79fd#diff-c23c6906c765513bcd9008c1b49f6746L193

**Comment by nicolas33** [comment]
What version are you using?

**Comment by buster** [comment]
just checked it out yesterday.. tried first on master, then on next...

**Comment by nicolas33** [comment]
Fixed in efc4df1bd73bb58fd170105f364fb0e80a0a2c97, please test `next` branch.

This is a quick fix not fixing the real cause of this bug. Database should return an empty string, not None.

Hence, this issue is kept open.

**Comment by buster** [comment]
Thanks, not it is working. After pulling the latest version, offlineimap fetched 4 Mails from my Sent folder, where it always raised the exception before.. don't know why only the sent folder, all others synced fine.

**Comment by nicolas33** [comment]
Code is commented, closing.
