### ISSUE TITLE
Cannot rmdir, folder gets created again and again

### ISSUE THREAD

**Issue by pyluyten** [OfflineIMAP/offlineimap#117]
If I do rm -r a local Maildir folder, next offlineimap sync, either quick or not, will create back the folder from the remote IMAP. statusbackend is sqllite. Appart from this, I can't find anything interesting in .offlineimaprc.

For example from F.A.Q. <<1.1.7   May I delete local folders?>> I understand this is not the intended behaviour.

I thought
- rmdir + deleting status would "force refreshing" the folder while,
- just rmdir would delete remotely (push).

yum info offlineimap
Nom                 : offlineimap
Architecture        : noarch
Version             : 6.5.5
Révision            : 1.fc20

I shall probably open on fedora's side.

**Comment by nicolas33** [comment]
Try folderfilter to ignore a folder.

For sure, deleting a whole folder locally is not going to be pushed remotely. It was considered too much dangerous.
