### ISSUE TITLE
Offlineimap creates additional labels in Gmail and then complains about their UID validity

### ISSUE THREAD

**Issue by rmopl** [OfflineIMAP/offlineimap#12]
Problem appeared after upgrading Ubuntu to 12.10 and offlineimap to
6.5.4. It's not particularly severe but gets a little messy.

I have labels in my main Gmail account named after my other e-mail
addresses under another label 'aliasy', for example
aliasy/rafal <at> ochmanski.com. When syncing all labels with offline imap
it correctly creates locally a folder aliasy.rafal <at> ochmanski.com and
downloads the messages but also apparently creates remotely (in the
Gmail account, that is) a folder/label aliasy/rafal <at> ochmanski/com
(note the slash instead of the dot before com) and then complains
about its UID validity https://gist.github.com/f16ec751cccba1eb27cd

I removed those labels (with slashes in place of dots here and there)
but they reappear after offlineimap run. I'm assuming they're being
recreated in the process of syncing.

My config is fairly standard https://gist.github.com/7e5af06945bd8d92470b

**Comment by nicolas33** [comment]
Looks like we had a working release at some point. Bisecting the bug should be made to help fixing this issue.

**Comment by rmopl** [comment]
@nicolas33, I don't use OfflineIMAP or mutt with Gmail any more. 

@ojarva, it was a functional work-around at the time.

**Comment by nicolas33** [comment]
Thanks.
