### ISSUE TITLE
offlineimap hangs when network connection disappears

### ISSUE THREAD

**Issue by vext01** [OfflineIMAP/offlineimap#125]
Hi,

First of all, thanks for offlineimap. I use it every day with mutt.

I have a script which runs a sleep / offlineimap loop in the background. Every so often I found that mail stopped syncing, and when I ran offlineimap manually it would say a lock exists. I pinned this down to the following:

When I suspended my laptop when offlineimap was mid-sync, it was hanging, leaving a lockfile behind. The same effect can be reproduced by taking the network interface down mid-sync.

It seems offlineimap will eventually fail after such a hang, but it takes a long time. Eventually you get a message like:
```
ERROR: Exceptions occurred during the run!
ERROR: All authentication types failed:
        PLAIN: command: AUTHENTICATE => socket error: <class 'socket.error'> - [Errno 54] Connection reset by peer
        LOGIN: connection closed
```

Ideally we should have a little more control over this. I would like offlineimap to wait, say 30 seconds (configurable) , before giving up, This would mean my mail loop script would recover from the above situation it a reasonable amount of time.

I'm running 6.5.6 on OpenBSD with Python 2.7.8.

P.S.

You forgot to bump the version number for the 6.5.6 release:
https://github.com/jasperla/openbsd-wip/blob/master/mail/offlineimap/patches/patch-offlineimap___init___py

**Comment by xim** [comment]
Running 6.3.4 on Debian Jessie. When offlineimap has been syncing emails for a while, this happens (most likely in response to network hiccups) – my timeout is set to 30 seconds.

At the end of the output, offlineimap is hanging, not doing anything.

    Account sync Exchange:
     Next refresh in 60 seconds
     Next refresh in 50 seconds
     Next refresh in 40 seconds
     Next refresh in 30 seconds
    Exception in thread Thread-12020:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/usr/lib/pymodules/python2.7/offlineimap/imapserver.py", line 433, in noop
        imapobj.noop()
      File "/usr/lib/pymodules/python2.7/offlineimap/imaplib2.py", line 876, in noop
        return self._simple_command('NOOP', **kw)
      File "/usr/lib/pymodules/python2.7/offlineimap/imaplib2.py", line 1549, in _simple_command
        return self._command_complete(self._command(name, *args), kw)
      File "/usr/lib/pymodules/python2.7/offlineimap/imaplib2.py", line 1310, in _command_complete
        typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
      File "/usr/lib/pymodules/python2.7/offlineimap/imaplib2.py", line 172, in get_response
        raise typ(exc_fmt % str(val))
    abort: command: NOOP => no response after 30.0 secs
    
     Next refresh in 20 seconds
     Next refresh in 10 seconds
     ***** Finished processing account Exchange
     Copying folder structure from IMAP to Maildir
    ^CCTRL-C pressed, aborting...

**Comment by nicolas33** [comment]
This version is more than 3 years old. Please try current v6.5.7-rc2.

**Comment by xim** [comment]
Yes, seeing better behaviour in a newer version. Thanks.

**Comment by nicolas33** [comment]
Thanks for the feedback.

**Comment by khatchad** [comment]
I am running offlineimap 6.6.1 on mac and am experiencing a similar issue. My timeout is also set to 30s.

**Comment by nicolas33** [comment]
I think OfflineIMAP might be sensitive to some small network issues. I won't work on this myself.
You might like to open a new detailed issue.

**Comment by khatchad** [comment]
Thanks @nicolas33 but it seems that #56 is what I am experiencing. Also, @vext01, setting the socket timeout to 10 helps but does not completely solve the problem.
