### ISSUE TITLE
'Unknown interpreted text role "ref"' in the man page

### ISSUE THREAD

**Issue by mineo** [OfflineIMAP/offlineimap#128]
The section "FOLDER FILTERING AND NAMETRANS" includes the following:

     :ref:`folder_filtering_and_name_translation`
     System Message: ERROR/3 (MANUAL.rst:, line 338)
              Unknown interpreted text role "ref".

That's because the `:ref:` role itself is coming from Sphinx, not the RST specification itself. Letting Sphinx generate the man page would probably help here.

(The same thing happens with the files generated by running `make html` in the `docs` directory.)

**Comment by nicolas33** [comment]
This is no more handled by Sphinx and is part of the new website.
