### ISSUE TITLE
missing IDLE documentation

### ISSUE THREAD

**Issue by schmeisers** [OfflineIMAP/offlineimap#13]
I'm trying to get IDLE working on my (gmail) account.  The example config file has a brief description of the options, then refers to the manual for details.  The manual just points back to the example config file without any further details.

**Comment by nicolas33** [comment]
Couldn't find the circular references.

**Comment by hobarrera** [comment]
The [sample conf](https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L553-L554) points to the doc for further information, but the documentation doesn't seem to provide anything further.
