### ISSUE TITLE
status_backend=plain doesn't work

### ISSUE THREAD

**Issue by ildar** [OfflineIMAP/offlineimap#133]
Having status_backend=plain in [Account] section doesn't work: 
>   File "/usr/lib/python2.7/site-packages/offlineimap/folder/LocalStatusSQLite.py", line 62, in __init__
>     raise UserWarning('SQLite backend chosen, but no sqlite python '
> UserWarning: SQLite backend chosen, but no sqlite python bindings available. Please install.
> 
>   SQLite backend chosen, but no sqlite python bindings available. Please install.

**Comment by Hubbitus** [comment]
I have:

		$ ./offlineimap.run
		OfflineIMAP 6.5.6
		Licensed under the GNU GPL v2+ (v2 or any later version)
		Account sync AntPahanBakToBackup:
		*** Processing account AntPahanBakToBackup
		Establishing connection to imap.gmail.com:993
		Establishing connection to imap.gmail.com:993
		Folder BAK_test/Ant/РГКs/Уфа/test [acc: AntPahanBakToBackup]:
		ERROR: ERROR in syncfolder for AntPahanBakToBackup folder BAK/Ant/РГКs/Уфа/test: Traceback (most recent call last):
		File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 399, in syncfolder
		statusrepos.getsep()))
		File "/usr/lib/python2.7/site-packages/offlineimap/repository/LocalStatus.py", line 105, in getfolder
		self.import_other_backend(folder)
		File "/usr/lib/python2.7/site-packages/offlineimap/repository/LocalStatus.py", line 68, in import_other_backend
		folderbk = dic['class'](folder.name, repobk)
		File "/usr/lib/python2.7/site-packages/offlineimap/folder/LocalStatusSQLite.py", line 59, in __init__
		self.connection = sqlite.connect(self.filename, check_same_thread = False)
		OperationalError: unable to open database file

With status_backend = plain option.

**Comment by dliessi** [comment]
Same error as @Hubbitus here.

**Comment by dliessi** [comment]
> Same error as @Hubbitus here.

I got the error with v6.5.6.
I then tried v6.5.7-rc2: the error disappeared and the sync completed without errors.

**Comment by nicolas33** [comment]
Thank you much for this feedback!
Closing.

**Comment by silasdb** [comment]
If you cannot upgrade to v6.5.7, the workaround (bad) solution I found after it happened to me (because LocalStatus file was corrupted due to a system crash) was to delete the LocalStatus file (normally in ~/.offlineimap/Account-XXX/LocalStatus/folder_name) and the entire folder in "$MAIL" and run offlineimap to resync everything again.
