### ISSUE TITLE
support unicode (AssertionError: assert(line == magicline) in LocalStatus.py)

### ISSUE THREAD

**Issue by ibennetch** [OfflineIMAP/offlineimap#134]
Hi, I have been seeing a problem when trying to sync a Gmail account:

```
ERROR: Exceptions occurred during the run!
ERROR: ERROR in syncfolder for Work folder [Gmail]/All Mail: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/offlineimap/accounts.py", line 407, in syncfolder
    statusfolder.cachemessagelist()
  File "/Library/Python/2.7/site-packages/offlineimap/folder/LocalStatus.py", line 72, in cachemessagelist
    assert(line == magicline)
AssertionError


ERROR: ERROR in syncfolder for Home folder [Gmail]/All Mail: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/offlineimap/accounts.py", line 407, in syncfolder
    statusfolder.cachemessagelist()
  File "/Library/Python/2.7/site-packages/offlineimap/folder/LocalStatus.py", line 72, in cachemessagelist
    assert(line == magicline)
AssertionError
```

Interestingly, I try to sync three Gmail accounts this way; two produce this error message ("Work" and "Home", as you see above); the third works perfectly fine.

I believe I'm running 6.5.6, but due to #92 `offlineimap --version` reports 6.5.5. The account type is IMAP for all three.

I saw the related thread at http://thread.gmane.org/gmane.mail.imap.offlineimap.general/6417 but don't see any resolution there.

**Comment by nicolas33** [comment]
The cause is an unsupported encoding somewhere. Requesting comments in the mailing list.
