### ISSUE TITLE
Non ASCII in folder names cannot sync

### ISSUE THREAD

**Issue by hsanson** [OfflineIMAP/offlineimap#14]
My offlineimap installation worked perfectly with my Gmail until I upgraded my Ubuntu to 12.10. Now offlineimap fails with errors like:

   'ascii' codec can't decode byte 0xe7 in position 1: ordinal not in range(128)

I tried with both the Ubuntu version and git version of offlineimap.

**Comment by nicolas33** [comment]
Closing because we never got asked feedbacks.
