### ISSUE TITLE
Feature for syncing everything but deletes from a remote IMAP mailbox

### ISSUE THREAD

**Issue by avar** [OfflineIMAP/offlineimap#144]
I'd like to request a feature, and I'm willing to work on this given some guidance on the code (asked on the IRC channel a while ago but got no answers).

I want to sync from an IMAP mailbox to a Maildir, but not sync any deletes from the mailbox. The use case is e.g. having an ISP with a low amount of space on your IMAP mailbox, and then having a Maildir + dovecot locally to serve up all the mail I've ever received.

I looked at the code and there's a point at which it syncs IMAP delete operations that maps to unlink(), I could just add some option to no-op that, but are there some caveats with that? E.g. with the local DB getting out of sync or corrupted?

**Comment by nicolas33** [comment]
Duplicates #47 I think.
