### ISSUE TITLE
Feature. Restore local Maildir to IMAP server.

### ISSUE THREAD

**Issue by chris001** [OfflineIMAP/offlineimap#146]
Feature request created from offlineimap mailing list help request and solution offered, functional but a little time consuming, and risk of human error.

Requesting this new Feature on behalf of many previous users in same situation, trying to use offlineimap to perform a backup of imap server mailboxes (A) to local maildir (B), then restore local maildir (B) to a different imap server (C).

To save time, and reduce the change of user's error causing email data loss, it would be good to add a command line option, or config file option, to automatically do this - Restore Maildir to IMAP server.

"Hi,

Perhaps I misunderstood how offlineimap works, however I now find myself in a hole. I used offlineimap to create a maildir copy of an email account, joe@company.com, as I needed to move the account to a new server. For reasons too long to go into here I was forced to make a local copy as the email provider forced me to delete the account on one account, before moving it to a new account. This meant of course, I couldn't do an IMAP sync between two live accounts, as joe@company.com would only ever exist on one server.

The sync from IMAP -> maildir went as expected. Actually pretty quick for 1.8 Gb of mail!

I deleted the account from the old server and set it up on the new server. I changed the DNS settings and logged into the webmail interface: the new account was empty as expected. I ran offlineimap again using the same .offlineimaprc file, and got a bunch of errors:

UID validity problem for folder INBOX.Spam (repo Remote) (saved 1212983672; got 1419237195); skipping it. Please see FAQ and manual on how to handle this.

So I looked in the FAQ and saw that the answer lay in the cached information. However the solution is to delete the contents of the maildir and cache, which is not what I want to do as this is now the only copy of the mail!

I thought I might be able to address this by editing the saved UIDs. I tried changing the UID in .offlineimap/Repository-Remote/FolderValidity/INBOX.Spam from the incorrect one to the correct one (ie 1212983672 to 1419237195). However, running this sync now deletes the mails in the maildir copy, whereas I thought it would sync them back to the server. So it appears to be syncing from the empty server copy to the full local copy. Hardly bidirectional sync!

So ... what is the correct way to get these mails from the Local maildir copy into the new IMAP account? The account owner is standing behind me tapping his foot, so I need to figure it out swiftly!

Is there a way to force the sync? Is there a way to specify the direction of the sync? What have I mis-understood?

Plutocrat."

"Dec 22 at 11:06 AM
Pluto Crat
To
offlineimap-project@lists.alioth.debian.org
Dec 22 at 8:44 PM
Hi Nicholas,

Thanks for your very clear and thorough instructions. All is good now,
and hopefully anyone else having a similar problem will be able to find
the answer in this mailing list! Perhaps one for the FAQ?

While I'm writing, I thought I'd mention how I got in this position in
the first place. I have an account with Mediatemple. I was hosting a
domain for a friend, and wanted to transfer it from my account to his
account. However it was impossible to set up the domain on both accounts
at the same time, so I needed to make a copy of his email, delete the
account on the source end, and then create it on the target end. It was
frustrating because I knew that if I talked to the right tech person,
they could just move the maildir between accounts. If I'd had access to
the server myself, I could have done it in seconds, rather than the 6
hours it took me to make a local copy and re-upload it. Ah well. Its all
over now.

Thanks again. And thanks for offlineimap."

On Tuesday, 23 December, 2014 12:05 AM, Nicolas Sebrecht wrote:
> On Mon, Dec 22, 2014 at 05:23:04PM +0800, Plutocrat wrote:
>
> <...>
>
>> So I looked in the FAQ and saw that the answer lay in the cached
>> information. However the solution is to delete the contents of the
>> maildir and cache, which is not what I want to do as this is now the
>> only copy of the mail!

> Not true, AFAIR. While this is the strong way, deleting the cache is
> enough. It might be worth to make a backup of the maildir before
> proceeding, though.
>

>> So ... what is the correct way to get these mails from the Local
>> maildir copy into the new IMAP account? The account owner is standing
>> behind me tapping his foot, so I need to figure it out swiftly!

> The best way is to let OfflineIMAP recreate its cache according to the
> new server, from scratch.
>
> 1. Move the maildir directory to maildir.old. Create a new empty
>    maildir directory.
>
> 2. Delete the cache. OfflineIMAP is now ready to start from scratch as
>    if it was its first execution.
>
> 3. Run OfflineIMAP once. Now, it has a clean cache and a fresh maildir
>    content.
>
> 4. Then, we want to copy the content (your raw mails) from maildir.old to
>    maildir. Compare the trees between the old and new maildir before
>    copying.
>
> Depending of what was done while migrating the IMAP server, your might
> find the exact same trees or not. If not, there two alternatives:
> - tune your OfflineIMAP configuration to have the new tree matching the
>    old one. This requires deleting the maildir and re-sync to not have
>    unexpected upload sync due to changed nametrans rules or whatever.
>    This is the hard way.
> or
> - manually copy the emails from the old maildir to the new maildir on a
>    per-folder basis. This should be the easy way.
>
> 5. Re-sync. The local mails are synced back to the server.
>"

**Comment by nicolas33** [comment]
Hmm, depending of what the user expects when restoring a backup and what it currently has on the remote, it's hard to implement expectations. I'll write a documentation for the new website, instead.
