### ISSUE TITLE
make checks for the sep characters in foldernames (dot, slash)

### ISSUE THREAD

**Issue by adborden** [OfflineIMAP/offlineimap#148]
I'm using Hotmail's IMAP service, so I'm not sure if this is an issue with their implementation or not. I have a folder "dog.food.me@hotmail.com" on Hotmail. It seemed to download fine the first time. On the second run of `offlineimap -o` it crashes with this error:
```
$ offlineimap -o
OfflineIMAP 6.5.5
  Licensed under the GNU GPL v2+ (v2 or any later version)
Account sync live:
 *** Processing account live
 Establishing connection to imap-mail.outlook.com:993
 Creating folder dog/food/me@hotmail/com[Remote]
Folder Deleted [acc: live]:
 Syncing Deleted: IMAP -> Maildir
Account sync live:
 ERROR: getfolder() asked for a nonexisting folder 'dog'.
Folder Deleted [acc: live]:
 Establishing connection to imap-mail.outlook.com:993
Account sync live:
 *** Finished account 'live' in 0:03
ERROR: Exceptions occurred during the run!
ERROR: getfolder() asked for a nonexisting folder 'dog'.

Traceback:
  File "/usr/lib64/python2.7/site-packages/offlineimap/accounts.py", line 241, in syncrunner
    self.sync()
  File "/usr/lib64/python2.7/site-packages/offlineimap/accounts.py", line 320, in sync
    localfolder = self.get_local_folder(remotefolder)
  File "/usr/lib64/python2.7/site-packages/offlineimap/accounts.py", line 269, in get_local_folder
    replace(self.remoterepos.getsep(), self.localrepos.getsep()))
  File "/usr/lib64/python2.7/site-packages/offlineimap/repository/Maildir.py", line 134, in getfolder
    OfflineImapError.ERROR.FOLDER)
```

Output of offlineimap --info

```
OfflineIMAP 6.5.5
  Licensed under the GNU GPL v2+ (v2 or any later version)
Remote repository 'Remote': type 'IMAP'
Host: imap-mail.outlook.com Port: None SSL: True
Establishing connection to imap-mail.outlook.com:993
Server supports ID extension.
Server welcome string: * OK Outlook.com IMAP4rev1 server version 17.4.0.0 ready (BLU451-IMAP209)
Server capabilities: ('IMAP4REV1', 'CHILDREN', 'ID', 'NAMESPACE', 'UIDPLUS', 'UNSELECT')

Folderlist:
 Deleted
 dog
 dog.food.me@hotmail.com
 dog/food
 dog/food/me@hotmail
 dog/food/me@hotmail/com
 Drafts
 gmail
 Inbox
 Junk
 party
 Sent
 TEST

Local repository 'Local': type 'Maildir'
Folderlist:
 gmail
 Drafts
 party
 Junk
 dog.food.me@hotmail.com
 Inbox
 TEST
 Sent
 Deleted
```

**Comment by nicolas33** [comment]
Taking this one since it looks related to encodings are unsupported character at some point.

**Comment by nicolas33** [comment]
The problem lies in the fact that you are using one of the "sep" character in your foldername. You can't do that because offlineimap has no way to know whether it's a separator or a valid character. Hence, any dot is considered as a separator.

**Comment by adborden** [comment]
Hmm, okay thanks. Is this a bug in Hotmail's implementation? I'm looking at [RFC 3501](https://tools.ietf.org/html/rfc3501#section-5.1) which talks about a separator character of the server's choosing, but I don't see how it specifies that character to the client OR if that separator is always "."

**Comment by nicolas33** [comment]
This is a limitation of offlineimap. It has to handle both sides (local and remote) separators. Remote is usually '/' (defined by the server) while your local sep is probably the dot. The latter can be changed via the "sep" configuration option.

Since offlineimap has to convert names both ways, it will convert any local dot to '/' and any remote '/' to dot. There is no way to say "this sep character here in that string must not be converted". Hence, using either sep in a folder name is confusing offlineimap.

**Comment by nicolas33** [comment]
This is rather regular issue. We should prevent this with a clear message or add an entry to the FAQ.

**Comment by nicolas33** [comment]
Please, test https://github.com/nicolas33/offlineimap/tree/ns/fix-sep.

**Comment by nicolas33** [comment]
Next version of the fix: https://github.com/nicolas33/offlineimap/tree/ns/fix-sep-2.

**Comment by noc0lour** [comment]
I think I have a workaround for people who have the local sep in the remote folder name. Things should work out if we the `local_sep -> remote_sep` conversion is executed before the `nametrans` for `local -> remote` is done. With this workaround I can convert dots to something else (e.g !) and covert them back to dots immediately before the transfer to remote.  But this would introduce a large behavioral change for people using nametrans.

**Comment by nicolas33** [comment]
Discussed in the mailing list, following your patch.
