### ISSUE TITLE
fix syncing back Gmail labels

### ISSUE THREAD

**Issue by nicolas33** [OfflineIMAP/offlineimap#151]
@konvpalto : Waiting for you. :-) I don't have the time for this one.

@cro : Also, sign-off your patches please!

**Comment by konvpalto** [comment]
This seems to be related to some pull request, but I fail to find which one.  Nicolas?

**Comment by nicolas33** [comment]
Oh, I've created this issue from the pull-request (there is a direct icon for that) but Github did not keep the link back to it. Not so smart!
Will look at that.

**Comment by nicolas33** [comment]
I guess it was about #106 you have closed today. Closing this offending issue anyway.
For now, I'll directly comment on pull-requests.
