### ISSUE TITLE
OAUTH2 implementation

### ISSUE THREAD

**Issue by nicolas33** [OfflineIMAP/offlineimap#152]

**Comment by nicolas33** [comment]
Looks like we have concurrent pull requests:
- #72 
- #141 

Please, join your efforts. The mailing list is a big help and a favourite place for such work. ,-)

**Comment by cscorley** [comment]
I am in the middle of a move, but I'd be happy to rebase mine onto next if I ever get the chance. May be a month or two.

**Comment by nicolas33** [comment]
Be aware that I intend big changes after v6.5.7 will be out. I think the stable could be out for the coming month.

After that we'll go for a v6.6.0 about Python3, some library changes and deep refactoring.

So, I aim to freeze the code until this is done, might it be for a *long* time.

See https://github.com/OfflineIMAP/offlineimap/wiki/Roadmap

**Comment by nicolas33** [comment]
Big refactoring canceled.

**Comment by nicolas33** [comment]
Done.
