### ISSUE TITLE
ERROR in syncfolder for yahoo folder Inbox: abort: command: SEARCH => connection terminated

### ISSUE THREAD

**Issue by peterski007** [OfflineIMAP/offlineimap#158]
All was well for six months till a few days ago with Yahoo. Gmail works fine but Yahoo sync works on all folders except the 'Inbox' with this output:

OfflineIMAP 6.5.7-rc1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync yahoo:
 *** Processing account yahoo
 Establishing connection to imap.mail.yahoo.com:993
Folder Archive [acc: yahoo]:
 Syncing Archive: IMAP -> Maildir
Folder Drafts [acc: yahoo]:
 Syncing Drafts: IMAP -> Maildir
Folder Inbox [acc: yahoo]:
 Syncing Inbox: IMAP -> Maildir
 ERROR: ERROR in syncfolder for yahoo folder Inbox: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/offlineimap/accounts.py", line 449, in syncfolder
    remotefolder.cachemessagelist()
  File "/Library/Python/2.7/site-packages/offlineimap/folder/IMAP.py", line 216, in cachemessagelist
    msgsToFetch = self._msgs_to_fetch(imapobj)
  File "/Library/Python/2.7/site-packages/offlineimap/folder/IMAP.py", line 193, in _msgs_to_fetch
    res_type, res_data = imapobj.search(None, search_cond)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 975, in search
    return self._simple_command(name, *criteria, **kw)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 1616, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 1379, in _command_complete
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 177, in get_response
    raise typ(exc_fmt % str(val))
abort: command: SEARCH => connection terminated

  command: SEARCH => connection terminated
Folder Notes [acc: yahoo]:
 Syncing Notes: IMAP -> Maildir
 Establishing connection to imap.mail.yahoo.com:993
Folder Sent [acc: yahoo]:
 Syncing Sent: IMAP -> Maildir
Account sync yahoo:
 *** Finished account 'yahoo' in 0:05
ERROR: Exceptions occurred during the run!
ERROR: ERROR in syncfolder for yahoo folder Inbox: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/offlineimap/accounts.py", line 449, in syncfolder
    remotefolder.cachemessagelist()
  File "/Library/Python/2.7/site-packages/offlineimap/folder/IMAP.py", line 216, in cachemessagelist
    msgsToFetch = self._msgs_to_fetch(imapobj)
  File "/Library/Python/2.7/site-packages/offlineimap/folder/IMAP.py", line 193, in _msgs_to_fetch
    res_type, res_data = imapobj.search(None, search_cond)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 975, in search
    return self._simple_command(name, *criteria, **kw)

  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 1616, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 1379, in _command_complete
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 177, in get_response
    raise typ(exc_fmt % str(val))
abort: command: SEARCH => connection terminated

  command: SEARCH => connection terminated

[ [ .offlineimaprc config file contains: ] ]
```
[general]
# List of accounts to be synced, separated by a comma.
accounts = gmail, yahoo

[Account yahoo]
# Identifier for the local repository; e.g. the maildir to be synced via IMAP.
localrepository = yahoo-local
remoterepository = yahoo-remote

# Minutes between syncs
#autorefresh = 1 # In minutes not seconds. Doesn't work on OS X. Don't use since we use wrapper 'offlineimap-load'

# Identifier for the remote repository; i.e. the actual IMAP, usually non-local.
remoterepository = yahoo-remote

# Status cache. Default is plain, which eventually becomes huge and slow.
#status_backend = sqlite

# Maxage of mail to synchronize in days
maxage = 90

[Repository yahoo-local]
type = Maildir
localfolders = ~/Maildir-yahoo

[Repository yahoo-remote]
type = IMAP
# This only works in continuous mode since using '-o' option runs and exits by nature
keepalive = 100
holdconnectionopen = yes

remotehost = imap.mail.yahoo.com
remoteuser = username
remotepass = ***************
remoteport = 993
ssl = yes
maxconnections = 1
realdelete = no
folderfilter = lambda foldername: foldername in ['Inbox', 'Drafts', 'Sent', 'Spam', 'Notes', 'Archive']
cert_fingerprint = c8d50e4f236438c4910aeb11d9bc588502032637
```

**Comment by nicolas33** [comment]
Please, give the output of `offlineimap --info`.

**Comment by peterski007** [comment]
OfflineIMAP 6.5.7-rc1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Remote repository 'gmail-remote': type 'Gmail'
Host: imap.gmail.com Port: 993 SSL: 1
Establishing connection to imap.gmail.com:993
Server supports ID extension.
Server welcome string: * OK Gimap ready for requests from 78.151.154.158 e15mb5549070wjz
Server capabilities: ('IMAP4REV1', 'UNSELECT', 'IDLE', 'NAMESPACE', 'QUOTA', 'ID', 'XLIST', 'CHILDREN', 'X-GM-EXT-1', 'UIDPLUS', 'XXXXXXXXXXXXXXXX', 'ENABLE', 'MOVE', 'XXXXXXXXX', 'ESEARCH', 'UTF8=ACCEPT')

folderfilter= lambda foldername: foldername in ['INBOX', 'Archived', 'Documentation', 'Notes', 'Technology', '[Google Mail]/Drafts', '[Google Mail]/Sent Mail', 'DandT']

Folderlist:
 [Google Mail]/All Mail (disabled)
 [Google Mail]/Bin (disabled)
 [Google Mail]/Drafts
 [Google Mail]/Important (disabled)
 [google mail]/sent (disabled)
 [Google Mail]/Sent Mail
 [Google Mail]/Spam (disabled)
 [Google Mail]/Starred (disabled)
 Archived
 DandT
 Deleted Messages (disabled)
 Documentation
 INBOX
 Junk (disabled)
 Notes
 Receipts (disabled)
 Sent (disabled)
 sentmail (disabled)
 Trash (disabled)
 Visa Unit (disabled)

Local repository 'gmail-local': type 'Maildir'
Folderlist:
 [Google Mail].Drafts
 [Google Mail].Sent Mail
 Archived
 DandT
 Documentation
 INBOX
 Notes

**Comment by peterski007** [comment]
I separated the Gmail acount out from the config file leaving only the Yahoo account and the output from offlineimap --info -c yahoo.config is:

OfflineIMAP 6.5.7-rc1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Remote repository 'yahoo-remote': type 'IMAP'
Host: imap.mail.yahoo.com Port: 993 SSL: True
Establishing connection to imap.mail.yahoo.com:993
Server supports ID extension.
Server welcome string: * OK [CAPABILITY IMAP4rev1 ID NAMESPACE X-ID-ACLID UIDPLUS LITERAL+ CHILDREN XAPPLEPUSHSERVICE XYMHIGHESTMODSEQ AUTH=PLAIN AUTH=LOGIN AUTH=XOAUTH2 AUTH=XYMCOOKIE AUTH=XYMECOOKIE AUTH=XYMCOOKIEB64 AUTH=XYMPKI] IMAP4rev1 imapgate-1.8.1_01.61594 imap434.mail.ir2.yahoo.com
Server capabilities: ('IMAP4REV1', 'ID', 'NAMESPACE', 'X-ID-ACLID', 'UIDPLUS', 'LITERAL+', 'XAPPLEPUSHSERVICE', 'XYMHIGHESTMODSEQ')

folderfilter= lambda foldername: foldername in ['Inbox', 'Drafts', 'Sent', 'Spam', 'Notes', 'Archive']

Folderlist:
 Archive
 Bulk Mail (disabled)
 Deleted Messages (disabled)
 Draft (disabled)
 Drafts
 Inbox
 Junk (disabled)
 Junk E-mail (disabled)
 Notes
 Sent
 Sent Messages (disabled)
 Trash (disabled)
 Y! Conversations (disabled)

Local repository 'yahoo-local': type 'Maildir'
Folderlist:
 Archive
 Drafts
 Inbox
 Junk E-mail
 Notes
 Sent
 Trash

A sync using `` offlineimap -c yahoo.config -o -a yahoo`` is still the same:

OfflineIMAP 6.5.7-rc1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync yahoo:
 *** Processing account yahoo
 Establishing connection to imap.mail.yahoo.com:993
Folder Archive [acc: yahoo]:
 Syncing Archive: IMAP -> Maildir
Folder Drafts [acc: yahoo]:
 Syncing Drafts: IMAP -> Maildir
Folder Inbox [acc: yahoo]:
 Syncing Inbox: IMAP -> Maildir
 ERROR: ERROR in syncfolder for yahoo folder Inbox: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/offlineimap/accounts.py", line 449, in syncfolder
    remotefolder.cachemessagelist()
  File "/Library/Python/2.7/site-packages/offlineimap/folder/IMAP.py", line 216, in cachemessagelist
    msgsToFetch = self._msgs_to_fetch(imapobj)
  File "/Library/Python/2.7/site-packages/offlineimap/folder/IMAP.py", line 193, in _msgs_to_fetch
    res_type, res_data = imapobj.search(None, search_cond)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 975, in search
    return self._simple_command(name, *criteria, **kw)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 1616, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 1379, in _command_complete
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 177, in get_response
    raise typ(exc_fmt % str(val))
abort: command: SEARCH => connection terminated

  command: SEARCH => connection terminated
Folder Notes [acc: yahoo]:
 Syncing Notes: IMAP -> Maildir
 Establishing connection to imap.mail.yahoo.com:993
Folder Sent [acc: yahoo]:
 Syncing Sent: IMAP -> Maildir
Account sync yahoo:
 *** Finished account 'yahoo' in 0:06
ERROR: Exceptions occurred during the run!
ERROR: ERROR in syncfolder for yahoo folder Inbox: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/offlineimap/accounts.py", line 449, in syncfolder
    remotefolder.cachemessagelist()
  File "/Library/Python/2.7/site-packages/offlineimap/folder/IMAP.py", line 216, in cachemessagelist
    msgsToFetch = self._msgs_to_fetch(imapobj)
  File "/Library/Python/2.7/site-packages/offlineimap/folder/IMAP.py", line 193, in _msgs_to_fetch
    res_type, res_data = imapobj.search(None, search_cond)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 975, in search
    return self._simple_command(name, *criteria, **kw)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 1616, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 1379, in _command_complete
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 177, in get_response
    raise typ(exc_fmt % str(val))
abort: command: SEARCH => connection terminated

  command: SEARCH => connection terminated

**Comment by peterski007** [comment]
Looks like it was a Yahoo Mail problem on their IMAP Servers!
Mac Mail had loads of users calling Apple not able to connect to Yahoo Mail using OSX Mail app.

Looks like whatever Yahoo broke has now been fixed!

Check out this thread:  https://discussions.apple.com/thread/6681181 
```
francois_cm Jan 14, 2015 2:14 PM
Re: Apple Mail won't retrieve new mail from Yahoo IMAP in response to D.R.C.

Hi all,

I just got off the phone with Apple service care (at 4:30 pm eastern time) and they confirm the problem comes from Yahoo (they had a lot of call concerning Yahoo today). It seems that Yahoo have been noticed of the problem for Apple Mail users... Hope they'll fix it quickly.
```
