### ISSUE TITLE
Show database path when "OperationalError: unable to open database file"

### ISSUE THREAD

**Issue by bjornfor** [OfflineIMAP/offlineimap#163]
I recently got this error message from offlineimap:

```
$ offlineimap
OfflineIMAP 6.5.5
  Licensed under the GNU GPL v2+ (v2 or any later version)
*** Processing account GMail
Establishing connection to imap.gmail.com:993
ERROR: ERROR in syncfolder for GMail folder Google_Mail/Sent_Mail:
Traceback (most recent call last):
  File "/nix/store/rrckvnbghklfv1y1qi8lpsm2mlihrin1-offlineimap-6.5.6/lib/python2.7/site-packages/offlineimap/accounts.py",
line 399, in syncfolder
    statusrepos.getsep()))
  File "/nix/store/rrckvnbghklfv1y1qi8lpsm2mlihrin1-offlineimap-6.5.6/lib/python2.7/site-packages/offlineimap/repository/LocalStatus.py",
line 105, in getfolder
    self.import_other_backend(folder)
  File "/nix/store/rrckvnbghklfv1y1qi8lpsm2mlihrin1-offlineimap-6.5.6/lib/python2.7/site-packages/offlineimap/repository/LocalStatus.py",
line 68, in import_other_backend
    folderbk = dic['class'](folder.name, repobk)
  File "/nix/store/rrckvnbghklfv1y1qi8lpsm2mlihrin1-offlineimap-6.5.6/lib/python2.7/site-packages/offlineimap/folder/LocalStatusSQLite.py",
line 59, in __init__
    self.connection = sqlite.connect(self.filename, check_same_thread = False)
OperationalError: unable to open database file
```

When debugging this, it would have helped a lot if the path to the database file was printed. Not knowing any better, I (unsuccessfully) tried to locate files matching "\*sql\*" or "\*db\*" in my maildir.

Thanks to Nicolas Sebrecht for helping me on the mailing list (and suggesting I make an github issue about printing the database file path).

**Comment by nicolas33** [comment]
Fixed in 655c2b1.

**Comment by bjornfor** [comment]
Thanks!

**Comment by bjornfor** [comment]
@nicolas33: I don't think this is properly fixed. The traceback I pasted above comes from an "OperationalError" exception, but the change you did in 655c2b1 is modifying an existing error message in an "except NameError" block. So it is a different code path.

I think it would be best (from user perspective) to give a different message when the "OperationalError" occurs. That's when the database filename is important. If the python sqlite module doesn't work, the database filename doesn't matter much, I guess.

**Comment by nicolas33** [comment]
You are plain right, of course. I missed the `NameError` of the `except` clause.
Thank you much. a1383da
