### ISSUE TITLE
Quick sync no longer syncs read flags

### ISSUE THREAD

**Issue by amac16** [OfflineIMAP/offlineimap#165]
Running quick sync no longer seems to sync flags (read/unread).

**Comment by nicolas33** [comment]
Could you please `git bisect` the issue?

**Comment by nicolas33** [comment]
http://offlineimap.github.io/doc/git-bisect.html

**Comment by shaggytwodope** [comment]
I'm using the version from the arch repos (`offlineimap 6.5.7-1`), and it appears I'm getting this same issue but only with my gmail account.  Read and unread status doesn't update and when I sync the read status is reset.  This is a recent issue, I'am guessing it's related to the gmail labels? I could be very wrong of course.

**Comment by rubdos** [comment]
Hi, apparently I have the same issue. Fedora 22 64bit, clean installed and configured OfflineIMAP with notmuch and afew yesterday.

My phone receives my e-mail, but since I enabled IMAP idle on OfflineIMAP yesterday, my phone receives a lot more mail than my PC.

**Comment by nicolas33** [comment]
Might be an IDLE issue, then.

Are you still having this problem with v6.5.7 (stable)?

**Comment by rubdos** [comment]
I recently came back to Thunderbird after a reinstall of my system, so I can't test right now. I probably will in the future though.

**Comment by blami** [comment]
I am affected too. OfflineIMAP version 6.5.5 (what's in Ubuntu) IDLE is disabled and account is not GMail.

**Comment by nicolas33** [comment]
Please, provide the config file. Are read flags not syncing to both sides are only in one direction?

**Comment by nicolas33** [comment]
Might be related to #185.

**Comment by nicolas33** [comment]
I wonder why we were syncing read flags with quick mode in the first place.
