### ISSUE TITLE
support for accepting invalid certificates

### ISSUE THREAD

**Issue by phavx** [OfflineIMAP/offlineimap#171]
I'm running a domain (my.tld) on a shared webhoster (something.else) who has a certificate (*.something.else).

When I set _remotehost = mail.my.tld_ and _ssl = yes_, it crashes with something like domain not named in certificate. When I set _remotehost = server.something.else_ it works as expected.

I couldn't find an option to accept certificates like this, but it would imho be nice to have(pretty much any other client I'm using can do this). This is of course mostly a cosmetic problem in my personal config, but it might also help in the future should I decide to move my domain to another hoster.

(side note, missing directories for the imap folders get created, but it gives a crash if the basedir doesn't exist - so _localfolders = ~/.foo/bar_ doesn't work if ~/.foo doesn't exist, didn't expect that. Intentional or oversight?)

**Comment by konvpalto** [comment]
*.something.else isn't an invalid certificate, it is rather a wildcard one, permitted by a standard.  And if when you set remotehost to "server.something.else" and get no problems, it means that wildcards works.  And the X.509 recommendations say that we should check subjectAltName and then DN of the certificate to match the domain name we're connecting to.

So, your proposition contradicts with the current X.509 standards.  It is the other question how implementing CAs do domain validation (they often don't do much or charge for "extended validation" certs).  So, making it "I want to connect to machine X.Y, but call it A.B for certificate validation" a kind of skips the link between the name of the machine one is connected to (X.Y), its IP address determined by DNS and certificate for this machine obtained in this TCP session.  We can, of course, try to mimic this with A.B by checking if it maps to the same IP as X.Y, but that will be non-trivial for DNS names that correspond to many different IPs (DNS load-balancing and alike).  Not sure if we will be able to plug into the current certificate validation infrastructure that deep, but, perhaps, it even possible.

Having said that, are you sure that you won't be happier if your configuration will contain "remotehost = server.something.else"?

**Comment by phavx** [comment]
Personally I don't care that much what's in my config, I'd just add a comment reminding me why it's there. I just saw it as unusual to go that route as other clients offer the option to accept a cert and just continue on with the work.

As we all know, the SSL system is broken on so many systems anyway, mostly in terms of trust, it imho doesn't really hurt to give people that option, especially people having not that much knowledge. If those people trust their provider, it's still better to accept a cert of this kind than to turn SSL off completly, imho.

Granted, those people probably aren't that much of a target group for offlineimap, still I think a solution or at least a hint for a work around should be given(after all, it took me quite some time to figure out the problem). I don't know how much work it would be to implement accepting certificates like this, an alternative might be a note in the documentation, something like "if you are on shared webhosting and get a SSL error domain not found in certificate, find out the real server and enter that into your config".

**Comment by nicolas33** [comment]
I agre with @konvpalto that the configuration should match the certificate content, not much the domain name you use which doesn't provide a certificate. So, I'm not in favour of implementing a *workaround*.

Though, I'm concerned about the "it took me a while to figure it out" and I think it's worth putting that in the documentation, even if it sounds not much a common setup (it's the first time I'm reading something about that).

**Comment by phavx** [comment]
As I said, it's probably not that common because people having their stuff on a shared hosting usually aren't the target audience for projects like this.

I appreciate that it's planned to get this documented, so thanks for that. Close at will or when it's implemented.

**Comment by nicolas33** [comment]
Done.
