### ISSUE TITLE
password from mysql database

### ISSUE THREAD

**Issue by naveensharmayoung** [OfflineIMAP/offlineimap#175]
i am using mysql database to store password of gmail and getting it via function
python file 
def username():
   db = MySQLdb.connect(host="localhost", # your host, usually localhost
                     user="root", # your username
                      passwd="1555511", # your password
                      db="database") # name of the data base

   cur = db.cursor()

 
   cur.execute("select password from database)
   data = cur.fetchall()
   for row in data:
       fname = row[0]

       return fname 
and my offlineimaprc files is 
[Repository Remote2]
type = IMAP
remotehost = imap.gmail.com
remoteuser = nk86@gmail.com
remotepasseval = username()
ssl = yes
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
maxconnections = 3

realdelete = no
but error in authentication how to correct this error
*** Finished account 'GMail1' in 0:15
ERROR: Exceptions occurred during the run!
ERROR: All authentication types failed:
        PLAIN: [AUTHENTICATIONFAILED] Invalid credentials (Failure)
        LOGIN: [AUTHENTICATIONFAILED] Invalid credentials (Failure)

**Comment by nicolas33** [comment]
* look how others use python file and compare to yours
* run your python function directly to check if it works
* make usual debugging:
  - add print statements
  - try `-d` CLI options
