### ISSUE TITLE
how to define array of accounts in accounts

### ISSUE THREAD

**Issue by naveen1336** [OfflineIMAP/offlineimap#180]
i want to create a array of account because the no of accounts are large how could i delcare a array of accounts in accounts section of offlineimap

**Comment by nicolas33** [comment]
I think you should write your own wrapper in Python or shell script. Also, it's possible to have more than one configuration file and call offlineimap with the `-c` CLI option to limit the range of accounts.
How many accounts do you handle?

**Comment by naveensharmayoung** [comment]
100 accounts

**Comment by nicolas33** [comment]
i want users read the docs, try by themselves and request support for specific matters
:-p
