### ISSUE TITLE
Encode/decode mailbox names from modified UTF7

### ISSUE THREAD

**Issue by kappa** [OfflineIMAP/offlineimap#192]
IMAP mailbox names fully support Unicode but use a rather exotic ASCII-safe modified UTF7 encoding.
See https://tools.ietf.org/html/rfc3501#section-5.1.3

Having local directories (Maildir) named as
    &BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-
    &BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-.takoe
    &BB4EQgQ,BEAEMAQyBDsENQQ9BD4-
...makes no sense.

offlineimap should support re-encoding mailbox names when storing them as directories on local filesystem.

**Comment by andreygursky** [comment]
I'm also missing this. For now I'm using a workaround [1].

[1] http://notes.pomeo.me/offlineimap_и_кириллица.html

**Comment by andreygursky** [comment]
Aha, I believe it's already WIP: https://github.com/nicolas33/offlineimap/commit/6a4b27a41ce4880a69d7e2e85c4371396d44a552.

**Comment by nicolas33** [comment]
See:
* http://article.gmane.org/gmane.mail.imap.offlineimap.general/6800
* http://article.gmane.org/gmane.mail.imap.offlineimap.general/6804
* http://article.gmane.org/gmane.mail.imap.offlineimap.general/6813

**Comment by nicolas33** [comment]
@andreygursky: how far this workaround is working for you?

**Comment by nicolas33** [comment]
Minimal UTF-7 feature merged.
