### ISSUE TITLE
Minor documentation updates...

### ISSUE THREAD

**Issue by mobamoba** [OfflineIMAP/offlineimap#197]
I recently moved over from a Linux-based server to MS Exchange and thought it might be helpful to add to the installation documentation page that Offlineimap works great, not only on Linux, but on Windows as well via Cygwin  The only instructions are that the minimum Cygwin install needs to include both the Devel and Python packages in order to both make and run Offlineimap.

Cygwin's bash shell automatically creates a home directory (e.g. <Cygwin install directory>/home/<username>) which is where the .offlineimap files reside.

I thought it might be helpful to put in the documentation because - while it was ultimately very easy to figure out how to do - it might save someone some Googling.

Also, for whatever reason, Microsoft refers to the SHA fingerprint as a "thumbprint" - maybe adding that to the sample conf file might make it simpler for a Windows user to find it.

**Comment by nicolas33** [comment]
Good news. Willing to write the patches?

**Comment by mobamoba** [comment]
Sure, just created the pull requests.

**Comment by nicolas33** [comment]
Thank you much!
