### ISSUE TITLE
UIBase.exc_queue size limitation mechanism required

### ISSUE THREAD

**Issue by hirthwork** [OfflineIMAP/offlineimap#199]
Currently exc_queue is not limited, so long running instance of offlineimap can accumulate thousands of exception reports and most of them will concern same issue with unavailable item on server.
Besides of memory consumption this causes significant output size on shutdown, when all these exceptions are being printed to console.

My suggestion is to add optional config parameter which will allow to limit exc_queue capacity.
As for me, I won't bother myself reading more than ten tracebacks.

**Comment by nicolas33** [comment]
Did you have issue with memory consumption because of exceptions? If so many exceptions occur, I'd say there are more urgent things to fix...

**Comment by hirthwork** [comment]
I definitely have issue with memory consumption, but my python development skill doesn't allow to find root cause by process dump analysis.
The exception I have is always the same: offlineimap reports there is no message with specific UID, and UID is always the same. This exception occurs every minute.
So, for me there is no big surprise that these exceptions stores some local objects references, which in turn prevents some heavy objects garbage collecting.

**Comment by nicolas33** [comment]
Why don't you fix this UID issue?

**Comment by hirthwork** [comment]
What do you mean by saying 'fix'?
I've already tried to delete all offlineimap and mutt data for this folder and
synchronize from scratch, but the problem is still here.

**Comment by nicolas33** [comment]
The root cause is the UID exceptions that should not happen. I don't know how you tried to fix it and what's the raised exception about this UID.

**Comment by hirthwork** [comment]
Most probably this is the server side issue. I see no way how can I fix 3rd party IMAP server, so configurable workaround has been suggested

**Comment by nicolas33** [comment]
This would be a serious fault. Did you try to contact the support service?

**Comment by hirthwork** [comment]
Will do this on the next week.
