### ISSUE TITLE
Suspend computer with IDLE -> no emails fetched

### ISSUE THREAD

**Issue by erikw** [OfflineIMAP/offlineimap#20]
Hi,

I'm running OfflineIMAP IDLE-mode as I want fast mail notification but when I put my computer to sleep and wake it up the process seems to seems to hang as it does not fetch any new mails. If I run it in a shell and observe stdout after the wakeup it does simply not say anything at all. If I strace it it just keeps printing 

	select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)

The exact [configuration] (https://github.com/erikw/dotfiles/blob/personal/.offlineimaprc) I'm using can be seen in my dotfiles repo and the version I'm using in 6.5.4.

I'm not pleases with having to kill and restart OfflineIMAP each time I sleep my computer :) Any ways of fixing this?

**Comment by nicolas33** [comment]
Issue documented as known limitation.
