### ISSUE TITLE
no-delete-local

### ISSUE THREAD

**Issue by petr-fischer** [OfflineIMAP/offlineimap#204]
Hello, is possible to add this useful patch for "no-delete-local" option to the official offlineimap release? https://github.com/OfflineIMAP/offlineimap/commit/266c88f7a1b041ba169e0c0cab767bf412c23672

**Comment by nicolas33** [comment]
Could you send this patch by mail to the mailing list, please?

**Comment by petr-fischer** [comment]
OK

**Comment by nicolas33** [comment]
Continuing on the mailing list. Thanks.
