### ISSUE TITLE
do not want to deleteing message from local folders when deleted from remote repository

### ISSUE THREAD

**Issue by naveen1336** [OfflineIMAP/offlineimap#211]
is there any setting in offlineimap to restrict offlineimap to delete emails from local repository when deleted from remote repository if possible how to do that

**Comment by manuelRiel** [comment]
There are two settings that may be interesting for you:

`realdelete`: Only removes message labels, but doesn't delete it. Sounds like it was made for Gmail.
`readonly`: Makes the repository read-only, thus only syncing one-way.

The first one may be your best bet, if you are looking to dump all mails in an archive, while still adding new messages.

**Comment by naveen1336** [comment]
is these setting work on [local repository] section of config file

**Comment by ojdo** [comment]
There is [discussion from May in the newsgroup](http://thread.gmane.org/gmane.mail.imap.offlineimap.general/7318) about a patch ([commit here](https://github.com/OfflineIMAP/offlineimap/commit/266c88f7a1b041ba169e0c0cab767bf412c23672)) that introduces a `no-delete-local` option. The patch is quite short, but some issue remain (no dashes in config options) before it can be included.

**Comment by nicolas33** [comment]
Duplicate of #47.
Implemented recently. See #47 for details.

**Comment by naveen1336** [comment]
thanks nicolas33 finally this feature include
