### ISSUE TITLE
Folder creation fails sporadically with "Mailbox already exists."

### ISSUE THREAD

**Issue by m3nu** [OfflineIMAP/offlineimap#212]
On first sync, I need to run offlineimap in a loop due to these errors in folder creation. Some kind of race condition?

`Folder 'INBOX/20 Karajangasse/K&AOQ-ufer/T11 - Gabler'[***_exchange] could not be created. Server responded: ('NO', ['Mailbox already exists.'])`

**Comment by nicolas33** [comment]
Do you have nametrans rules? Also check http://offlineimap.org/doc/FAQ.html#i-get-a-mailbox-already-exists-error.

**Comment by maugsburger** [comment]
I get a similar bug, syncing to an Exchange 2013 server:
```Creating folder INBOX/01 Todo/Trash[info-exc]
Creating folder INBOX/01 Todo[info-exc]
ERROR: Creating folder INBOX/01 Todo on repository info-exc```

Probably, it's because Exchange automatically creates the `INBOX/01 Todo` when `INBOX/01 Todo/Trash` is created - but offlineimap thinks in about parent-folder-less subfolders (as e.g. dovecot supports it).

**Comment by nicolas33** [comment]
Does this error happen again on next sync?

BTW, I think offlineimap should create folders in order of the hierarchy to avoid such issue.

**Comment by maugsburger** [comment]
No, it doesn't happen again on the next sync. I needed to run offlineimap several times until all folders were created successfully, then everything works smoothly.
