### ISSUE TITLE
Open file leak LocalStatus-sqlite

### ISSUE THREAD

**Issue by m3nu** [OfflineIMAP/offlineimap#213]
This was already reported a few years ago, but still persists. When syncing accounts with many folders, offlineimap never closes those sqlite db files. It's easy to verify the issue with lsof. There are hundreds of open files in this path:

`/Users/admin/.offlineimap/Account-marin/LocalStatus-sqlite/`

**Comment by manuelRiel** [comment]
The workaround is to run `ulimit -n 2048` before running offlineimap.

**Comment by nicolas33** [comment]
My ulimit is missing `-n` option...
Care to update the man page?

**Comment by manuelRiel** [comment]
Wouldn't it make more sense to just close those sqlite files, once they're not needed any more?

**Comment by manuelRiel** [comment]
I don't mind changing that, if you point me to the right section in the code. You'll know it better than me.

**Comment by nicolas33** [comment]
Ok. Will check that.

**Comment by nicolas33** [comment]
Looks like closing the db was never implemented! See https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap/folder/LocalStatusSQLite.py

I would implement the missing closing code and see how this module is used to call the new method.

Sorry for the long delay, I forgot about this issue.

**Comment by nicolas33** [comment]
Fixed in 6fb5700f9498fbe85657eaf0624dc1984c202a16.
