### ISSUE TITLE
Setting passwords in keystore is non-trivial

### ISSUE THREAD

**Issue by Profpatsch** [OfflineIMAP/offlineimap#218]
I use the following two functions:

```python
import keyring

def get_password(server, username):
    return keyring.get_password(server, username)

def set_password(server, username, password):
    keyring.set_password(server, username, password)
```

Problem: setting the passwords is a manual act, offlineimap doesn’t use the set_password to save the password it queries.

I tried the following:

```python
import keyring
import getpass
def get_password(server, username):
    pw = keyring.get_password(server, username)
    if not pw:
        pw = getpass.getpass("Password: ")
        set_password(server, username, password)
    return pw
```

but offlineimap’s multithreadedness screws that up (try it!).

What do?

**Comment by nicolas33** [comment]
This feature was not implemented. Learning OfflineIMAP to store a password don't worth it.
