### ISSUE TITLE
pidfile location and usage

### ISSUE THREAD

**Issue by lahwaacz** [OfflineIMAP/offlineimap#229]
To complete the compliance to the XDG standard (see #32), the pidfile should be created in `$XDG_RUNTIME_DIR` instead of the (admittedly configurable) metadata dir.

But more importantly, the pidfile is bound one to one with the metadata dir, but there can be multiple instances of offlineimap per metadata dir (e.g. with different value for the `-a` argument) overwriting their own pidfiles and just changing the location to `$XDG_RUNTIME_DIR` will not help. This leads to a question whether the pidfile is necessary/useful at all. IMHO they are traditionally used by daemon managers to keep track of processes, for which they need to be able to set custom pidfile path per-instance.

**Comment by nicolas33** [comment]
Done in 141abfdf5066ecaed37742d6985ef4834b1cafa0.
