### ISSUE TITLE
Working example script with spam filter?

### ISSUE THREAD

**Issue by dpo** [OfflineIMAP/offlineimap#230]
I've been trying to get bogofilter to append a spam header to my incoming messages without success. I just can't find an example out there that explains how to set up spam filtering when e-mail is fetched with `offlineimap`. I'm not running an e-mail server. I'm simply synchronizing several IMAP accounts locally. I use Mutt to read messages. All is well except for spam filtering.

Here's what I tried. I installed bogofilter and in my `~/.offlineimaprc`, I have
```
postsynchook = ~/bin/process-new-mail ~/Mail/Account1
```

In `~/bin/process-new-mail`, I have
```
check_spam() {
  # Protect against paths with white space
  SAVEIFS=$IFS
  IFS=$(echo -en "\n\b");
  new=$(find $1/INBOX/new -type f)
  for f in $new
  do
    bogofilter -u -p -I $f -O $1/INBOX-processed/new/$(basename $f)
  done
  IFS=$SAVEIFS
}

check_spam $1
```

The main idea is that `offlineimap` places new email in `~/Mail/Account1/INBOX/new`. Bogofilter will look for it there and place processed files in `~/Mail/Account1/INBOX-processed/new`. Mutt will look for new messages in the latter location.

If I run `~/bin/process-new-mail ~/Mail/Account1` from the command line, all is well. But if the script is run from `offlineimap`'s `postsynchook`, there's only garbage in the output location. Mutt can't make sense of it and locks up.

Could anyone share a working setup?

**Comment by nicolas33** [comment]
I could not reproduce this error. I think there's no need to change IFS and the "new" variable is useless.

I think that blindly marking emails as good with `-u` is going against bogofilter way of working.

Perhaps, adding the correct shebang would help.
