### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by capi** [OfflineIMAP/offlineimap#231]
I was trying to backup a very old server of mine, using current `master` branch, on an `Ubuntu 14.04 LTS 32-bit` box with `Python 2.7.6`:

    Copy message from remote-dpc-carp0001:INBOX:
     ERROR: Copying message 262355 [acc: dpc-carp0001]
      Python int too large to convert to C long
    Thread 'Copy message from remote-dpc-carp0001:INBOX' terminated with exception:
    Traceback (most recent call last):
      File "/mnt/data/homes/martin/projects-local/offlineimap/offlineimap/threadutil.py", line 163, in run
        Thread.run(self)
      File "/usr/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/mnt/data/homes/martin/projects-local/offlineimap/offlineimap/folder/Base.py", line 775, in copymessageto
        new_uid = dstfolder.savemessage(uid, message, flags, rtime)
      File "/mnt/data/homes/martin/projects-local/offlineimap/offlineimap/folder/Maildir.py", line 355, in savemessage
        os.utime(os.path.join(self.getfullname(), tmpname), (date, date))
    OverflowError: Python int too large to convert to C long
    
    
    Last 3 debug messages logged for Copy message from remote-dpc-carp0001:INBOX prior to exception:
    thread: Register new thread 'Copy message from remote-dpc-carp0001:INBOX' (account 'dpc-carp0001')
    imap: Returned object from fetching 262355: 'Received: from Home-83.pucioasa.optinet.ro (unknown [86.55.83.38])
            by mail.vnet1.dont-panic.cc (Postfix) with ESMTP id 693F0D125
            for <administrative...------=_NextPart_000_0023_7A_2227A1B8.21BBBA1B--
    
    '
    maildir: Write mail 'INBOX:262355' with flags set([])
    ERROR: Exceptions occurred during the run!
    ERROR: Copying message 262355 [acc: dpc-carp0001]
      Python int too large to convert to C long
    
    Traceback:
      File "/mnt/data/homes/martin/projects-local/offlineimap/offlineimap/folder/Base.py", line 775, in copymessageto
        new_uid = dstfolder.savemessage(uid, message, flags, rtime)
      File "/mnt/data/homes/martin/projects-local/offlineimap/offlineimap/folder/Maildir.py", line 355, in savemessage
        os.utime(os.path.join(self.getfullname(), tmpname), (date, date))

**Comment by capi** [comment]
Issue is caused by `utime_from_header = yes` for the local repository and a SPAM message that is quite far in the future, exceeding `int32` as timestamp.

The message's date header is:

    Date: Thu, 03 Sep 3610 21:32:03 +0300

Maybe a check should be added if the date is that far in the future and set to native C's `long` max-value (depending if `i386` or `amd64`).

**Comment by nicolas33** [comment]
On Thu, Aug 27, 2015 at 12:31:53PM -0700, Martin Carpella wrote:
>    Issue is caused by utime_from_header = yes for the local repository and
>    a SPAM message that is quite far in the future, exceeding int32 as
>    timestamp.
> 
>    The message's date header is:
> Date: Thu, 03 Sep 3610 21:32:03 +0300
> 
>    Maybe a check should be added if the date is that far in the future and
>    set to native C's long max-value (depending if i386 or amd64).

Aargh. This should be a rare case. I think it would be better to just
discard the offending mail and notice the user. Playing with data type
is annoying, code intrusive and prone to errors.

Patches welcome.

>    —
>    Reply to this email directly or [1]view it on GitHub.
> 
> References
> 
>    1. https://github.com/OfflineIMAP/offlineimap/issues/231#issuecomment-135530756

-- 
Nicolas Sebrecht

**Comment by capi** [comment]
Wouldn't it be necessary even for properly discarding the message to check it against the platforms `long` max-value? Or would you just catch and handle the `OverflowError`?

**Comment by nicolas33** [comment]
On Thu, Aug 27, 2015 at 01:57:03PM -0700, Martin Carpella wrote:
>    Wouldn't it be necessary even for properly discarding the message to
>    check it against the platforms long max-value? Or would you just catch
>    and handle the OverflowError?

Catch and handle the overflow so that code is less tricky.

-- 
Nicolas Sebrecht

**Comment by nicolas33** [comment]
On Thu, Aug 27, 2015 at 10:48:29PM +0200, Nicolas Sebrecht wrote:
>On Thu, Aug 27, 2015 at 12:31:53PM -0700, Martin Carpella wrote:
>>    Issue is caused by utime_from_header = yes for the local repository and
>>    a SPAM message that is quite far in the future, exceeding int32 as
>>    timestamp.
>>
>>    The message's date header is:
>> Date: Thu, 03 Sep 3610 21:32:03 +0300
>>
>>    Maybe a check should be added if the date is that far in the future and
>>    set to native C's long max-value (depending if i386 or amd64).
>
>Aargh. This should be a rare case. I think it would be better to just
>discard the offending mail and notice the user. Playing with data type
>is annoying, code intrusive and prone to errors.
>
>Patches welcome.

OK, how about this:

--------

Handle out-of-bounds dates

Handle case where email's internal time is erroneously so large as to
cause overflow errors when setting file modification time with
utime_from_header = true.

Signed-off-by: Janna Martl <janna.martl109@gmail.com>
---
 offlineimap/folder/Maildir.py | 16 +++++++++++++---
 1 file changed, 13 insertions(+), 3 deletions(-)

diff --git a/offlineimap/folder/Maildir.py b/offlineimap/folder/Maildir.py
index 3f5c071..f969390 100644
--- a/offlineimap/folder/Maildir.py
+++ b/offlineimap/folder/Maildir.py
@@ -350,9 +350,19 @@ class MaildirFolder(BaseFolder):
         tmpname = self.save_to_tmp_file(messagename, content)
 
         if self.utime_from_header:
-            date = emailutil.get_message_date(content, 'Date')
-            if date != None:
-                os.utime(os.path.join(self.getfullname(), tmpname), (date, date))
+            try:
+                date = emailutil.get_message_date(content, 'Date')
+                if date != None:
+                    os.utime(os.path.join(self.getfullname(), tmpname),
+                        (date, date))
+            # In case date is wrongly so far into the future as to be > max int32
+            except:
+                from email.Parser import Parser
+                from offlineimap.ui import getglobalui
+                datestr = Parser().parsestr(content, True).get("Date")
+                ui = getglobalui()
+                ui.warn("UID %d has invalid date %s; not changing file "\
+                    "modification time" % (uid, datestr))
 
         self.messagelist[uid] = self.msglist_item_initializer(uid)
         self.messagelist[uid]['flags'] = flags
-- 
2.5.0

**Comment by OI-mailinglist** [comment]
On 28Aug2015 17:38, Nicolas Sebrecht <notifications@github.com> wrote:
>On Thu, Aug 27, 2015 at 10:48:29PM +0200, Nicolas Sebrecht wrote:
>>Patches welcome.
>OK, how about this:
[...]
>+                date = emailutil.get_message_date(content, 'Date')
>+                if date != None:

Please, use "is not".

>+                    os.utime(os.path.join(self.getfullname(), tmpname),
>+                        (date, date))
>+            # In case date is wrongly so far into the future as to be > max int32
>+            except:

Please warn about the exception and the date causing it.

Tahnks,
Cameron Simpson <cs@zip.com.au>

**Comment by nicolas33** [comment]
On Fri, Aug 28, 2015 at 08:38:21PM -0400, Janna Martl wrote:

> OK, how about this:
> 
> --------

Git supports scissors line but it must have 8< or >8 like this:

  --->8---

It will remove everything above. See
https://www.kernel.org/pub/software/scm/git/docs/git-mailinfo.html

,-)

> 
> Handle out-of-bounds dates
> 
> Handle case where email's internal time is erroneously so large as to
> cause overflow errors when setting file modification time with
> utime_from_header = true.
> 
> Signed-off-by: Janna Martl <janna.martl109@gmail.com>
> ---
>  offlineimap/folder/Maildir.py | 16 +++++++++++++---
>  1 file changed, 13 insertions(+), 3 deletions(-)

Patch looks fine to me. Will merge. Thank you.

-- 
Nicolas Sebrecht

**Comment by nicolas33** [comment]
On Sat, Aug 29, 2015 at 12:48:20AM -0700, OfflineIMAP mailing list wrote:

> >+ date = emailutil.get_message_date(content, 'Date')
> >+ if date != None:

>    Please, use "is not".

Correct.

> >+ os.utime(os.path.join(self.getfullname(), tmpname),
> >+ (date, date))
> >+ # In case date is wrongly so far into the future as to be > max
>    int32
> >+ except:

Correct.

I'm fine with the patch as-is because it's enough to make OfflineIMAP
stable. A new patch with the suggested changes included would obviously
be better.

IOW, I'll wait to see if someone comes with a better patch or I'll merge
this one.

Thanks!

-- 
Nicolas Sebrecht

**Comment by nicolas33** [comment]
Applied: ee0de28cc457b6983f1e75cf28748f5a16320ed9
