### ISSUE TITLE
`getfolder() asked for a nonexisting folder` on a read-only Gmail repository

### ISSUE THREAD

**Issue by ildar** [OfflineIMAP/offlineimap#241]
> Account sync Maildir2Gmail:
>  *** Processing account Maildir2Gmail
>  Establishing connection to imap.gmail.com:993
>  ERROR: getfolder() asked for a nonexisting folder '[Gmail]/&BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-'.
>  *** Finished account 'Maildir2Gmail' in 0:19
> ERROR: Exceptions occurred during the run!
> ERROR: getfolder() asked for a nonexisting folder '[Gmail]/&BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-'.

I want to export Maildir to Gmail, so I
> [Repository Maildir]
> type = Maildir
> localfolders = ~/Mail
> sep = /
> readonly = True
> nametrans = lambda foldername: 'import/' + foldername 
> [Repository Gmail_acc]
> type = Gmail
> nametrans = lambda folder: re.sub('import/', '', folder)

Why does it complain on Gmail folders? I don't care about them, don't want to sync them at all!

**Comment by nicolas33** [comment]
Try filtering them out.

**Comment by ildar** [comment]
Did it. But IMHO that should be fixed in code... someday. So emergency ==
minor.

**Comment by prologic** [comment]
I've run into this issue as well. Can someone explain what this means exactly? I have a remote IMAP folder called "Archive" and I get:
```
#!bash
 ERROR: getfolder() asked for a nonexisting folder 'Archive'.
 *** Finished account 'main' in 0:01
ERROR: Exceptions occurred during the run!
ERROR: getfolder() asked for a nonexisting folder 'Archive'.

Traceback:
  File "/Users/prologic/lib/python2.7/site-packages/offlineimap/accounts.py", line 263, in syncrunner
    self.__sync()
  File "/Users/prologic/lib/python2.7/site-packages/offlineimap/accounts.py", line 343, in __sync
    localfolder = self.get_local_folder(remotefolder)
  File "/Users/prologic/lib/python2.7/site-packages/offlineimap/accounts.py", line 292, in get_local_folder
    replace(self.remoterepos.getsep(), self.localrepos.getsep()))
  File "/Users/prologic/lib/python2.7/site-packages/offlineimap/repository/Maildir.py", line 150, in getfolder
    OfflineImapError.ERROR.FOLDER)
```

I don't understand why I cannot synchronize my remote folders :/

**Comment by nicolas33** [comment]
Some users hitting this issue might be due to #148.

**Comment by nicolas33** [comment]
Please, provide your configuration file.

**Comment by nicolas33** [comment]
Closing. Open a new issue if you hit this again.
