### ISSUE TITLE
Removal of "maxage" for imap-to-imap sync in 6.5.7 causes duplication of messages on sync

### ISSUE THREAD

**Issue by lmoellendorf** [OfflineIMAP/offlineimap#242]
When upgrading to 6.5.7 I saw that "maxage" is not supported for imap to imap sync anymore.
I sync my local dovecot (on localhost) with several remote imap servers
Dovecot uses a Maildir directory structure on my local disk.

When syncing with offlineimap 6.5.7 with "maxage" removed from the config all mails older then the previously set maxage are duplicated on each and every sync!

How can I safely upgrade to 6.5.7?
Is it safe to sync the remote hosts directly with dovecot's Maildir directories? I am working on my dovecot imap accounts most of the time. Will all my flags be synced when syncing directly to Maildir?

**Comment by nicolas33** [comment]
Not syncing flags is a CLI option.

What do you mean by

> When syncing with offlineimap 6.5.7 with "maxage" removed from the config all mails older then the previously set maxage are duplicated on each and every sync!

**Comment by lmoellendorf** [comment]
I updated offlineimap to version 6.5.7.

When I started offlineimap it refused to start because I had `maxage=360` set.

I removed `maxage` and restarted offlineimap. 
offlineimap started to upload all mails older then 360 days.
I realized this is not a good idea and killed offlineimap.

I downgraded offlineimap to version 6.5.6 and added `maxage=360` again.
When starting offlineimap it began to download mails from the remote IMAP which were already on my local IMAP server. I killed offlineimap.
I started offlineimap again and it downloaded the same mails another time so the mails were tripled.

**Comment by nicolas33** [comment]
Ok. First, there are good tools to remove duplicates, like mutt.

About the maxage removal with v6.5.7, does this help ? http://offlineimap.org/devel/2015/04/14/why-we-changed-maxage.html

**Comment by lmoellendorf** [comment]
> Ok. First, there are good tools to remove duplicates, like mutt.

I know, I use mutt. But this does not help if offlineimap duplicates all messages at each sync. However, this may be another, not related, issue.

> About the maxage removal with v6.5.7, does this help ? http://offlineimap.org/devel/2015/04/14/why-we-changed-maxage.html

Thank you, this was very helpful. And it also explained strange behaviour with one particular mailbox and maxage I had in the past.

One question is still not answered:

Is it possible and save to sync the remote IMAP directly with the local  Maildir directories and host those Maildir directories in dovecot (at the same time)?

Like this:
```                                                                
                                                                
   +--------------+          +--------------+      +----------+ 
   |              |          |              |      |          | 
   | remote IMAP  |          |  local IMAP  |      |  MUA     | 
   |              |          |  (dovecot)   +------+  (mutt)  | 
   +-------^------+          |              |      |          | 
           |                 +--------------+      +----------+ 
           |                       |                            
           |syncs                  |hosts                       
           |                       |                            
           |                       |                            
   +---------------+         +-----v-----+                      
   |               |         |           |                      
   |  offlineimap  |   syncs |  local    |                      
   |               +--------->  Maildir  |                      
   +---------------+         |           |                      
                             +-----------+                      
                                                                
````

(Hope this ascii drawing is readable)

**Comment by nicolas33** [comment]
I could see the drawing by pasting it in vim which displays the content with fixed fonts.

I've contacted the maintainer of Dovecot in a recent past about that. It's supported by Dovecot to feed its maildir database "behind its back". There's an option to _not_ enable about quick IMAP rendering because Dovecot will cache the Maildir in RAM. I can't remember the name of this option. This might worth a documentation page in the website. ,-)

**Comment by lmoellendorf** [comment]
Ok, I will do a backup of my mails and try it. 

Here is what I found in the Dovecot Wiki:

* [Maildir - Dovecot extensions](http://wiki2.dovecot.org/MailboxFormat/Maildir)

> Since the standard maildir specification doesn't provide everything needed to fully support the IMAP protocol, Dovecot had to create some of its own non-standard extensions. The extensions still keep the maildir standards compliant, so MUAs not supporting the extensions can still safely use it as a normal maildir. 

* [Syncing - Locking] (http://wiki2.dovecot.org/MailboxFormat/Maildir)

> Although maildir was designed to be lockless, Dovecot locks the maildir while doing modifications to it or while looking for new messages in it. This is required because otherwise Dovecot might temporarily see mails incorrectly deleted, which would cause trouble. Basically the problem is that if one process modifies the maildir (eg. a rename() to change a message's flag), another process in the middle of listing files at the same time could skip a file. The skipping happens because readdir() system call doesn't guarantee that all the files are returned if the directory is modified between the calls to it. This problem exists with all the commonly used filesystems.
>
> Because Dovecot uses its own non-standard locking (dovecot-uidlist.lock dotlock file), other MUAs accessing the maildir don't support it. This means that if another MUA is updating messages' flags or expunging messages, Dovecot might temporarily lose some message. After the next sync when it finds it again, an error message may be written to log and the message will receive a new UID.
>
> Delivering mails to new/ directory doesn't have any problems, so there's no need for LDAs to support any type of locking. 

* [Optimizations] (http://wiki2.dovecot.org/MailLocation/Maildir)

> maildir_very_dirty_syncs=yes: Assume that only Dovecot accesses cur/ directory. If another process (or even Dovecot which doesn't update index files) does changes to cur/ while the mailbox is simultaneously being modified by Dovecot, Dovecot may not notice those external changes. It's still safe to deliver new mails to new/ using non-Dovecot software. 

I will make sure `maildir_very_dirty_syncs=no` is set in `/etc/dovecot/conf.d/10-mail.conf`.

* [Index, Cache and Transaction log] (http://wiki.dovecot.org/IndexFiles)

> Mailbox synchronization
>
> The main index's header also contains mailbox syncing state:
>
>  * *Maildir: cur/ and new/ directories' timestamps*
>  * mbox: mbox file's mtime and size
>
> *The index file is synchronized against mailbox only if the syncing information changes.*

[...]

> Cache
>
> Only the mailbox metadata that client(s) have asked for earlier are stored into cache file. This allows Dovecot to be adaptive to different clients' needs and still not waste disk space (and cause extra disk I/O!) for fields that client never needs.

[...]

> Transaction log
>
> All changes to the main index go through transaction log first. This has two advantages when the mailbox is accessed using multiple simultaneous connections:
>
>    It allows getting a list of changes quickly so that IMAP clients can be notified of the changes. An alternative would be to do a comparison of two index mappings, which is what most other IMAP servers do.
>
>    *mmap_disable=yes implementation relies on the transaction log. Instead of re-reading the whole main index file after each change it's necessary to only read a few bytes from the transaction log.* 

* [Mail processes](http://wiki1.dovecot.org/MainConfig#Mail_processes)

> mmap_disable = no
>    Don't use mmap() at all. This is required if you store indexes to shared filesystems (NFS or clustered filesystem). 

  * [man mmap](http://linux.die.net/man/2/mmap)

> map [...] files [...] into memory

* [Memory mapping](http://wiki1.dovecot.org/MailLocation/SharedDisk)

> By default Dovecot mmap()s the index files. This may not work with all clustered filesystems, and it most certainly won't work with NFS. *Setting mmap_disable = yes disables mmap() and Dovecot does its own internal caching.* If mmap() is supported by your filesystem, it's still not certain that it gives better performance. Try benchmarking to make sure. 

Not sure if setting `mmap_disable = yes` in `/etc/dovecot/conf.d/10-mail.conf` has any positive effect?

* [Fsyncing](http://wiki1.dovecot.org/MailLocation/LocalDisk)

> By default Dovecot calls fsync() and fdatasync() whenever it's useful to prevent potential data loss. The main reason for this is so that Dovecot won't lie that the message was saved to the disk, if in fact a power failure a second later would lose the message. With IMAP clients this is perhaps a less serious problem, because the lost message was most likely either a mail in Draft mailbox or a message in "Sent Messages" mailbox. In any case a message that the user had already seen. However if Dovecot LDA loses a message, the user never even knew that the message existed, unless the sender decides to resend it.
>
> Since power failures and kernel panics are quite rare, many people are tempted to disable fsyncing because it may increase the performance quite a lot. Dovecot allows this since v1.0.rc27 by setting fsync_disable=yes.

<pre># When to use fsync() or fdatasync() calls:
#   optimized (default): Whenever necessary to avoid losing important data
#   always: Useful with e.g. NFS when write()s are delayed
#   never: Never use it (best performance, but crashes can lose data)
#mail_fsync = optimized
</pre>

I will make sure  `mail_fsync = always` is set in `/etc/dovecot/conf.d/10-mail.conf`.

**Comment by nicolas33** [comment]
OfflineIMAP doesn't uses mmap and Dovecot's mmap is about its own index file which is not a maildir thing. So, options about mmap and the index are out of OfflineIMAP.

I'm not sure why you want so aggressive fsync. `mail_fsync = optimized` looks good and what you want unless you use NFS.

I'm not a Dovecot expert nor a user of it. Thanks for all those docs. If someone is willing to write a documentation page about Dovecot, I'll help. :)

**Comment by lmoellendorf** [comment]
nicolas33: Yes, you are right. I mixed up syncing the cache with the actual
state of the Maidir and syncing of the data held in RAM to the file system.

I tried to sync between IMAP and Maildir without success.

Before syncing with offlineimap I had these folders in Maildir:

```
.ads
.archive
.drafts
.forums
.providers
.sent
.support
.trash
.webshops
cur
new
tmp
```
After syncing with offlineimap I get this folders:

```
.
..
.ads
.archive
.drafts
.forums
.providers
.sent
.support
.trash
.webshops
INBOX
Postausgang
cur
drafts
maildirfolder
new
sent
subscriptions
tmp
trash
```

I don't know where the folders "maildirfolder" and "subscriptions" come from.
Maybe the e-mail provider added those.

Additionally I get this errror:

```
$ offlineimap -c /home/user/offlineimapfiles/offlineimaprc.hermes
OfflineIMAP 6.5.7
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync hermes@whatever.org:
 *** Processing account hermes@whatever.org
 Establishing connection to imap.whatever.org:993
 Creating folder Postausgang[hermes@whatever.org-Local]
 Creating folder drafts[hermes@whatever.org-Local]
 Creating folder INBOX[hermes@whatever.org-Local]
 Creating folder trash[hermes@whatever.org-Local]
 Creating folder sent[hermes@whatever.org-Local]
 Creating folder /[hermes@whatever.org-Remote]
 ERROR: Creating folder  on repository hermes@whatever.org-Remote
  Folder '/'[hermes@whatever.org-Remote] could not be created. Server responded: ('NO', ['unsupported folder name'])
 ERROR: Folder '/'[hermes@whatever.org-Remote] could not be created. Server responded: ('NO', ['unsupported folder name'])
 *** Finished account 'hermes@whatever.org' in 0:00
ERROR: Exceptions occurred during the run!
ERROR: Creating folder  on repository hermes@whatever.org-Remote
  Folder '/'[hermes@whatever.org-Remote] could not be created. Server responded: ('NO', ['unsupported folder name'])

Traceback:
  File "/usr/lib64/python2.7/site-packages/offlineimap/repository/Base.py", line 242, in sync_folder_structure
    src_repo.makefolder(dst_name_t)
  File "/usr/lib64/python2.7/site-packages/offlineimap/repository/IMAP.py", line 434, in makefolder
    OfflineImapError.ERROR.FOLDER)

ERROR: Folder '/'[hermes@whatever.org-Remote] could not be created. Server responded: ('NO', ['unsupported folder name'])

Traceback:
  File "/usr/lib64/python2.7/site-packages/offlineimap/accounts.py", line 263, in syncrunner
    self.__sync()
  File "/usr/lib64/python2.7/site-packages/offlineimap/accounts.py", line 329, in __sync
    remoterepos.sync_folder_structure(localrepos, statusrepos)
  File "/usr/lib64/python2.7/site-packages/offlineimap/repository/Base.py", line 242, in sync_folder_structure
    src_repo.makefolder(dst_name_t)
  File "/usr/lib64/python2.7/site-packages/offlineimap/repository/IMAP.py", line 434, in makefolder
    OfflineImapError.ERROR.FOLDER)
```

This is my config:

```
[general]
accounts = hermes@whatever.org
maxsyncaccounts = 6
status_backend = plain
ui = TTYUI

[Account hermes@whatever.org]
localrepository = hermes@whatever.org-Local
remoterepository = hermes@whatever.org-Remote

[Repository hermes@whatever.org-Local]
type = Maildir
localfolders = "/home/user/Maildir/hermes@whatever.org"
maxage = 720
nametrans = lambda foldername: foldername.replace('drafts', 'Entwurf').replace('trash', 'Papierkorb').replace('sent', 'Gesendet')

[Repository hermes@whatever.org-Remote]
type = IMAP
remotehost = imap.whatever.org
remoteuser = hermes@whatever.org
ssl = yes
remotepassfile = ~/offlineimapfiles/Password.IMAP.hermes@whatever.org
nametrans = lambda foldername: foldername.replace('Entwurf', 'drafts').replace('Papierkorb', 'trash').replace('Gesendet', 'sent')
```

And here are my questions:

* Can I tell offlineimap to respect the existing dovecot Maildir structure and use leading dots for the mail folders?
* What does the error message mean? Is offlineimap misinterpreting the leading dots of the mail folders and trying to create a root folder ('/') ?

**Comment by nicolas33** [comment]
On Mon, Sep 28, 2015 at 12:08:52PM -0700, Lars Möllendorf wrote:

>    I don't know where the folders "maildirfolder" and "subscriptions" come
>    from.
>    Maybe the e-mail provider added those.

Yes. Sometimes, mail providers don't show all the folders (reachable
with IMAP) in their web interface. You might want to filter them.

>    And here are my questions:
>      * Can I tell offlineimap to respect the existing dovecot Maildir
>        structure and use leading dots for the mail folders?

It looks like it does since it didn't created directories named webshops
or support.

>      * What does the error message mean? Is offlineimap misinterpreting
>        the leading dots of the mail folders and trying to create a root
>        folder ('/') ?

Yes. I don't know why it tries to create this / directory. Try playing
with the sep option. AFAICT, you might need to fix it to dot.

I think the maildir structure of your mail provider doesn't match the
Dovecot's structure. I guess you have to configure more nametrans rules
so they match each other.  I encourage you to play outside the real
Dovecot's maildir until they match.

-- 
Nicolas Sebrecht

**Comment by lmoellendorf** [comment]
These are the local (dovecot) mailboxes:

.ads
.archive
.drafts
.forums
.providers
.sent
.support
.trash
.webshops

These are the remote mailboxes:

Entwurf
Gesendet
INBOX
Papierkorb
Postausgang

Please note: I had the other mailboxes (ads, archive, forums, providers, support, webshops) before, but I deleted them.

My nametrans rules are:

// remote -> local
nametrans = lambda foldername: foldername.replace('Entwurf', 'drafts').replace('Papierkorb', 'trash').replace('Gesendet', 'sent')

The only mailbox missing is "Postausgang" which I don't need locally

When I start offlineimap with the config above, the local mailbox list looks like this:

.ads
.archive
.drafts
.forums
.providers
.sent
.support
.trash
.webshops
INBOX
Postausgang
cur
drafts
new
sent
tmp
trash

So apparently offlineimap created "INBOX" instead of using the existing "cur"/"new"/"tmp"
"drafts" instead of using ".drafts"
"sent" instead of using ".sent"
"trash" instead of using ".trash"
And "Postausgang" should be ".Postausgang".

Please have a look at "Directory Structure" (http://wiki2.dovecot.org/MailboxFormat/Maildir):

> By default Dovecot uses Maildir++ directory layout for organizing mailbox directories. This means that all the folders are directly inside ~/Maildir directory:
>
>    ~/Maildir/new, ~/Maildir/cur and ~/Maildir/tmp directories contain the messages for INBOX. The tmp directory is used during delivery, new messages arrive in new and read shall be moved to cur by the clients.
>
>    ~/Maildir/.folder/ is a mailbox folder
>
>    ~/Maildir/.folder.subfolder/ is a subfolder of a folder (ie. "folder/subfolder") 
>
>
> You can also optionally use the "fs" layout by appending :LAYOUT=fs to mail_location. This makes the folder structure look like:
>
>    ~/Maildir/new, ~/Maildir/cur and ~/Maildir/tmp directories contain the messages for INBOX, just like with Maildir++.
>
>    ~/Maildir/folder/ is a mailbox folder
>
>    ~/Maildir/folder/subfolder/ is a subfolder of a folder 

Seems like my dovecot instance uses Maildir++. Please note, that even the fs-layout does not have "INBOX" but  "cur"/"new"/"tmp".

Is offlineimap capable to manage Maildir++?

**Comment by nicolas33** [comment]
On Wed, Sep 30, 2015 at 02:31:06PM -0700, Lars Möllendorf wrote:

>    My nametrans rules are:
> 
>    // remote -> local
>    nametrans = lambda foldername: foldername.replace('Entwurf',
>    'drafts').replace('Papierkorb', 'trash').replace('Gesendet', 'sent')

Why don't you use rules like `foldername.replace('Entwurf', '.drafts')`
with the dot?

>    The only mailbox missing is "Postausgang" which I don't need locally
> 
>    When I start offlineimap with the config above, the local mailbox list
>    looks like this:
> 
>    .ads
>    .archive
>    .drafts
>    .forums
>    .providers
>    .sent
>    .support
>    .trash
>    .webshops
>    INBOX
>    Postausgang
>    cur
>    drafts
>    new
>    sent
>    tmp
>    trash
> 
>    So apparently offlineimap created "INBOX" instead of using the existing
>    "cur"/"new"/"tmp"

I don't see that cur/tmp/new are existing before the first sync, above.

>    "drafts" instead of using ".drafts"
>    "sent" instead of using ".sent"
>    "trash" instead of using ".trash"
>    And "Postausgang" should be ".Postausgang".

I'd say you have to fix your nametrans rules. OfflineIMAP looks to do
the right thing.

> 
>    Please have a look at "Directory Structure"
>    ([1]http://wiki2.dovecot.org/MailboxFormat/Maildir):

I'm aware of IMAP protocol, Maildir format, etc; thanks.

>      By default Dovecot uses Maildir++ directory layout for organizing
>      mailbox directories. This means that all the folders are directly
>      inside ~/Maildir directory:
> 
>      ~/Maildir/new, ~/Maildir/cur and ~/Maildir/tmp directories contain
>      the messages for INBOX. The tmp directory is used during delivery,
>      new messages arrive in new and read shall be moved to cur by the
>      clients.
> 
>      ~/Maildir/.folder/ is a mailbox folder
> 
>      ~/Maildir/.folder.subfolder/ is a subfolder of a folder (ie.
>      "folder/subfolder")
> 
>      You can also optionally use the "fs" layout by appending :LAYOUT=fs
>      to mail_location. This makes the folder structure look like:

I don't know if the fs layout can help but the "INBOX path" section in
http://wiki.dovecot.org/MailLocation looks very interesting for you.

>    Is offlineimap capable to manage Maildir++?

Maildir++ can be read as a Maildir database, so yes.

-- 
Nicolas Sebrecht

**Comment by lmoellendorf** [comment]
> I don't see that cur/tmp/new are existing before the first sync, above.

Sorry, a copy paste error.

> Why don't you use rules like `foldername.replace('Entwurf', '.drafts')`
> with the dot?

This approach was not obvios to me. I used the same nametrans rules for
imap-to-imap sync and back then there was no need to translate from mailbox name to
Maidir path.

> I'd say you have to fix your nametrans rules. OfflineIMAP looks to do
> the right thing.

So I have to setup a rule for each and every folder name? And whenever I add a
folder I have to adjust the offlineimap config?

I now have these rules:

```
nametrans = lambda foldername: foldername.replace('.drafts', 'Entwurf').replace('.trash', 'Papierkorb').replace('.sent', 'Gesendet').replace('/', 'INBOX').replace('.ads', 'ads').replace('.archive', 'archive').replace('.forums', 'forums').replace('.providers', 'providers').replace('.support', 'support').replace('.webshops', 'webshops')

nametrans = lambda foldername: foldername.replace('Entwurf', '.drafts').replace('Papierkorb', '.trash').replace('Gesendet', '.sent').replace('INBOX', '/').replace('ads', '.ads').replace('archive', '.archive').replace('forums', '.forums').replace('providers', '.providers').replace('support', '.support').replace('webshops', '.webshops')
```

And no dotless folders are created in the Maildir anymore. However, the error about '/' still exists:

```
OfflineIMAP 6.5.7
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync hermes@whatever.org:
 *** Processing account hermes@whatever.org
 Establishing connection to imap.whatever.org:993
 Creating folder /[hermes@whatever.org-Remote]
 ERROR: Creating folder  on repository hermes@whatever.org-Remote
  Folder '/'[hermes@whatever.org-Remote] could not be created. Server responded: ('NO', ['unsupported folder name'])
 ERROR: Folder '/'[hermes@whatever.org-Remote] could not be created. Server responded: ('NO', ['unsupported folder name'])
 *** Finished account 'hermes@whatever.org' in 0:00
ERROR: Exceptions occurred during the run!
ERROR: Creating folder  on repository hermes@whatever.org-Remote
  Folder '/'[hermes@whatever.org-Remote] could not be created. Server responded: ('NO', ['unsupported folder name'])

Traceback:
  File "/usr/lib64/python2.7/site-packages/offlineimap/repository/Base.py", line 242, in sync_folder_structure
    src_repo.makefolder(dst_name_t)
  File "/usr/lib64/python2.7/site-packages/offlineimap/repository/IMAP.py", line 434, in makefolder
    OfflineImapError.ERROR.FOLDER)

ERROR: Folder '/'[hermes@whatever.org-Remote] could not be created. Server responded: ('NO', ['unsupported folder name'])

Traceback:
  File "/usr/lib64/python2.7/site-packages/offlineimap/accounts.py", line 263, in syncrunner
    self.__sync()
  File "/usr/lib64/python2.7/site-packages/offlineimap/accounts.py", line 329, in __sync
    remoterepos.sync_folder_structure(localrepos, statusrepos)
  File "/usr/lib64/python2.7/site-packages/offlineimap/repository/Base.py", line 242, in sync_folder_structure
    src_repo.makefolder(dst_name_t)
  File "/usr/lib64/python2.7/site-packages/offlineimap/repository/IMAP.py", line 434, in makefolder
    OfflineImapError.ERROR.FOLDER)
```

Are these nametrans rules wrong?:

```
[...].replace('/', 'INBOX')[...]
[...].replace('INBOX', '/')[...]
```

> I don't know if the fs layout can help but the "INBOX path" section in
> http://wiki.dovecot.org/MailLocation looks very interesting for you.

Do you mean I should move my local INBOX to .INBOX or something like that?

**Comment by nicolas33** [comment]
On Sat, Oct 03, 2015 at 08:22:54AM -0700, Lars Möllendorf wrote:

>    So I have to setup a rule for each and every folder name? And whenever
>    I add a
>    folder I have to adjust the offlineimap config?

No. Write a more generic rule using regexp.

>    And no dotless folders are created in the Maildir anymore.

Good.

>                                                               However, the
>    error about '/' still exists:

Ok. I believe I understand what's going on. OfflineIMAP detects the
new/cur/tmp at the root of the maildir. Hence, it's trying to create a
folder with name '/' on the remote. It's a bug #255.

>    Are these nametrans rules wrong?:
> [...].replace('/', 'INBOX')[...]
> [...].replace('INBOX', '/')[...]

No, but they won't apply. They are inefficient.

>    Do you mean I should move my local INBOX to .INBOX or something like
>    that?

No, I mean you should fix the INBOX layout at the Dovecot's side rather
than at OfflineIMAP's side.  Dovecot's default is to use the root of the
maildir as INBOX. That's why you have new/tmp/cur before any sync.

The idea is to tell Dovecot to use a dedicated folder instead (whatever
name you want):

```
-> maildir
   -> INBOX
      -> new
      -> cur
      -> tmp
   -> .anotherFolder
      -> new
      -> cur
      -> tmp
```

-- 
Nicolas Sebrecht

**Comment by lmoellendorf** [comment]
FYI

These are the relevant configuration steps:

in offlineimaprc:
```
[general]
accounts = hermes@whatever.org

[Account hermes@whatever.org]
localrepository = hermes@whatever.org-Local
remoterepository = hermes@whatever.org-Remote
maxage = 360

[Repository hermes@whatever.org-Local]
type = Maildir
localfolders = /home/user/Maildir/hermes@whatever.org
# Note: the lstrip('.') removes the leading dot from the folder names
# This is not needed if you use "fs" layout http://wiki2.dovecot.org/MailboxFormat/Maildir
# The replace() functions are just examples for adding additional nametrans rules
# which are applied *after* the leading dots have been removed.
nametrans = lambda foldername: foldername.lstrip('.').replace('drafts', 'Entwurf').replace('trash', 'Papierkorb').replace('sent', 'Gesendet')

[Repository hermes@whatever.org-Remote]
type = IMAP
remotehost = imap.whatever.org
remoteuser = hermes@whatever.org
ssl = yes
remotepassfile = ~/Projekte/sources/offlineimapfiles/Password.IMAP.hermes@whatever.org
# Note: the '.'+foldername prepends the missing dot to the folder names
# The replace() functions are just examples for adding additional nametrans rules
# which are applied *before* the leading dots are added.
nametrans = lambda foldername: '.'+foldername.replace('Entwurf', 'drafts').replace('Papierkorb', 'trash').replace('Gesendet', 'sent')
```

In dovecot make sure to specify the INBOX path (http://wiki.dovecot.org/MailLocation). E.g. to set the INBOX path to "INBOX" in  /etc/dovecot/users:

```
hermes@whatever.org:{plain}pass:1000:1000::/home/user::userdb_mail=maildir:/home/user/Maildir/hermes@whatever.org:INBOX=/home/user/Maildir/hermes@whatever.org/.INBOX
```
And it is a good idea to make sure `maildir_very_dirty_syncs=no` (which is the default) is set in `/etc/dovecot/conf.d/10-mail.conf`.

That's it.
