### ISSUE TITLE
Maildir with read-only files and folders fails

### ISSUE THREAD

**Issue by ildar** [OfflineIMAP/offlineimap#243]
> [Repository Maildir]
> type = Maildir
> localfolders = ~/Mail/_tmp
> readonly = True

The files and folders have unix permissions read-only. Then offlineimap fails:

>  Copy message -1 (1 of 91) Maildir:aFolder -> Gmail_acc
>  ERROR: Copying message -1 [acc: Maildir2Gmail]
>   [Errno 13] Permission denied
>  ERROR: Syncing folder aFolder [acc: Maildir2Gmail]
>   [Errno 13] Permission denied
>  ERROR: ERROR in syncfolder for Maildir2Gmail folder aFolder: Traceback (most re
> cent call last):
>   File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 575, in
> syncfolder
>     localfolder.syncmessagesto(remotefolder, statusfolder)
>   File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 979, in syncmessagesto
>     action(dstfolder, statusfolder)
>   File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 853, in __syncmessagesto_copy
>     register = 0)
>   File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 779, in copymessageto
>     self.change_message_uid(uid, new_uid)
>   File "/usr/lib/python2.7/site-packages/offlineimap/folder/Maildir.py", line 431, in change_message_uid
>     os.path.join(self.getfullname(), newfilename))
> OSError: [Errno 13] Permission denied

**Comment by nicolas33** [comment]
Not sure what it tries to do, here.

**Comment by yang-ling** [comment]
> The files and folders have unix permissions read-only. 

And error message said

> OSError: [Errno 13] Permission denied

so I think you can make folders writable?

**Comment by nicolas33** [comment]
OfflineIMAP should not change the rights of the files.

**Comment by yang-ling** [comment]
Sorry I didn't make it clear. I mean @ildar can make his/her folders writable first, and then run offlineimap.

**Comment by ildar** [comment]
Of course I could have guessed that. But IMHO using a read-only folder
marked as read-only in offlineIMAP is right from a user's perspective. It
could happen because:

1. He backs up mail from a read-only media (e.g. DVD)

2. He wants to be sure that his local data is immutable.

**Comment by nicolas33** [comment]
The code calling for the sync (writes) looks good.
```
File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 575, in syncfolder
       localfolder.syncmessagesto(remotefolder, statusfolder)
```

I think the problem lands somewhere else; closing. If you re-open, please provide the offlineimap version.

**Comment by DaveDavenport** [comment]
I can reproduce this:
```
OfflineIMAP 7.0.9
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync ***:
 *** Processing account ***
 Establishing connection to **** (***-remote)
 Creating new Local Status db for ***-local:
Folder  [remote name INBOX] [acc: ***]:
 Syncing INBOX: IMAP -> Maildir
 Copy message UID -1610 (1/1610) ***-local: -> ***-remote
 ERROR: Copying message -1610 [acc: ***]
  [Errno 13] Permission denied
 ERROR: while syncing  [account ***]
  [Errno 13] Permission denied
 ERROR: ERROR in syncfolder for *** folder : Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 592, in syncfolder
    localfolder.syncmessagesto(remotefolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1110, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 938, in __syncmessagesto_copy
    self.copymessageto(uid, dstfolder, statusfolder, register=0)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 842, in copymessageto
    self.change_message_uid(uid, new_uid)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Maildir.py", line 477, in change_message_uid
    os.path.join(self.getfullname(), newfilename))
OSError: [Errno 13] Permission denied
```

Even in offline mode offlineimap tries to change the filename of the local message to the new UID?. 
I am trying to sync from a local Maildir (read-only) to a remote imap. The local maildir is read-only.

**Comment by nicolas33** [comment]
Actually, this rename is expected to happen whatever the read-only option.

When setting the local repository (Maildir) to readonly, this means we won't add/delete/update the local Maildir. This does not mean there is NO writes to the local repository.

When Offlineimap uploads a new email the remote assigns a new UID which is stored in the filename. If Offlineimap can't do this, it would have no way to map the UID to the file: on the next sync Offlineimap would consider the UID as deleted, propagate the deletion on remote and re-upload the same email (still considered not on remote).

**Comment by DaveDavenport** [comment]
Yes, realized that when looking at code. Sorry for the noise.

**Comment by nicolas33** [comment]
This was definitely not noise. ,-) I've added documentation in offlineimap.conf about that.
