### ISSUE TITLE
Return value of offlineimap

### ISSUE THREAD

**Issue by sachdevaprash** [OfflineIMAP/offlineimap#248]
Gives a return value of 0 even if it fails to fetch mail from the client due to a bad server SSL fingerprint.

To reproduce, set the server fingerprint to an incorrect value and run offlineimap in shell (ZSH). Then check the return value using "$?" in the shell.

**Comment by nicolas33** [comment]
Why duplicate the other issue?

**Comment by nicolas33** [comment]
Oh, sorry, it is not the same project. Thanks.

**Comment by sachdevaprash** [comment]
I've made a simple patch for this. It works for my particular application, but I don't know if that is OK with everything else.

diff --git a/offlineimap/init.py b/offlineimap/init.py
index a48c152..e141d32 100644
--- a/offlineimap/init.py
+++ b/offlineimap/init.py
@@ -48,7 +48,8 @@ class OfflineImap:
         if options.diagnostics:
             self.__serverdiagnostics(options)
         else:
-            self.__sync(options)
+            ret = self.__sync(options)
+            return ret;
 
     def __parse_cmd_options(self):
         parser = OptionParser(version=offlineimap.__bigversion__,
@@ -339,11 +340,13 @@ class OfflineImap:
                 offlineimap.mbnames.write(True)
 
             self.ui.terminate()
+            return 0;
         except (SystemExit):
             raise
         except Exception as e:
             self.ui.error(e)
             self.ui.terminate()
+            return 1;
 
     def __sync_singlethreaded(self, accs):
         """Executed if we do not want a separate syncmaster thread

**Comment by sachdevaprash** [comment]
A very newbie question: What would be a good way to send a patch? Or should I clone it into github and send a pull request?

**Comment by nicolas33** [comment]
Sending a pull request is fine.

**Comment by nicolas33** [comment]
Done.
