### ISSUE TITLE
enable packaging with PyPi

### ISSUE THREAD

**Issue by ahknight** [OfflineIMAP/offlineimap#26]
Happens on Ubuntu and OS X.

$ pip install offlineimap
Downloading/unpacking offlineimap
  Downloading offlineimap-6.5.5-rc2.tar.gz (97kB): 97kB downloaded
  Running setup.py egg_info for package offlineimap
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/ahknight/.virtualenvs/imap/build/offlineimap/setup.py", line 28, in <module>
        from test.OLItest import TextTestRunner, TestLoader, OLITestLib
    ImportError: No module named OLItest
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/ahknight/.virtualenvs/imap/build/offlineimap/setup.py", line 28, in <module>

    from test.OLItest import TextTestRunner, TestLoader, OLITestLib

ImportError: No module named OLItest

**Comment by nicolas33** [comment]
We are missing contributors to support Pypi.

**Comment by prologic** [comment]
How is "We are missing contributors to support Pypi" a resolution to this issue? I'm trying to install the latest OfflineIMAP form PyPI as well and running into the same issue. We **need** to re-open this issue and fix this ASAP!

**Comment by prologic** [comment]
FWIW installing from git works:
```
#!bash
$ pip install git+https://github.com/OfflineIMAP/offlineimap.git#egg=offlineimap
Collecting offlineimap from git+https://github.com/OfflineIMAP/offlineimap.git#egg=offlineimap
  Cloning https://github.com/OfflineIMAP/offlineimap.git to /private/var/folders/t7/gp30573d0ls9l67qb4yvnjd18xyrc0/T/pip-build-seWEbq/offlineimap
Installing collected packages: offlineimap
  Running setup.py install for offlineimap ... done
Successfully installed offlineimap-6.7.0
```

**Comment by prologic** [comment]
I believe al that's needed is for the person that owns the [offlineimap](https://pypi.python.org/pypi/offlineimap) package to do (*from a fhresh remote/master*):
```
#!bash
python setup.py sdist bdist_wheel register upload
```

**Comment by nicolas33** [comment]
There's no requirement it to be done by owners. Anyway, I'll see how to do that since I realize this is more expected than what I thought.

**Comment by prologic** [comment]
As iI (*nor others*) own the offlineimap package on PyPi; it *should* be done by the owner :)

**Comment by prologic** [comment]
Besides; it makes little to no sense to just randomly publish new packages by other people. Makes it hard to find what the "right" package is :)

**Comment by nicolas33** [comment]
Not random people. One assigned maintainer.

**Comment by prologic** [comment]
AFAIK PyPi only support single projects; no namespacing or group-based permissions :) That maintainer/person would have to have the username/password used to originally register the offlineimap package; or the original owner delete it and the new maintainer re-create it (*but that would't be good because you'd loose package publish history*)/

**Comment by prologic** [comment]
Looks like "Author: John Goerzen" owns the package?

**Comment by nicolas33** [comment]
Won't have time to work on this. Since `pip install --user git+https://github.com/OfflineIMAP/offlineimap.git@master` works well, I consider this issue low priority.

**Comment by prologic** [comment]
I *think* the point is someone just needs to republish a new version to PyPi. The fact that a `pip install` of te current git HEAD works is proof enough :)

**Comment by ahknight** [comment]
I think the point is he doesn't care to properly maintain this and mbsync is faster...

**Comment by nicolas33** [comment]
Anyone can do the job of contacting the current owner to first [remove the package](http://stackoverflow.com/questions/20403387/how-to-remove-a-package-from-pypi).

@ahknight I'd like to say:
* Thank you for your constructive feedback at your first (and only one) appearance here (at that time).
* Thank you for your offer in helping improving and maintaining OfflineIMAP.
* Thank you to have bought OfflineIMAP and the silver support service. Your inputs are critical.
* Thank you much for your warm encouragements.
* Thank you for tracking OfflineIMAP issues while it looks like it's not the tool you use. I expect more insightful comments to come from your intensive use.
* Thank you for teaching me how a "propely maintained" project looks like. I highly need lessons from your impressive experience on how to maintain a free software. I'm a beginner in the matter in comparison to you.
* Thank you for all your past contributions. We can't live without you.
* Thank you for pointing out that other tools can do the job. Nobody here would have guessed alone.

**Comment by chris001** [comment]
I have found the solution for automatically deploying new releases of offlineimap to PyPi!
Github will automatically deploy to PyPi, a tagged release, which has passed code checks of github's Travis-CI.
We just have to configure Travis-CI in github, to check the build for no syntax errors etc.
And configure in github/Travis the PyPi account to deploy to.
Full details here.... 
"How to deploy a python package on PyPi with GitHub and Travis CI"
http://5minutes.youkidea.com/howto-deploy-python-package-on-pypi-with-github-and-travis.html
We should do this immediately or as soon as possible in my opinion...

**Comment by chris001** [comment]
The owner of 6.5.5-RC2 on PyPi is 

>  Package Index Owner: spaetz 

@spaetz could you help with resolving this issue, ie configure gihub travis-ci with your pypi credentials to auto publish new version of the offlineimap python package each time a new tag is added on master!

**Comment by nicolas33** [comment]
Good idea! I didn't know Travis CI could do that.
I think it would be best to free the `offlineimap` namespace on pypi so that we can use it from a official `offlineimap` account.

**Comment by chris001** [comment]
:+1:
Agreed, it'd be best to free the offlineimap namespace on pypi for use by user offlineimap. Paging sebastian @spaetz

**Comment by spaetz** [comment]
Nicolas, let me know your pypi user name and I will ad you as owner of the package

**Comment by nicolas33** [comment]
@spaetz I've registered the `offlineimap` login name.

**Comment by spaetz** [comment]
offlineimap is now owner of the pypi project. Feel freebto remove me from ownership if you can successfully log in.

**Comment by nicolas33** [comment]
Thanks.
