### ISSUE TITLE
v6.6.0 milestone

### ISSUE THREAD

**Issue by nicolas33** [OfflineIMAP/offlineimap#268]
@vaab, @renard: I plan to release v6.6.0 at the beginning of december. Would be nice to get your pull requests updated! ,-)

Cf. #265, #267.

**Comment by renard** [comment]
I am currently hitting #205 and this is a PITA to debug. Thus I can write a patch against 6.5.7 (https://github.com/OfflineIMAP/offlineimap/archive/v6.5.7.tar.gz) which is actually a working brew version on OSX.

**Comment by renard** [comment]
@nicolas33 I just pushed the changed according your comments on #265.

**Comment by nicolas33** [comment]
Thanks.

OfflineIMAP tend to be hard to debug in general. :-( That's one of the reason why I'm working on [imapfw](http://sourceforge.net/projects/imaplib2/)!

**Comment by vaab** [comment]
@nicolas33 hmm, already did apply the change you've mentionned on issue #266  in the PR #267 . Have I missed something else ?

**Comment by nicolas33** [comment]
@vaab: My bad. Didn't see the update.
