### ISSUE TITLE
Confused by the "Deleting X messages" status

### ISSUE THREAD

**Issue by bnvk** [OfflineIMAP/offlineimap#270]
Every so often, when running offlineimap I see the following status in my terminal

```
Deleting 57 messages (7506:7562) in Maildir[SourceOne]
Deleting 19 messages (6001:6019) in Maildir[SourceTwo]
```

The configuration of `MailSource` is as follows:

```
[Account SourceOne]
localrepository = SourceOneLocal
remoterepository = SourceOneRemote
maxage = 11

[Repository SourceOneLocal]
type = Maildir
localfolders = ~/Messages
restoreatime = no

[Repository SourceOneRemote]
type = IMAP
remotehost = imap.domain.com
remoteuser = name@domain.com
remotepass = allmysecretsbelongtoyou
remoteport = 993
ssl = yes
cert_fingerprint = 239841982313asSfa11231313asd2345
idlefolders = ['INBOX']
nametrans = lambda foldername: re.sub('^INBOX', 'Sourceprefix', foldername)
folderfilter = lambda foldername: foldername in ['INBOX']
maxconnections = 1
holdconnectionopen = no
createfolders = False
readonly = True
```

I can't tell what this message means. Oddly, my MUA is [Mailpile](https://mailpile.is) and occasionally it cannot find messages that I've downloaded via offlineimap. My first thought about what offlineimap is doing is that `"it is deleting my messages locally"` which is making my client unable to find them. 

Is there anything in my configuration that would make it do that? Another thought it is has to do with my server, but that is also odd, as nothing else is talking to that mailserver or accessing the mail (as far as I know), so none of the IMAP flags should change on any of the messages.

**Comment by nicolas33** [comment]
Might be a maxage issue. See: http://offlineimap.org/devel/2015/04/14/why-we-changed-maxage.html

**Comment by bnvk** [comment]
@nicolas33 this very well could be a `maxage` issue, but it's very odd and makes for a strange experience to have your previously downloaded local mail disappearing. 

If I understand that link you shared and the changes you made to maxage correctly- basically there's no way to do the sort of the thing whereby offlineimap only downloads mail after a certain fixed point in time- e.g. all messages after `2015-11-01` and never before then, yes?

**Comment by nicolas33** [comment]
That's what maxage is about so it's possible while not in the IMAP/IMAP case. The link explains the internals.

**Comment by bnvk** [comment]
@nicolas33 hrm, interesting. I'm using it in the Local Maildir / IMAP case and am definitely not getting that experience as mail keeps getting deleted every day! Hrm, not sure what to do then!

**Comment by nicolas33** [comment]
Did you try latest v6.6.1?

**Comment by bnvk** [comment]
@nicolas33 no, I had been on 6.5.* I just updated and will report back to you in a few days. Thanks :+1:
