### ISSUE TITLE
Locally moved messaged are FUBAR'd on remote (OfflineIMAP/Exchange)

### ISSUE THREAD

**Issue by approximate** [OfflineIMAP/offlineimap#275]
After I delete messages locally and sync my local Maildir with remote Exchange account, the original messages are deleted, but for some reason Outlook (both desktop and web clients) shows that there are *new* messages created on the remote side, with all headers stripped, and the entire original message including original headers is included as a plaintext content. These new messages only have three headers ("X-OfflineIMAP:", "MIME-Version:" and "Content-Type:"), all other headers including mandatory ones (e.g. "From:" or "To:") are missing.

Did anyone have the same issue? How can I debug this, provided I don't have any administrative access to the remote mail server?

**Comment by approximate** [comment]
Additional info: I am using [FDM](https://github.com/nicm/fdm) to sort mails from my local Inbox to target subfolders. The FUBAR'd messages all appear in the *target* subfolders, never in Inbox. My MUA, which is [Mutt](https://www.mutt.org), does *not* show these messages, which, if I understand everything correctly, means that they only exist on the remote, and are not synched back to local account by OfflineIMAP. The FDM is configured not to update the "Received:" header, meaning that the message is only moved from Inbox to the target folder.

**Comment by nicolas33** [comment]
I've never heard about something like that before. My best guess is that OfflineIMAP and FDM are not playing well together. First time I hear about FDM, too.
I'm not sure to understand how FDM works. The documentation is quite short.

Anyway, you might want to get rid of FDM some time to see if you still have this issue. I'm working with imapfilter for years without any problem.

PS: always say the versions you're using, at least.

**Comment by approximate** [comment]
@nicolas33 
I am using OfflineIMAP v.6.5.6 (most recent version on Fedora).

I think I found the problem. When syncing, OfflineIMAP adds those three headers in order to track the message that was moved to another local folder by FDM, but it also adds a blank line after them, which makes the rest of the message (including original headers) a new message body. 

This seems to have been fixed in 6.5.7rc1. I am going to test with the latest Git version (6.6.0rc3)

FDM ([here is the doc btw](https://github.com/nicm/fdm/blob/master/MANUAL)) is configured not to change messages in any way, it only moves them to another folder. I am [not the only person to use this combo](http://donnlee.com/2010/01/22/do-you-love-mutt-use-offlineimap-fdm-and-rejoice/).

**Comment by nicolas33** [comment]
Thanks for all these info.
v6.5.6 is more than a year old and I'm more confident with v6.6.0-rc3, yes.

**Comment by approximate** [comment]
@nicolas33 
I have confirmed that using FDM is not the root cause: moving messages manually in Mutt causes  the same problem with OfflineIMAP v6.5.6.

I have tested my OfflineIMAP/FDM/Mutt setup with v.6.6.0rc3, and the issue does not reappear: messages moved to other folders by FDM are synced to Exchange server correctly, the  headers seem to be fine too (OfflineIMAP adds "X-OfflineIMAP" header  which is visible in Outlook desktop and web clients).

So, the original issue seems to be solved in v.6.5.7 and later versions, but now I have another problem now: how do I fix hundreds of messages with screwed headers that OfflineIMAP pushed to the server? I have a local uncorrupted copy of those messages -- no new headers, original headers and content are both intact. OfflineIMAP does not download the corrupted messages from the remote server anymore. My IMAP knowledge is just a bit more than zero, so I am guessing these messages have the same UIDs as my local copies, but they also have '\Seen' flag now, so OfflineIMAP ignores them while syncing. If I found a way to get them again from the server, I wrote a script that removes those new erroneous headers and extra blank line and restores the original message. I then could reprocess those fixed messages with FDM and re-sync with OfflineIMAP, hoping that the UID will stay the same as long as I don't rename any files. Am I correct in my theory? Any ideas on how to get those corrupted messages to my local Maildir?

**Comment by nicolas33** [comment]
ASAIU, your theory is corrupted. Since the IMAP server has hundreds of broken mails, the best is to:
1. Backup your local maildir.
2. Rename the maildir (filesystem).
3. Delete all OfflineIMAP cache.
4. Delete all mails on the IMAP server.
5. Start a fresh sync to recreate the local (empty) maildirs.
6. Copy back the local mails to the fresh empty maildir.
7. Sync again to re-upload all the local mails to the server.
