### ISSUE TITLE
OfflineIMAP not fit for IMAP relocation purposes

### ISSUE THREAD

**Issue by frispete** [OfflineIMAP/offlineimap#276]
For the task of relocating some IMAP mailboxes, I tried to use v.6.5.7 of this app.

When relocating some domains from one provider to another last night, I fetched some mailboxes from these domains beforehand. All was well. After the domain move, I recreated the email accounts in the new environment. Since the new account was identical, I couldn't foresee the trouble, that offlineimap gave me. On invocation, I noticed a long list of numbers, and a couple of UID validity errors. Studying the output details, I realized, that it deleted the local files of the biggest mailbox completely, and failed for most of the rest of the work due to UID validity errors. 

In essence, only the junk stuff survived, and all important stuff either failed or vanished. I don't need to tell you, how this made me feel...

You should warn the user about those scenarios, that does not fit the purpose beforehand. And, please do this prominently in the docs. 

Unfortunately, I closed the window with the output erroneously, but if you think, that this scenario is one that is really worth to support, I'm inclined to reproduce this failure again.

**Comment by nicolas33** [comment]
It's true that OfflineIMAP targets users with some IMAP knowledges outside the main uses cases. Patches are welcome.

The IMAP protocol and UIDs don't allow to do what you expect by only changing the remote configuration of an account. However, OfflineIMAP can actually do what you want. Here is how to do the migration the safe way, via local maildirs:

1. Sync the "old" mailboxes.
2. Backup.
3. Create a new dedicated account (with a different name and local path for the maildir) for the "new" mailboxes **and sync** (result will be almost empty).
4. Locally copy the local mails (`cp -a`) from the "old" maildirs to the "new" maildirs and sync.
