### ISSUE TITLE
Hangs on "terminating NOW"

### ISSUE THREAD

**Issue by amandabee** [OfflineIMAP/offlineimap#277]
I've had a couple of instances of dropping my internet connection mid-sync and finding that `offlineimap` just hangs. It says it is syncing but never seems to finish. If I try to kill it with <kbd>ctrl</kbd><kbd>c</kbd> it says it will take a few seconds, but that, too hangs:

```
Folder INBOX.Archives.2015 [acc: Example]:
 Syncing INBOX.Archives.2015: IMAP -> Maildir
^CTerminating NOW (this may take a few seconds)...
```
If I close the terminal altogether I won't be able to run it again b/c the lock will still be in place. How should I safely shut down offlineimap? How can we make it smarter about dropped connections?

I'd love any tips on what I can do as a user and/or I'm happy to help document the problem so we can fix it.

**Comment by nicolas33** [comment]
There's no way to **safely** stop OfflineIMAP if first <kbd>ctrl</kbd><kbd>c</kbd> fails. It has to be killed.
Duplicates #60.
