### ISSUE TITLE
support subscriptions on IMAP/IMAP

### ISSUE THREAD

**Issue by net147** [OfflineIMAP/offlineimap#280]
I noticed when doing a one-way sync from one IMAP server to another IMAP server that nested folders are not added to the subscriptions. For example if I have an IMAP folder Archives/2014 and Archive/2015, then Archives is added to the subscriptions but Archives/2014 and Archives/2015 isn't. As a result, the nested folders don't appear in Thunderbird. Manually adding the missing nested folders to the dovecot subscriptions file for the IMAP account fixes it.

I am using dovecot 2.2.18 and offlineimap 6.5.7.

**Comment by nicolas33** [comment]
AFAICT, OfflineIMAP doesn't support subscriptions at all.

I guess that some folders are set subscribed outside of OfflineIMAP. That's probably the destination IMAP server which is doing this.

**Comment by nicolas33** [comment]
This is expected behaviour. Subscriptions are per folder configuration option.
