### ISSUE TITLE
OfflineIMAP cannot handle calendar events and crashes

### ISSUE THREAD

**Issue by bjoernb** [OfflineIMAP/offlineimap#281]
Everytime I receive a message with an appointment OfflineIMAP
crashes. The only thing that helps deleting the mail and restarting
OfflineIMAP. Here is a traceback:

    Copy message 60 from Kalender:
     WARNING: ERROR attempting to copy message 60 for account mpimet:Traceback (most recent call last):
      File "/usr/lib/pymodules/python2.7/offlineimap/folder/Base.py", line 250, in copymessageto
        message = self.getmessage(uid)
      File "/usr/lib/pymodules/python2.7/offlineimap/folder/IMAP.py", line 215, in getmessage
        raise OfflineImapError(reason, severity)
    OfflineImapError: IMAP server 'myexampleimap' does not have a message with UID '60'
    
    Copy message 62 from Kalender:
     WARNING: ERROR attempting to copy message 62 for account mpimet:Traceback (most recent call last):
      File "/usr/lib/pymodules/python2.7/offlineimap/folder/Base.py", line 250, in copymessageto
        message = self.getmessage(uid)
      File "/usr/lib/pymodules/python2.7/offlineimap/folder/IMAP.py", line 215, in getmessage
        raise OfflineImapError(reason, severity)
    OfflineImapError: IMAP server 'myexampleimap' does not have a message with UID '62'
    
     Thread 'Copy message 60 from Kalender' terminated with exception:
    Traceback (most recent call last):
      File "/usr/lib/pymodules/python2.7/offlineimap/threadutil.py", line 140, in run
        Thread.run(self)
      File "/usr/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/usr/lib/pymodules/python2.7/offlineimap/folder/Base.py", line 250, in copymessageto
        message = self.getmessage(uid)
      File "/usr/lib/pymodules/python2.7/offlineimap/folder/IMAP.py", line 215, in getmessage
        raise OfflineImapError(reason, severity)
    OfflineImapError: IMAP server 'myexampleimap' does not have a message with UID '60'
    
    
    Last 1 debug messages logged for Copy message 60 from Kalender prior to exception:
    thread: Register new thread 'Copy message 60 from Kalender' (account 'myexample')

**Comment by nicolas33** [comment]
* offlineimap version?
* Could you provide a raw offending mail?
* Did you check if offending UID really exist?
* What do you have in this "Kalender" folder? A workaround might be to folderfilter this folder.

**Comment by bjoernb** [comment]
Quoting Nicolas Sebrecht (2015-11-26 18:01:39)
>   • offlineimap version?

6.3.4

>   • Could you provide a raw offending mail?

Unfortunately I have deleted that offending mail from the IMAP
server. Plus it is work mail that I do not want disclose on the
internet.

>   • Did you check if offending UID really exist?
It happens with every appointment I get from my colleagues

>   • What do you have in this "Kalender" folder? A workaround might be to
>     folderfilter this folder.

I think this folder gets automagically created by Microsoft Outlook on
the IMAP Server and then synced to my maildirs

**Comment by nicolas33** [comment]
AFAIU, they are calendar events and have few interest being synced to the local maildir. If all events happen to one dedicated folder, it's better filtering it.

**Comment by nicolas33** [comment]
v6.3.4 is more than 4 years old. I'll release v6.6.0 in December. It might be time to update OfflineIMAP. :-)

**Comment by bjoernb** [comment]
OfflineIMAP is still v6.3.4.1 in Debian Testing: https://packages.debian.org/stretch/offlineimap
Therefore I am using this old version.

**Comment by nicolas33** [comment]
http://offlineimap.org/doc/installation.html#ball

**Comment by bjoernb** [comment]
I switched to using isync/mbsync, because OfflineIMAP was as well not fetching mails very reliable. I often had to kill the program and start it again to see new mail coming in.

**Comment by nicolas33** [comment]
Looks rather close to #296.
