### ISSUE TITLE
Some confusion around syncing drafts

### ISSUE THREAD

**Issue by Gastove** [OfflineIMAP/offlineimap#283]
Let's say I start an email on my laptop in a mail client and save it as a draft, and then I run `offlineimap`. In Gmail (accessed via Google Inbox) -- and on my other computers -- the draft appears, as a draft. Everything is perfect so far. 

But now, things just get... not-what-I'd-expect. If I open that draft on my local mail client again, edit it more, save it, sync it -- the changes never propagate. If I open the draft in Inbox and edit it, _those_ changes will sync locally -- but now the local message wont be marked as a draft (potentially a glitch with my local mail client?). 

It's not readily apparent to me if this is a problem with offlineimap, my configurations (attached below), or my expectations (_should_ drafts sync content?). Thanks for the awesome tool, and the time!

```
[general]
ui=TTYUI
accounts = Gmail
autorefresh = 5
pythonfile = ~/.offlineimap.py

[Account Gmail]
localrepository = Gmail-Local
remoterepository = Gmail-Remote
maxconnections = 3

[Repository Gmail-Local]
type = Maildir
localfolders = ~/.Mail/gastove@gmail.com

[Repository Gmail-Remote]
type = Gmail
remotehost = imap.gmail.com
remoteuser = gastove@gmail.com
remotepasseval = keyring.get_password('gmail', 'personal')
realdelete = no
ssl = yes
sslcacertfile = /Users/gastove/ssl-ca-cert.pem
maxconnections = 1
folderfilter = lambda folder: folder not in ['[Gmail]/Trash',
                                             '[Gmail]/Spam',
                                             '[Gmail]/All Mail']
```

**Comment by nicolas33** [comment]
Once edited, the mail in the Draft folder should be rewritten with a new filename like if it were a new mail. If not, OfflineIMAP won't detect the change.

**Comment by Gastove** [comment]
Ahh. Okay, good to know. The file names... are just for OfflineIMAP's use, right? Having a new file name shouldn't create any confusion updating the same draft on the remote server, yeah?

**Comment by nicolas33** [comment]
That's conformance to the Maildir format. Any change in a mail should have the filename changed.
