### ISSUE TITLE
XOAUTH2 authentication failed warnings when XOAUTH2 is not set up properly

### ISSUE THREAD

**Issue by mineo** [OfflineIMAP/offlineimap#285]
Everytime offlineimap 6.6.0 tries to sync my gmail account, it logs warnings like `XOAUTH2 authentication failed: AUTHENTICATE command error: BAD ['Client aborted AUTHENTICATE command. [somethingsomething]']. Data: OFIG2 AUTHENTICATE XOAUTH2
` and then proceeds to sync just fine. This seems to be caused by the new XOAUTH2 support and can be disabled as described in [this post](https://bbs.archlinux.org/viewtopic.php?pid=1588425#p1588425). 

However, the documentation at https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L764 lists XOAUTH2 as a still experimental feature and some mandatory parameters, which I did not set. I think offlineimap shouldn't generate warnings when I have not configured an experimental feature correctly and should in this case just do what it did pre-XOAUTH2.

**Comment by nicolas33** [comment]
XOAUTH2 aims to leave EXPERIMENTAL status soon enough to be enabled. It's quite often requested feature.

I think honoring the new default `auth_mechanisms` configuration option is more important. Hence, you should remove XOAUTH2 from this line to avoid the warning.

**Comment by shaggytwodope** [comment]
I tried the solution shared by @mineo, and it works for gmail, however its messing up for teknik.io. Is there a way (not that imap savy) to find out what auth method I should use?

**Comment by shaggytwodope** [comment]
Dispite the error being the same, I solved my problem by setting the options ``cert_fingerprint =`` manually. Just in case anyone else runs into this issue. (May be unrelated to any changes for offlineimap).

**Comment by nicolas33** [comment]
Option maked stable.
