### ISSUE TITLE
Add an option to delete each message from a repository after successfully copying it

### ISSUE THREAD

**Issue by BlacklightShining** [OfflineIMAP/offlineimap#287]
This would be really nice to have for all us paranoid types that like our mail deleted from the server and just kept locally.

**Comment by BlacklightShining** [comment]
This is related to #204 ([associated mailing-list discussion](http://thread.gmane.org/gmane.mail.imap.offlineimap.general/7318)) and can probably be based on its changes.

**Comment by BlacklightShining** [comment]
Oh, issue #47 just got closed as completed. This can just be implemented as an option to delete all messages on the repository (or maybe just messages from specified folders), then.

**Comment by nicolas33** [comment]
You're right, obviously.

This should be already possible with `-k` option. However, I agree we could introduce a new CLI option like `--no-sync-deletes {local,remote}` just for the `sync_deletes` configuration option.

**Comment by BlacklightShining** [comment]
My apologies; I meant adding a _configuration_ option (which could, of course, be specified by users either in the config file or with `-k`). Currently, no such option seems to exist.

**Comment by nicolas33** [comment]
Hmm, the title change make things clear. However, #47 is unrelated to this.

**Comment by BlacklightShining** [comment]
@nicolas33 #204 is not as related as I thought, apparently: it prevents deletions from being synced (so that you can manually delete messages from just one repository). #47 implements part of the original intent of this request; all that's left is to…err…add an option to delete each message from a repository after successfully copying it. :)

**Comment by nicolas33** [comment]
> add an option to delete each message from a repository after successfully copying it.

Yes, this is totally unrelated to #47. While this should not be too hard to implement, I'd rather focus on imapfw. If someone comes up with patches, I'll review ASAP.

**Comment by nicolas33** [comment]
I think this won't be implemented easily. offlineimap is a syncer and there are lot of expectations that both sides should end in a similar state.

**Comment by nicolas33** [comment]
There is a very effective workaround for users missing this feature. The idea is to configure offlineimap to download the emails to an intermediate local path and write a small script to move the emails to the final location. Offlineimap will consider the moved emails as deleted and propagate the deletions on the remote.

The `postsynchook` feature might help to get this done automatically on each sync.

**Comment by nicolas33** [comment]
Actually, we won't implement the requested feature because offlinimap codebase was not designed for this kind of usage. I still think the above workaround is good enough, though.
