### ISSUE TITLE
OAUTH env variables

### ISSUE THREAD

**Issue by vonpupp** [OfflineIMAP/offlineimap#288]
Hello,

Is it possible to use getosenv with the following variables?:
- oauth2_client_id
- oauth2_client_secret
- oauth2_refresh_token

I am using environment variables for `remoteusereval` (and `remotepasseval` pior switching to oauth), and I think it will be more secure to use environment variables or something similar so I don't commit my credentials with the configs.

Is this possible?

Thank you very much.

**Comment by nicolas33** [comment]
It's currently not implemented.

**Comment by nicolas33** [comment]
The other oauth2 related option would need to be accessible from the env, too.

**Comment by nicolas33** [comment]
I think the best policy is to introduce more eval configuration options as requested in #307.
