### ISSUE TITLE
Make this the canonical repository

### ISSUE THREAD

**Issue by mikemcquaid** [OfflineIMAP/offlineimap#289]
Hello!

It seems that https://github.com/jgoerzen/offlineimap is now deprecated and this is the canonical repository. How would you feel about making this the canonical repository (so it doesn't show as a fork). Normally you can just ask GitHub Support and they'll do this for you but as I work there I can do it for you, if you like.

Note: this is not a request from GitHub or me with my GitHub hat on but with my "Homebrew maintainer" hat on (see https://github.com/Homebrew/homebrew/pull/47638 for more context). CC @nijikon and @DomT4 who were interested in this from the Homebrew side.

Thanks for your work!

**Comment by nicolas33** [comment]
Making this repository canonical is welcome. The best would be to have a github feature to allow doing this, IMHO.

May I ask why you rename OfflineIMAP with Homebrew?

**Comment by mikemcquaid** [comment]
@nicolas33 We renamed it from `offline-imap` to `offlineimap` as that's the name Debian uses and the upstream repository name.

**Comment by mikemcquaid** [comment]
> Making this repository canonical is welcome.

Done!

**Comment by DomT4** [comment]
:+1: :clap:

**Comment by nicolas33** [comment]
Thanks.

What's your upstream? Debian uses the correct name, AFAICT. https://packages.debian.org/search?keywords=offlineimap.

**Comment by mikemcquaid** [comment]
@nicolas33 Sorry: I mean, it's also the name of this repository :)

**Comment by nijikon** [comment]
:+1:
