### ISSUE TITLE
2 accounts on 1 server, passwords in netrc, offlineimap asks for password of one

### ISSUE THREAD

**Issue by x421** [OfflineIMAP/offlineimap#295]
Hey there,

I have two email-adresses on one server and use .netrc to store my passwords. However, as soon as I add the second account to .netrc the first one wants a password. If I remove the second one again, everything is fine.

I checked:

* if the username in .netrc might be the same due to copy & paste (no)
* if the remoteuser in .offlineimaprc might be the same due to copy & paste (no)
* every account on its own (works fine)

What else can I check before blaming the software? The installed version of offlineimap is 6.5.4.

**Comment by nicolas33** [comment]
Please, try v6.6.1 while I doubt this will fix the issue.

**Comment by x421** [comment]
Updated, did not fix it, as you expected it.

**Comment by frioux** [comment]
I have the same problem, v6.7.0 also doesn't fix it.

**Comment by frioux** [comment]
Ok I figured it out.  It's because OfflineIMAP uses python's built in netrc parser, which is based on the hostname only.  [See here](http://turing.com.br/pydoc/2.7/library/netrc.html).  I'm working on a patch that skips the builtin netrc parser.  @nicolas33, please let me know if that's not an option.

**Comment by frioux** [comment]
[Bug is known in core python and has been open since 2011](https://bugs.python.org/issue11416).  Will submit a PR with the fixed version of netrc and code to use it later tonight.

**Comment by nicolas33** [comment]
@frioux Thank you much for your work on this issue. It's great to have the PR open while this bug is not fixed upstream. However, I'd rather not to merge it because importing and patching the netrc module is bad: we don't aim to maintain our own version of netrc.

**Comment by nicolas33** [comment]
I'm closing since we couldn't get a proper fix about this issue. It is now documented in the man page.

**Comment by frioux** [comment]
FWIW you could, you just didn't like my solution and weren't willing to
modify it yourself.

-- 
sent from a rotary phone, pardon my brevity

**Comment by nicolas33** [comment]
Yes, I meant we couldn't get a fix merged into the mainline. And yes, I'm not willing to fix all the issues of others. I think I'm doing enough job.

**Comment by chris001** [comment]
Why isn't python maintainer team merging this bug fix into `netrc` ?!  Incredible!
