### ISSUE TITLE
does not have a message with UID [exchange IMAP server]

### ISSUE THREAD

**Issue by ernestorenanche** [OfflineIMAP/offlineimap#296]
I installed and configured offlineIMAP. When I run it, it connects to my three email accounts, download few emails and then crash.
I cannot understand what the error is trying to tell me.
Here is [the link to the debug log](https://gist.github.com/ernestorenanche/2791f94afc4c15ca6b2b).
I hide my email address and my password that appear in plain text in the log.
When I relaunch offlineIMAP, I get the same error again and again.
Any help would be appreciated.

Ernesto.

**Comment by nicolas33** [comment]
OfflineIMAP version? Is this IMAP server a public or private service ? What's the remote domain name? Do you know which IMAP server is in use ?

**Comment by ernestorenanche** [comment]
I use version 6.5.5.
I used it first only with gmail and it worked fine and then I added a public
server (outlook.com) and a private server for my company (which also use
outlook).


Ernesto On ven., janv. 22, 2016 at 6:28 PM, Nicolas Sebrecht < notifications@github.com [notifications@github.com] > wrote:
OfflineIMAP version? Is this IMAP server a public or private service ? What's
the remote domain name? Do you know which IMAP server is in use ?

—
Reply to this email directly or view it on GitHub
[https://github.com/OfflineIMAP/offlineimap/issues/296#issuecomment-173985225] .[https://github.com/notifications/beacon/APiPV8l2KZxzYHwMbjkfVTO7waAHI5dFks5pcl4fgaJpZM4HKZ8q.gif]

**Comment by nicolas33** [comment]
Again exchange server. We had similar report in the mailing list:
```
Subject: OfflineImapError: IMAP server ... does not have a message with UID
 '15541'
From: Tomas Nordin <hidden>
Date: Thu, 07 Jan 2016 21:59:19 +0100
Message-ID: <8737u9ds2g.fsf@debian.tompa.tv>


Hi

I get this error when trying to fetch mail from an account I beleive is
on an exchange server:

Thread 'Copy message 15541 from INBOX' terminated with exception:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/offlineimap/threadutil.py", line 140, in run
    Thread.run(self)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pymodules/python2.7/offlineimap/folder/Base.py", line 250, in copymessageto
    message = self.getmessage(uid)
  File "/usr/lib/pymodules/python2.7/offlineimap/folder/IMAP.py", line 215, in getmessage
    raise OfflineImapError(reason, severity)
OfflineImapError: IMAP server 'remote_kth' does not have a message with UID '15541'

I have tried closing all other connections to that account before
running offlineimap. I tried deleting the directory .offlineimap before
running the command again.

I also searched for some mail among the already downloaded mails with
the UID 15541 but found none.

Can somebody give me some guidance. Is it possible tell offlineimap to
ignore that message or something?

$ uname -a
Linux debian 3.2.0-4-686-pae #1 SMP Debian 3.2.68-1+deb7u1 i686 GNU/Linux

$ offlineimap --version
6.3.4

Best regards
/
Tomas
```

Could you try with latest stable v6.6.1, please?

The RFC stands that UIDS must be successive. It looks like Microsoft has broken this rule in their exchange products. I think this breaks legitimate OfflineIMAP's assumption we are making since the early days.

**Comment by nicolas33** [comment]
For anyone hitting this issue, Tomas wrote a very nice blog post two days ago to share his experience with you: http://offlineimap.org/server/imap/error/2016/01/27/error-no-such-number.html

**Comment by nicolas33** [comment]
Duplicates #62.
