### ISSUE TITLE
crash with dots in foldernames

### ISSUE THREAD

**Issue by bechampion** [OfflineIMAP/offlineimap#297]
hi guys ,  the first time I've installed and run the tool , all went fine and emails were downloaded but now this is happening any ideas?

[~]:offlineimap
OfflineIMAP 6.6.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync dada:
 *** Processing account dada
 Establishing connection to dad.dada.com:993
 Creating folder Tasks// B/[Remote]
 ERROR: While attempting to sync account 'dada'
  CREATE command error: BAD ['Command Argument Error. 11']. Data: NBLM8 CREATE "Tasks// B/"

 *** Finished account 'dada' in 0:01
ERROR: Exceptions occurred during the run!
ERROR: While attempting to sync account 'dada'
  CREATE command error: BAD ['Command Argument Error. 11']. Data: NBLM8 CREATE "Tasks// B/"

Traceback:
  File "/Library/Python/2.7/site-packages/offlineimap/accounts.py", line 263, in syncrunner
    self.__sync()
  File "/Library/Python/2.7/site-packages/offlineimap/accounts.py", line 329, in __sync
    remoterepos.sync_folder_structure(localrepos, statusrepos)
  File "/Library/Python/2.7/site-packages/offlineimap/repository/Base.py", line 246, in sync_folder_structure
    src_repo.makefolder(dst_name_t)
  File "/Library/Python/2.7/site-packages/offlineimap/repository/IMAP.py", line 463, in makefolder
    result = imapobj.create(foldername)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 759, in create
    return self._simple_command('CREATE', mailbox, **kw)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 1691, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/Library/Python/2.7/site-packages/offlineimap/imaplib2.py", line 1444, in _command_complete
    raise self.error('%s command error: %s %s. Data: %.100s' % (rqb.name, typ, dat, rqb.data))

Thanks in advance!

**Comment by nicolas33** [comment]
What's your configuration file? (hide anything private)

**Comment by bechampion** [comment]
Thanks It's pasted below
```
[general]
accounts = ipsoft
[Account ipsoft]
localrepository = Local
remoterepository = Remote
maxsize=0
maxage=1
[Repository Local]
type = Maildir
localfolders = ~/OfflineMail/
maxage=1
maxsize=0

[Repository Remote]
maxsize=0
maxage=1
type = IMAP
cert_fingerprint=123123123
remotehost = remote
remoteuser = user
remotepass = pass
```

**Comment by bechampion** [comment]
i've got two macs running "el capitan" had the same problem , first time it all runs fine , second i get that exception.
Thanks again!

**Comment by nicolas33** [comment]
I wonder if there's a bug around maxage/maxsize options. My guess is that OfflineIMAP tries to create already existing folders. This might be to the way folders are considered extisting or not (which might be changing during the run whether OfflineIMAP still consider a folder has mails once maxage/maxsize applied).

Anyway, `maxage = 1` is very critical value due to how it internally works. Also, `maxsize = 0` looks wrong if it doesn't disable the max size. This would require more digging.

**Comment by bechampion** [comment]
I've removed ```maxsize``` and moved ```maxage=1``` ,but still getting the same problem , if i delete the ```localfolder``` everything works again , so your assumption that it is trying to recreate the folder could be right?.

**Comment by nicolas33** [comment]
Ok. What do you mean by removing the `localfolder`?

What's the output of `offlineimap --info`?

**Comment by nicolas33** [comment]
I'm pretty sure the culprit is the two-dots in the foldername. One is wrongly considered as the hierarchy separator.

Try renaming `. B.` on the remote.

**Comment by bechampion** [comment]
That did it! ,  I've removed it from local and remote (using owa)  , and now it's syncing again! .

Thanks a lot for working on this on a Sunday!

**Comment by bechampion** [comment]
I've also stopped syncing all mailboxes , and only the ones i need ,  the exchange server adds a ton of ridic mailboxes as a policy!

**Comment by nicolas33** [comment]
Dups #148
