### ISSUE TITLE
IMAP (custom) tags are not synced 

### ISSUE THREAD

**Issue by mrvdb** [OfflineIMAP/offlineimap#305]
Setup: 
```gnus <-> local IMAP dovecot <-> remote IMAP Cyrus``

offlineimap version 6.6.1 (arch linux package)

I'm mostly concerned about the 'gnus-forward', 'gnus-expire' etc. tags that gnus sets on messages, but I also have some usecases where I use sieve with, for example,  ```addtag "gnus-expire"``` to set tags on the remote end which never end up in the local IMAP store.

What I see:
- connect imap client to local dovecot: All tags which have been set locally are present, no tags from the remote are present
- connect imap client to remote: All tags set with sieve are there, but none of the tags set by gnus

If I'm interpreting the docs correctly the ```synclabels``` option and ```customflag_x``` options are not applicable in this case.

**Comment by nicolas33** [comment]
Why is `synclabels` not applicable in this case?

**Comment by mrvdb** [comment]
I understood that was only for Gmail as written in the conf file:
```...
# Specifies if we want to sync GMail labels with the local repository.
# Effective only for GMail IMAP repositories.
#
```

**Comment by mrvdb** [comment]
A workaround is described in this mailinglist message (assuming it will still work, haven't tried yet):

http://lists.gnu.org/archive/html/info-gnus-english/2011-10/msg00052.html

**Comment by nicolas33** [comment]
Thanks for resurrecting this. If it works, it would be great to get this written somewhere [in the docs or as a blog post](offlineimap.org).

**Comment by mrvdb** [comment]
What were you trying to link to? The link in the comment does not have a valid target.

**Comment by mrvdb** [comment]
I added https://github.com/OfflineIMAP/offlineimap/wiki/Syncing-custom-tags to the wiki

**Comment by nicolas33** [comment]
I'm not sure that's the best place but it's still much better than providing nothing. ,-)
Thank you much.

**Comment by mrvdb** [comment]
Just a FYI, i chose the github wiki because the threshold for making a change to the website was too high. Even for an experienced jekyll user, the process is too wieldy for these kind of 'tips-'n-tricks' additions.

**Comment by nicolas33** [comment]
Did you consider updating the [documentation online](https://github.com/OfflineIMAP/offlineimap.github.io/blob/master/_doc/use_cases.md)?

**Comment by mrvdb** [comment]
Yes, the wiki was easier.

**Comment by nicolas33** [comment]
Dups #209.

**Comment by deisi** [comment]
how about marks in mu4e are they the same? I have some custom marks there I like to sync e.g. `todo`. I tired to add them by adjusting adding a `('todo' , 't')` to https://github.com/OfflineIMAP/offlineimap/wiki/Syncing-custom-tags
and then started offlineimap. Sadly it seems not to be that simple, because its not showing up at my other machine.

**Comment by nicolas33** [comment]
This feature is more a hack than anything actually supported so I'm not sure this would work. There is currently no guarantee that the codebase is using the *modified version of imaputil*. Someone should add a `customflags` configuration option.

**Comment by deisi** [comment]
Okay, thx.
I found out about the `synclabels = yes` option. Is that the preferred way? However its not doing anything at all for me. Any idear?

**Comment by nicolas33** [comment]
`synclabels` is not about custom flags and is Gmail specific.

**Comment by deisi** [comment]
I tired to use it with gmail tags, but I couldn't get it to work.
Anyhow, I was hoping it would be more generic and I could use it with
other mail services as well, but if that is not the case, then its not
the feature I'm looking fore anyways.
