### ISSUE TITLE
cert_fingerprint errors for SSL connections

### ISSUE THREAD

**Issue by mcgiwer** [OfflineIMAP/offlineimap#309]
While attempting to use a IMAP connection to server with uses SSL, I'm getting following error:

`ERROR: Server SSL fingerprint '[trunchated for security reasons]' for hostname '[trunchated for security reasons]' does not match configured fingerprint. Please verify and set 'cert_fingerprint' accordingly if not set yet.`

**Comment by nicolas33** [comment]
Do they differ? Which offlineimap version?
It looks like your configuration is wrong somewhere.

**Comment by mcgiwer** [comment]
it's a fresh instalation of it and I had configured the program lbasing on documentation

**Comment by nicolas33** [comment]
No version provided, no configuration file provided.
