### ISSUE TITLE
Entire folder being redownloaded every sync

### ISSUE THREAD

**Issue by justmytwospence** [OfflineIMAP/offlineimap#313]
### General informations

- OfflineIMAP version: Homebrew 6.6.1
- server name or domain: imap.gmail.com
- CLI options: `offlineimap -o -a work`
- configuration (remove private data):
```
[general]
accounts = personal, work
fsync = False
maxsyncaccounts = 2
pythonfile = ~/.offlineimap/offlineimap.py
ui = ttyui

[DEFAULT]
auth_mechanisms = PLAIN
autorefresh = 1
sslcacertfile = /usr/local/etc/openssl/cert.pem
status_backend = sqlite

[Account work]
localrepository = work-local
remoterepository = work-remote

[Repository work-local]
type = Maildir
localfolders = ~/Mail/work
nametrans = lambda folder: {"Archive": "[Gmail]/All Mail",
                            "Drafts": "[Gmail]/Drafts",
                            "Inbox": "INBOX",
                            "Sent": "[Gmail]/Sent Mail",
                            "Spam": "[Gmail]/Spam",
                            "Trash": "[Gmail]/Trash"}.get(folder, folder)

[Repository work-remote]
type = Gmail
remotepasseval = get_authinfo_pass("imap.gmail.com", "sboucher@work.com")
remoteuser = sboucher@work.com
nametrans = lambda folder: {"[Gmail]/All Mail": "Archive",
                            "[Gmail]/Drafts": "Drafts",
                            "INBOX": "Inbox",
                            "[Gmail]/Sent Mail": "Sent",
                            "[Gmail]/Spam": "Spam",
                            "[Gmail]/Trash": "Trash"}.get(folder, folder)
```

### Log error

```
...
Folder Archive [remote name [Gmail]/All Mail] [acc: work]:
 Syncing [Gmail]/All Mail: Gmail -> Maildir
 ERROR: ERROR in syncfolder for work folder Archive: Traceback (most recent call last):
  File "/usr/local/Cellar/offlineimap/6.6.1/libexec/offlineimap/accounts.py", line 561, in sy
ncfolder                                                                                    
    check_uid_validity(localfolder, remotefolder, statusfolder)
  File "/usr/local/Cellar/offlineimap/6.6.1/libexec/offlineimap/accounts.py", line 423, in ch
eck_uid_validity                                                                            
    localfolder.save_uidvalidity()
  File "/usr/local/Cellar/offlineimap/6.6.1/libexec/offlineimap/folder/Base.py", line 246, in
 save_uidvalidity                                                                           
    os.rename(uidfilename + ".tmp", uidfilename)
OSError: [Errno 2] No such file or directory
...
```

### Step to reproduce the error

Things were working fine until a few days ago. I started getting weird XOAUTH errors for the first time. Adding `auth_mechanisms = PLAIN` fixed those. I don't think its related but it might be.

The above error only occurs when I completely clear out my work account and try to sync from scratch:

```
rm ~/Mail/work/*
rm .offlineimap/*work*
offlineimap -o -a work
```

After the first sync attempt, subsequent sync attempts do not throw this error, BUT it the goes on to **re**download my whole archive ([Gmail]/All Mail) even if I already have it locally.

**Comment by nicolas33** [comment]
The error is raised from here:

``` python
    def save_uidvalidity(self):
        """Save the UIDVALIDITY value of the folder to the cache

        This function is not threadsafe, so don't attempt to call it
        from concurrent threads."""

        newval = self.get_uidvalidity()
        uidfilename = self._getuidfilename()

        with open(uidfilename + ".tmp", "wt") as file:
            file.write("%d\n"% newval)
        os.rename(uidfilename + ".tmp", uidfilename)
        self._base_saved_uidvalidity = newval
```

It looks like the file gets deleted in between the `write` and the `rename`. That's odd since this function is not called from concurrent threads.

What's the filsystem used for `.offlineimap`?

I'd guess the full re-download is due to the error wiping all previous records from the cache while it should not.

**Comment by justmytwospence** [comment]
I'm on OSX 10.11.3, so hfs+ I think?

**Comment by justmytwospence** [comment]
I've made a little progress here. In the process of solving that XOAUTH error, I discovered `[DEFAULT]`, and moved some of my config to it, including `status_backend`. Putting `status_backend` back into the actual Account section seems like it might have fixed things. I will update when my 30,000 archived messages sync and I can test. Do I misunderstand how the `[DEFAULT]` section works?

**Comment by nicolas33** [comment]
> Do I misunderstand how the [DEFAULT] section works?

No, you look to get it right. However, I don't figure how the `[DEFAULT]` change could be the cause of your issues.

**Comment by nicolas33** [comment]
I think the change to use the `[DEFAULT]` section has not been correctly set up or parsed by the parser. If the backend was wrong, we can expect a full re-download.

I'd like to view the configuration file to check if it was right and help me reproduce this issue.

**Comment by nicolas33** [comment]
Oh! Sorry, the configuration is above.

Yes, the DEFAULT section is wrongly used. This feature still requires the option to be defined in the correct section to its "default value". IOW, you could use it like this:

```
[general]
accounts = personal, work

[DEFAULT]
plain_auth_only = PLAIN
default_backend = sqlite

[Account work]
localrepository = work-local
remoterepository = work-remote
status_backend = %(default_backend)s

[Repository work-remote]
type = Gmail
auth_mechanisms = %(plain_auth_only)s
```

Sorry I did not catch this sooner.
