### ISSUE TITLE
slow synchronizing to Exchange via Davmail

### ISSUE THREAD

**Issue by biocyberman** [OfflineIMAP/offlineimap#318]
### General informations

- OfflineIMAP version: 6.7.0
- server name or domain: localhost IMAP server provided by DavMail 4.7.1
- CLI options: offlineimap -o

```
# Configuration file offlineimaprc goes here. REMOVE PRIVATE DATA.
accounts = AAH
maxsyncaccounts = 1
maxconnections = 3
holdconnectionopen = true
# keep alive 60 seconds
keepalive = 60
# autorefresh in 3 minutes
autorefresh = 3
[Account AAH]
localrepository = AAH-Local
remoterepository = AAH-Remote

[Repository AAH-Local]
type = Maildir
localfolders = /home/Mail/AAH

[Repository AAH-Remote]
type = IMAP 
remoteuser = aahuser 
remotepass = secretpass
realdelete = no
ssl = no
remotehost = localhost
remoteport = 1143
folderfilter = lambda folder: not (re.search('^Sync',folder) or re.search('Junk', folder))

```
### Log error

```
Logs go here. REMOVE PRIVATE DATA.

ERROR: Copying message 330 [acc: AAH]
  EXAMINE command error: BAD ['unable to handle request: ErrorTimeoutExpired The request timed out.  request: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"><soap:Header><t:RequestServerVersion Version="Exchange2010_SP1"/></soap:Header><soap:Body><m:GetFolder><m:FolderShape><t:BaseShape>IdOnly</t:BaseShape><t:AdditionalProperties><t:ExtendedFieldURI PropertyTag="0x10f3" PropertyType="String"/><t:ExtendedFieldURI PropertyTag="0x6752" PropertyType="Integer"/><t:ExtendedFieldURI PropertyTag="0x3603" PropertyType="Integer"/><t:ExtendedFieldURI PropertyTag="0x6751" PropertyType="Integer"/><t:FieldURI FieldURI="folder:DisplayName"/><t:ExtendedFieldURI PropertyTag="0x360a" PropertyType="Boolean"/><t:ExtendedFieldURI PropertyTag="0x670a" PropertyType="SystemTime"/><t:ExtendedFieldURI PropertyTag="0x3613" PropertyType="String"/><t:ExtendedFieldURI PropertyTag="0x3602" PropertyType="Integer"/><t:ExtendedFieldURI PropertyTag="0x3008" PropertyType="SystemTime"/></t:AdditionalProperties></m:FolderShape><m:FolderIds><t:FolderId Id="DDDDQICNjcO9niNtAQCl5iRAhlh1SZml8BVHpJBzAAACrUsAAAA=" ChangeKey="AQAAABQAAAAQGVzmeIRpRJU9r8NfN4u5ABH4Aw=="/></m:FolderIds></m:GetFolder></soap:Body></soap:Envelope>']. Data: INBOX/Subfolder

Traceback:
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 787, in copymessageto
    message = self.getmessage(uid)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 285, in getmessage
    data = self._fetch_from_imap(str(uid), 2)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 695, in _fetch_from_imap
    imapobj.select(self.getfullname(), readonly = True)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplibutil.py", line 50, in select
    result = super(UsefulIMAPMixIn, self).select(mailbox, readonly)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1058, in select
    self._deliver_exc(self.error, '%s command error: %s %s. Data: %.100s' % (name, typ, dat, mailbox), kw)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1491, in _deliver_exc
    raise exc(dat)
```

### Steps to reproduce the error

- Setup Davmail at local host, use default insecure ports, enable IMAP server
- Test connection with `offlineimap --info`. Everthing looks fine.
- Test IMAP connection with Thunderbird. Everything works, sync 8000 emails in about 7 minutes.
- Setup offlinemap with encrypted password, but because sync'ing too slow, I used plain text password to test.
- Run `offlineimap -o` to prepopulate the maildir. Email sync'ing is still very slow. And finally gave up with the error.

**Comment by nicolas33** [comment]
> Test IMAP connection with Thunderbird. Everything works, sync 8000 emails in about 7 minutes.

Not sure Thunderbird is downloading the full emails. Probably just the headers.

> Setup offlinemap with encrypted password, but because sync'ing too slow, I used plain text password to test.

I don't get how plain text password can improve speed.

> Run offlineimap -o to prepopulate the maildir. Email sync'ing is still very slow. And finally gave up with the error.

While I do believe in your user experience, "still very slow" is not very meaningful.
There are two diffferent issues to address seperately:
1. The error.
2. The speed.
We are not sure both are related.

About the error, please try with `maxconnections = 1`.

For the performance issue, you might like to audit the CPU, bandwidth and disk usages to check if there's anything obvious/compelling. Please, provide numbers.

However, I wonder the timeout error for the request
```
EXAMINE command error: BAD ['unable to handle request: ErrorTimeoutExpired The request timed out.  request: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" <...>
```
is what makes OfflineIMAP slow. It really looks like Davmail don't get a response from the Exchange server making OfflineIMAP waiting for something. I would first fix the `maxconnections` option.

**Comment by biocyberman** [comment]
- Thunderbird: It did download the full email. I turned off davmail and still can view randomly any email, even with attachments.

- Plain password: That is just a way to disable passphrase request to unlock the password. Because offlineimap was running in background for about 1 minute after I entered passphrase to release the password, I thought "let it goes straight to see what happens".

- Audit CPU, bandwidth: I haven't thought about this because other activities are working normally. Besides, Thunderbird did OK so I made the phrase 'very slow' do describe the relative performance against Thunderbird. Anyway, I tested connection speed to the email network (because I can't test the mail server directly), I got the real connection and writing to `maildir` disk about 2.5MByte/s at the time of test. I ran again the `offlineimap -o` and the speed and error appeared again. It take about 2 to 3 seconds to copy/sync a message of less than 100kB.

This is the `top` output, which does not look like the computer is working hard at all:
```
 top - 21:27:55 up 10:47,  5 users,  load average: 1.04, 1.00, 0.69             
Tasks: 223 total,   3 running, 220 sleeping,   0 stopped,   0 zombie           
%Cpu(s):  5.1 us,  2.5 sy,  0.0 ni, 91.3 id,  0.2 wa,  0.8 hi,  0.0 si,  0.0 st
KiB Mem:   8115652 total,  3828600 used,  4287052 free,   187076 buffers       
KiB Swap: 19530748 total,        0 used, 19530748 free.  1322120 cached Mem    

```
- The error: I change `maxconnections = 1` and rerun `offlineimap -o`. This is the error I got:

```
 Establishing connection to localhost:1143
Thread 'Copy message from AAH-Remote:INBOX' terminated with exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/threadutil.py", line 163, in run
    Thread.run(self)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 787, in copymessageto
    message = self.getmessage(uid)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 285, in getmessage
    data = self._fetch_from_imap(str(uid), 2)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 695, in _fetch_from_imap
    imapobj.select(self.getfullname(), readonly = True)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplibutil.py", line 50, in select
    result = super(UsefulIMAPMixIn, self).select(mailbox, readonly)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1052, in select
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 199, in get_response
    raise typ(exc_fmt % str(val))
OfflineImapError: Server 'localhost' closed connection, error on SELECT 'INBOX'. Server said: command: EXAMINE => socket error: <type 'exceptions.IOError'> - Too many read 0

Last 1 debug messages logged for Copy message from AAH-Remote:INBOX prior to exception:
thread: Register new thread 'Copy message from AAH-Remote:INBOX' (account 'AAH')
```
- For comparison, I set up an Gmail account. THe sync process went about hafl a second a message.

- One thing I wonder though, it could be that `Thunderbird` abused the mail server and `offlineimap` is suffering the throttle. This I have no way to check for now. I will wait for a day or so to try again and contact the admin as well.

**Comment by biocyberman** [comment]
Thinking about it further, the comparison against `Thunderbird` may be unfair. You may be right that Thunderbird fetched mail headers first, and the mail content later. So the check of email content in Thunderbird I described in the previous comment is not meaningful.

**Comment by nicolas33** [comment]
> offlineimap is suffering the throttle

I remember we had reports that OfflineIMAP has glitches with Exchange server due to some Exchange limitations out of IMAP standard in this area. I don't remember feedbacks about that via davmail, though.

**Comment by biocyberman** [comment]
Thanks for very responsive feedback. I will try to find a way around this somehow.

**Comment by dolohow** [comment]
I cannot reproduce your problem.  I am using davmail with exchange in corporate network and syncing is much faster comparing to fetching emails from my private gmail account.

**Comment by nicolas33** [comment]
@dolohow Thanks!

1. I'm pretty sure Thunderbird only downloads headers first. I don't think we should compare with it.
2. offlineimap is suffuring the throttle and this might worth reporting this issue upstream to imaplib2.
3. Since we have different feedbacks about offlineimap/davmail/exchange this might help comparing your setups and configs.

**Comment by sidhu1f** [comment]
Offlineimap(6.7.0) + davmail(4.7.1) + exchange setup taking several seconds per message on a modern laptop running Debian(stretch).

My .offlineimaprc:
`
[general]
accounts = work

[Account work]
localrepository = loc-work
remoterepository = rem-work

[Repository loc-work]
type = Maildir
localfolders = ~/Test

[Repository rem-work]
type = IMAP
ssl = no
remoteuser = <userid>
remotehost = localhost
remoteport = 1143
`

**Comment by nicolas33** [comment]
Please, try without Davmail to confirm this comes from offlineimap.
