### ISSUE TITLE
OfflineIMAP does not follow XDG Base Spec

### ISSUE THREAD

**Issue by gioele** [OfflineIMAP/offlineimap#32]
OfflineIMAP stores its configuration in `~/.offlineimaprc`. Instead of cluttering the home directory, it should follow the XDG Base Directory spec and store its configuration in its own directory under `$XDG_CONFIG_HOME` (`.config` by default).

http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by lahwaacz** [comment]
To complete the compliance to the XDG standard, the pidfile should be created in `$XDG_RUNTIME_DIR` instead of the (configurable) metadata dir.

**Comment by gioele** [comment]
@lahwaacz please fine another issue just for that problem.
