### ISSUE TITLE
Self signed certificate fails to verify how to proceed ?

### ISSUE THREAD

**Issue by delanoe** [OfflineIMAP/offlineimap#322]
### General informations

- OfflineIMAP version: 6.6.1 (Debian Stretch)
- server name or domain: fedex.iscpif.fr (self signed certificate)

Configuration file offlineimaprc goes here. REMOVE PRIVATE DATA.
```
[Repository LocalISCPIF]
type = Maildir
localfolders = ~/mail/inbox-ISCPIF-imap/

[Repository RemoteISCPIF]
type = IMAP
remotehost = fedex dot iscpif dot fr
ssl = yes
remoteuser = user
remotepass = password
sslcacertfile = /etc/ssl/certs/ca-certificates.crt

``

### Log error

Account sync ISCPIF:
 *** Processing account ISCPIF
  Establishing connection to fedex.iscpif.fr:993
   ERROR: Unknown SSL protocol connecting to host 'fedex.iscpif.fr' for
   repository 'RemoteISCPIF'. OpenSSL responded:
   [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
   (_ssl.c:590)
    *** Finished account 'ISCPIF' in 0:00
    ERROR: Exceptions occurred during the run!
    ERROR: Unknown SSL protocol connecting to host 'fedex.iscpif.fr' for
    repository 'RemoteISCPIF'. OpenSSL responded:
    [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
    (_ssl.c:590)


Traceback:
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 263, in syncrunner
    self.__sync()
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 326, in __sync
    remoterepos.getfolders()
  File "/usr/share/offlineimap/offlineimap/repository/IMAP.py", line 384, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/usr/share/offlineimap/offlineimap/imapserver.py", line 483, in acquireconnection
    tls_level=self.tlslevel,
  File "/usr/share/offlineimap/offlineimap/imaplibutil.py", line 186, in __init__
    super(WrappedIMAP4_SSL, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/imaplib2.py", line 2138, in __init__
    IMAP4.__init__(self, host, port, debug, debug_file, identifier, timeout, debug_buf_lvl)
  File "/usr/lib/python2.7/dist-packages/imaplib2.py", line 357, in __init__
    self.open(host, port)
  File "/usr/share/offlineimap/offlineimap/imaplibutil.py", line 194, in open
    super(WrappedIMAP4_SSL, self).open(host, port)
  File "/usr/lib/python2.7/dist-packages/imaplib2.py", line 2151, in open
    self.ssl_wrap_socket()
  File "/usr/lib/python2.7/dist-packages/imaplib2.py", line 522, in ssl_wrap_socket
    self.sock = ssl.wrap_socket(self.sock, self.keyfile, self.certfile, ca_certs=self.ca_certs, cert_reqs=cert_reqs, ssl_version=ssl_version)
  File "/usr/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()

**Comment by nicolas33** [comment]
Could you confirm you can connect with openssl, please?

**Comment by delanoe** [comment]
openssl s_client  -connect fedex.iscpif.fr:imaps
gives:
CONNECTED(00000003)
depth=0 C = FR, O = CNRS, OU = UMR7656, CN = imap.iscpif.fr, emailAddress = antoine.jacoutot@polytechnique.edu
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = FR, O = CNRS, OU = UMR7656, CN = imap.iscpif.fr, emailAddress = 
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/C=FR/O=CNRS/OU=UMR7656/CN=imap.iscpif.fr/emailAddress=antoine.jacoutot@polytechnique.edu
   i:/C=FR/O=CNRS/CN=CNRS-Standard
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIEBDCCAuygAwIBAgICd2QwDQYJKoZIhvcNAQEFBQAwNDELMAkGA1UEBhMCRlIx
DTALBgNVBAoTBENOUlMxFjAUBgNVBAMTDUNOUlMtU3RhbmRhcmQwHhcNMDgwMzI
awK0xQzV41hqCZaJUo5ctKOyLSXyjdbcAEfgBHs6GZrsLCw+i6O7c3jdz0Nf/ZgU
NKFXbcywhizi6C9pzWijfOMnGlzeKVRSgC99lnlJD+IIo5kt5RIBux/tzk3DPWiu
yyqH7jcnw0i0P5dHELcdAgMBAAGjggFcMIIBWDAMBgNVHRMBAf8EAjAAMBEGCWCG
SAGG+EIBAQQEAwIGwDAOBgNVHQ8BAf8EBAMCBeAwHQYDVR0lBBYwFAYIKwYBBQUH
AwEGCCsGAQUFBwMCMC8GCWCGSAGG+EIBDQQiFiBDZXJ0aWZpY2F0IHNlcnZldXIg
Q05SUy1TdGFuZGFyZDAdBgNVHQ4EFgQUDMvUYW9r4X9vWee1uamXPNyXbKkwUwYD
VR0jBEwwSoAUZ1ml5Qd0SQPvBc/MLqQY1RDInjyhL6QtMCsxCzAJBgNVBAYTAkZS
MQ0wCwYDVQQKEwRDTlJTMQ0wCwYDVQQDEwRDTlJTggECMBkGA1UdEQQSMBCCDmlt
YXAuaXNjcGlmLmZyMEYGA1UdHwQ/MD0wO6A5oDeGNWh0dHA6Ly9jcmxzLnNlcnZp
Y2VzLmNucnMuZnIvQ05SUy1TdGFuZGFyZC9nZXRkZXIuY3JsMA0GCSqGSIb3DQEB
BQUAA4IBAQAzjvNpDkQjZJ+cOSRnueeajvJRTCD8XzDSwmB5j8ILvmcYZJTobLnN
ISAy/3NNPV0UiaY70ML5YGsfDEvyqlrjRPW8svN7J+bib1JxkcTQe8LzROuALMA5
6e9teAlbXBEYLrMdBC4OwGAA4aUirOCqSMnjZRMhCdvzlQkYVI1bya83Tk9VyLsa
xMmdZwCgxspOAPCjU8NUYQTmKhLuCJQe0ywofci1YsSwzSEgpQP16Wk5l1Zd1rHS
/0Y0NYWzyx3Ud7Skbr2ljvtvltxbj4dwow/XI+tbS8hWU1I1MYHvp+4vsttyOTA1
pqAdQPdcRfp4Syq5cUcWW45D8LJs426L
-----END CERTIFICATE-----
subject=/C=FR/O=CNRS/OU=UMR7656/CN=imap.iscpif.fr/emailAddress=bla@
issuer=/C=FR/O=CNRS/CN=CNRS-Standard
---
No client certificate CA names sent
Server Temp Key: DH, 1024 bits
---
SSL handshake has read 1750 bytes and written 503 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-SHA
Server public key is 1024 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES256-SHA
    Session-ID: 3152948F27BF6AD24B67585C9F6E3308A41783B1C94B9D39F1B13B7E21A8724A
    Session-ID-ctx: 
    Master-Key: CAD027EFC731634BAC34A11378E43342083AD4A4CC970D9BD1AC729631E34BD532E9640FB21BE7148EE164FDFA4D480D
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket:
    0000 - f1 83 0f b0 f5 71 82 db-f2 01 ab 43 d1 b7 c1 eb   .....q.....C....
    0010 - 44 3f b2 59 7a 9c 47 f6-e5 62 b4 1e c6 d9 c9 4b   D?.Yz.G..b.....K
    0020 - be a9 b0 32 93 97 5f cf-9f 3f 03 7b 26 55 ea 86   ...2.._..?.{&U..
    0030 - 24 b5 52 95 4d 06 59 46-6d c6 fc 9e c4 72 90 ee   $.R.M.YFm....r..
    0040 - d6 a4 81 7d a7 61 8b 73-2e 54 44 64 31 d4 13 cf   ...}.a.s.TDd1...
    0050 - 6a 92 3e 9b 5d 57 c0 83-4d ae 49 87 8f 8e 38 d5   j.>.]W..M.I...8.
    0060 - bc d0 f9 1c ac 1c df 3b-55 ca df 7b 77 f4 bb cd   .......;U..{w...
    0070 - d9 67 79 65 a6 5e ac c2-27 24 4d 19 1b 13 7f 2b   .gye.^..'$M....+
    0080 - c2 66 35 07 e9 1a c6 c5-c8 5e df 9b 4d 9f bb e0   .f5......^..M...
    0090 - 6f 87 8c 7a e4 c2 a0 75-8c c1 8c 53 4e 4f b5 15   o..z...u...SNO..

    Start Time: 1459231140
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
* OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE AUTH=PLAIN SASL-IR] imap.iscpif.fr Cyrus IMAP v2.4.13 server ready

**Comment by konvpalto** [comment]
You could try to put CA certificate for /C=FR/O=CNRS/CN=CNRS-Standard into /etc/ssl/certs/ca-certificates.crt (just add it to the end of the file). Or put it into the separate file and change value for sslcacertfile.

Though the part of the problem can be that you're using certificate that is issued by the obsolete CA root, https://igc.services.cnrs.fr/CNRS2-Standard/?lang=en&act=view&view_CA=CNRS-Standard&cmd=search_CA_certificate&body=view_ca.html

As I know, CNRS moved to CNRS2 certificates some years ago,
  https://igc.services.cnrs.fr/search_CA_certificate/?CA=GRID2-FR&lang=en&body=view_ca.html
and the certificate of your IMAP server is expired in 2010,
{{{
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 30564 (0x7764)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=FR, O=CNRS, CN=CNRS-Standard
        Validity
            Not Before: Mar 21 14:29:34 2008 GMT
            Not After : Mar 21 14:29:34 2010 GMT
        Subject: C=FR, O=CNRS, OU=UMR7656, CN=imap.iscpif.fr/emailAddress=antoine.jacoutot@polytechnique.edu
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (1024 bit)
                Modulus:
                    00:db:d5:f0:44:31:e8:d1:ea:b8:50:b6:14:26:25:
                    55:06:14:6b:02:b4:c5:0c:d5:e3:58:6a:09:96:89:
                    52:8e:5c:b4:a3:b2:2d:25:f2:8d:d6:dc:00:47:e0:
                    04:7b:3a:19:9a:ec:2c:2c:3e:8b:a3:bb:73:78:dd:
                    cf:43:5f:fd:98:14:34:a1:57:6d:cc:b0:86:2c:e2:
                    e8:2f:69:cd:68:a3:7c:e3:27:1a:5c:de:29:54:52:
                    80:2f:7d:96:79:49:0f:e2:08:a3:99:2d:e5:12:01:
                    bb:1f:ed:ce:4d:c3:3d:68:ae:cb:2a:87:ee:37:27:
                    c3:48:b4:3f:97:47:10:b7:1d
                Exponent: 65537 (0x10001)
}}}

So, the best way would be to advise your IMAP admins to get new certificate from CNRS2 and when they'll do that and you'll put appropriate root certificate to your sslcacertfile things should be OK.

**Comment by delanoe** [comment]
Hi, thanks for your reply.
Yes I have contact the admin already. Changes are coming but I need to have an access immediatly.

In fact I added the certificate already and I got the same error.

I tried to put it at the end of the file: /etc/ssl/certs/ca-certificates.crt
or in a new file.

I changed my offlineimaprc configuration accordingly.

But Maybe I did not put the right file. I put this one:

-----BEGIN CERTIFICATE-----
MIIDbTCCAlWgAwIBAgIBAjANBgkqhkiG9w0BAQQFADArMQswCQYDVQQGEwJGUjEN
MAsGA1UEChMEQ05SUzENMAsGA1UEAxMEQ05SUzAeFw0wMTA0MjcwNTQ2NDlaFw0x
MTA0MjUwNTQ2NDlaMDQxCzAJBgNVBAYTAkZSMQ0wCwYDVQQKEwRDTlJTMRYwFAYD
VQQDEw1DTlJTLVN0YW5kYXJkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEA3OEeIT0Gi+q9XrSI2w+Tl7RtBz2GYgAtyv+1So7nVqSPYSzxoCqr9irdfCy/
73VVC6wJTudOYcDnDPCQFUUSAsKM68MSZOJjEBguywcx2YHl3CmCmzFW4oEeim+n
6KlYEURWg12zTnhwLd+2/XKBRdXx7k3O777VPQyQIEWaCYCvD0zaIA6Avzqz6yeA
wLkPwKFOQNw6/Woqv0DVLHGA+fi6a+TqKgCrL76a8Kd2bZgpnA8v8ELyGJdbyfbM
GV+6wr4S0lywkJTAt8sGBO+PMO0yLXpK95O7oAmktO4zy9CDm7W1s5DejpAeWZwg
1Use7ddMT4b6HDoqoemsBaCdvwIDAQABo4GSMIGPMAwGA1UdEwQFMAMBAf8wHQYD
VR0OBBYEFGdZpeUHdEkD7wXPzC6kGNUQyJ48MFMGA1UdIwRMMEqAFFbraLnSXH6Y
taVTw5FvY1jE+Wu3oS+kLTArMQswCQYDVQQGEwJGUjENMAsGA1UEChMEQ05SUzEN
MAsGA1UEAxMEQ05SU4IBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEEBQADggEB
AAYDR4NyRZDCTuEh16sXqQFVBspAbVWiHV7r4hQjWeQJ4pD2PI02Bg9LpyYjZcLq
Bppyu7iMy4pf73k2JX4A1/MGlPuDRCkmN8fu6YfObIaAG3E90mKv9s1ibFMP5nqT
AIx7LjPgQR2qvmWYdvGVB3Sz5j9TddVLBjZLKcT23I4TgEAQc4KtFXsEcVC1NzPy
yGS7oRB+Nsatr29wUqbRrszMurDoWRKPYg2tA91LKuiJOYhRL+1h6Lcwh9snVW1m
h6NRCYBhcVEFvhMd2UEw/HVfCpabGP++kIG0E8ByEQj9appqB730gyy0YDZkB/o9
aqewkAR2g90zyzTiF5gEC6E=
-----END CERTIFICATE-----

**Comment by nicolas33** [comment]
> I tried to put it at the end of the file: /etc/ssl/certs/ca-certificates.crt
> or in a new file.

I wonder the certificate must be in its own file. Not sure, though.

> I changed my offlineimaprc configuration accordingly.
> 
> But Maybe I did not put the right file. I put this one:

I'm afraid we have no clue to tell you which file is correct.

> openssl s_client -connect fedex.iscpif.fr:imaps
> gives:
> CONNECTED(00000003)
> depth=0 C = FR, O = CNRS, OU = UMR7656, CN = imap.iscpif.fr, emailAddress = blah@
> verify error:num=20:unable to get local issuer certificate
> verify return:1
> depth=0 C = FR, O = CNRS, OU = UMR7656, CN = imap.iscpif.fr, emailAddress = 
> verify error:num=21:unable to verify the first certificate
> 
> verify return:1

The certificate/configuration you're using for SSL is not working. Those errors are not related to offlineimap.

We can't help much because SSL configuration depends on the sites users try to connect. The openssl command must work to confirm the SSL transport is working and correctly configured or offlineimap will fail.

Once the openssl command works and if you have doubts about offlineimap, you might use the `-d imap` CLI option.

**Comment by delanoe** [comment]
Ok, thanks for your replies, thanks for offlineimap.
Cheers

**Comment by konvpalto** [comment]
If you need immediate access, then comment out sslcacertfile in remote repository configuration and add there a fingerprint line:
> cert_fingerprint = 031b236fb5bf4ccf6042fb1c381500a525a691ca

It should do the trick.

**Comment by delanoe** [comment]
2016/03/29 23:03, konvpalto:
> If you need immediate access, then comment out sslcacertfile in remote
> repository configuration and add there a fingerprint line:
> 
>     cert_fingerprint = 031b236fb5bf4ccf6042fb1c381500a525a691ca
> 
> It should do the trick.

Yes, it did. Thanks!


-- 
Alexandre Delanoë
