### ISSUE TITLE
offlineimap removes all my emails on second run

### ISSUE THREAD

**Issue by dolohow** [OfflineIMAP/offlineimap#327]
### General informations

- OfflineIMAP version: 6.7.0
- server name or domain: Davmail

```
[general]
accounts = AccountName
fsync = false
maxconnections = 1
sockettimeout = 10

[mbnames]
enabled = yes
filename = ~/.mutt/mailboxes
header = "mailboxes "
peritem = "+%(accountname)s/%(foldername)s"
sep = " "
footer = "\n"

[notifications]
summary = "[{account}] Nowa wiadomość"
notifier = "notify-send"

[Account AccountName]
localrepository = Local-AccountName
remoterepository = Remote-AccountName
status_backend = sqlite
autorefresh = 1
status_backend = sqlite
#maxage = 15

[Repository Local-AccountName]
type = Maildir
localfolders = ~/Mail/AccountName

[Repository Remote-AccountName]
type = IMAP
remotehost = 10.15.197.26
remoteport = 1143
remoteuser = USERNAME
ssl = no
holdconnectionopen = yes
keepalive = 60
```

### Log error

First run `$ offlineimap -o`:
```
...
Copy message 1876 (191 of 191) Remote-AccountName:INBOX -> Local-AccountName
```

Second run `$ offlineimap`:
```
Folder INBOX [acc: AccountName]:
 Deleting 190 messages (831,836:852,854,856:858,915,918,925,1028,1031,1034,1037,1040,1043,1046,1082,109
0,1093,1096,1195,1198,1201,1204,1227,1286,1288,1334,1337,1340,1346,1387,1390,1393,1395,1449,1496,1499,1
502,1505,1569,1571,1574,1577,1580,1598,1602,1612,1615,1620:1621,1623:1624,1640,1643,1646,1653,1665,1673
,1675,1677,1683:1685,1692,1698,1701,1716,1720,1722,1724,1729,1733:1734,1736,1738,1769,1772,1775,1778,17
81,1784,1788:1789,1791,1793:1794,1797,1804:1806,1808,1813,1815,1817,1820,1823,1825:1826,1829,1833,1847,
1849,1855:1856,1868,1871,1873:1874,1876:1878,1881:1882,1886,1888:1893,1908,1911,1913,1918,1921:1922,192
4,1934,1961,1996,1999,2002,2005,2007,2009,2112,2115,2122,2125,2127,2131,2134,2144,2148,2152,2162,2165,2
168,2171,2174,2177,2180,2183,2186,2189,2192,2195,2198,2201,2204,2208,2210,2213,2216,2222,2227:2228,2288
,2312,2363,2366,2369,2371) in Maildir[INBOX]
```

### Steps to reproduce the error
1. Set up oflfineimap like above.
2. Run `offlineimap -o` to fetch all emails (works as expected).
3. Uncomment line `maxage = 15`
4. Offlineimap starts to removing all emails from local maildir (INBOX, Sent etc) while keeping them on Exchange server (maybe it would remove them, but I did not wait until it completes (ctrl+c repeatedly)

Interesting thing is that it keeps one message in INBOX.

Happens: always

**Comment by nicolas33** [comment]
Definetly not cool.

I can think of different root causes:
* a bug with `autorefresh`
* a bug with `maxage`
* a bug with both `autorefresh` and `maxage`
* a bug unrelated to all above.

Would be great if you could run other tests with:

1. `autorefresh` disabled for both syncs
2. no change in `maxage = 15` for both sync
3. no `maxage` at all for both syncs
4. no `autorefresh` and no `maxage` for both syncs

In order to help, I made a dedicated version which will print what would be deleted without ever deleting anything: https://github.com/nicolas33/offlineimap/tree/test-deletions which includes commit https://github.com/nicolas33/offlineimap/commit/5903670b5a35a8c2e929337a227ce5d44a586d16.

For the tests, please duplicate the configuration file and **tune both `metadata` and `localfolders` options**. Also, **don't forget to remove the content of both paths *between* the tests**.

**Comment by dolohow** [comment]
> In order to help, I made a dedicated version which will print what would be deleted without ever deleting anything: https://github.com/nicolas33/offlineimap/tree/test-deletions which includes commit nicolas33@5903670.

Applied, thanks.

> 1. autorefresh disabled for both syncs

Issue still present

> 2. no change in maxage = 15 for both sync

It only fetched one message from 8 April for every maildir (I received more at that day, maybe 22 - 15 = 7) which is weird, cause I am receiving messages every day.

> 3. no maxage at all for both syncs

Works fine

> 4. no autorefresh and no maxage for both syncs

Works fine

**Comment by nicolas33** [comment]
Looks really like an issue with maxage. I wonder the Exchange server is providing weird date times.

**Comment by dolohow** [comment]
You want some more data? maybe I could attach somewhere with debugger?

**Comment by nicolas33** [comment]
Running tests with davmail removed from the setup could help to know if davmail is the cause, too.

**Comment by dolohow** [comment]
Exchange is the only way to get the emails. If I can directly connect to it with offlineimap then I can remove the davmail proxy or you can suggest another proxy-like program.

**Comment by nicolas33** [comment]
Si there data loss? Are the emails deleted on the remote, too?

**Comment by dolohow** [comment]
Just like I said, after I saw offlineimap is deleting messages I pressed 
Ctrl+C three times. Then I applied your patch, so that no emails will be 
removed on remote. But I guess offlineimap would remove only local mails 
and leave the remote ones untoched.

**Comment by nicolas33** [comment]
Thank you much for your patch @dolohow !

**Comment by runcom** [comment]
happens on Gmail remotes as well, just lost all my INBOX

**Comment by nicolas33** [comment]
@runcom Open a new issue, please.
