### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by fser** [OfflineIMAP/offlineimap#328]
> This v1.0 template stands in `.github/`.

### General informations

- OfflineIMAP version: 6.5.5
- server name or domain: imap.univ-lille1.fr
- CLI options: none

```
[general]
accounts = univ

[Account univ]
localrepository = local
remoterepository = imap-cri

[Repository local]
type = Maildir
localfolders = ~/Maildir

[Repository imap-cri]
type = IMAP
remotehost = imap.univ-lille1.fr
remoteuser = <<my login>>
remotepass = <<my passwd>>
createfolders = False
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
ssl = yes
```
I get no log errors nor steps to reproduce, but *at some point* offlineimaps fails.
I run it using cron job every two minutes. Currently, the pid file is not even correct, and the process is stucked in an infinite loop:

```
$ cat .offlineimap/pid 
16843

This process don't exist anymore
$ ps aux | grep offline
fser     17133  0.2  0.7 692744 28696 ?        Ssl  Apr21  17:00 /usr/bin/python2.7 /usr/bin/offlineimap
$ strace -p 17133
...
gettimeofday({1461565468, 170399}, NULL) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
...
```

**Comment by nicolas33** [comment]
Is this reproducible with v6.7.0?

**Comment by nicolas33** [comment]
About the wrong PID, see #329.

**Comment by nicolas33** [comment]
BTW, I think this very low sleep time (2 mins) for the cron job might not help. You might want to start offlineimap from a shell script like:

```
ps aux | grep -q '/usr/bin/offlineimap'  || offlineimap
```

**Comment by fser** [comment]
Thanks for the hint. However, this is a rather small mailbox. Most of the time, synchronization don't take more than 10 seconds. I'll try to upgrade to 6.7.0 but I couldn't properly reproduce. I just get to see that the process is stucked somehow, sometimes.

**Comment by nicolas33** [comment]
Keeping open so that you can add more reproducible information.

**Comment by fser** [comment]
As soon as the bug reoccurs!

**Comment by nicolas33** [comment]
Look not that common. :-)
I'm clonsing. Feel free to report more information here and we'll re-open.
