### ISSUE TITLE
Don't delete entire mailbox without confirmation

### ISSUE THREAD

**Issue by shlevy** [OfflineIMAP/offlineimap#333]
I was trying to set up offlineimap for the first time, and my original setup had some folder mapping errors so I modified my configuration, removed the local mail directory, and ran again. Of course, as explained in http://docs.offlineimap.org/en/latest/FAQ.html#may-i-delete-local-folders, offlineimap treated this as me asking to delete every message on the server. I understand why the 2-way syncing behavior is there, but I think it's a fairly common procedure for figuring out new software to nuke the tool's state and start fresh. It's not obvious that there's extra state in `.offlineimap`, so for the case where the entire mail directory is deleted I think it makes sense for offlineimap to confirm the deletion.

**Comment by nicolas33** [comment]
Actually, removing the Maildir should not imply emails deletions currently. AFAIR, emails are deleted only if the *files* in the maildir are removed.

This might need more checks.

**Comment by nicolas33** [comment]
Fixed.

**Comment by nicolas33** [comment]
Will be included in v7.0.0.

**Comment by nicolas33** [comment]
http://www.offlineimap.org/doc/FAQ.html#may-i-delete-local-folders
