### ISSUE TITLE
create folders in order of hierarchy

### ISSUE THREAD

**Issue by nicolas33** [OfflineIMAP/offlineimap#335]
See #212.
For example, `a/` must be created before `a/bc`.

**Comment by dolohow** [comment]
I hit that too and I was thinking about implementing mkdir -p behavior.

**Comment by nicolas33** [comment]
I think that would be easier than ordering.

**Comment by nicolas33** [comment]
It seems server specific. I couldn't reproduce this issue.

**Comment by nicolas33** [comment]
Patch applied. Should be in the next release (after 7.2.3).
