### ISSUE TITLE
password with percent sign 

### ISSUE THREAD

**Issue by ezekieldas** [OfflineIMAP/offlineimap#342]
> This v1.0 template stands in `.github/`.

### General informations

- OfflineIMAP version: offlineimap-6.5.2.1-3.el6.noarch
- server name or domain: n/a
- CLI options: n/a

```
Configuration file offlineimaprc goes here. REMOVE PRIVATE DATA.
```

```
The pythonfile file goes here (if any). REMOVE PRIVATE DATA.
```

### Log error

```
Logs go here. REMOVE PRIVATE DATA.
```

### Steps to reproduce the error

Use something like:

remotepass = 23%adf9202^aw..

ERROR: Exceptions occurred during the run!
ERROR: While attempting to sync account 'LuxSci'
  '%' must be followed by '%' or '(', found: '23%adf9202^aw..'
- 
-

**Comment by nicolas33** [comment]
Did you read this?
* https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L823
* https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L42

**Comment by ezekieldas** [comment]
Hi --Thank you. I may have seen that at some point but I've been using 
the same config for so many years now I rarely reference the commented 
version.

Neither of these sections are really clear though. The first gives an 
example that doesn't include a %. The second doesn't make any sense to me.

Does this mean that if my password is 'p%ssword' I have to use 'p%%ssword'


remotepass = p%ssword 	# FAIL / NO / WRONG / INCORRECT
remotepass = p%%ssword  # WIN  / YES / RIGHT / CORRECT

But why does documentation have to fix this? I just changed over 24 
passwords recently (to long and complex). Offlineimap was one of the few 
items that wouldn't take certain characters. What's parsing that file? 
Any plans to change this?

Cheers,
-zeek

**Comment by nicolas33** [comment]
The % is a feature of the parsing library. I've never tried to disable this and I won't because it's used by users. I'll improve the doc.

**Comment by ezekieldas** [comment]
Did my example make sense?

Does this mean that if my password is 'p%ssword' I have to use 'p%%ssword'


remotepass = p%ssword     # FAIL / NO / WRONG / INCORRECT
remotepass = p%%ssword  # WIN  / YES / RIGHT / CORRECT

**Comment by dolohow** [comment]
Correct.

**Comment by nicolas33** [comment]
Done.
