### ISSUE TITLE
All mail deleted from remote Gmail account

### ISSUE THREAD

**Issue by runcom** [OfflineIMAP/offlineimap#349]
#### General informations

- offlineimap version (`offlineimap -V`): 6.7.0
- Python version: 2.7.11
- server name or domain: Gmail
- CLI options: 

#### Configuration file offlineimaprc

```
[general]
accounts = Gmail
fsync = false
ui = ttyui

[notifications]
summary = "[{account}] test"
notifier = "notify-send"

[Account Gmail]
autorefresh = 0.5
quick = 10
localrepository = Gmail-Local
remoterepository = Gmail-Remote
status_backend = sqlite

[Repository Gmail-Local]
type = Maildir
localfolders = ~/Mail
nametrans = lambda folder: {'drafts':  '[Gmail]/Drafts',
                            'sent':    '[Gmail]/Sent Mail',
                            'important':    '[Gmail]/Important',
                            'spam':    '[Gmail]/Spam',
                            'starred': '[Gmail]/Starred',
                            'trash':   '[Gmail]/Trash',
                            'archive': '[Gmail]/All Mail',
                            }.get(folder, folder)
sep = /

[Repository Gmail-Remote]
type = Gmail
maxconnections = 2
remoteuser = amurdaca@gmail.com
remotepass = 
realdelete = no
keepalive = 60
holdconnectionopen = yes
createfolders = False
nametrans = lambda foldername: re.sub ('^\[gmail\]', 'bak',
                               re.sub ('sent_mail', 'sent',
                               re.sub ('fedora/', 'fedora-',
                               re.sub ('starred', 'flagged',
                               re.sub (' ', '_', foldername.lower())))))

folderfilter = lambda foldername: foldername not in ['[Gmail]/All Mail', '[Gmail]/Important']
# Necessary as of OfflineIMAP 6.5.4
sslcacertfile = /etc/ssl/certs/ca-bundle.crt

[mbnames]
enabled = yes
filename = ~/.mutt/mailboxes
header = "mailboxes "
peritem = "+%(accountname)s/%(foldername)s"
sep = " "
footer = "\n"
```

#### pythonfile (if any)

```
REMOVE PRIVATE DATA.
```

#### Logs, error

```
Jul 15 13:06:13 localhost.localdomain offlineimap[5990]: Folder inbox [remote name INBOX] [acc: Gmail]:
Jul 15 13:06:13 localhost.localdomain offlineimap[5990]:  Syncing INBOX: Gmail -> Maildir
Folder inbox [remote name INBOX] [acc: Gmail]:
Jul 15 13:06:16 localhost.localdomain offlineimap[5990]:  Deleting 3140 messages (1:9,11:13,15,17,19:21,23,31:38,40:4
Jul 15 13:06:16 localhost.localdomain offlineimap[5990]: 550,2553:2564,2568:2581,2586:2616,2619:2626,2628:2637,2639:2
```

#### Steps to reproduce the error

- synced first time with `offlineimap` -> downloaded all inbox folder
- then i wanted to purge the `~/Mail` dir so i did `rm -rf ~/Mail`
- run `offlineimap` again
- all inbox deleted

**Comment by runcom** [comment]
I probably understand that offlineimap was syncing the local folder with the remote and due to local folder empty -> that led to removing all remote email but that seems to harsh. Can't there be a confirmation somehow? Also, How do i achieve the same w/o deleting all remote mail? meaning, how do i purge my local mailboxes and the next fetch won't delete all my remote emails

**Comment by nicolas33** [comment]
See https://github.com/OfflineIMAP/offlineimap/issues/333#issuecomment-227907749.

**Comment by nicolas33** [comment]
> Also, How do i achieve the same w/o deleting all remote mail? meaning, how do i purge my local mailboxes and the next fetch won't delete all my remote emails

You might be looking for the `sync_deletes` option which is included in the upcoming v7.0.0.

**Comment by nicolas33** [comment]
Also, don't forget that offlineimap is a syncer. It is aimed at propagating changes. Originally, all the changes. Both above features are recent.

**Comment by runcom** [comment]
So I was just unlucky enough to have an older version....... Great ha

**Comment by nicolas33** [comment]
v7.0.0 is still not out!

**Comment by runcom** [comment]
@nicolas33 any eta on v7.0.0 GA?

**Comment by nicolas33** [comment]
We don't have ETA. However, I can say we are late in the release cycle so the current `next` branch is almost ready for the stable. I expect very few changes before it's marked stable. I run the the tip of `next` in a daily basis for all my accounts. Actually, I think it's more reliable than v6.7.0.

**Comment by runcom** [comment]
Right, I'm now running rc5 from source
