### ISSUE TITLE
[v7.0.0] Parsing the accounts lists now care about spaces

### ISSUE THREAD

**Issue by pierremoreau** [OfflineIMAP/offlineimap#355]
#### General informations

- offlineimap version (`offlineimap -V`): 7.0.0
- Python version: 2.7.12 

#### Configuration file offlineimaprc

Working configuration with <7.0.0, but failing with 7.0.0
```
[general]
accounts = account1, account2, account3, account4, account5
#[snip]
```

Working configuration with 7.0.0
```
[general]
accounts = account1,account2,account3,account4,a\ccount5
#[snip]
```

#### Logs, error

```
ERROR: The account ' account2' does not exist
ERROR: The account ' account3' does not exist
ERROR: The account ' account4' does not exist
ERROR: The account ' account5' does not exist
ERROR: Exceptions occurred during the run!
ERROR: The account ' account2' does not exist
ERROR: The account ' account3' does not exist
ERROR: The account ' account4' does not exist
ERROR: The account ' account5' does not exist
Valid accounts are: account1, account2, account3, account4, account5
```

#### Steps to reproduce the error

1. Take an existing working configuration file with multiple accounts set up;
2. Introduce spaces after the comma separating each account defined in `accounts`;
3. Start `offlienimap`.

**Comment by nicolas33** [comment]
This should be fixed in the current `next` branch (see above).
Thanks for the report!

**Comment by pierremoreau** [comment]
Thank you for the quick fix!
