### ISSUE TITLE
oauth2_refresh_token is ignored

### ISSUE THREAD

**Issue by ferki** [OfflineIMAP/offlineimap#362]
#### General informations

- offlineimap version (`offlineimap -V`): `offlineimap v7.0.2, imaplib2 v2.55 (bundled)`
- Python version: `2.7.10` and `3.4.3`
- server name or domain: `imap.gmail.com`
- CLI options: `-d imap`

#### Configuration file offlineimaprc

```
[Repository remote]
type = Gmail
remoteuser = user
auth_mechanisms = XOAUTH2
oauth2_client_id = id
oauth2_client_secret = secret
oauth2_refresh_token = token
```

Let me know if you need the whole file, but I believe that snippet is enough to reproduce.

#### Logs, error

```
 [imap]: Attempting XOAUTH2 authentication
 [imap]: xoauth2handler: access_token "<function <lambda> at 0x7f64aab7c938>"
 [imap]: xoauth2handler: returning "user=userauth=Bearer <function <lambda> at 0x7f64aab7c938>"
 [imap]: xoauth2handler: access_token "<function <lambda> at 0x7f64aab7c938>"
 [imap]: xoauth2handler: returning "user=userauth=Bearer <function <lambda> at 0x7f64aab7c938>"
 XOAUTH2 authentication failed: [AUTHENTICATIONFAILED] Invalid credentials (Failure)
```

Looks like the generation of a new access token is skipped because the default value of `oauth2_access_token` is not `None`, but `<function <lambda> at 0x7f64aab7c938>`, leading to authentication failure, and thus an aborted sync.

#### Steps to reproduce the error

- configure `oauth2_refresh_token` according to sample config
- try to sync
- if I completely override `oauth2_access_token` [here](https://github.com/OfflineIMAP/offlineimap/blob/65295b01efc2a4c1e5152aaf74a2044b0a2b22fb/offlineimap/imapserver.py#L233) with `self.oauth2_access_token = None` then it works

**Comment by nicolas33** [comment]
Should be fixed with above patch. Please, let me know if this works.

**Comment by ferki** [comment]
It did solve my case, thank you :+1:

**Comment by nicolas33** [comment]
Thank you much for the report and feedback. Applied.
