### ISSUE TITLE
abort: command: FETCH => socket error: <type 'exceptions.IOError'> - Too many read 0

### ISSUE THREAD

**Issue by seanfarley** [OfflineIMAP/offlineimap#368]
This seemed a bit different from #292 because that issue happened to be on a specific message and mine seems to be fetching uids.

#### General informations

- system/distribution (with version): Macports OS X 10.11
- offlineimap version (`offlineimap -V`): 7.0.4
- Python version: 2.7.12
- server name or domain: mail.farley.io
- CLI options: -d imap

#### Configuration file offlineimaprc

```ini
[general]
accounts = main
pythonfile = ~/.offlineimap.py

[Account main]
localrepository = main-local
remoterepository = main-remote
status_backend = sqlite

presynchook  = ~/.config/maildir-notmuch-sync.sh pre ~/.mail
postsynchook = ~/.config/maildir-notmuch-sync.sh post ~/.mail

[Repository main-local]
type = Maildir
localfolders = ~/.mail
nametrans = lambda folder: folder if folder != 'inbox' else 'INBOX'

[Repository main-remote]
# maxconnections = 3
type = IMAP
ssl = true
remotehost = mail.farley.io
remoteuser = sean@farley.io
remotepasseval = get_keychain_pass(account="sean@farley.io", server="mail.farley.io")
cert_fingerprint = 48f8b45422dbb711fbd158c74e6e4aecc68e3b0b
nametrans = lambda folder: folder.lower()
# folderfilter = lambda foldername: foldername not in ['archive']
```

#### pythonfile (if any)

```python
import commands
def get_keychain_pass(account=None, server=None):
    params = {
        'security': '/usr/bin/security',
        'command': 'find-internet-password',
        'account': account,
        'server': server
    }

    command = ("%(security)s %(command)s -w -a %(account)s "
               "-s %(server)s") % params
    return commands.getoutput(command)
```

#### Logs, error

[offlineimap-debug.txt](https://github.com/OfflineIMAP/offlineimap/files/398306/offlineimap-debug.txt)

#### Steps to reproduce the error

- I can reproduce this every time.
- Let me know if I can help with debugging (it's my own mail server so I can inspect that, too)

**Comment by nicolas33** [comment]
Run offlineimap from current `next` branch. I've added one line of debug message (-d imap'). You'll see the FETCH comand issued to the server.

Next, try this command in a manual IMAP session to check you get a valid response for this folder.

**Comment by seanfarley** [comment]
Aha, thanks! It turns out dovecot was running out of memory. A few tweaked settings in dovecot and this issue was resolved!

**Comment by nicolas33** [comment]
Ok. Thank you for the feedback.
