### ISSUE TITLE
Add support for creating virtual mailboxes with mbnames

### ISSUE THREAD

**Issue by darnir** [OfflineIMAP/offlineimap#375]
#### General informations
- system/distribution (with version):  Arch Linux
- offlineimap version (`offlineimap -V`):  offlineimap v7.0.5, imaplib2 v2.55 (bundled)
- Python version: Python 2.7.12
- server name or domain: 
- CLI options: 
#### Configuration file offlineimaprc

```
[mbnames]

enabled = yes
filename = ~/.mutt/mailboxes
header = "mailboxes "
peritem = "+%(accountname)s/%(foldername)s"
sep = " "
footer = "\n"
```

Could you please add some support to create fake mailboxes for each "accountname" as well? Currently, the above configuration will create a mailbox entry for each "accountname/foldername", but I'd like to create a mailbox entry for each "$accountname" as well. The reason to do this is so Mutt reads it as a mailbox and will automatically nest all the folders underneath it. This makes life very simple when using mutt + offlineimap to synchronize multiple IMAP mailboxes.

EDIT:
To be clear, the above configuration may create a `~/.mutt/mailbxes` file that looks like this:

```
mailboxes "+mlist/foo" "+mlist/bar" "+account2/abc" "+account2/def"
```

Whereas, I am looking for a way to have the following file created:

```
mailboxes "+mlist/" "+mlist/foo" "+mlist/bar" "+account2/" "+account2/abc" "+account2/def"
```

**Comment by nicolas33** [comment]
Can't the  `header` configuration option do what you need?

`header = 'mailboxes "+mlist/" "+account2/"'`

**Comment by darnir** [comment]
That would work. Though the following configuration:
 
```
header = "mailboxes +%(accountname)s"
peritem = "+%(accountname)s/%(foldername)s"
```

Causes the error: 

```
ERROR: Bad value substitution:
        section: [mbnames]
        option : header
        key    : accountname
        rawval : "
```

I really would prefer if I could use the account names automatically without having to mention them explicitly.

**Comment by nicolas33** [comment]
I've looked at the code. I'm not sure the feature worth the added code complexity and adding/removing accounts already requires configuration file edition.

IOW, I won't implement this myself but I'm fine with patches.

**Comment by nicolas33** [comment]
> Can't the header configuration option do what you need?

I don't know why I've talked about the header.

Actually, it should already be possible to do what you want with the peritem:
```
peritem = "+%(accountname)/ +%(accountname)s/%(foldername)s"
```
