### ISSUE TITLE
accountname variable for remotehost and remoteuser?

### ISSUE THREAD

**Issue by darkpixel** [OfflineIMAP/offlineimap#386]
I have about 50 mailboxes I need to suck out of a dying Exchange server.

I loathe having to create multiple accounts, along with multiple repositories (local and remote) for each user.

I tried:
```
[Repository remote]
type = IMAP
remotehost = "%(accountname)s"
remoteuser = "mydomain/mailcopyuser/%(accountname)s"
```

(The format for logging into another user's mailbox under MS Exchange is domain/user-with-access/target-mailbox).

imapsync blows up with the error:
```
InterpolationMissingOptionError: Bad value substitution:
	section: [Repository remote]
	option : remotehost
	key    : account
	rawval : "%(accountname)s"
```

Am I missing something, or is this unsupported?

**Comment by nicolas33** [comment]
> I loathe having to create multiple accounts, along with multiple repositories (local and remote) for each user.

I'd go with a script building the final configuration from a list of users and a configuration extract template.

> InterpolationMissingOptionError: Bad value substitution

How did you define accountname? What do you have in the DEFAULT section?

I wonder you're misinterpreting the interpolation feature of configparser: https://docs.python.org/2/library/configparser.html

**Comment by darkpixel** [comment]
Snipped .offlineimaprc:
```
[general]
accounts = user1, user2, user3, user4
ui = blinkenlights
maxsyncaccounts=5
maxconnections=5

[Account user1]
localrepository = local
remoterepository = remote

[Repository local]
type = Maildir
localfolders = "/tank/mailstore/%(accountname)s"

[Repository remote]
type = IMAP
remotehost = "%(accountname)s"
remoteuser = "mydomain/mailcopyuser/%(accountname)s"
```

The docs on the variables is a bit sparse.  I'm sure I have something messed up...

**Comment by nicolas33** [comment]
accountname in %(accountname)s is never defined.

```
[DEFAULT]
to_expand = default_value

[section]
this_option = %(to_expand)s
```

Here, the value of *this_option* is *default_value*. That's what interpolation is about.

**Comment by darkpixel** [comment]
Aah.  So I could do something like:
```
[general]
accounts = user1, user2, user3, user4
ui = blinkenlights
maxsyncaccounts=5
maxconnections=5

[Account user1]
localrepository = local
remoterepository = remote
the_user = user1

[Repository local]
type = Maildir
localfolders = "/tank/mailstore/%(the_user)s"

[Repository remote]
type = IMAP
remotehost = "%(accountname)s"
remoteuser = "mydomain/mailcopyuser/%(the_user)s"
```

Or am I still missing it?

**Comment by nicolas33** [comment]
> Or am I still missing it?

You're still missing to define the "the_user" variable:

```
[DEFAULT]
the_user = user1
```

I guess this feature does not work as you expect.

**Comment by nicolas33** [comment]
Sorry, I've missed the definition in the Account section. AFAICT, the variable must be defined in all the sections it is used if not defined in the DEFAULT section:

```
[Repository local]
the_user = user1
type = Maildir
localfolders = "/tank/mailstore/%(the_user)s"

[Repository remote]
the_user = user1
type = IMAP
remotehost = "%(the_user)s"
remoteuser = "mydomain/mailcopyuser/%(the_user)s"
```

Hence, I believe this won't help to achieve what you want.

**Comment by nicolas33** [comment]
The other way of handling this is to write a skeleton like

```
[Account USERNAME]
localrepository = local_USERNAME
remoterepository = remote_USERNAME

[Repository local_USERNAME]
type = Maildir
localfolders = "/tank/mailstore/USERNAME"

[Repository remote_USERNAME]
type = IMAP
remotehost = "USERHOST"
remoteuser = "mydomain/mailcopyuser/USERNAME"
```

Then, generate the final configuration file from this skeleton. A script shell with something like 
```
cat path/to/skeleton | sed -e "s,USERNAME,$username,g" | sed -e "s,USERHOST,$userhost,g"
```
can do the job. The $username and $userhost variables would be filled by reading a line oriented file like:

```
user1 userhost1
user2 userhost2
```

**Comment by darkpixel** [comment]
I ended up doing something similar with a template file that would get appended to the configuration.

Thanks for the pointers.
