### ISSUE TITLE
Ask for all account passwords prior to syncing.

### ISSUE THREAD

**Issue by vext01** [OfflineIMAP/offlineimap#39]
If you have several accounts set up, you have to wait for the first account to sync before typing the password for the second account.

It would be better if offlineimap asked for all passwords in one batch.

**Comment by nicolas33** [comment]
I'm "rejecting" this request. Not that it's not valid but that OfflineIMAP already supports a *lot of ways* to configure passwords without having to care about them anymore.

My point is that the required code to support this requested feature does not worth the trouble.

So, I'm closing unless any other maintainer (@konvpalto, @xnox , @spaetz or @X-Ryl669) do want to work on this and convince the others I'm wrong.

**Comment by nicolas33** [comment]
Thank you much for the suggestion, BTW.

**Comment by konvpalto** [comment]
And what was the suggestion that made you to reopen this?

**Comment by nicolas33** [comment]
Nothing. Clicked the wrong icon, sorry.
Thank you!
