### ISSUE TITLE
improve speed of the SQLite cache (incredibly slow)

### ISSUE THREAD

**Issue by muggenhor** [OfflineIMAP/offlineimap#390]
#### General informations
- system/distribution (with version):
  
  ```
  Distributor ID: Debian
  Description:    Debian GNU/Linux testing (stretch)
  Release:        testing
  Codename:       stretch
  ```
- offlineimap version (`offlineimap -V`): 7.0.8+dfsg1-1: offlineimap v7.0.8, imaplib2 v2.55 (system)
- Python version: v2.7.12+
- server name or domain: private dovecot mail server
- CLI options: `offlineimap -u ttyui -o`
#### Steps to reproduce the error
- Have a previously synced account (IMAP to Maildir) with version 6.7.0.1+dfsg1-1
- Upgrade to 7.0.8+dfsg1-1

After some toying around I discovered the problem to be that while migrating from the text-based status files to the SQLite based ones it executes this statement, about once per second:

``` sql
INSERT INTO status (id,flags,mtime,labels) VALUES (?,?,?,?)
```

The reason it takes about a second per statement seems to be that A) it doesn't use the `executemany` option but addresses every mail separately, and B) after every single `execute(INSERT...)` it calls connection.commit(). Which forces a full transaction commit to be done, written and _flushed_ to disk (`fdatasync` shows up a lot on an strace). Just wrapping the loop over `copylist` in `BaseFolder.__syncmessagesto_copy` inside `with statusfolder.connection:` (to commit upon leaving the block without exception) and changing `LocalStatusSQLiteFolder.__sql_write` to no longer call `self.connection.commit()` causes a more than 100x speedup.

With that change it took seconds per folder instead of half an hour per folder (for the big ones). I reverted that change after the conversion, because it's important that .commit() gets called on all paths that write to the database, and I'm not familiar enough with the source to be sure that I've covered all those with my changes. That being said, for a one-time conversion this change is essential, because I've got about 100k mails, and I don't like waiting 100k seconds=1.16 days if no timeouts occur (apparently dovecot likes closing connections without data passing through them for more than several minutes). The timeout thing required me to manually SIGINT offlineimap and restart a few times (it noticed that the connection dropped, but still kept waiting, possibly on one of the parallel threads).

For reference a patch (with white-space differences eliminated for Base.py because it's just indenting the for loop underneath to make it the with block):

``` diff
--- /usr/share/offlineimap/offlineimap/folder/Base.py.orig      2016-10-08 10:10:56.000000000 +0200
+++ /usr/share/offlineimap/offlineimap/folder/Base.py   2016-10-24 22:48:07.569843397 +0200
@@ -891,6 +891,7 @@
             )
             return

+        with statusfolder.connection:
         for num, uid in enumerate(copylist):
             # Bail out on CTRL-C or SIGTERM.
             if offlineimap.accounts.Account.abort_NOW_signal.is_set():
--- /usr/share/offlineimap/offlineimap/folder/LocalStatusSQLite.py.orig 2016-10-08 10:10:56.000000000 +0200
+++ /usr/share/offlineimap/offlineimap/folder/LocalStatusSQLite.py      2016-10-24 22:49:59.270357859 +0200
@@ -169,7 +169,6 @@
                         else:
                             self.connection.execute(sql, args)
                     success = True
-                    self.connection.commit()
             except sqlite.OperationalError as e:
                 if e.args[0] == 'cannot commit - no transaction is active':
                     pass
@@ -183,6 +182,7 @@
         """Upgrade the sqlite format from version 'from_ver' to current"""

         if self.connection is not None:
+            self.connection.commit()
             self.connection.close() # Close old connections first.
         self.connection = sqlite.connect(self.filename,
                                          check_same_thread=False)
@@ -256,6 +256,7 @@
             self._databaseFileLock.removeOneUser()
             if self._databaseFileLock.shouldClose():
                 try:
+                    self.connection.commit()
                     self.connection.close()
                 except:
                     pass
```

**Comment by muggenhor** [comment]
PS This is maybe related to #319, as at least the disc writing thing is an issue that I saw as well. It's not related to the cache though, it's caused by not using the cache (by committing earlier than necessary the write-cache is being flushed constantly).

**Comment by nicolas33** [comment]
> The reason it takes about a second per statement seems to be that A) it doesn't use the executemany option but addresses every mail separately, and B) after every single execute(INSERT...) it calls connection.commit(). Which forces a full transaction commit to be done, written and flushed to disk (fdatasync shows up a lot on an strace). Just wrapping the loop over copylist in BaseFolder.__syncmessagesto_copy inside with statusfolder.connection: (to commit upon leaving the block without exception) and changing LocalStatusSQLiteFolder.__sql_write to no longer call self.connection.commit() causes a more than 100x speedup.

This is interesting. I think we could well have no commint done to each SQL INSERT/statement. We already have the fsync configuration option and it would make sense for the SQLite cache to honor it.
Would you agree to update your patch and PR, please?

**Comment by nicolas33** [comment]
Notice that cache conversion is not the only use case. This applies every time there are lot of changes (e.g.: long time since previous run). I've seen people talk about this lately: https://twitter.com/jaycee/status/790548908824932356.

**Comment by nicolas33** [comment]
> PS This is maybe related to #319, as at least the disc writing thing is an issue that I saw as well. It's not related to the cache though, it's caused by not using the cache (by committing earlier than necessary the write-cache is being flushed constantly).

Above is not clear enough. I guess the cache you're talking about is the disk cache. However, when we talk about the cache we always talk about the sqlite (or legacy text) cache of offlineimap representing the remote. The SQLite database *is* the cache in offlineimap terminology.

**Comment by muggenhor** [comment]
>> PS This is maybe related to #319, as at least the disc writing thing is an issue that I saw as well. It's not related to the cache though, it's caused by not using the cache (by committing earlier than necessary the write-cache is being flushed constantly).
> 
> Above is not clear enough. I guess the cache you're talking about is the disk cache. However, when we talk about the cache we always talk about the sqlite (or legacy text) cache of offlineimap representing the remote. The SQLite database is the cache in offlineimap terminology.

No, I was talking about this remark from #319:
> Running strace on the process reveals, that this might be related to the sqlite cache:

And interpreted that to mean "the cache of SQLite" instead of "the cache stored in SQLite". But I suppose that was the wrong interpretation (it was pretty late for me). My point was that the cache of SQLite itself was likely not to blame.

As for my patch, it's a hack that does a pretty large layering violation (accessing internals of the derived storage class from the base storage class).

In order to implement this properly I think the storage class' API needs the addition of a start/stop transaction pair of methods. I'd personally go with `__enter__`/`__exit__` for ease of use. In addition to that we need to be sure that interruptions in the middle, when they cause a transaction rollback on `statusfolder`, don't cause data-consistency problems (SIGINT isn't a problem in most cases because it's not dealt with by throwing an exception). I don't know anything about how offlineimap handles it when the statusfolder misses data for mails that have been synced. If it handles that gracefully already then I think my hack can be safely refactored to something more suitable.

PS I see what you mean with the slowdown with lots of changes. Syncing the IMAP folder I'm receiving the LKML in is taking a long time.

**Comment by nicolas33** [comment]
> My point was that the cache of SQLite itself was likely not to blame.

I think SQLite is to blame. The commits blocks the program until the data is declared by the disk as written to the disk.

> As for my patch, it's a hack that does a pretty large layering violation (accessing internals of the derived storage class from the base storage class).

> In order to implement this properly I think the storage class' API needs the addition of a start/stop transaction pair of methods. I'd personally go with __enter__/__exit__ for ease of use. In addition to that we need to be sure that interruptions in the middle, when they cause a transaction rollback on statusfolder, don't cause data-consistency problems (SIGINT isn't a problem in most cases because it's not dealt with by throwing an exception).

I agree the patch needs improvements. The __enter__/__exit__ change sounds nice. This would leave the issue to unexpected halts like SIGKILL, power loss, etc. I think this would be good enough for people wanting speed.

> I don't know anything about how offlineimap handles it when the statusfolder misses data for mails that have been synced. If it handles that gracefully already then I think my hack can be safely refactored to something more suitable.

If valid data is not written to the cache, offlineimap will re-do unecessary operations on next run. This could lead to duplicates, but no data loss.

**Comment by nicolas33** [comment]
>> My point was that the cache of SQLite itself was likely not to blame.

> I think SQLite is to blame. The commits blocks the program until the data is declared by the disk as written to the disk.

Oh, I think I get what you mean, here. I agree that whatever the backend format, the same issues would be there.

**Comment by muggenhor** [comment]
>>> My point was that the cache of SQLite itself was likely not to blame.
>> 
>> I think SQLite is to blame. The commits blocks the program until the data is declared by the disk as written to the disk.
> 
> Oh, I think I get what you mean, here. I agree that whatever the backend format, the same issues would be there.

Right, it's just that we're not using SQLite in a way that it actually can be performant: we're asking it do be really safe with its data, which just happens to have a price.

**Comment by nicolas33** [comment]
Patch improved and applied. Thanks!

**Comment by ff2000** [comment]
Finally 7.0.9 hit Gentoo. Did a full (non maxage) sync after the update after setting general.fsync to False. Had to wait hours for it to finish with nearly unusable Laptop because of permanent disk I/O. Another sync with maxage=10days followed by full sync and again disk I/O for hours. As of fsync was set to False I did not want to interrupt it :/
So for my use case the patch didn't improve performance.

**Comment by nicolas33** [comment]
@ff2000 If you want to change maxage, please see #384.

fsync set to "no" allows to not commit at each new UID but once the whole list is written. I don't think this applies to updating the flags so there might be ways to optimization.

**Comment by hmh** [comment]
The initial conversion on 7.0.12 (Debian Stable) is indeed extremely slow, to the point of being unusable.

There is a workaround, though, in the name of usability for at least this initial conversion: install the eatmydata package, and run "eatmydata offlineimap <offlineimap options>".  This uses a LD_PRELOAD trick to make fsync() and friends just return without doing anything.

offlineimap really should have at least an one-off strategy when initially converting from text->sqlite where it *before doing anything* just creates the entire sqllite database as a single transaction.  Only after that was done, it should attempt to use the database in whatever "safe" mode it wants...

**Comment by nicolas33** [comment]
I didn't know the "eatmydata" trick; thanks. I'll add this to the online documentation.

I agree that offlineimap should handle the backend migration better. I'm not sure this is worth the changes in the code, especially because users can workaround the limitations with eatmydata.

**Comment by chris001** [comment]
Is it possible for `offlineimap` itself to load `eatmydata` so that the workaround is automatic with no user effort required.

**Comment by nicolas33** [comment]
Yes but I think it's easy enough to write a small wrapper in shell to do this job. ,-)

**Comment by chris001** [comment]
OK, is it possible to write this small wrapper in shell and include it in the package and have it run by default for all of these troublesome slow sqlite operations?  Users will be happy with 100x speed increase!

**Comment by nicolas33** [comment]
Sure, `./contrib` is there for such customization.

**Comment by nicolas33** [comment]
http://www.offlineimap.org/doc/tipsandtricks.html

**Comment by nicolas33** [comment]
I'm closing since I wrote the new documentation page but I still welcome improvements. ,-)

**Comment by chris001** [comment]
OK, new script added to contrib to help users install `eatmydata` from git source on distros which don't have it packaged.
