### ISSUE TITLE
release on pypi

### ISSUE THREAD

**Issue by petri** [OfflineIMAP/offlineimap#4]
I could not find offlineimap on pypi, the python package index. Apparently there is no release here. Please make one.

I am willing to help as well & take the newest release & release it on pypi, if that's ok. Just let me know.

**Comment by tyrion** [comment]
Since this issue is still open, I comment here. Would it be possible to add the latest release of offlineimap to pypy?
Thanks

**Comment by nicolas33** [comment]
Anyone interested in pypi are welcome to contribute. Other than that, if someone can't find the last release consider helping.
The reason behind is that we (the current managers) have so much to do that we can't even review and merge pull requests with fair delays.

I'm closing but don't take it bad. Pypi is a good thing for OfflineIMAP. We have to make choices about where we must put the focus first.

Again, you're welcome if you'd like to make to hands dirty. ,-)
