### ISSUE TITLE
Regression in 2264133: We try to create folders that already exist on the remote

### ISSUE THREAD

**Issue by avar** [OfflineIMAP/offlineimap#405]
(Deleted boilerplate, irrelevant to this report)

Since 2264133 which is currently in the `next` branch and not in the
`master` branch there's a regression where it'll try to create folders
that already exist on the remote if you use the `nametrans` feature.

This happens both with my exchange server & GMail server remote, I'm
using `nametrans` with both. I just happened to test the master branch
for my merged #404.

I don't have a patch but I looked into why it happens, it's a logic
error in @sheeprine's patch where before we'd operate on folder object
names, but now it does e.g.:

    src_list.append(foldername)
    src_hash[foldername.replace(
        src_repo.getsep(), dst_repo.getsep())] = folder

Which means that this:

    print [dst_folder.sync_this, dst_name_t, src_list]
    if dst_folder.sync_this and not dst_name_t in src_list:

Now returns:

    [1, 'Sent Items', ['Calendar', 'Contacts', 'Drafts', 'INBOX', 'Journal', 'Junk', 'Notes', 'Outbox', 'Sent', 'Tasks', 'Trash']]

Wheras before we'd get:

    [1, 'Sent Items', [<offlineimap.folder.IMAP.IMAPFolder object at 0x7fc724b73d50>, <offlineimap.folder.IMAP.IMAPFolder object at 0x7fc724b73f10>, <offlineimap.folder.IMAP.IMAPFolder object at 0x7fc724b8f090>, <offlineimap.folder.IMAP.IMAPFolder object at 0x7fc724b8f0d0>, <offlineimap.folder.IMAP.IMAPFolder object at 0x7fc724b8f110>, <offlineimap.folder.IMAP.IMAPFolder object at 0x7fc724b8f210>, <offlineimap.folder.IMAP.IMAPFolder object at 0x7fc724b8f290>, <offlineimap.folder.IMAP.IMAPFolder object at 0x7fc724b8f310>, <offlineimap.folder.IMAP.IMAPFolder object at 0x7fc724b8f390>, <offlineimap.folder.IMAP.IMAPFolder object at 0x7fc724b8f410>, <offlineimap.folder.IMAP.IMAPFolder object at 0x7fc724b73b90>]]

My python-fu isn't good but presumably that "in" does magic on that
object to resolve the alias.

So it seems this code needs to be fixed to stop flattening folder
names to `folder.getvisiblename()`. It's not clear from me from the
commit message & patch why that's being done, but comparing the
virtual names as before would fix it.

**Comment by nicolas33** [comment]
Having a correct folder structure is more important than having the (not official) UTF-8 support.

So, I'm inclined to revert  2264133 as a last resort before releasing the next version.

**Comment by nicolas33** [comment]
Does it work with above version?

**Comment by avar** [comment]
Yeah that works just tried your branch now, reverting that commit on top of next is also what I tested initially, and that worked.

There's probably some way to have @sheeprine's change here and not break the `nametrans` use-case, if there's a patch for that I'd be happy to test it.

**Comment by nicolas33** [comment]
Could you please check above version?

**Comment by avar** [comment]
The 783ed31 commit dies like the initial commit on next, i.e.:

    Folder '[Gmail]/Spam'[WorkGMailRemote] could not be created. Server responded: ('NO', ['[ALREADYEXISTS] Duplicate folder name [Gmail]/Spam (Failure)'])

And:

    ERROR: Folder 'Sent Items'[WorkRemote] could not be created. Server responded: ('NO', ['Mailbox already exists.'])

For GMail & exchange, respectively.

Applying this patch:
    
    diff --git a/offlineimap/repository/Base.py b/offlineimap/repository/Base.py
    index 8fd6523..cabc5a7 100644
    --- a/offlineimap/repository/Base.py
    +++ b/offlineimap/repository/Base.py
    @@ -213,2 +213,3 @@ class BaseRepository(CustomConfig.ConfigHelperMixin):
     
    +            print [dst_name_t, [src_hash.keys()]]
                 if dst_folder.sync_this and not dst_name_t in src_hash.keys():

Gives:

    ['Sent Items', [['Junk', 'Tasks', 'Drafts', 'Contacts', 'Journal', 'INBOX', 'Outbox', 'Calendar', 'Trash', 'Notes', 'Sent']]]

I.e. the Sent v.s. Sent Items mapping is still missing.

**Comment by nicolas33** [comment]
Could you share your nametrans rules for the Gmail account?

**Comment by avar** [comment]
I've got it here on github for both accounts: https://github.com/avar/dotfiles/blob/master/.offlineimaprc#L32 & https://github.com/avar/dotfiles/blob/master/.offlineimap.py#L15

I.e. just a two-way mapping so [Gmail].Drafts becomes Drafts, exchange Sent Items becomes Sent etc.

**Comment by nicolas33** [comment]
Ok. I've fully rewritten the block. Please, check above version.

**Comment by avar** [comment]
I tested 633bf4d, works for me. It's syncing things correctly now.

**Comment by nicolas33** [comment]
Thank you much.
