### ISSUE TITLE
 list.remove(x): x not in list

### ISSUE THREAD

**Issue by gerroon** [OfflineIMAP/offlineimap#407]
I am getting some errors when trying to sync an account.  I am apsting all the information I have in the message.

I am using Debian Testing, the Imap server is on Debian Wheezy.

offlineimap --version 7.0.9

 [Account ACCOUNT]
  localrepository = LocalACCOUNT
  remoterepository = RemoteACCOUNT

  [Repository LocalACCOUNT]
  type = Maildir
  localfolders = /home/user/Mail/OfflineImap/ACCOUNT

  [Repository RemoteACCOUNT]
  type = IMAP
  remotehost = imapserver
  remoteuser = account@account.com
  remotepasseval = mailpasswd("account")
  cert_fingerprint = xxxxxxxxxxxxxxxxxxxxxxxx

 ERROR: Copying message 166 [acc: ACCOUNT]
  list.remove(x): x not in list
 ERROR: while syncing INBOX.INBOX.Trash [account ACCOUNT]
  list.remove(x): x not in list
 ERROR: ERROR in syncfolder for ACCOUNT folder INBOX.INBOX.Trash: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/accounts.py", line 584, in syncfolder
    remotefolder.syncmessagesto(localfolder, statusfolder)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 1110, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 938, in __syncmessagesto_copy
    self.copymessageto(uid, dstfolder, statusfolder, register=0)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 833, in copymessageto
    message = self.getmessage(uid)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 308, in getmessage
    data = self._fetch_from_imap(str(uid), 2)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 749, in _fetch_from_imap
    self.imapserver.releaseconnection(imapobj)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imapserver.py", line 720, in releaseconnection
    self.assignedconnections.remove(connection)
ValueError: list.remove(x): x not in list

**Comment by nicolas33** [comment]
Is there everything you have in your configuration file?
Is this bug reproducible? Does it always fails while copying UID 166?
Do you get a better/different error message with current `next` branch?

**Comment by gerroon** [comment]
It is weird actually. It sometimes times out for a long time so much so that  Ihave to kill the process. However I can just use my regular email client to get mails from that very same account. So definetely the server is responsive and working except that offlineimap is having issues with it.

For instance sometimes it says  and stays there for a long time

[imap]: Using authentication mechanisms ['GSSAPI', 'XOAUTH2', 'CRAM-MD5', 'PLAIN', 'LOGIN']
 [maildir]: MaildirRepository initialized, sep is '.'
 *** Processing account ACCOUNT
 Establishing connection to mailserver (RemoteAccount)

**Comment by nicolas33** [comment]
Please, share all the sections of your configuration file.

**Comment by nicolas33** [comment]
What's the output of `offlineimap -V`?

**Comment by gerroon** [comment]
offlineimap v7.0.9, imaplib2 v2.55 (bundled), Python v2.7.12+

Sorry I did not have time to get other info yet.

**Comment by nicolas33** [comment]
Please try v7.0.11.

**Comment by gerroon** [comment]
@nicolas33 
Thanks for the update. 

I can confirm that v7.0.12 throws none of those errors anymore. At least my initial testing is positive

**Comment by nicolas33** [comment]
Thank you.
