### ISSUE TITLE
nametrans consistency check is insufficient

### ISSUE THREAD

**Issue by aroig** [OfflineIMAP/offlineimap#408]
Commit 481efa95f687 seems to break gmail labels sync.

Well not break, but on every go it attempts to unnecessarily change local labels on about 8k messages (all recent ones), which is quite slow due to disk IO.

I think it may be a statusfolder issue, and then it might go beyond gmail labels... I mean, what I see is consistent with the following: "offlineimap sees no labels in the statusfolder for the messages downloaded after I updated offlineimap".

 I am still investigating.

**Comment by aroig** [comment]
I think I got it. The statusfolder is indeed generated from scratch, but the problem is a nametrans issue. This commit started making use of the nametrans from local to remote, which previously was not used.

In my config I have a nametrans on the gmail repository (that strips `[Gmail]` in front of the folder's name), but no reverse nametrans on the local repository. However, the consistency check for nametrans only checks that local -> remote -> local stays the same, which it does in my case.

A PR is on its way fixing the nametrans check, and enforcing them to be truly one inverse of the other (both ways). I think this would be the best to avoid weird cases, and infinite loops, etc. However, this is going to break lots of configs, that had a partial nametrans like me, and did not notice because they never create folders.

**Comment by nicolas33** [comment]
Should we close this report or do you aim at implementing the second side nametrans rules?

**Comment by aroig** [comment]
Let's close it for now, since some of what I wrote is wrong. I still do not understand why 481efa9 triggered bad stuff, and we should improve how we deal with the inconsistencies of a missing local nametrans. But right now I can't spend more time on this...
