### ISSUE TITLE
call for official testers

### ISSUE THREAD

**Issue by nicolas33** [OfflineIMAP/offlineimap#412]
Currently, I test the code and release when it works for me and when I think it will work for most users. This is not satisfying.

We miss of official testers to track down regressions while freezing the code before next releases.

You can join by requesting us here or with a mail sent to me or the mailing list.

**You won't be requested randomly or after critical changes unless you clearly declare it's ok for you. I aim at adding a new step in our release cycle: officially freeze the code just before the next release, notify all the official testers and wait a week or so for your feedback.**

Currently, all the users **are** the testers.

**Comment by nicolas33** [comment]
@OfflineIMAP/collaborators @OfflineIMAP/maintainers @OfflineIMAP/offlineimap-contributors 

I'm thinking about adding each official contributor to the testers. This means you'll be notified by email on every releases and when needed before the releases. If you're opposed to this change, please let me know.

I think it makes sense to **force** each official contributor to be in the team of testers.

**Comment by aroig** [comment]
Count me in. I'm sort of doing it, installing next more or less weekly.

**Comment by iliastsi** [comment]
> I think it makes sense to **force** each official contributor to be in the team of testers.

Agreed!

-- 
Ilias

**Comment by darnir** [comment]
I might be able to help. I use the next branch and install it every few days on my Arch Linux system anyways

**Comment by nicolas33** [comment]
Great. I've added you to the list in https://github.com/OfflineIMAP/offlineimap/blob/master/MAINTAINERS.rst. Welcome!

**Comment by nicolas33** [comment]
Hi @chris001,

You're using offlineimap and you're closely following the issues for a long time.  You have very good understanding of the underlying concepts. Hence, I'd like you to join the team of testers. We need advanced users like you in this area. Would you agree?

**Comment by chris001** [comment]
OK @nicolas33  count me in.
* One more thing, I vote that we need to start using Travis-CI, right here in github, it's really great for automating tests, every time you commit something, it runs the code, and we need to add some settings so that the code will use a real mail server and provide real world results.  When a non-zero result is returned by the code, Travis-CI fails the commit, this makes it easier to decide which commits are bad and when the app is not ready for release. 
* Push releases automatically to pypi using the built in github feature.
* Every tester should create, maintain, and share credentials, for at least one free IMAP mail server account, or mail account on their already owned/administered mail server, of a unique type (gmail, yahoo US, yahoo BR, dovecot, cyrus, MS Exchange, MS Office 360, etc...), until all mail server types are covered, for the purposes of the automated (or hopefully not manual) testing.  Ideally only automated once the Travis-CI tests are running.
* Must explore the possibility of upgrading the code to transparently start using a Next-generation sync algorithm.  I have something to contribute towards this.

**Comment by nicolas33** [comment]
> OK @nicolas33 count me in.

Thanks. Will add you in the MAINTAINERS.rst file.

> One more thing, I vote that we need to start using Travis-CI, right here in github, it's really great for automating tests, every time you commit something, it runs the code, and we need to add some settings so that the code will use a real mail server and provide real world results. When a non-zero result is returned by the code, Travis-CI fails the commit, this makes it easier to decide which commits are bad and when the app is not ready for release.

Yes, we could do this.

> Push releases automatically to pypi using the built in github feature.

I'm not aware of this feature.

> Every tester should create, maintain, and share credentials, for at least one free IMAP mail server account, or mail account on their already owned/administered mail server, of a unique type (gmail, yahoo US, yahoo BR, dovecot, cyrus, MS Exchange, MS Office 360, etc...), until all mail server types are covered, for the purposes of the automated (or hopefully not manual) testing. Ideally only automated once the Travis-CI tests are running.

Not sure Travis infra allows out/in going traffic.

> Must explore the possibility of upgrading the code to transparently start using a Next-generation sync algorithm. I have something to contribute towards this.

I'm won't work on offlineimap myself except to maintain it. I'll use my free time for imapfw.
However, I welcome contributions.

**Comment by chris001** [comment]
@nicolas33 
The details for pushing the package release from github to pypi comes in a few variations:
http://5minutes.youkidea.com/howto-deploy-python-package-on-pypi-with-github-and-travis.html
https://docs.travis-ci.com/user/deployment/pypi/
https://www.codementor.io/arpitbhayani/host-your-python-package-using-github-on-pypi-du107t7ku

About Travis-CI infra allowing out/in traffic, this is a good point, and worth looking into.

**Comment by nicolas33** [comment]
> The details for pushing the package release from github to pypi comes in a few variations:

I've discarded this way of publishing the packages because this requires to release the credentials.
Packaging and publishing on pypi is just about one or two command lines for each release. This does not happen every day so it's not an issue. I don't want to spend more time on this.

**Comment by chris001** [comment]
I thought releasing the credentials would be foolish too.  Until I read more and saw how there's a line where they encrypt the credentials.  Anyway.

**Comment by chris001** [comment]
Good news, Travis-CI allows full network traffic, so it can test OfflineIMAP as it connects to many types of IMAP servers, and performs different types of syncs, under various test conditions.

1. First step, we must configure this repo to connect to Travis,
2. I'll configure some test IMAP accounts on an Office 365 developer account.  Dovecot, Cyrus, Yahoo, Gmail, icloud, and other IMAP accounts would be also needed.
3. Write some automated tests for this python app.

https://docs.travis-ci.com/user/ci-environment/
https://docs.travis-ci.com/user/languages/python/

> Networking #
>
> The virtual machines in the Legacy environment running the tests have IPv6 enabled. They do not have any external IPv4 address but are fully able to communicate with any external IPv4 service. The container-based, OSX, and GCE (both Precise and Trusty) builds do not currently have IPv6 connectivity.
>
> The IPv6 stack can have some impact on Java services in particular, where one might need to set the flag java.net.preferIPv4Stack to force the JVM to resort to the IPv4 stack should services show issues of not booting up or not being reachable via the network: -Djava.net.preferIPv4Stack=true.
>
> Most services work normally when talking to the local host by either localhost or 127.0.0.1.

**Comment by nicolas33** [comment]
LGTM.

(1) You might like to see [how it's done for imapfw](https://github.com/OfflineIMAP/imapfw/blob/master/.travis.yml).
(1&2) We'll have to [encrypt the credentials](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml) of the IMAP accounts.

**Comment by chris001** [comment]
Exactly!  I see the `.travis.yml` is running tests, which are referring to `AccountA`, obviously this is an IMAP account for testing purposes, is it using the encrypted environmental variables of Travis for the credentials to connect to the IMAP servers and sync the selected accounts?

**Comment by nicolas33** [comment]
No, it's not using the encrypt feature.

**Comment by chris001** [comment]
* After a long trouble with account verification, I now have credentials for 2 imap accounts (running on microsoft office 365) for use in automated testing of offlineimap code in Travis-CI.
* Could also produce 2 more office365 imap accounts for `travis` automated testing of `imapfw`.
* These credentials need to be added as encrypted environment variables to `.travis.yml` by using the `travis` ruby gem - Nicolas, any suggestion on how to do this?
* As soon as these office365 credentials are added, it should be no problem for volunteers to contribute IMAP test account credentials for `dovecot`, `gmail`, `yahoo`, `aol`, `web,de`, `free.fr`, `zarafa`, `zimbra`, `cyrus`, etc.
* Probably need to devise a scheme of maintaining one variable, an array of all of the the credentials, instead of having a separate environment variable for each and every email provider tested.  There will probably be at least 10 imap providers to test...

**Comment by nicolas33** [comment]
> These credentials need to be added as encrypted environment variables to .travis.yml by using the travis ruby gem - Nicolas, any suggestion on how to do this?

The process is described here: https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables.

**Comment by chris001** [comment]
> Encrypt environment variables with the public key attached to your repository using the `travis` gem:
>
>   If you do not have the travis gem installed, run `gem install travis`.
>
>    In your repository directory, run:
>
>    `travis encrypt MY_SECRET_ENV=super_secret --add env.matrix`
>
>    Commit the changes to your `.travis.yml`.
>
>    Encryption and decryption keys are tied to the repository. If you fork a project and add it to Travis CI, > it will not access to the encrypted variables.

**Comment by chris001** [comment]
I think these encrypted keys will encrypt correctly only when the repo maintainer ( @nicolas33 ) creates them from command line with ruby gem, adds them to the `.travis.yml` and commits the changes to this repo - do you agree?

**Comment by chris001** [comment]
I could transmit you these office365 email credentials by private message @nicolas33 - just tell me which email address or skype ID etc you prefer.

**Comment by chris001** [comment]
I think I could add these encrypted credentials only if I had commit privileges to this repo, As it is now, I only have ability to fork this repo and make PR - so the encryption key would be derived from the name of the forked repo name, and fail to decrypt properly if added to this repo `.travis.yml` here.

**Comment by nicolas33** [comment]
Ok, send me the credential by mail plz.

**Comment by chris001** [comment]
Sent four office365 IMAP accounts.
Automated testing with Travis on every commit = very cool!

**Comment by nicolas33** [comment]
Thanks! Here we are: https://github.com/nicolas33/offlineimap/tree/ns/ci
