### ISSUE TITLE
Error too many values to unpack

### ISSUE THREAD

**Issue by periklis** [OfflineIMAP/offlineimap#423]
#### General informations

- system/distribution (with version): OSX 10.11.6
- offlineimap version (`offlineimap -V`): 7.0.12, imaplib2 v2.55 (bundled)
- Python version: 2.7.13
- server name or domain: 
- CLI options: -c .offlineimaprc

#### Configuration file offlineimaprc

```
[general]
accounts = myaccount
pythonfile = /PATH/TO/offlineimap-helper.py

[Account myaccount]
localrepository = mylocal
remoterepository = myremote
autorefresh = 2
maxage = 2015-01-01

[Repository mylocal]
type = Maildir
localfolders = /PATH/TO/MAILDIR
utime_from_header = yes
filename_use_mail_timestamp = yes

[Repository myremote]
type = IMAP
ssl = yes
cert_fingerprint = MYFINGERPRINT
remotehost = HOSTNAME
remoteuser = USER
remotepasseval = get_keychain_pass(account="ACCOUNTNAME", server="HOSTNAME")
expunge = yes
folderfilter = lambda folder: not re.search('(^Folder1|^Folder2|shared.*)', folder)
```

#### pythonfile (if any)

```
#!/usr/bin/python
import re, subprocess
def get_keychain_pass(account=None, server=None):
    params = {
        'security': '/usr/bin/security',
        'command': 'find-generic-password',
        'account': account,
        'server': server,
        'keychain': '/PATH/TO/KEYCHAIN',
    }
    command = "sudo -u USERNAME %(security)s -v %(command)s -g -a %(account)s -s %(server)s %(keychain)s" % params
    output = subprocess.check_output(command, shell=True, stderr=subprocess.STDOUT)
    outtext = [l for l in output.splitlines()
               if l.startswith('password: ')][0]

    return re.match(r'password: "(.*)"', outtext).group(1)
```

#### Logs, error
```
offlineimap-7.0.12/lib/python2.7/site-packages/offlineimap/repository/IMAP.py", line 467, in getfolders\n    flags, delim, name = imapu
til.imapsplit(s)\n'
```
#### Steps to reproduce the error

- 
-

**Comment by nicolas33** [comment]
What's the remote IMAP server name or domain?

**Comment by periklis** [comment]
mail.mayflower.de

**Comment by periklis** [comment]
@nicolas33 What does the label "need contributor" mean?

**Comment by nicolas33** [comment]
It means I won't work on this myself. Here, it's because this error is not usual. The mail provider seems to provide data in unexpected format (for the current offlineimap, at least).

Hence, the call for others to get involved.

You might add some debug print() statement before the failing line so we can understand wha'ts happening exactly.

**Comment by periklis** [comment]
@nicolas33 ok, i'll try that to add some debug print statements at imap.py:467.

**Comment by periklis** [comment]
@nicolas33 After putting a debug statement with `logging` right before [IMAP.py#L461](/OfflineIMAP/offlineimap/blob/master/offlineimap/repository/IMAP.py#L461) for `listresult` i got the following output:
`2017-01-22 15:19:30,753 - DEBUG - ['[SERVERBUG] Internal error occurred. Refer to server log for more information. [2017-01-22 15:19:30]']`

It think this error has to do with the dovecot instance on the server side. Right?

**Comment by nicolas33** [comment]
> It think this error has to do with the dovecot instance on the server side. Right?

Right. We should not fail for this kind of response, though.

Could you share your debug statement?

**Comment by nicolas33** [comment]
Add a log statement for variable s if not already done, please. I think we fail checking the response here.

**Comment by nicolas33** [comment]
Sorry, I meant the listresult variable instead of s.

**Comment by nicolas33** [comment]
I wrote a patch where we check the response. Please, test above patch so I can merge for the next release.

However, this won't solve the issue on the Dovecot side.

**Comment by periklis** [comment]
I've discussed this issue with my administrators at our company. They observed broken ACLs on the server folder and they fixed them. Hence, the error evaporated. However, i attach my logging patch:
```
diff --git a/offlineimap/repository/IMAP.py b/offlineimap/repository/IMAP.py
index 23a397b..af90a64 100644
--- a/offlineimap/repository/IMAP.py
+++ b/offlineimap/repository/IMAP.py
@@ -20,6 +20,7 @@ import os
 import netrc
 import errno
 import codecs
+import logging
 from sys import exc_info
 from threading import Event
 
@@ -446,6 +447,8 @@ class IMAPRepository(BaseRepository):
     def getfolders(self):
         """Return a list of instances of OfflineIMAP representative folder."""
 
+        logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')
+
         if self.folders is not None:
             return self.folders
         retval = []
@@ -458,7 +461,10 @@ class IMAPRepository(BaseRepository):
             listresult = listfunction(directory=self.imapserver.reference)[1]
         finally:
             self.imapserver.releaseconnection(imapobj)
+
+        logging.debug(listresult)
         for s in listresult:
+
             if s == None or \
                    (isinstance(s, str) and s == ''):
                 # Bug in imaplib: empty strings in results from
```
Imho, you are right a check of listresult's content should be included, if the routine expects a specific data structure, while the imap server is able to put message in it. However, i am not an experienced pythoneer to propose any fix by the standards of this project.

**Comment by periklis** [comment]
Patch works fine for me, as i wrote above broken acl on the server side was the issue.

**Comment by nicolas33** [comment]
Ok. Thank you for the report. I'll merge the patch since this doesn't hurt (tested here, too).
