### ISSUE TITLE
Avoid redundant storage using hard links?

### ISSUE THREAD

**Issue by fnurl** [OfflineIMAP/offlineimap#424]
Would it be possible to have offlineimap identify when a identical email already has been downloaded and rather than creating a new file for it, make a hard link between the two?

This would be really nice for using folders as labels in a gmail setup.

**Comment by nicolas33** [comment]
Not sure what you mean by "identical". Offlineimap should delete each UID once. Since offlineimap way of working is based on UID, there should already be no identical mail (UIDs are differents).

**Comment by chris001** [comment]
@fnurl   Can you paste here a couple of the emails, with labels as folders, which were downloaded more than once from gmail ?
