### ISSUE TITLE
MD5 error with python3

### ISSUE THREAD

**Issue by crisidev** [OfflineIMAP/offlineimap#436]
#### General informations

- system/distribution (with version): OSX 10.12.3
- offlineimap version (`offlineimap -V`): offlineimap v7.0.13, imaplib2 v2.55 (bundled), Python v3.6.0
- Python version: 3.6.0 

#### Configuration file offlineimaprc

```
[general]
accounts = Test

[Account Test]
localrepository = Local
remoterepository = Remote

[Repository Local]
type = Maildir
localfolders = ~/Mail

[Repository Remote]
type = IMAP
remotehost = server.domain.com
remoteport = 1993
remoteuser = DOMAIN\\username
remotepass = xxxxxxxxx
auth_mechanisms = CRAM-MD5, LOGIN, XOAUTH2, PLAIN
sslcacertfile = /path/to/certfile.pem
ssl = yes
folderfilter = lambda foldername: re.search('INBOX', foldername)
```

#### Logs, error

```
OfflineIMAP 7.0.13
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync Test:
 *** Processing account Test
 Establishing connection to server.domain.com:1993 (Remote)
<class 'str'>
 ERROR: While attempting to sync account 'Test'
  Unicode-objects must be encoded before hashing
 *** Finished account 'Test' in 0:05
ERROR: Exceptions occurred during the run!
ERROR: While attempting to sync account 'Test'
  Unicode-objects must be encoded before hashing

Traceback:
  File "/Users/xxxxxx/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/site-packages/offlineimap/accounts.py", line 278, in syncrunner
    self.__sync()
  File "/Users/xxxxxx/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/site-packages/offlineimap/accounts.py", line 342, in __sync
    localrepos.getfolders()
  File "/Users/xxxxxx/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/site-packages/offlineimap/repository/Maildir.py", line 209, in getfolders
    self.folders = self._getfolders_scandir(self.root)
  File "/Users/xxxxxx/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/site-packages/offlineimap/repository/Maildir.py", line 197, in _getfolders_scandir
    self.getsep(), self)
  File "/Users/xxxxxx/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/site-packages/offlineimap/folder/Maildir.py", line 78, in __init__
    self._foldermd5 = md5(self.getvisiblename()).hexdigest()
```

**Comment by crisidev** [comment]
The problem is easy to fix. MD5 with python3 need an unicode object and we are passing a string.

Patching line 77 of offlineimap/folder/Maildir.py fixes the problem.
```self._foldermd5 = md5(self.getvisiblename().encode('utf-8')).hexdigest()```

I am not sure how to integrate this, since it is a python3 problem and maintain compatibility with python2.

**Comment by nicolas33** [comment]
Actually, py3 support is very hard due to py2 encoded string assumptions everywhere in the code. I wonder we should deprecate py3.

**Comment by nicolas33** [comment]
* https://twitter.com/OfflineIMAP/status/830575382453698562
* https://www.reddit.com/r/Python/comments/5qnvjl/why_is_python3_adoption_slow_even_though_there/

**Comment by chris001** [comment]
Supporting both python2.7 and 3 can be a dilemma.  Here's a guide which steps through the process of modifying python 2.7 code work on both python 2.7 and 3.x.  They say it's no problem.
https://docs.python.org/3/howto/pyporting.html
Spoiler alert: use `mypy` to annotate the types statically, and when that's complete, to port presumably with the command `2to3`.
This process relieves the uncertainty of the runtime dynamic typing with the unicode strings etc.  More likely than not, most of this type annotation of strings takes place inside `imaplib2` during its conversations with the imap4rev1 server, and the Maildir in the filesystem.

**Comment by nicolas33** [comment]
While this is technically possible to go to py3, I doubt this worth the efforts over restarting something new.

**Comment by crisidev** [comment]
I was actually making a mess by myself. I am on OSX and brew installs offlineimap specifying a python2 PYTHONPATH and I was running the script with python3. 

Once I went back to py2, everything works fine.

I agree with @nicolas33, having broken py3 support is worst than not having it at all.

**Comment by chris001** [comment]
We should add "warning this code fails to run correctly on python 3, try running it from python2" and exit.

Yet the fact remains, they say it is quite easy to get python2 code working on both python2 and python3.

The sync algorithm needs improvement, which is a separate matter.

**Comment by nicolas33** [comment]
Thanks for the feedback.
