### ISSUE TITLE
Problems with yahoo.com.br (different language for folders) mail

### ISSUE THREAD

**Issue by braselectron** [OfflineIMAP/offlineimap#437]
#### General informations

- system/distribution (with version): Ubuntu 14.04.5 - 32bits Kernel 3.13.0-108-generic 155-Ubuntu SMP
- offlineimap version (`offlineimap -V`): 7.0.13
- Python version: 2.7.6
- server name or domain: yahoo mail (yahoo.com and yahoo.com.br)
- CLI options:  ./offlineimap.py --dry-run --info

#### Configuration file offlineimaprc

```
[general]

#GENERAL_ACCOUNTS_NAME
accounts = *******@yahoo.com.br 

#ACCOUNT_NAME
[Account *******@yahoo.com.br]

localrepository = Local
remoterepository = Remote

[Repository Local]
type = Maildir
localfolders = ~/Documents/bkup/Yahoo
createfolders = True

[Repository Remote]
type = IMAP
keepalive = 100
holdconnectionopen = yes
#
# remove XOAUTH2 because of bug message
auth_mechanisms = GSSAPI, CRAM-MD5, PLAIN, LOGIN
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
# cert_fingerprint = 
ssl = yes
createfolders = False
remotehost = imap.mail.yahoo.com
remoteuser = *************
remotepass = *************
remoteport = 993
maxconnections = 1
realdelete = no
#folderfilter = lambda foldername: False
#
folderfilter = lambda folder: folder in ['Inbox', 'Sent']
```

#### pythonfile (if any)

no

#### Logs, error

```
OfflineIMAP 7.0.13
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
  imaplib2: 2.55 (bundled)
Remote repository 'Remote': type 'IMAP'
Host: imap.mail.yahoo.com Port: 993 SSL: True
Establishing connection to imap.mail.yahoo.com:993 (Remote)
Server supports ID extension.
Server welcome string: * OK [CAPABILITY IMAP4rev1 ID MOVE NAMESPACE X-ID-ACLID UIDPLUS LITERAL+ CHILDREN XAPPLEPUSHSERVICE XYMHIGHESTMODSEQ AUTH=PLAIN AUTH=LOGIN AUTH=XOAUTH2 AUTH=XYMCOOKIE AUTH=XYMECOOKIE AUTH=XYMCOOKIEB64 AUTH=XYMPKI] IMAP4rev1 imapgate-1.8.1_01.20166
Server capabilities: ('IMAP4REV1', 'ID', 'MOVE', 'NAMESPACE', 'X-ID-ACLID', 'UIDPLUS', 'LITERAL+', 'XYMHIGHESTMODSEQ')

folderfilter= lambda folder: folder in ['Inbox', 'Sent']

Folderlist:
 Archive (disabled)
 Bulk Mail (disabled)
 Draft (disabled)
 dyn (disabled)
 Inbox
 Sent
 Trash (disabled)

Local repository 'Local': type 'Maildir'
Folderlist:
 
(blank - no local directories shown)
```

#### Steps to reproduce the error

Download distribution file to ubuntu 14.04.5 /32bits system; configure .offlineimaprc file and use a yahoo.com.br mail account.

**Final Notes**
I noticed that the yahoo folder names for yahoo.com.br  are in Pt-BR (not in English) for when you use the web GUI.  If you try a translation functions the error is that the translated folder does not exist.   

`offlineimap.bundled_imaplib2.error: EXAMINE command error: BAD ['[TRYCREATE] EXAMINE error - Folder does not exist or server encountered an error']. Data: Caixa de entrada`

where "Caixa de entrada" is the Inbox in Pt-BR

**Comment by nicolas33** [comment]
Weird. It looks like yahoo IMAP is mixing both translated and original names:
- sometimes, offlineimap likely gets the original names as suggested by `offlineimap --info`
- sometimes, offlineimap likely gets the translated names as implied by the attempt to create the translated name on remote.

That's very weird.

**Comment by chris001** [comment]
@nicolas33  Yahoo is probably using front web https proxy with multiple back ends in a high availability round-robin, and serving randomly english or portuguese, without the user session sticking to one server.

**Comment by braselectron** [comment]
Please also check and see if the bug also affects other languages (Germany, Italy, France, etc), at does locations to be sure you are going through yahoo proxy layout.  Need contributors!

**Comment by braselectron** [comment]
UPDATE

I just created a en-us account on yahoo.com and it also did not grab the messages (no download).

It reads all the folder names, but no download.  Did I miss something on the offlineimaprc config file ?

**Comment by nicolas33** [comment]
I see no issue with the configuration file. Could you try from another system?

If you'd like to, I can try from here if you agree to share your credentials (via a private mail).

**Comment by nicolas33** [comment]
Also, please provide the full output of `offlinimap -V` (not --version).

**Comment by braselectron** [comment]
```
$ ./offlineimap.py -V
offlineimap v7.0.13, imaplib2 v2.55 (bundled), Python v2.7.6
```

I will try from other ubuntu stations I have here (32 and 64bits) and report back.

**Comment by braselectron** [comment]
OK.  So I tested with other hardware and other versions of Ubuntu/Debian/Lubuntu not only 32bits but also 64bits.

I believe the problem I detected is just this: lack clear and simple documentation on "Howto" and "Getting Started".

So the other answer to this "bug" is also:

1. When you use the parameters: <--dry-run> and/or <--info> it will not create the folders no the local host.

2. After you test the syntax and .offlineimaprc file with the <--dry-run> and/or <--info> you need to issue the real command (in my case since I only need to download for backup - single user no installation):

cd to folder of the version of offlineimap version you downloaded than at terminal prompt 'go for it':

`$ ./offlineimap`

3. Other thoughts: I do believe I did experience some "yahoo" system hiccup, yesterday, because checking my terminal buffer log, I did issue the correct offlineimap command, more than once.

Thank you @nicolas33 and @chris001 for the feedbacks.

So I will close this issue.

**Comment by nicolas33** [comment]
Ok, thank you for the feedback.
