### ISSUE TITLE
offlineimap using IDLE is not reconnecting if IP change / disconnection

### ISSUE THREAD

**Issue by 2Belette** [OfflineIMAP/offlineimap#439]
#### General informations

- system/distribution (with version): parabola (archlinux) 4.9.11
- offlineimap version (`offlineimap -V`): v7.0.13
- Python version:  v2.7.13
- server name or domain: own server and outlook.office365.com

#### Issue
Using offlineimap on my laptop for more than one year without IDLE, it was working ok but because [Microsoft decides to not reply on why there IMAP is taking so long](https://social.technet.microsoft.com/Forums/office/en-US/74410bfb-c2d5-460a-9bb7-2da6e1aa97a0/imap-smtp-slow-performance-on-office-365-10sec-idle-time-before-receivingsending-data?forum=officeitpro#6359b3d8-8b8f-4bb6-a68e-9594ed008245) everytime I connect I would like to use IDLE instead...

It is working well until my laptop change network / IP or putting it into sleep/hibernate.
When I start it again or connect to another network offlineimap is not doing anything related to the IDLE connection, it only reacts after reaching the autorefresh counter (30min for me).

Is there a way to make some tests to evaluate some parameters and re-initiate the IDLE connection ? Anyone on the same situation?

Many thanks

**Comment by nicolas33** [comment]
Relates to #159.

I think the best is to stop offlineimap on suspend and start it on resume. I'd be delighted someone add hooks scripts in ./contrib.

**Comment by chris001** [comment]
See #440 This is a reliable fast function to detect if internet connected or disconnected.

**Comment by nicolas33** [comment]
Closing this one to keep discussions in #159.
