### ISSUE TITLE
 exceptions not handled correctly in single-threaded mode

### ISSUE THREAD

**Issue by aspiers** [OfflineIMAP/offlineimap#44]
As described in [this post](http://article.gmane.org/gmane.mail.imap.offlineimap.general/6183).

@konvpalto mentioned in #29 that he can't reproduce, so I guess I need to provide a test case for this.  I don't have time right now, but I'll file this bug here so that we don't forget about it.

**Comment by nicolas33** [comment]
Should be fixed in next release.
