### ISSUE TITLE
Problems with migrating imap to imap

### ISSUE THREAD

**Issue by springbob2017** [OfflineIMAP/offlineimap#441]
Hi, I'm getting problems with migrate one imap mailbox to another imap mailbox on the same Mailserver.

- offlineimap version: 6.7.0.1
- Python version:  2.7.12 (on Ubuntu16.10 yakkety)

#### Configuration file offlineimaprc
[general]
accounts = business
maxsyncaccounts = 1	
socktimeout = 60

[Account business]
remoterepository = source_mailbox
localrepository = target_mailbox

[Repository source_mailbox]
type = IMAP
remotehost = mail.example.net
remoteuser = old@mydomain.com
remotepass = ************
ssl = yes
maxconnections = 1
cert_fingerprint = aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd

[Repository target_mailbox]
type = IMAP
remotehost = mail.example.net
remoteuser = new@mydomain.com
remotepass = ************
ssl = yes
maxconnections = 1
cert_fingerprint = aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd

Output of: offlineimap --info
===================
OfflineIMAP 6.7.0.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Remote repository 'source_mailbox': type 'IMAP'
Host: mail.example.net Port: None SSL: 1
Establishing connection to mail.example.net:993
Server supports ID extension.
Server welcome string: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
Server capabilities: ('IMAP4REV1', 'LITERAL+', 'SASL-IR', 'LOGIN-REFERRALS', 'ID', 'ENABLE', 'IDLE', 'SORT', 'SORT=DISPLAY', 'THREAD=REFERENCES', 'THREAD=REFS', 'THREAD=ORDEREDSUBJECT', 'MULTIAPPEND', 'URL-PARTIAL', 'CATENATE', 'UNSELECT', 'CHILDREN', 'NAMESPACE', 'UIDPLUS', 'LIST-EXTENDED', 'I18NLEVEL=1', 'CONDSTORE', 'QRESYNC', 'ESEARCH', 'ESORT', 'SEARCHRES', 'WITHIN', 'CONTEXT=SEARCH', 'LIST-STATUS', 'BINARY', 'MOVE', 'SPECIAL-USE', 'COMPRESS=DEFLATE', 'QUOTA')

Folderlist:
 INBOX
 INBOX.cars
 INBOX.bikes
 INBOX.Drafts
 etc.

Local repository 'target_mailbox': type 'MappedIMAP'
Host: mail.example.net Port: None SSL: 1
Establishing connection to mail.example.net:993
Server supports ID extension.
Server welcome string: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
Server capabilities: ('IMAP4REV1', 'LITERAL+', 'SASL-IR', 'LOGIN-REFERRALS', 'ID', 'ENABLE', 'IDLE', 'SORT', 'SORT=DISPLAY', 'THREAD=REFERENCES', 'THREAD=REFS', 'THREAD=ORDEREDSUBJECT', 'MULTIAPPEND', 'URL-PARTIAL', 'CATENATE', 'UNSELECT', 'CHILDREN', 'NAMESPACE', 'UIDPLUS', 'LIST-EXTENDED', 'I18NLEVEL=1', 'CONDSTORE', 'QRESYNC', 'ESEARCH', 'ESORT', 'SEARCHRES', 'WITHIN', 'CONTEXT=SEARCH', 'LIST-STATUS', 'BINARY', 'MOVE', 'SPECIAL-USE', 'COMPRESS=DEFLATE', 'QUOTA')

Folderlist:
 INBOX

When I now execute the command 'offlineimap' all folders from the source_mailbox are created in target_mailbox, but no messages are transferred. Instaed I get the following errors:

OfflineIMAP 6.7.0.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync business:
 *** Processing account business
 Establishing connection to mail.example.net:993
 Establishing connection to mail.example.net:993
 Creating folder INBOX.cars[target_mailbox]
 Creating folder INBOX.bikes[target_mailbox]
 Creating folder INBOX.Drafts[target_mailbox]
 etc.
 
Folder INBOX [acc: business]:
 Migrating LocalStatus cache from sqlite to plain "                     "status folder for target_mailbox:INBOX
 ERROR: ERROR in syncfolder for business folder INBOX: Traceback (most recent call last):
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 512, in syncfolder
    replace(remoterepos.getsep(), statusrepos.getsep()))
  File "/usr/share/offlineimap/offlineimap/repository/LocalStatus.py", line 112, in getfolder
    self.import_other_backend(folder)
  File "/usr/share/offlineimap/offlineimap/repository/LocalStatus.py", line 78, in import_other_backend
    folderbk.cachemessagelist()
  File "/usr/share/offlineimap/offlineimap/folder/LocalStatusSQLite.py", line 203, in cachemessagelist
    cursor = self.connection.execute('SELECT id,flags,mtime,labels from status')
AttributeError: 'NoneType' object has no attribute 'execute'

  'NoneType' object has no attribute 'execute'
Thread 'Folder INBOX [acc: business]' terminated with exception:
Traceback (most recent call last):
  File "/usr/share/offlineimap/offlineimap/threadutil.py", line 163, in run
    Thread.run(self)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 599, in syncfolder
    statusfolder.closefiles()
UnboundLocalError: local variable 'statusfolder' referenced before assignment

Last 1 debug messages logged for Folder INBOX [acc: business] prior to exception:
thread: Register new thread 'Folder INBOX [acc: business]' (account 'business')
ERROR: Exceptions occurred during the run!
ERROR: ERROR in syncfolder for business folder INBOX: Traceback (most recent call last):
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 512, in syncfolder
    replace(remoterepos.getsep(), statusrepos.getsep()))
  File "/usr/share/offlineimap/offlineimap/repository/LocalStatus.py", line 112, in getfolder
    self.import_other_backend(folder)
  File "/usr/share/offlineimap/offlineimap/repository/LocalStatus.py", line 78, in import_other_backend
    folderbk.cachemessagelist()
  File "/usr/share/offlineimap/offlineimap/folder/LocalStatusSQLite.py", line 203, in cachemessagelist
    cursor = self.connection.execute('SELECT id,flags,mtime,labels from status')
AttributeError: 'NoneType' object has no attribute 'execute'

  'NoneType' object has no attribute 'execute'
Exception in thread sslmailpool.ispgateway.de handler (most likely raised during interpreter shutdown):Exception in thread Account sync business (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/share/offlineimap/offlineimap/threadutil.py", line 239, in run
  File "/usr/share/offlineimap/offlineimap/threadutil.py", line 163, in run
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 282, in syncrunner
Traceback (most recent call last):

  File "/usr/share/offlineimap/offlineimap/ui/UIBase.py", line 333, in acctdone  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'time'  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/lib/python2.7/dist-packages/imaplib2.py", line 1761, in _handler

<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

Any help or hint would be appreciated.
Thanks

**Comment by nicolas33** [comment]
> offlineimap version: 6.7.01

Please, try v6.7.0.3.

> Python version: 8.25 (on Ubuntu16.10 yakkety)

Hmm, Python version should be v2.X or 3.X.

**Comment by springbob2017** [comment]
Thank you for your quick response,
Unfortunately upgrading to 6.7.0.3 didn't solve the problem.

**Comment by nicolas33** [comment]
Please, try v7.0.13. Reverting back to v6.7 series won't be possible. Archive the maildirs and the metadata (in ~/.offlineimap by default) first.

**Comment by nicolas33** [comment]
> Archive the maildirs and the metadata (in ~/.offlineimap by default) first.

My bad, you don't have local maildir since you're using IMAP to IMAP. You only need to backup the metadata.

I've deprecated the v6.7 series. We did a good job at improving the v7.0 and since v7.0.14, the v7.0 series is mature enough and more reliable than the v6.7 series.

**Comment by nicolas33** [comment]
Because of this change, I'm closing this report. Thank you!
