### ISSUE TITLE
XOAUTH2 Authentication Failed but not required!

### ISSUE THREAD

**Issue by tommasop** [OfflineIMAP/offlineimap#442]
#### General informations

- system/distribution (with version): OSX 10.11.6
- offlineimap version (`offlineimap -V`): offlineimap v7.0.14, imaplib2 v2.57 (bundled), Python v2.7.11
- Python version: 2.7.11
- server name or domain: G Suite
- CLI options: None

#### Configuration file offlineimaprc

```
[general]
accounts = A, B
ui = ttyui
pythonfile=~/bin/offlineimap-helpers.py

[Account A]
localrepository = LocalA
remoterepository = RemoteA

[Account B]  <-- G Suite
localrepository = LocalB
remoterepository = RemoteB

[Repository LocalA]
type = Maildir
localfolders = ~/Mail/A

[Repository RemoteA]
type = IMAP
createfolders = False
remotehost = 
remoteuser = 
remotepasseval = get_pass("A")
ssl=true
sslcacertfile = /usr/local/etc/openssl/cert.pem
expunge = no
folderfilter = lambda foldername: foldername not in ['INBOX.Trash']
nametrans = lambda folder: re.sub('^INBOX\.', '', re.sub(' +', '_', folder))
maxconnections = 3

[Repository LocalB]
type = Maildir
localfolders = ~/Mail/B

[Repository RemoteB]
type = IMAP
createfolders = False
auth_mechanisms = PLAIN,LOGIN   <-- WITHOUT THIS LINE GIVES THE ERROR
remotehost = imap.gmail.com
remoteuser = 
remotepasseval = get_pass("B")
ssl=true
sslcacertfile = /usr/local/etc/openssl/cert.pem
expunge = no
folderfilter = lambda foldername: foldername not in ['INBOX.Trash']
nametrans = lambda folder: re.sub('^INBOX\.', '', re.sub(' +', '_', folder))
folderfilter = lambda foldername: foldername not in ['[Gmail]/Spam','[Gmail]/Trash']
maxconnections = 3
```

#### pythonfile (if any)

```
#! /usr/bin/env python2
from subprocess import check_output

def get_pass(account):
        return check_output("gpg --quiet --for-your-eyes-only --no-tty --decrypt ~/.msmtp-" + account + ".gpg", shell=True).strip("\n")
```

#### Logs, error

```
Account sync B:
 *** Processing account B
 Establishing connection to imap.gmail.com:993 (RemoteB)
 XOAUTH2 authentication failed: AUTHENTICATE command error: BAD ['Client aborted AUTHENTICATE command. s4mb245366598wrc']. Data: IPNF2 AUTHENTICATE XOAUTH2
```

#### Steps to reproduce the error

- launch offlineimap

**Comment by nicolas33** [comment]
Does the above patch/version fix your issue?

**Comment by nicolas33** [comment]
It's possible to install offlineimap as a user: remove the currently installed offlineimap and download the zip (or `git clone` the repository). Then `./offlineimap.py [options]`.

**Comment by tommasop** [comment]
Thanks! You actually guessed the problem I was facing ... 
not being able to understand how to use the git repository! ;)

Excerpts from Nicolas Sebrecht's message of 2017-03-21 13:44:33 -0700:
> It's possible to install offlineimap as a user: remove the currently installed offlineimap and download the zip (or `git clone` the repository). Then `./offlineimap.py [options]`.
> 

-- 

________________
Tommaso Patrizi

Thinking Code

Email: tommasop@thinkingco.de
Skype: tommasop
Twitter: @tommasomatic

IN OBSCURO MIRANDA RELUCENT

**Comment by nicolas33** [comment]
,-)

I'm pretty sure you've noticed the correct version to check is [this one](https://github.com/nicolas33/offlineimap/tree/e35d634f0fc58459899542dd0e10437f2f4ce421).

I'd say that downloading the zip is better to be sure the version is correct. Otherwise, git users have to make sure they've "checkout" the correct branch.

**Comment by nicolas33** [comment]
Gentle up!

**Comment by klemens** [comment]
I had the same problem and the patch applied on top of version 7.1.0 seems to fix it (I didn't have any XOAUTH2-errors since then).

**Comment by nicolas33** [comment]
Thank you much @klemens ! Patch applied. :-)
