### ISSUE TITLE
offlineimap uses up all available memory

### ISSUE THREAD

**Issue by JanWelker** [OfflineIMAP/offlineimap#451]
#### General informations

OS:
Centos 7

Software:
Offlineimap 6.7.0
Python 2.7.5

Domains:
unibasel.ch and wth.in

#### Configuration file offlineimaprc

[general]
accounts = unibas.ch, wth.in
metadata = ~/.offlineimap
maxsyncaccounts = 2
socktimeout = 60
ui = TTYUI

[Account unibas.ch]
localrepository = local-unibas.ch
remoterepository = remote-unibas.ch
autorefresh = 10
status_backend = sqlite

[Account wth.in]
localrepository = local-wth.in
remoterepository = remote-wth.in
autorefresh = 10
status_backend = sqlite
  
[Repository local-unibas.ch]
type = Maildir
localfolders = ~/mail/unibasel

[Repository local-wth.in]
type = Maildir
localfolders = ~/mail/wth.in
   
[Repository remote-unibas.ch]
type = IMAP
keepalive = 60
remotehost = mail.unibas.ch
cert_fingerprint = 2bab8ba86d3492d3400fd97cd1fb5da77ad888a5
ssl = yes
remoteuser = xxxx
remotepass = xxxx
idlefolders = ['INBOX','tickets','rss']

[Repository remote-wth.in]
type = IMAP
keepalive = 60
remotehost = mail.wth.in
cert_fingerprint = 85b1d3ef5a6104835b73a1d98e32a1da103c1301
ssl = yes
remoteuser = xxxx
remotepass = xxxx
idlefolders = ['INBOX']

[mbnames]
enabled = yes
filename = ~/.mutt/mailboxes
header = "mailboxes "
peritem = "+%(foldername)s"
sep = " "
footer = "\n"

#### Logs, error

Mar 29 05:26:04 its-a-trap kernel: offlineimap invoked oom-killer: gfp_mask=0x280da, order=0, oom_score_adj=0
Mar 29 05:26:04 its-a-trap kernel: offlineimap cpuset=/ mems_allowed=0
Mar 29 05:26:04 its-a-trap kernel: CPU: 1 PID: 10425 Comm: offlineimap Not tainted 3.10.0-514.10.2.el7.x86_64 #1
Mar 29 05:26:04 its-a-trap kernel: Hardware name: Dell Inc. Latitude E7270/0T0V7J, BIOS 1.4.2 03/04/2016
Mar 29 05:26:04 its-a-trap kernel: ffff88030e7d1f60 00000000a11703a3 ffff8803f56a3a78 ffffffff816864ef
Mar 29 05:26:04 its-a-trap kernel: ffff8803f56a3b08 ffffffff8168149a ffffffff812ae91b 0000000000000000
Mar 29 05:26:04 its-a-trap kernel: 0000000000000000 0408000000000426 fffeffff00000000 0000000000000001
Mar 29 05:26:04 its-a-trap kernel: Call Trace:
Mar 29 05:26:04 its-a-trap kernel: [<ffffffff816864ef>] dump_stack+0x19/0x1b
Mar 29 05:26:04 its-a-trap kernel: [<ffffffff8168149a>] dump_header+0x8e/0x225
Mar 29 05:26:04 its-a-trap kernel: [<ffffffff812ae91b>] ? cred_has_capability+0x6b/0x120
Mar 29 05:26:04 its-a-trap kernel: [<ffffffff8118480e>] oom_kill_process+0x24e/0x3c0
Mar 29 05:26:04 its-a-trap kernel: [<ffffffff8109389e>] ? has_capability_noaudit+0x1e/0x30
Mar 29 05:26:04 its-a-trap kernel: [<ffffffff81185046>] out_of_memory+0x4b6/0x4f0
Mar 29 05:26:04 its-a-trap kernel: [<ffffffff81681fa3>] __alloc_pages_slowpath+0x5d7/0x725
Mar 29 05:26:04 its-a-trap kernel: [<ffffffff8118b155>] __alloc_pages_nodemask+0x405/0x420
Mar 29 05:26:04 its-a-trap kernel: [<ffffffff811d22ba>] alloc_pages_vma+0x9a/0x150
Mar 29 05:26:04 its-a-trap kernel: [<ffffffff811b157f>] handle_mm_fault+0xc6f/0xfe0
Mar 29 05:26:04 its-a-trap kernel: [<ffffffff81691fd4>] __do_page_fault+0x154/0x450
Mar 29 05:26:04 its-a-trap kernel: [<ffffffff81692305>] do_page_fault+0x35/0x90
Mar 29 05:26:04 its-a-trap kernel: [<ffffffff8168e5c8>] page_fault+0x28/0x30
Mar 29 05:26:04 its-a-trap kernel: Mem-Info:
Mar 29 05:26:04 its-a-trap kernel: active_anon:3867470 inactive_anon:63837 isolated_anon:0#012 active_file:0 inactive_file:66 isolated_file:0#012 unevictable:8 dirty:15 writeback:0 unstable:0#012 slab_reclaimable:9142 slab_unreclaimable:13304#012 mapped:54464 shmem:64012 pagetables:12886 bounce:0#012 free:34123 free_pcp:812 free_cma:0
Mar 29 05:26:04 its-a-trap kernel: Node 0 DMA free:15896kB min:64kB low:80kB high:96kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15980kB managed:15896kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:0kB slab_unreclaimable:0kB kernel_stack:0kB pagetables:0kB unstable:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
Mar 29 05:26:04 its-a-trap kernel: lowmem_reserve[]: 0 2474 15753 15753
Mar 29 05:26:04 its-a-trap kernel: Node 0 DMA32 free:63696kB min:10604kB low:13252kB high:15904kB active_anon:2406736kB inactive_anon:36244kB active_file:0kB inactive_file:328kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:2780408kB managed:2535528kB mlocked:0kB dirty:0kB writeback:0kB mapped:29920kB shmem:36328kB slab_reclaimable:4184kB slab_unreclaimable:8480kB kernel_stack:960kB pagetables:7560kB unstable:0kB bounce:0kB free_pcp:1372kB local_pcp:192kB free_cma:0kB writeback_tmp:0kB pages_scanned:2961 all_unreclaimable? yes
Mar 29 05:26:04 its-a-trap kernel: lowmem_reserve[]: 0 0 13278 13278
Mar 29 05:26:04 its-a-trap kernel: Node 0 Normal free:56900kB min:56908kB low:71132kB high:85360kB active_anon:13063144kB inactive_anon:219104kB active_file:0kB inactive_file:0kB unevictable:32kB isolated(anon):0kB isolated(file):0kB present:13860864kB managed:13597276kB mlocked:32kB dirty:60kB writeback:0kB mapped:187936kB shmem:219720kB slab_reclaimable:32384kB slab_unreclaimable:44736kB kernel_stack:5424kB pagetables:43984kB unstable:0kB bounce:0kB free_pcp:1876kB local_pcp:228kB free_cma:0kB writeback_tmp:0kB pages_scanned:49 all_unreclaimable? yes
Mar 29 05:26:04 its-a-trap kernel: lowmem_reserve[]: 0 0 0 0
Mar 29 05:26:04 its-a-trap kernel: Node 0 DMA: 2*4kB (U) 2*8kB (U) 2*16kB (U) 1*32kB (U) 3*64kB (U) 2*128kB (U) 0*256kB 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15896kB
Mar 29 05:26:04 its-a-trap kernel: Node 0 DMA32: 1099*4kB (UE) 745*8kB (UE) 536*16kB (UE) 327*32kB (UEM) 155*64kB (UE) 96*128kB (UEM) 27*256kB (UE) 10*512kB (EM) 0*1024kB 0*2048kB 0*4096kB = 63636kB
Mar 29 05:26:04 its-a-trap kernel: Node 0 Normal: 3853*4kB (UEM) 1701*8kB (UEM) 723*16kB (UEM) 461*32kB (UEM) 25*64kB (U) 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 56940kB
Mar 29 05:26:04 its-a-trap kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
Mar 29 05:26:04 its-a-trap kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
Mar 29 05:26:04 its-a-trap kernel: 64220 total pagecache pages
Mar 29 05:26:04 its-a-trap kernel: 0 pages in swap cache
Mar 29 05:26:04 its-a-trap kernel: Swap cache stats: add 0, delete 0, find 0/0
Mar 29 05:26:04 its-a-trap kernel: Free swap  = 0kB
Mar 29 05:26:04 its-a-trap kernel: Total swap = 0kB
Mar 29 05:26:04 its-a-trap kernel: 4164313 pages RAM
Mar 29 05:26:04 its-a-trap kernel: 0 pages HighMem/MovableOnly
Mar 29 05:26:04 its-a-trap kernel: 127138 pages reserved
Mar 29 05:26:04 its-a-trap kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
Mar 29 05:26:04 its-a-trap kernel: [ 9595] 35198  9595  3786268  3430960    7125        0             0 offlineimap
Mar 29 05:26:04 its-a-trap kernel: Out of memory: Kill process 9595 (offlineimap) score 851 or sacrifice child
Mar 29 05:26:04 its-a-trap kernel: Killed process 9595 (offlineimap) total-vm:15145072kB, anon-rss:13723812kB, file-rss:28kB, shmem-rss:0kB

#### Steps to reproduce the error
Run offlineimap and wait a day

**Comment by nicolas33** [comment]
Sorry, the v6.7 series is not anymore supported. Please, try v7.0.14.
