### ISSUE TITLE
Understanding the code class IMAPServer(object) 

### ISSUE THREAD

**Issue by braselectron** [OfflineIMAP/offlineimap#462]
#### General informations

- system/distribution (with version): Ubuntu 14.04.5 - 32bits Kernel 3.13.0-117-generic 165-Ubuntu SMP
- offlineimap version (`offlineimap -V`): 7.0.13
- Python version: 2.7.6
- server name or domain: imap.mail.yahoo mail and imap.gmail.com 

#### Basic Configuration using IMAPClient 

When using 
   from imapclient import IMAPClient

We use
               server = IMAPClient(HOSTNAME, use_uid=True, ssl=True)
               server.login(USERNAME, PASSWORD)

to connect to imap server and login

But yahoo and gmail sees this as a insecure connection and blocks it.

You could use your browser and change "security setting" and allow "insecure apps" but it would be a security problem (and yahoo complains every time you login).

#### Technical Background

According to https://support.google.com/accounts/answer/6010255:

Google may block sign in attempts from some apps or devices that do not use modern security standards. Since these apps and devices are easier to break into, blocking them helps keep your account safer.

What are those "modern security standards" and why is it dangerous to allow apps which do not support them? Also, is it dangerous to enable the option (allow less secure apps) if you do not use those apps? If so, why?

The OAuth2.0 over IMAP (according to this page) is the needed connection protocol. As far as I know, this is Google's own extension and is not used by any other service providers, others use Xoauth, or other similar protocols.

#### My Question:

Can I use offlineimap/imapserver.py to fix this issue by using class IMAPServer in place of IMAPClient or did I miss something here ?

```
 PRIVATE DATA REMOVED.
```

**Comment by nicolas33** [comment]
> What are those "modern security standards" and why is it dangerous to allow apps which do not support them? 

For Google, I think they assume OAUTH2. This would be a question for Google, though.

> Also, is it dangerous to enable the option (allow less secure apps) if you do not use those apps? If so, why?

I'd say that with OAUTH2, you have full control of "who" is attempting to authenticate via shared token.



> The OAuth2.0 over IMAP (according to this page) is the needed connection protocol. As far as I know, this is Google's own extension and is not used by any other service providers, others use Xoauth, or other similar protocols.

Basically, yes.



> My Question:
> 
> Can I use offlineimap/imapserver.py to fix this issue by using class IMAPServer in place of IMAPClient or did I miss something here ?

You're right that offlineimap/imapserver.py is the IMAP client based on imaplib2. You're free to re-use this code while you comply to the [GPLv2 licence](https://github.com/OfflineIMAP/offlineimap/blob/master/COPYING).

**Comment by nicolas33** [comment]
I'm closing but you're free to feed this issue again.
