### ISSUE TITLE
offlineimap hangs consistently on my "saved" folder

### ISSUE THREAD

**Issue by msoulier** [OfflineIMAP/offlineimap#463]
Every time I try to sync, offlineimap hangs on my home account on the "saved"
folder. I've tried deleting the local data, but it seems like there's something
in that folder that it doesn't like.

- Mac OS El Capitan
```
    msoulier@anton:~$ offlineimap -V
    offlineimap v7.1.0, imaplib2 v2.57 (bundled), Python v2.7.13
    msoulier@anton:~$

```
- server name or domain: 

    webfaction.com

    - CLI options:  none

#### Configuration file offlineimaprc
    [general]
    pythonfile = ~/.offlineimap.py
    accounts = Home, Work
    ui = Noninteractive.Basic
    socktimeout = 60
    metadata = ~/Mail/.offlineimap
    # maxage = 365

    [Account Home]
    localrepository = HomeLocal
    remoterepository = HomeRemote
    #postsynchook = notmuch new
    autorefresh = 5
    quick = 24

    [Account Work]
    localrepository = MitelLocal
    remoterepository = MitelRemote
    #postsynchook = notmuch new
    autorefresh = 5
    quick = 24

    [Repository HomeRemote]
    createfolders = False
    type = IMAP
    ssl = yes
    sslcacertfile = ~/cacert.pem
    remotehost = mail.webfaction.com
    remoteuser = msoulier
    remotepasseval = get_imap_pass('HomeRemote')
    folderfilter = lambda folder: not re.search('(^draft|^junk|^deleted|^trash)', folder, re.IGNORECASE)

    [Repository MitelRemote]
    createfolders = False
    type = IMAP
    ssl = yes
    sslcacertfile = ~/cacert.pem
    remotehost = outlook.office365.com
    remoteuser = michael.soulier@mitel.com
    remotepasseval = get_imap_pass('MitelRemote')
    folderfilter = lambda folder: not re.search('(^Sync|^Sent|^RSS|^Draft|^Contacts|^Calendar|^Tasks|^Junk|^Deleted)', folder)

    [Repository HomeLocal]
    type = Maildir
    localfolders = ~/Mail/home
    sep = .

    [Repository MitelLocal]
    type = Maildir
    localfolders = ~/Mail/work
    sep = .

#### pythonfile (if any)
    msoulier@anton:~$ cat .offlineimap.py
    import os

    credfile = os.path.join(os.environ['HOME'], '.offlineimap.creds')

    def get_imap_pass(repo):
        cf = open(credfile, "r")
        creds = {}
        for line in cf:
            line = line.strip()
            name, cred = line.split(' = ')
            creds[name] = cred

        return creds.get(repo, '')

#### Logs, error
None, just hangs. Is there a verbose logging option?

#### Steps to reproduce the error
Unknown. Attempt to sync my account.

**Comment by msoulier** [comment]
Actually I think it's something after my saved folder. I told offlineimap to skip my saved folder and it just seemed to hang on a different folder.

**Comment by nicolas33** [comment]
The debug mode for all is `offlineimap -d ALL`. It would be great to add the `-1` (one) switch, too.

**Comment by msoulier** [comment]
Interesting. The problem seems to go away with the -1 switch.

**Comment by msoulier** [comment]
Without the -1 switch, it hangs here

Syncing saved: IMAP -> Maildir
INFO:OfflineImap:Syncing saved: IMAP -> Maildir
Loading message list for Maildir[saved]
DEBUG:OfflineImap:Loading message list for Maildir[saved]
Message list for Maildir[saved] loaded: 62 messages
DEBUG:OfflineImap:Message list for Maildir[saved] loaded: 62 messages
[thread]: Unregister thread 'Folder rogers [acc: Home]'
DEBUG:OfflineImap:[thread]: Unregister thread 'Folder rogers [acc: Home]'

**Comment by nicolas33** [comment]
This excerpt is trimmed too much.

**Comment by nicolas33** [comment]
I'd be interested by the results with these options (`-1` removed):
- `maxconnexions = 1`
- `singlethreadperfolder = yes`

**Comment by benutzer193** [comment]
a little typo in nicolas33 last message, it should be:
`maxconnections = 1`

**Comment by nicolas33** [comment]
Thanks for the fix @benutzer193 . It wrote the french word. :-(

**Comment by benutzer193** [comment]
@nicolas33 je sais :wink:

**Comment by msoulier** [comment]
I found many conflicts with folder names having varying case but the same name, which works on linux but not on MacOS due to its file system. I deleted my local files and downloaded everything again from the server, and it is currently working.

**Comment by nicolas33** [comment]
Thank you much for the report. This is something we have to document. May I ask what's the file system?

**Comment by nicolas33** [comment]
Done in the FAQ.
