### ISSUE TITLE
Question - move offlineimap config to new server

### ISSUE THREAD

**Issue by zuku81** [OfflineIMAP/offlineimap#464]
#### General informations - Old server

- system/distribution (with version): Debian 8.7
- offlineimap version (`offlineimap -V`): 6.3.4-1 (system wide installation)
- Python version: 2.7.9-1
- server name or domain: 
- CLI options: 

#### General informations - New server
- system/distribution (with version): Debian 8.7
- offlineimap version (`offlineimap -V`): 7.1.0 (single user installation)
- Python version: 2.7.9-1
- server name or domain: 
- CLI options: 

I have to move my offlineimap to new server, should I move folder /.offlineimap where inside are my account names with repository and with all synchronisation statuses, so then when I run it first time on new server synchronisation will not start from beginning  #?

**Comment by nicolas33** [comment]
Yes. You should copy the `metadata` directory, the `localfolders` directories and your configuration files (including the pythonfile if any).

You might like to try the dry-run mode or set the remotes to "read only" for the first run.

**Comment by nicolas33** [comment]
system wide vs single user installation has no impact.
