### ISSUE TITLE
Add `--batch` option to skip interactive password prompts

### ISSUE THREAD

**Issue by shtrom** [OfflineIMAP/offlineimap#466]
When passwords are stored in a separate (GPG-encrypted) store, and OfflineIMAP is started periodically by the system, it hangs when the GPG agent cannot decrypt the password (e.g., no passphrase cached), OfflineIMAP hangs indefinitely on the failure and doesn't remove the lock file, thus preventing any later instance (when a passphrase has been entered) from running.

#### General informations

- OS X Sierra
- `offlineimap v7.1.0, imaplib2 v2.57 (bundled), Python v2.7.13`
- CLI options: launched by `launchd` periodically
```
?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>EnvironmentVariables</key>
    <dict>
      <key>PATH</key>
      <string>/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin</string>
    </dict>
    <key>KeepAlive</key>
    <false/>
    <key>Label</key>
    <string>homebrew.mxcl.offlineimap</string>
    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/opt/offlineimap/bin/offlineimap</string>
    </array>
    <key>StartInterval</key>
    <integer>300</integer>
    <key>RunAtLoad</key>
    <true />
    <key>StandardErrorPath</key>
    <string>/dev/null</string>
    <key>StandardOutPath</key>
    <string>/dev/null</string>
  </dict>
</plist>
```

#### Configuration file offlineimaprc
The problem is when using pass with a GPG agent, but no passphrase configured in the agent (e.g., at night when I'm not at the station)

```
remotepasseval = get_pass("server/account")
```

#### pythonfile (if any)

```
#! /usr/bin/env python
from subprocess import check_output

def get_pass(account):
        return check_output("pass %s | head -n 1" % (account), shell=True).rstrip().decode("utf-8")

if __name__ == "__main__":
    import sys
    print(get_pass(sys.argv[1]))
```

#### Logs, error

```
omehani@ombp:~$ offlineimap
OfflineIMAP 7.1.0
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync Account:
 *** Processing account Account
Account sync Account:
 Establishing connection to mail.account.net:993 (Account)
gpg: decryption failed: No secret key
Enter password for account 'Account':```

In batch mode, OfflineIMAP should just skip over the interactive password request.

#### Steps to reproduce the error

- Clear the GPG passphrase from the agent
- Wait for the launchctl task to kick offs

Result:
- offlineimap process hangs indefinitely, and lockfile present for the account

Expected result (if using a new option, e.g., `--batch`):
- skip over any missing password and don't ask for input
- clear up lock and terminate for accounts with missing info

**Comment by nicolas33** [comment]
What about the Basic UI, BTW? Does adding `-u basic` do what you want?

This Basic UI is historically the way to not get asked for a password. Both have diverged a bit but they are very similar about the available features.

**Comment by nicolas33** [comment]
See `man 7 offlineimapui` or the [man page online](http://www.offlineimap.org/doc/offlineimapui.html). ,-)

**Comment by nicolas33** [comment]
Oh, and you might like to check the syslog UI, too.

**Comment by nicolas33** [comment]
I'm closing but we may re-open on request.

**Comment by shtrom** [comment]
Ah, yeah, this seems to have fixed the issue nicely. I'll get the `lauchctl` config updated with HomeBrew.

**Comment by nicolas33** [comment]
Good idea! :-)
