### ISSUE TITLE
Sync mails for specific time period

### ISSUE THREAD

**Issue by DeepakLabh** [OfflineIMAP/offlineimap#468]
Hi,

I was searching for the feature in offlineimap which would only sync mails for specific date range.

Is the feature available in the current version of tool.

Thanks.

**Comment by DeepakLabh** [comment]
I discovered defining maxage would solve the problem but ,In my case it isn't.

my offlineimaprc content:
`[general]
accounts = Outlook
maxsyncaccounts = 3

[Account Outlook]
localrepository = Local
remoterepository = Remote

[Repository Local]
type = Maildir
localfolders = ~/outlook_backup/USERNAME/mail
maxage = 2

[Repository Remote]
type = IMAP
remotehost = imap-mail.outlook.com
remoteport = 993
remoteuser = xxx@abc.com
remotepass = xxx
ssl = yes
realdelete = no
maxconnections = 3
sslcacertfile = /etc/ssl/certs/ca-certificates.crt`

**Comment by nicolas33** [comment]
You need to explain what you expect and what you currently get with more details.

**Comment by DeepakLabh** [comment]
I need the 2-3 days older emails to be synced/saved in my local machine, but now I am getting whole emails saved/synced.

**Comment by nicolas33** [comment]
`maxage` must be in the account section.

**Comment by nicolas33** [comment]
Notice that once fully downloaded, you might have to wait some days to see this working. Already downloaded emails are only ignored.

**Comment by DeepakLabh** [comment]
Thanks, It solved the problem.
