### ISSUE TITLE
offlineimap.timer doesn't work

### ISSUE THREAD

**Issue by knezi** [OfflineIMAP/offlineimap#469]
If I simply activate the provided timer by:

```
systemctl --user enable offlineimap.timer
systemctl --user start offlineimap.timer
```

Then `systemctl --user list-timers` lists this timer, but all times (next, past) are N/A. It works if I add this line into the timer:

```
OnBootSec=1m
```

So I guess there needs to be specified first time of run and then the repetition.

**Comment by nicolas33** [comment]
May I ask why this is required?

**Comment by nicolas33** [comment]
Patch applied, BTW.

**Comment by knezi** [comment]
@nicolas33 because OnUnitInactiveSec specificies how many seconds after the last run next run will be executed. When you boot, there's no last run and therefore the timer won't be triggered. This is why you add OnBootSec, which will run it once after boot and then it will be run repeatedly thanks to the first parameter.

**Comment by nicolas33** [comment]
Ok, thank you.
