### ISSUE TITLE
sync all but deletions on local or remote

### ISSUE THREAD

**Issue by lenar** [OfflineIMAP/offlineimap#47]
Could you add new option for local repositories? Something like ```saveonly = True|False```.
Default would be ```False``` (current behavior).When ```True``` no already saved message nor created folder should be deleted from local repository even if deleted from remote one.

This change would make OfflineIMAP perfect for IMAP account archival (combined with  ```readonly = True``` on remote repository).

Would you consider it?

**Comment by nicolas33** [comment]
@konvpalto : don't know if you had time to work on this but if by chance you have a local WIP, please put it to the `pu` branch. Even crazy or hardly experimental code might be worth sharing these days, I believe. ,-)

**Comment by avar** [comment]
For what it's worth I wanted this feature too (and filed issue #144, which was a duplicate) and eventually just ended up moving to mbsync with a config line of `Sync New ReNew Flags`. Leaving out the `Delete` flag so it doesn't sync deletions.

**Comment by nicolas33** [comment]
@naveen1336 @m3nu @ojdo 

Feature implemented in d5853b5d65da93ba9a0c31f6e38320651746aa87 while still experiemental and **UNTESTED**.

Please, test current `next` branch and report failures. Be aware that local cache was enabled to sqlite after current stable release v6.7.0. This means you might want to set `status_backend = plain` to come back to any earlier version once tested.

**Comment by nicolas33** [comment]
Positive feedbacks would be appreciated, too. :-)

**Comment by max72bra** [comment]
hi nicolas, seems to not work here.
i've patched master branch with this commit only and added new config line.
`[Repository local]
type = Maildir
localfolders = ~/Maildir
sync_deletes = no`
it continues to locally delete messages

**Comment by nicolas33** [comment]
@max72bra First, you should really download the full sources instead of cherry-picking the commit.

If you want to disable local deletes, `sync_deletes` must stand in the remote section: the commit disables the *sync* of deletions not the *write* of deletions.

**Comment by max72bra** [comment]
oh! I really misunderstood the documentation, sorry for the waste of time.
testing immediately

**Comment by max72bra** [comment]
QED works like a charm. this is a long awaited and desired feature. good choice!
backing up 20+ accounts in "append mode": no deletions applied for now.
sorry again for the waste of time.

**Comment by trbs** [comment]
Testing it, so far so good :)
Thanks !

**Comment by avar** [comment]
@nicolas33 

    > Positive feedbacks would be appreciated, too. :-)

Was that comment for me? It's hard to tell with the way GitHub flattens threads. In any case I wasn't meaning to negatively portray offlineimap. It's just that because it didn't have that feature I switched to mbsync and it's been working for me, I'm happy that the same feature's being implemented in offlineimap

**Comment by ojdo** [comment]
Having tested it: works for me!
 1. added `sync_deletes = no` to the **remote** side repository
 2. deleted a message on the remote side
 3. run `offlineimap`
 4. observe that mail remains on local maildir. SUCCESS :+1: 

The option doc string might need some more directional wording. Current:
>  Remove messages on remote when deleted in local. Default is yes.

Suggestion (with probably too much redundant verbiage):
> *Propagate* message *deletion to* remote when deleted on local. *Set to no to keep locally deleted messages remotely.* Default is yes.

Plus: a pointer to the "reverse" option in the other repo section might be beneficial to avoid confusions like above.

**Comment by nicolas33** [comment]
Thanks you much for the feedbacks. Marked as tested and still experimental. Documentation improved.

**Comment by jloh** [comment]
Do we have any idea when this will be put into the master branch? I'm hoping to install this on a FreeNAS box for email archiving/backups but have no idea if it'll be the right version.

**Comment by nicolas33** [comment]
@konvpalto might have good hints about the releases in BSD.

This will be in next `master` with next release candidate. I still have no idea when it will come, though.

**Comment by dolohow** [comment]
@jloh You can always do

1. Install git
2. Fetch repository
    git clone https://github.com/OfflineIMAP/offlineimap.git
3. Change branch to next
    git checkout next
4. Run offlineimap
    python offlineimap.py

Enjoy

**Comment by nicolas33** [comment]
Without git, you can simply download the zip file provided by github. ,-)

**Comment by jloh** [comment]
Ahh awesome. Either of those will work perfectly, thanks @dolohow / @nicolas33!

**Comment by avar** [comment]
For anyone reading the backlog and wondering about the current status: This is now in the master branch, and looks like it'll be released in v7.0.0 which is currently in rc phase.

**Comment by jloh** [comment]
I've turned this setting on and its working well, I'm wondering what happens in a scenario like this though:

I do an initial sync of my whole email account. After this is complete I move messages from my Inbox to another folder and then run another sync. The messages are no longer in my inbox, but in a folder. Will offlineimap treat this as a delete and not sync it (if I have this setting on) and just add the email to the folder as well or will it see that its moved?

**Comment by nicolas33** [comment]
> I do an initial sync of my whole email account. After this is complete I move messages from my Inbox to another folder and then run another sync.

##### initial

- local:

INBOX: A, B, C

- server:

INBOX: A, B, C

##### move A, B, C to NEW_FOLDER and sync

- local:

INBOX: (empty)
NEW_FOLDER: A', B', C'

A == A' (same content) but UIDs are different.

- server:

INBOX: A, B, C
NEW_FOLDER: A', B', C' # If folder creation is not disabled.

**Comment by nicolas33** [comment]
Notice that offlineimap has no "move" understanding. Emails are either created or removed (or changed for flags). On local moves, offlineimap sees deletions and creations.

**Comment by nicolas33** [comment]
Yet another note: in IMAP terminology, a "folder" **is** a maildir.

**Comment by jloh** [comment]
Perfect, thanks. If I then ran something like imapfilter over the maildir (after the second sync) I'd still get duplicates right? Because imapfilter would just move them into the maildir after offlineimap has sync'd the second copy of the email.

**Comment by nicolas33** [comment]
> Perfect, thanks. If I then ran something like imapfilter over the maildir (after the second sync) I'd still get duplicates right? Because imapfilter would just move them into the maildir after offlineimap has sync'd the second copy of the email.

With imapfilter, you can *move* emails. Offlineimap would sync the new/moved emails and remove them in the local maildir. Here, **I assume you have "sync_deletes = no" set on the *local* repository** so that deletions are **not** propagated *by offlineimap* **to** the remote. If you make changes *on the remote* with another software, then offlineimap propagates all of changes to the local repository.

**Comment by nicolas33** [comment]
NB: I think imapfilter can't work on maildirs. It works on IMAP servers for sure.

**Comment by JayEn84** [comment]
Sorry for bumping this closed issue, but we try to keep deleted emails in the target and cannot get this to work, so I think this is the correct place to ask. We try to do incremental backups using OfflineIMAP where both, local and remote, are IMAP accounts. We currently use OfflineIMAP 7.013 and Python 2.7.12.

The config file looks like this:
```
[general]
accounts = test
maxsyncaccounts = 1
socktimeout = 60

[Account test]
remoterepository = source_mailbox
localrepository = target_mailbox

[Repository source_mailbox]
type = IMAP
remotehost = local.mail.net
remoteuser = local@email.net
remotepass = ****************
ssl = yes
maxconnections = 1
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
readonly = True

[Repository target_mailbox]
type = IMAP
remotehost = remote.mail.net
remoteuser = remote@email.de
remotepass = ********
ssl = yes
maxconnections = 1
sync_deletes = no
sslcacertfile = /etc/ssl/certs/ca-certificates.crt 
```
If an email or a folder is deleted in the source, it is also deleted in the target after running OfflineIMAP. It seems that `sync_deletes = no` does not have any impact. Does anyone have an idea what's wrong?

**Comment by avar** [comment]
@JayEn84 You put the `sync_deletes` in the wrong section. You can put it in *either* the local or remote repository. What you've done means "when I delete stuff *locally*, don't sync those deletes". I.e. you'll find that if you locally delete a mail and sync with that setting, it's not deleted on the server.

If you put it in the remote repository (`source_mailbox`) it means "don't sync deletes from this remote".

**Comment by nicolas33** [comment]
On top of @JayEn84 said (thank you), I'd say it's NOT possible to make proper backups in IMAP/IMAP mode.

If anything goes wrong or badly changes while syncing, the "backup" mailbox will be wrong too.

See http://www.offlineimap.org/documentation.html#make-backups-of-a-mailbox

**Comment by JayEn84** [comment]
Thanks @avar , we thought we tried this but obviously did not - sorry!
Thanks @nicolas33 for pointing this out, we will keep it in mind.
