### ISSUE TITLE
Offlineimap error using with virtualenvironment

### ISSUE THREAD

**Issue by DeepakLabh** [OfflineIMAP/offlineimap#471]
There is an issue when you run offlineimap after installation via git on virtual environment.

the env path for _path_to_venv/bin/offlineimap_ is _"#!/usr/bin/python"_
the error was:
_**Traceback (most recent call last):
  File "xxx/home/xxx/yyy/bin/offlineimap", line 20, in <module>
    from offlineimap import OfflineImap
ImportError: No module named offlineimap**_
 I changed it to _"#!/path_to_venv/bin/python"_ and it worked.

**Comment by nicolas33** [comment]
Well, we never supported installations in virutal envs but I think we should.

We need to know the virtual env tool you use and the steps to reproduce this to see if we can do something about that.

**Comment by DeepakLabh** [comment]
Hi Nicolas, I tried reproducing the error the same way I did earlier, but couldn't (Moved to the new infrastructure with python 3.X), and it is working well with virtual-environments as well. 

Thanks.
