### ISSUE TITLE
How to use python module keyring for passwords on mac osx

### ISSUE THREAD

**Issue by mec07** [OfflineIMAP/offlineimap#473]
#### General informations

- system/distribution (with version): Mac OS X v10.12.5 and I'm using fish shell (although I don't think that should make a difference as this is a python program)
- offlineimap version (`offlineimap -V`): 
```offlineimap v7.1.0, imaplib2 v2.57 (bundled), Python v2.7.13```
- Python version: 
```Python 2.7.13```
- server name or domain: outlook365
- CLI options: 

#### Configuration file offlineimaprc

```
[general]
accounts = work,liveerrors,deverrors
maxsyncaccounts = 3
pythonfile = ~/.mutt/offlineimap.py
auth_mechanisms = GSSAPI, CRAM-MD5, PLAIN, LOGIN

[Account work]
localrepository = work-local
remoterepository = work-remote

[Repository work-local]
type = Maildir
localfolders = ~/Maildir/work

[Repository work-remote]
type = IMAP
remotehost = outlook.office365.com
remoteuser = my-email-address
remotepass = get_password("outlook.office365.com", "my-email-address")
sslcacertfile = /etc/ssl/cert.pem
folderfilter = lambda foldername: foldername not in ["Contacts", "Calendar"]

[mbnames]
enabled = yes
filename = ~/.mutt/mailboxes
header = "mailboxes "
peritem = "+%(accountname)s/%(foldername)s"
sep = " "
footer = "\n"
```

#### pythonfile (if any)

```
#! /usr/local/bin/python
from keychain import get_password
```

#### Logs, error

```
OfflineIMAP 7.1.0
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
ERROR: No module named keychain
ERROR: Exceptions occurred during the run!
ERROR: No module named keychain
```

#### Steps to reproduce the error

- Install keychain
```pip install keychain```
- Run offlineimap
```offlineimap```

**Comment by mec07** [comment]
Any help with this would be really appreciated. Maybe it is as simple as setting an environment variable or something? It's just not finding the keychain python module.

**Comment by nicolas33** [comment]
I did not know `keychain`. I've checked what it is: https://github.com/blockstack/keychain-manager-py .

I think you'd rather want `keyring`.

**Comment by mec07** [comment]
That's embarrassing... lol :| Thanks!

**Comment by mec07** [comment]
Another comment, just in case someone finds this by googling it. I had the syntax incorrect above.

The line 
```remotepass = get_password("outlook.office365.com", "my-email-address")```
actually only works for plaintext passwords, i.e
```remotepass = plaintext-password```

If you want to inject python code you have to have `remotepasseval` instead of `remotepass`, i.e.:
```remotepasseval = get_password("outlook.office365.com", "my-email-address")```
