### ISSUE TITLE
systemd WatchdogSec is documented but not implemented

### ISSUE THREAD

**Issue by hobarrera** [OfflineIMAP/offlineimap#476]
The documentation [mentions](http://www.offlineimap.org/doc/contrib/systemd.html#signals) support for systemd's watchdog, but offlineimap does not actually implement this.

The `WatchdogSec` functionality [specifies](https://www.freedesktop.org/software/systemd/man/systemd.service.html#WatchdogSec=) that the [`sd_notify`](https://www.freedesktop.org/software/systemd/man/sd_notify.html#) function must be called during this interval, else the service gets killed.

Since systemd doesn't implement this, the end result is offlineimap **ALWAYS** being killed, regardless of its current status. The docs, suggest that this would happen only in scenarios such as _"may not return successfully after a suspend and resume"_.

IMHO, it's sanest to trim this bit of doc (which can be confusing if you don't dig into the systemd docs and offlineimap code), and rather suggest things like `socktimeout` to handle these scenarios. Otherwise, clarify this documentation a bit more.

**Comment by nicolas33** [comment]
I think that @benutzer193 wrote the service file with the assumption that offlineimap should *END* before the timeout (with a large enough timeout for all use cases).

I agree that the limitation you describe should either be fixes or documented, though.

**Comment by hobarrera** [comment]
Oh, since I run it deamon-like (with IDLE and quick-refreshes), I assumed a perma-running service.
If that's the case, then those docs need a bit of extending/clarification.

I wish I had the time right now to volunteer, but I won't for a while, regrettably. :(

**Comment by hobarrera** [comment]
Actually, no, the way it's written in the docs right now, it'll be stopped and restarted immediately, so:

* On clean exit (code 0), it just stops, period.
* If it's still running after 5m, it gets killed, and restarted immediately.

There's no timer related, so the first case simply stops, forever.

**Comment by nicolas33** [comment]
I've read the doc again. I agree this is confusing if not wrong in the first place.
We must (and will) improve it.

Thanks for the report. :-)

**Comment by nicolas33** [comment]
@benutzer193, opinion on this?

**Comment by benutzer193** [comment]
@nicolas33 will take a look.

**Comment by benutzer193** [comment]
@nicolas33 I'd propse:

```
Restart=on-failure
RestartSec=60
TimeoutStopSec=120
```
or is there a reason for `Restart=always`, I don't see?
We could push the Timeout up a lot, as we use the oneshot switch and if there is no problem the Timeout shouldn't be necessary anyway, so it is only a failsafe, if something goes wrong.
I actually left the Watchdog functionality like it was before my first commit. But @hobarrera is correct of course.
I also think it's safe to remove that part from the docs.

Your opinions?

**Comment by nicolas33** [comment]
> We could push the Timeout up a lot, as we use the oneshot switch and if there is no problem the Timeout shouldn't be necessary anyway, so it is only a failsafe, if something goes wrong.

I agree to increase the number. Those provided are not mandatory and left to user customization anyway.
I think the systemd timeout would help if offlineimap hangs (e.g. suspend/resume case) when the socket timeout is not triggered.



> I actually left the Watchdog functionality like it was before my first commit.

Ah, right. I've missed this.

> But @hobarrera is correct of course.
> I also think it's safe to remove that part from the docs.

Ok, to remove both the doc and the watchdog configuration lines. We don't correctly support this anyway.

@benutzer193 Would you like to make the changes or should I update the files?

Thanks for your inputs. ,-)

**Comment by benutzer193** [comment]
I can prepare a PR.

**Comment by nicolas33** [comment]
Ok, thanks!

**Comment by nicolas33** [comment]
Done.

**Comment by benutzer193** [comment]
@hobarrera for clarification:
The non-oneshot systemd service files are supposed to run permanently (just added restart on failure with the last update, thanks to your suggestion) and the oneshot service files (which are used by the timers) run like the name suggests one time.
