### ISSUE TITLE
folder not synced with Davmail

### ISSUE THREAD

**Issue by einlandarzt** [OfflineIMAP/offlineimap#485]
#### General informations
- system/distribution (with version): 
Ubuntu 17.04
- offlineimap version (`offlineimap -V`): 
7.0.12
- Python version: 
2.7.13
- server name or domain: 
mail.campus.unibe.ch
- CLI options: 

#### Configuration file offlineimaprc
[general]
accounts = unibe
ssl = no
maxsyncaccounts = 1

[Account unibe]
localrepository = unibe-local
remoterepository = unibe-remote
status_backend = sqlite

[Repository unibe-local]
type = Maildir
localfolders = ~/mail/unibe

[Repository unibe-remote]
type = IMAP
remotehost = localhost
remoteuser = redacted
remotepass = redacted
remoteport = 1143
ssl = no
~                                     
#### Steps to reproduce the error

offlineimap -a unibe -f Archive

Folder Archive contains thousands of messages on the server, none of which are synced.
- 
-

**Comment by nicolas33** [comment]
The `-f Archive` CLI option makes subfolders to be ignored. `-f Archives` is about syncing `Archives` only, not `Archives/foo` or `Archives/sub`.

**Comment by einlandarzt** [comment]
Yes, but there are no subfolder in "Archive"; it's about all the messages in the folder "Archive" that are not synced. So maybe my wording was imprecise, it's not about subfolders not being synced, but about a folder, "Archive", that isn't synced. Thanks

**Comment by nicolas33** [comment]
Could you provide the output of `offlineimap -a unibe -f Archives -d imap`?

Are you sure the folder is `Archives` and not `INBOX/Archives`?

**Comment by einlandarzt** [comment]
I am indeed. Also, the folder was automatically created locally when I first ran offlineimap, so the remote folder structure was actually replicated. Missing are the messages.

**Comment by einlandarzt** [comment]
OfflineIMAP 7.0.12
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Debug mode: Forcing to singlethreaded.
Now debugging for imap: IMAP protocol debugging
Now debugging for : Other offlineimap related sync messages
Account sync unibe:
 [imap]: Using authentication mechanisms ['GSSAPI', 'XOAUTH2', 'CRAM-MD5', 'PLAIN', 'LOGIN']
 *** Processing account unibe
 Establishing connection to localhost:1143 (unibe-remote)
 [imap]: Attempting LOGIN authentication
 [imap]: Attempting IMAP LOGIN authentication
 []: Filtering out 'Trash'[unibe-remote] due to folderfilter
 []: Filtering out 'Drafts'[unibe-remote] due to folderfilter
 []: Filtering out 'INBOX'[unibe-remote] due to folderfilter
 []: Filtering out 'Junk'[unibe-remote] due to folderfilter
 []: Filtering out 'Unsent Messages'[unibe-remote] due to folderfilter
 []: Filtering out 'Sent'[unibe-remote] due to folderfilter
 []: Filtering out 'Synchronisierungsprobleme'[unibe-remote] due to folderfilter
 []: Filtering out 'Synchronisierungsprobleme/Konflikte'[unibe-remote] due to folderfilter
 []: Filtering out 'Synchronisierungsprobleme/Lokale Fehler'[unibe-remote] due to folderfilter
 []: Filtering out 'Synchronisierungsprobleme/Serverfehler'[unibe-remote] due to folderfilter
 []: Copying folder structure from unibe-remote to unibe-local
 Syncing Archive: IMAP -> Maildir
 Loading message list for Maildir[Archive]
 Message list for Maildir[Archive] loaded: 0 messages
 Loading message list for IMAP[Archive]
 Syncing messages IMAP[Archive] -> Maildir[Archive]
 Syncing messages Maildir[Archive] -> IMAP[Archive]
 []: Not syncing filtered folder 'Drafts'[unibe-remote]
 []: Not syncing filtered folder 'INBOX'[unibe-remote]
 []: Not syncing filtered folder 'Junk'[unibe-remote]
 []: Not syncing filtered folder 'Sent'[unibe-remote]
 []: Not syncing filtered folder 'Synchronisierungsprobleme'[unibe-remote]
 []: Not syncing filtered folder 'Synchronisierungsprobleme/Konflikte'[unibe-remote]
 []: Not syncing filtered folder 'Synchronisierungsprobleme/Lokale Fehler'[unibe-remote]
 []: Not syncing filtered folder 'Synchronisierungsprobleme/Serverfehler'[unibe-remote]
 []: Not syncing filtered folder 'Trash'[unibe-remote]
 []: Not syncing filtered folder 'Unsent Messages'[unibe-remote]
 *** Finished account 'unibe' in 0:23

**Comment by nicolas33** [comment]
Do you have the same results with v7.1.1?

**Comment by einlandarzt** [comment]
I don't know, haven't tried. I installed via apt-get and Ubuntu 17.04.

**Comment by nicolas33** [comment]
It's possible to install offlineimap as a user: remove the currently installed offlineimap and download the zip (or `git clone` the repository). Then `./offlineimap.py [options]`.

**Comment by einlandarzt** [comment]
Just tried v7.1.1, the problem is still present.

**Comment by nicolas33** [comment]
Please, try this patched version: 520a3b0 with `-d imap`. We should get more info.

**Comment by einlandarzt** [comment]
OfflineIMAP 7.1.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.55 (system), Python v2.7.13, OpenSSL 1.0.2g  1 Mar 2016
Debug mode: Forcing to singlethreaded.
Now debugging for imap: IMAP protocol debugging
Now debugging for : Other offlineimap related sync messages
Account sync unibe:
 [imap]: Using authentication mechanisms ['GSSAPI', 'XOAUTH2', 'CRAM-MD5', 'PLAIN', 'LOGIN']
 *** Processing account unibe
 Establishing connection to localhost:1143 (unibe-remote)
 [imap]: Attempting LOGIN authentication
 [imap]: Attempting IMAP LOGIN authentication
 []: Filtering out 'Trash'[unibe-remote] due to folderfilter
 []: Filtering out 'Drafts'[unibe-remote] due to folderfilter
 []: Filtering out 'INBOX'[unibe-remote] due to folderfilter
 []: Filtering out 'Junk'[unibe-remote] due to folderfilter
 []: Filtering out 'Unsent Messages'[unibe-remote] due to folderfilter
 []: Filtering out 'Sent'[unibe-remote] due to folderfilter
 []: Filtering out 'Synchronisierungsprobleme'[unibe-remote] due to folderfilter
 []: Filtering out 'Synchronisierungsprobleme/Konflikte'[unibe-remote] due to folderfilter
 []: Filtering out 'Synchronisierungsprobleme/Lokale Fehler'[unibe-remote] due to folderfilter
 []: Filtering out 'Synchronisierungsprobleme/Serverfehler'[unibe-remote] due to folderfilter
 []: Copying folder structure from unibe-remote to unibe-local
 Syncing Archive: IMAP -> Maildir
 Loading message list for Maildir[Archive]
 Message list for Maildir[Archive] loaded: 0 messages
 Loading message list for IMAP[Archive]
 [imap]: [unibe-remote]Archive: _msgs_to_fetch(): min_date None, min_uid None
 [imap]: [unibe-remote]Archive: _msgs_to_fetch: folder looks empty
 Message list for IMAP[Archive] loaded: 0 messages
 Syncing messages IMAP[Archive] -> Maildir[Archive]
 Syncing messages Maildir[Archive] -> IMAP[Archive]
 []: Not syncing filtered folder 'Drafts'[unibe-remote]
 []: Not syncing filtered folder 'INBOX'[unibe-remote]
 []: Not syncing filtered folder 'Junk'[unibe-remote]
 []: Not syncing filtered folder 'Sent'[unibe-remote]
 []: Not syncing filtered folder 'Synchronisierungsprobleme'[unibe-remote]
 []: Not syncing filtered folder 'Synchronisierungsprobleme/Konflikte'[unibe-remote]
 []: Not syncing filtered folder 'Synchronisierungsprobleme/Lokale Fehler'[unibe-remote]
 []: Not syncing filtered folder 'Synchronisierungsprobleme/Serverfehler'[unibe-remote]
 []: Not syncing filtered folder 'Trash'[unibe-remote]
 []: Not syncing filtered folder 'Unsent Messages'[unibe-remote]
 *** Finished account 'unibe' in 0:23

**Comment by nicolas33** [comment]
Ok, we get `[imap]: [unibe-remote]Archive: _msgs_to_fetch: folder looks empty`, so the select seems to pretend there is no message.

Please, try the d14406f version so we show the returned response from the server.

**Comment by einlandarzt** [comment]
OfflineIMAP 7.1.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.55 (system), Python v2.7.13, OpenSSL 1.0.2g  1 Mar 2016
Debug mode: Forcing to singlethreaded.
Now debugging for imap: IMAP protocol debugging
Now debugging for : Other offlineimap related sync messages
Account sync unibe:
 [imap]: Using authentication mechanisms ['GSSAPI', 'XOAUTH2', 'CRAM-MD5', 'PLAIN', 'LOGIN']
 *** Processing account unibe
 Establishing connection to localhost:1143 (unibe-remote)
 [imap]: Attempting LOGIN authentication
 [imap]: Attempting IMAP LOGIN authentication
 []: Filtering out 'Trash'[unibe-remote] due to folderfilter
 []: Filtering out 'Drafts'[unibe-remote] due to folderfilter
 []: Filtering out 'INBOX'[unibe-remote] due to folderfilter
 []: Filtering out 'Junk'[unibe-remote] due to folderfilter
 []: Filtering out 'Unsent Messages'[unibe-remote] due to folderfilter
 []: Filtering out 'Sent'[unibe-remote] due to folderfilter
 []: Filtering out 'Synchronisierungsprobleme'[unibe-remote] due to folderfilter
 []: Filtering out 'Synchronisierungsprobleme/Konflikte'[unibe-remote] due to folderfilter
 []: Filtering out 'Synchronisierungsprobleme/Lokale Fehler'[unibe-remote] due to folderfilter
 []: Filtering out 'Synchronisierungsprobleme/Serverfehler'[unibe-remote] due to folderfilter
 []: Copying folder structure from unibe-remote to unibe-local
 Syncing Archive: IMAP -> Maildir
 Loading message list for Maildir[Archive]
 Message list for Maildir[Archive] loaded: 0 messages
 Loading message list for IMAP[Archive]
 [imap]: [unibe-remote]Archive: _msgs_to_fetch(): min_date None, min_uid None
 [imap]: [unibe-remote]Archive: _msgs_to_fetch(): res_type is ''OK'', imapdata is '[None]'
 [imap]: [unibe-remote]Archive: _msgs_to_fetch(): folder looks empty
 Message list for IMAP[Archive] loaded: 0 messages
 Syncing messages IMAP[Archive] -> Maildir[Archive]
 Syncing messages Maildir[Archive] -> IMAP[Archive]
 []: Not syncing filtered folder 'Drafts'[unibe-remote]
 []: Not syncing filtered folder 'INBOX'[unibe-remote]
 []: Not syncing filtered folder 'Junk'[unibe-remote]
 []: Not syncing filtered folder 'Sent'[unibe-remote]
 []: Not syncing filtered folder 'Synchronisierungsprobleme'[unibe-remote]
 []: Not syncing filtered folder 'Synchronisierungsprobleme/Konflikte'[unibe-remote]
 []: Not syncing filtered folder 'Synchronisierungsprobleme/Lokale Fehler'[unibe-remote]
 []: Not syncing filtered folder 'Synchronisierungsprobleme/Serverfehler'[unibe-remote]
 []: Not syncing filtered folder 'Trash'[unibe-remote]
 []: Not syncing filtered folder 'Unsent Messages'[unibe-remote]
 *** Finished account 'unibe' in 0:24

**Comment by nicolas33** [comment]
That's weird. The server pretends there is no email in this folder.

**Comment by einlandarzt** [comment]
Weird. The folder is full of messages, they are accessible from webmail (can show you a screenshot).

**Comment by nicolas33** [comment]
I wonder this is because the Archive folder is marked \Archive special folder so the server do not expose the messages in the SELECT command.

A workaround could be to disable the special \Archive meaning on the server (if possible) or to duplicate/move the content to another folder.

**Comment by einlandarzt** [comment]
Hm, I actually have the same issue with the Sent-folder (and all other folders), so I'm not sure about this suggestion. Currently, the only folder that is correctly synced is Inbox.

**Comment by nicolas33** [comment]
Another workaround might be to use Davmail. We have recent changes to improve support of Davmail in the current `next` branch. Patches will be included in the next release planned to this week-end or next week.

Do you know what's the IMAP server exactly? What's the output of `offlineimap -a unibe --info`?

**Comment by einlandarzt** [comment]
I am actually using davmail already. I connect to my local davmail app.

**Comment by einlandarzt** [comment]
OfflineIMAP 7.1.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.55 (system), Python v2.7.13, OpenSSL 1.0.2g  1 Mar 2016
  imaplib2: 2.55 (system)
Remote repository 'unibe-remote': type 'IMAP'
Host: localhost Port: 1143 SSL: False
Establishing connection to localhost:1143 (unibe-remote)
Server welcome string: * OK [CAPABILITY IMAP4REV1 AUTH=LOGIN MOVE] IMAP4rev1 DavMail 4.7.3-trunk server ready
Server capabilities: ('IMAP4REV1', 'AUTH=LOGIN', 'MOVE')

Folderlist:
 Archive
 Drafts
 INBOX
 Junk
 Sent
 Synchronisierungsprobleme
 Synchronisierungsprobleme/Konflikte
 Synchronisierungsprobleme/Lokale Fehler
 Synchronisierungsprobleme/Serverfehler
 Trash
 Unsent Messages

Local repository 'unibe-local': type 'Maildir'
Folderlist:
 Synchronisierungsprobleme.Serverfehler
 Archive
 Drafts
 Synchronisierungsprobleme.Konflikte
 Unsent Messages
 Synchronisierungsprobleme
 INBOX
 Trash
 Junk
 Sent
 Synchronisierungsprobleme.Lokale Fehler

**Comment by nicolas33** [comment]
Please read #479 and check you Keepalive configuration option in Davmail.

**Comment by einlandarzt** [comment]
Thank you so much, I think that was it! Sorry for not having realized that this issue had been brought up already.

**Comment by nicolas33** [comment]
Thanks for the report. I've improved the FAQ.

**Comment by nicolas33** [comment]
BTW, you might really run with the current `next` branch until the next release is out.
