### ISSUE TITLE
Request for reviewers

### ISSUE THREAD

**Issue by nicolas33** [OfflineIMAP/offlineimap#487]
Github has introduced a new feature for reviewers.

  https://help.github.com/articles/about-codeowners/

If you'd like to be a reviewer on pull requests, please send me the lines you'd like to have in the CODEOWNERS file. The format is the path to track followed by your github username (or email address added to the github account).

Here's a sample:
```
* @nicolas33
offlineimap* @nicolas33 @you
```

Code review is good. ,-)

**Comment by chris001** [comment]
Would be great to send Piers notifications for `offlienimap/bundled_imaplib2.py  piers@janeelix.com`.
You can add my username ` @chris001` also.

**Comment by chris001** [comment]
It looks like `bundled_imaplib2.py` here is set to 2.55.
https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap/virtual_imaplib2.py
Should it match the version in `bundled_imaplib2.py` 2.57 ?

**Comment by nicolas33** [comment]
I think that if Piers want to be notified he will request us. ,-)

Ok to increase the imaplib2 requirement: done. I've added your username to the CODEOWNERS file.

Thank you.
