### ISSUE TITLE
can't delete from gmail?

### ISSUE THREAD

**Issue by jungle-boogie** [OfflineIMAP/offlineimap#489]
#### General informations

- system/distribution (with version):
OpenBSD -current

- offlineimap version (`offlineimap -V`): 
offlineimap v7.1.2, imaplib2 v2.57 (bundled), Python v2.7.13, LibreSSL 2.6.0

- Python version:
Python 2.7.13 (default, Aug 10 2017, 22:12:37)

- server name or domain: 
- CLI options: 

#### Configuration file offlineimaprc

```
[general]
accounts = personal

[Account personal]
localrepository = personal-local
remoterepository = personal-remote

[Repository personal-local]
type = Maildir
localfolders = ~/mail/
# Spaces in pathname are bad. Lets use `archive` which is a simple word
# Besides, we only need `All Mail` folder.
# Sup would manage mails on its own.
# If your GMail language setting is not English, you can execute
# `offlineimap --info` to find out the name of folder which is
# translated and encoded after your account is configured.
nametrans = lambda folder: {'archive': '[Gmail]/All Mail',
                            }.get(folder, folder)
sync_deletes = yes

[Repository personal-remote]
# IMAP with hardcoded GMail config
type = Gmail
synclabels = yes
labelsheader = openbsd-misc
# The path of ca-certfile might be different on your system.
sslcacertfile = /etc/ssl/cert.pem
# Remember that GMail requires full mail address as username
remoteuser = trump@gmail.com
remotepass = 
nametrans = lambda folder: {'[Gmail]/All Mail': 'archive',
                            }.get(folder, folder)
folderfilter = lambda folder: folder == '[Gmail]/All Mail'
sync_deletes = yes

```

#### Logs, error

```
$ offlineimap
OfflineIMAP 7.1.2
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.13, LibreSSL 2.6.0
Account sync personal:
 *** Processing account personal
 Establishing connection to imap.gmail.com:993 (personal-remote)
Folder archive [remote name [Gmail]/All Mail] [acc: personal]:
 Syncing [Gmail]/All Mail: Gmail -> Maildir
 Deleting 9 messages (136209,136217:136218,136229,136407,136489,136530:136531,136559) in Gmail[[Gmail]/All Mail]
Account sync personal:
 *** Finished account 'personal' in 1:10
```

Above we see emails are deleted via mutt, synced with `offlineimap`, but in the gmail account, the emails are surprisingly still present.

All I would like to do is delete emails with mutt and have them actually removed from the mailbox.

What's the best way to accomplish this?

**Comment by chris001** [comment]
The delete in Gmail is actually a flag, the message doesn't move anywhere, it just appears to.  When you delete a message it is supposed to add the flag "Trash" and by doing this the message appears in Gmail to have moved to the `Trash` folder.

**Comment by nicolas33** [comment]
AFAIR, Google does **not** allow deletions in `[Gmail]/All Mail`.

**Comment by jungle-boogie** [comment]
So do I need something like this to delete mail?

```
sync_deletes = yes
set trash = "+[Google Mail]/Trash"
realdelete=yes
```

**Comment by nicolas33** [comment]
There's nothing we can do for this folder. It's a server side limitation.

**Comment by chris001** [comment]
@nicolas33   As you know it's complicated with Gmail they make you go thru multiple layers of effort to truly delete a message because they don't like to destroy potentially searchable information, but here's a conversation where a user of Thunderbird was able to configure the settings in Gmail web interface "Immediately delete the message forever" and folder subscriptions, to get the delete to work over IMAP.
http://forums.mozillazine.org/viewtopic.php?f=39&t=2694887

**Comment by chris001** [comment]
@nicolas33   As you know it's complicated with Gmail they make you go thru multiple layers of effort to truly delete a message because they don't like to destroy potentially searchable information, but here's a conversation where a user of Thunderbird was able to configure the settings in Gmail web interface "Immediately delete the message forever" and folder subscriptions, to get the delete to work over IMAP.
http://forums.mozillazine.org/viewtopic.php?f=39&t=2694887

**Comment by jungle-boogie** [comment]
Unfortunately, that doesn't seem to work in mutt. I still only have `Gmail[[Gmail]/All Mail]` appearing when I delete an email.

Can you show be a config with trash listed?

**Comment by nicolas33** [comment]
We have this comment in `offlineimap/folder/Gmail.py`:
```
    Removing a message from a folder will only remove the "label" from
    the message and keep it in the "All mails" folder. To really delete
    a message it needs to be copied to the Trash folder. However, this
    is dangerous as our folder moves are implemented as a 1) delete in
    one folder and 2) append to the other. If 2 comes before 1, this
    will effectively delete the message from all folders. So we cannot
    do that until we have a smarter folder move mechanism.

    For more information on the Gmail IMAP server:
      http://mail.google.com/support/bin/answer.py?answer=77657&topic=12815
      https://developers.google.com/google-apps/gmail/imap_extensions
```

The support for realdelete was removed for Gmail because this could lead to dataloss.

**Comment by nicolas33** [comment]
The best is to folderfilter `All Mail`.

**Comment by asdf8dfafjk** [comment]
@chris001 i have auto expunge off + immediately delete permanently in my Gmail settings and sync_deletes in my offlineimap settings. When i delete and run offlineimap, it says deleting id 767, when i rerun offlineimap, it says copying id 767. Do you know what would help?

**Comment by chris001** [comment]
@asdf8dfafjk Can you "folderfiler" the `All Mail` folder, so that your `offlineimap` will not see that folder on the Gmail server, therefore, not try to copy messages from `All Mail` to your local machine folder `All Mail`...?
