### ISSUE TITLE
INBOX is not synced with Exchange server behind davmail

### ISSUE THREAD

**Issue by shiquanwang** [OfflineIMAP/offlineimap#49]
The Exchange server in my company has no IMAP.
So I use davmail (port 1143) to work as a bridge and sync the exchange email to a local dovecot (port 143).

However all folders are synced well except the INBOX.
The output of ttyui is
````
shiquanwang@las-z820:~$ offlineimap -a Davmail
OfflineIMAP 6.5.4
  Licensed under the GNU GPL v2+ (v2 or any later version)
Account sync Davmail:
 *** Processing account Davmail
 Establishing connection to localhost:1143
 Establishing connection to localhost:143
 Creating folder INBOX/test[LocalDav]
Folder INBOX/test [acc: Davmail]:
 Creating new Local Status db for LocalDav:INBOX.test
Folder INBOX [acc: Davmail]:
 Creating new Local Status db for LocalDav:INBOX
Folder INBOX/test [acc: Davmail]:
 Syncing INBOX/test: IMAP -> MappedIMAP
Folder INBOX [acc: Davmail]:
 Syncing INBOX: IMAP -> MappedIMAP
Folder INBOX/test [acc: Davmail]:
 Copy message 1 (1 of 1) RemoteDav:INBOX/test -> LocalDav
Account sync Davmail:
 *** Finished account 'Davmail' in 0:43
````

If there is a sub-folder under INBOX, the first run of offlineimap is OK.
The second run will give the error:
````
shiquanwang@las-z820:~$ offlineimap -a Davmail
OfflineIMAP 6.5.4
  Licensed under the GNU GPL v2+ (v2 or any later version)
Account sync Davmail:
 *** Processing account Davmail
 Establishing connection to localhost:1143
 Establishing connection to localhost:143
 Creating folder INBOX/test[LocalDav]
 ERROR: Creating folder INBOX/test on repository LocalDav
  Folder 'INBOX/test'[LocalDav] could not be created. Server responded: ('NO', ['[ALREADYEXISTS] Mailbox already exists'])
 ERROR: Folder 'INBOX/test'[LocalDav] could not be created. Server responded: ('NO', ['[ALREADYEXISTS] Mailbox already exists'])
 *** Finished account 'Davmail' in 0:11
ERROR: Exceptions occurred during the run!
ERROR: Creating folder INBOX/test on repository LocalDav
  Folder 'INBOX/test'[LocalDav] could not be created. Server responded: ('NO', ['[ALREADYEXISTS] Mailbox already exists'])
ERROR: Folder 'INBOX/test'[LocalDav] could not be created. Server responded: ('NO', ['[ALREADYEXISTS] Mailbox already exists'])
````

**Comment by nicolas33** [comment]
First, I don't get why so many users try to sync IMAP servers with Dovecot when the latter provides such tool : http://wiki2.dovecot.org/Tools/Doveadm/Sync.

Other than that, why davmail does not provide the exisiting folders in the first place? I mean, OfflineIMAP won't try to create existing folders if the IMAP server correctly provide them.

**Comment by secomi** [comment]
I also do have the same problem. When behing davmail, the INBOX, is not synced. 
Although checking davmail logs, all the mails are seen:

I am using OfflineIMAP7.1.1

The sync is not happening. 
The workaround mentioned by shiquanwang works. But I wanted to check if in the recent years they was a new particular option in the configuration files?


[logDavmail.txt](https://github.com/OfflineIMAP/offlineimap/files/1066328/logDavmail.txt)

Thanks

**Comment by nicolas33** [comment]
Could you open a new issue, please?

**Comment by secomi** [comment]
Sure, #479 has been opened with hopefuly all the requested information details.
