### ISSUE TITLE
synclabels question

### ISSUE THREAD

**Issue by jungle-boogie** [OfflineIMAP/offlineimap#490]
#### General informations

- system/distribution (with version): 
OpenBSD -current

- offlineimap version (`offlineimap -V`): 
offlineimap v7.1.2, imaplib2 v2.57 (bundled), Python v2.7.13, LibreSSL 2.6.0

- Python version: 
Python 2.7.13 (default, Aug 10 2017, 22:12:37)

#### Configuration file offlineimaprc

```
[general]
accounts = personal


[Account personal]
localrepository = personal-local
remoterepository = personal-remote

[Repository personal-local]
type = Maildir
localfolders = ~/mail/

[Repository personal-remote]
type = Gmail
synclabels = yes
labelsheader = X-Keywords
sslcacertfile = /etc/ssl/cert.pem
remoteuser = trump@gmail.com
remotepass = 
sync_deletes = yes
realdelete= yes

```

### question

My config is now much simpler than before.

This appears to have created many directories in `~/mail/` when offlineimap was started:
```
...
tinc
tmux
virtualization
voiceops
wireshark
```
However, when I open mutt and navigate to the various directories, there is no mail. The only one with mail is `[Gmail].Important/`

So does synclabels only create the directories but it keeps them empty and everything goes into Important? Previously this was `All Mail`.

Do I need the name translation thing setup on each and every label I have so offlineimap can move it into the correct directory?

If that's the case, could you please show me an offlineimaprc file with the few labels above?

**Comment by nicolas33** [comment]
Was the sync done cleanly? What happens on next sync?

Each email is a file in the "cur" sub-directory. So, it's easy to know how many emails are in your maildirs.

**Comment by nicolas33** [comment]
"cur" or "new" or "tmp", BTW.

**Comment by jungle-boogie** [comment]
Hi @nicolas33,

It's far from being completed, as it needs to download many, many emails. Once it's completed, should the emails go in the correct labeled directory?

in the important cur directory, there's already over 1000, but these have labels of other labels.

for instance, wireshark emails are in important/cur and not in wireshark/cur.

**Comment by nicolas33** [comment]
AFAIR, Gmail labels are exposed like folders to the IMAP clients. So yes, offlineimap should have the emails in the local folders.

It's correct to have emails downloaded for some labels while still missing in other folders when the sync is not done, yet.

**Comment by jungle-boogie** [comment]
I also see `/home/jungle/.offlineimap/Account-personal/LocalStatus-sqlite` has a database for each gmail label, but only the labels above have any data in the databases, as expected.

**Comment by nicolas33** [comment]
News here?

**Comment by jungle-boogie** [comment]
I think it'll be good, just slow.

I don't have internet at my new location yet, so I can't re-connect and download mail.
