### ISSUE TITLE
documentation should mention direction

### ISSUE THREAD

**Issue by LaszloHont** [OfflineIMAP/offlineimap#491]
#### General informations
It's not clear in any of the documentation I have read if changes to the local copy of an offlineimap sync from an imap server will affect the imap server.

```
$ whatis offlineimap
offlineimap (1)      - Synchronize mailboxes and Maildirs
```

All of the documentation I have read about backing up gmail never assumes the sync is one way, but the man page doesn't explicitly say this.

- system/distribution (with version): 
- offlineimap version (`offlineimap -V`): 
- Python version: 
- server name or domain: 
- CLI options: 

#### Configuration file offlineimaprc

```
REMOVE PRIVATE DATA.
```

#### pythonfile (if any)

```
REMOVE PRIVATE DATA.
```

#### Logs, error

```
REMOVE PRIVATE DATA.
```

#### Steps to reproduce the error

- 
-

**Comment by nicolas33** [comment]
offlineimap does both ways sync by default. It can sync one either way, too.

**Comment by nicolas33** [comment]
Thanks for your report: http://www.offlineimap.org/doc/offlineimap.html

**Comment by LaszloHont** [comment]
Thanks. Maybe I am skim reading too fast, but which option forces the sync to only happen one way?

**Comment by LaszloHont** [comment]
(the reason I noticed this was because my gmail sync is getting its deleted labels back!)

**Comment by nicolas33** [comment]
Getting one way sync is done by setting one side read only (the `readonly` configuration option).

https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf

**Comment by LaszloHont** [comment]
Excellent thank you. I searched for so many thanks, but not 1-way (although I did search for direction, "one way")
