### ISSUE TITLE
can't connect to outlook.com via imap

### ISSUE THREAD

**Issue by Offerel** [OfflineIMAP/offlineimap#492]
When I try to connect to Outlook.com via imap, I get the following error:

OfflineIMAP 7.0.12
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync main:
 *** Processing account main
 Establishing connection to imap-mail.outlook.com:993 (main-microsoft)
 PLAIN authentication failed: AUTHENTICATE failed.
 LOGIN authentication failed: LOGIN failed.
 ERROR: All authentication types failed:
        PLAIN: AUTHENTICATE failed.
        LOGIN: LOGIN failed.
 *** Finished account 'main' in 0:02
ERROR: Exceptions occurred during the run!
ERROR: All authentication types failed:
        PLAIN: AUTHENTICATE failed.
        LOGIN: LOGIN failed.

Traceback:
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 278, in syncrunner
    self.__sync()
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 341, in __sync
    remoterepos.getfolders()
  File "/usr/share/offlineimap/offlineimap/repository/IMAP.py", line 452, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/usr/share/offlineimap/offlineimap/imapserver.py", line 540, in acquireconnection
    self.__authn_helper(imapobj)
  File "/usr/share/offlineimap/offlineimap/imapserver.py", line 415, in __authn_helper
    "failed:\n\t%s"% msg, OfflineImapError.ERROR.REPO)

I have the following config:

[Repository main-microsoft]
type = IMAP
remotehost = imap-mail.outlook.com
remoteuser = mymail@outlook.com
remotepass = my password
folderfilter = lambda foldername: foldername in ["Junk"]
ssl = yes
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
maxconnections = 4
auth_mechanisms = GSSAPI, CRAM-MD5, PLAIN, LOGIN

What I'm doing wrong?

**Comment by nicolas33** [comment]
Do you have the same issue with the latest v7.1.2?

It's possible to install offlineimap as a user: remove the currently installed offlineimap and download the zip (or `git clone` the repository). Then `./offlineimap.py [options]`.

**Comment by nicolas33** [comment]
What if you comment out the `auth_mechanisms` configuration option?

**Comment by Offerel** [comment]
It's the same problem with 7.1.2. I use the older version, since this is the version for Debian 9.

If I set # before the auth_mechanisms line, I get the same error with 7.1.2. but with 7.0.12 I get something about xoauth.

**Comment by nicolas33** [comment]
I wonder there's a character wrongly interpreted in the password. Could you try with a temporary simple alphabetic password?

**Comment by Offerel** [comment]
Ahhhh that was the Problem!!! Many many thx. For the other Account i use a Password with some higer ANSI Signs. Since offlineimap has thrown a error about this, i have set all passwords between 2 ' Signs. This seems to be missinterpreted by offlineimap. I have now corrected this in my settings and now i could login to both accounts. Thats now my working configuration for outlook.com:

```
[Repository main-microsoft]                                                                                                                                                    
type = IMAP                                                                                                                                                                    
remotehost = imap-mail.outlook.com                                                                                                                                             
remoteuser = mymail@outlook.com                                                                                                                                       
remotepass = mypassword                                                                                                                                                  
folderfilter = lambda foldername: foldername in ["Junk"]                                                                                                                       
ssl = yes                                                                                                                                                                      
sslcacertfile = /etc/ssl/certs/ca-certificates.crt                                                                                                                             
maxconnections = 4                                                                                                                                                                                                                                                                                          
nametrans = lambda folder: re.sub('Junk', 'Spam', folder)   
```

Many thy for your fast help.

**Comment by nicolas33** [comment]
Thank you for your feedback!
