### ISSUE TITLE
Synchronisation error "[ALREADYEXISTS] folder already exists"

### ISSUE THREAD

**Issue by fwolfst** [OfflineIMAP/offlineimap#496]
#### General informations

Synchronisation fails in my case with the message that a folder already exists. In my understanding this should not be a problem per se. I could imagine that there is some encoding issue (in comparing folder names), as the user in question is german.

Is there any way that I can at least work around that issue (I dont car if I have to create folders by hand or such stuff, it is a one-time migration, not a regular synchronisation process)?

- system/distribution (with version): 
uname -a: `Linux 7linden 2.6.32-55-server #117-Ubuntu SMP Tue Dec 3 17:45:11 UTC 2013 x86_64 GNU/Linux` (thats a ubuntu 10.04 dinosaur)
- offlineimap version (`offlineimap -V`): `offlineimap v7.1.2, imaplib2 v2.57 (bundled), Python v2.6.5`
- Python version: `Python 2.6.5`
- server name or domain: 1&1
- CLI options: `-c configfile`

#### Configuration file offlineimaprc

```
[general]
accounts = br

[Account br]
localrepository = imap_br_org
remoterepository = imap_br_nr
synclabels = yes
labelsheader = X-Keywords
ssl = no

[Repository imap_br_nr]
#This is the remote repository
type = IMAP
remotepass = pass
remoteuser = user
remotehost = 192.168.12.16
folderfilter = lambda folder: folder not in ['Junk']
ssl = no

[Repository imap_br_org]
#This is the local repository
type = IMAP
remotepass = pass
remoteuser = user@server.org
remotehost = imap.1und1.de 
ssl = no

```
#### Logs, error
**Folder names changed for privacy reasons - I do not SEE any specific special characters or so in the folder name and a lot of other folders with special characters in their names were created successfully before**
```
 Creating folder Archives/A Folder6/B/C and D  - Rather Long name[imap_br_org]
 ERROR: Creating folder Archives/A Folder6/B/C and D  - Rather long name on repository imap_br_org
  Folder 'Archives/A Folder6/B/C and D  - Rather long name'[imap_br_org] could not be created. Server responded: ('NO', ['[ALREADYEXISTS] folder already exists'])
 ERROR: Folder 'Archives/A Folder6/B/C and D  - Rather long name'[imap_br_org] could not be created. Server responded: ('NO', ['[ALREADYEXISTS] folder already exists'])
 *** Finished account 'br' in 0:11
ERROR: Exceptions occurred during the run!
ERROR: Creating folder Archives/A Folder6/B/C and D  - Rather long name on repository imap_br_org
  Folder 'Archives/A Folder6/B/C and D  - Rather long name'[imap_br_org] could not be created. Server responded: ('NO', ['[ALREADYEXISTS] folder already exists'])

Traceback:
  File "offlineimap-7.1.2/offlineimap/repository/Base.py", line 204, in sync_folder_structure
    local_repo.makefolder(local_name)
  File "offlineimap-7.1.2/offlineimap/repository/IMAP.py", line 563, in makefolder
    OfflineImapError.ERROR.FOLDER)
```
#### Steps to reproduce the error

- Just running offlineimap with the given servers and config file ...

**Comment by nicolas33** [comment]
> Is there any way that I can at least work around that issue (I dont car if I have to create folders by hand or such stuff, it is a one-time migration, not a regular synchronisation process)?

Your might like to mark the remote readonly. See the [configuration file](https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf).

**Comment by fwolfst** [comment]
Thanks for your quick reply @nicolas33 , but I think I dont grasp it.

> Your might like to mark the remote readonly. See the configuration file.

I'll try later, with a new backup first. But to me that sounds as if then I would one-way-only-snychronize (FROM remote TO local). I want it the other way around ... I want local mails (old server) been copied to the remote server (new).

**Comment by nicolas33** [comment]
There might be a bug, then. It's not expected to attempt to create a folder when in readonly.

**Comment by nicolas33** [comment]
The issue was about the local IMAP side. This is know issue #335. Hence, I'm closing this one.

**Comment by fwolfst** [comment]
yes, and thanks a lot! I did not find that issue.
