### ISSUE TITLE
Interplay of IMAP folder name encoding and configurable operations

### ISSUE THREAD

**Issue by uliska** [OfflineIMAP/offlineimap#497]
Starting from #299 I have begun working on a configuration option to replace `decodefoldernames` that will provide proper two-way support for converting utf-7 encoded IMAP names to and from utf-8.

In the course of discussion the question was raised whether enabling this option could affect side-effects on existing installations using `decodefoldernames` (see https://github.com/OfflineIMAP/offlineimap/issues/299#issuecomment-332027856).

Investigating this I realized that by default *all* operations like `folderfilter`, `nametrans` etc. currently work on the original IMAP names. This means for example that in order to filter a folder `INBOX.Fächer` I will have to define 

```
folderfilter = lambda name: name == 'INBOX.F&AOQ-cher'
```

The same is true for any `nametrans` functions. If `decodefoldernames` is enabled it will work *after* the `nametrans`, so `nametrans` must work on the original IMAP names.

This makes me somehow wonder if anyone is using any of this at all because I find it pretty awkward to define filters and functions while having to use the UTF-7 encodings to specify them.

---

The underlying reason I'm asking this is: If I implement proper UTF-8 support for IMAP folder names this will do the reencoding at the very first moment when a folder representation is created, so *everything* that is done to process IMAP folder names would then (if the option is enabled on the current account) work on the UTF-8 encoded name.

I think this is definitely an improvement - but it might break any configuration file that uses any of the text processing functionality, at least if any non-ASCII folder names are involved.

**Comment by nicolas33** [comment]
> This makes me somehow wonder if anyone is using any of this at all because I find it pretty awkward to define filters and functions while having to use the UTF-7 encodings to specify them.

Yes, many people use those features.

**Comment by nicolas33** [comment]
> The underlying reason I'm asking this is: If I implement proper UTF-8 support for IMAP folder names this will do the reencoding at the very first moment when a folder representation is created, so everything that is done to process IMAP folder names would then (if the option is enabled on the current account) work on the UTF-8 encoded name.

This would break the FMD5, too. I wonder the best path is to encode/decode just before and after those functions.

**Comment by uliska** [comment]
> This would break the FMD5, too.

I'm not sure about that. *(Disclaimer: I can't claim to have understood all parts of the code yet, I try to be serious about considering the code that I find and possible implications, so I don't want to "rush through" my ideas. But of course I can proceed only step by step.)*

What happens if someone enables the new `utf8foldernames` setting for an existing and already synced account?

##### a) previously `decodefoldernames` was used
In this case I'm quite sure nothing would change: The FMD5 value of a folder name is created with

```python
self._foldermd5 = md5(self.getvisiblename()).hexdigest()
```
in `MaildirFolder`'s `__init__()`.

The result of `self.getvisiblename()` includes the application of `decode_mailbox_name()` and any nametrans function, so there should be no difference between using the old or the new option.

##### b) previously `decodefoldernames` was not used

In this case not only the MD5 value but the local folder name will have changed (e.g. from `Sp&AOQ-ter` to `Später`). This will break things, yes. There will be a different local folder name, which will sort-of break the synchronization. But within that new folder the MD5 value should be correct again. So what will happen is that a new folder is created with the utf-8 name, next to the old utf-7 name, and depending on the config the old folder is deleted or not.
The thing that could happen is if between the last "old" and the first "new" synchronization a local MUA has changed anything in the affected folder. These changes would not be properly synchronized anymore. So this is something that should be documented to be avoided.

**BUT:** I think changing an existing synchronization pair from utf-7 to utf-8 encoded local folder names is just not an option anyway. Who would want to do that, it just doesn't make sense? There will inevitably be duplicate or renamed folders anyway.

**I think that anyone who wants to make use of a new utf-8 option for bidirectional sync will have to create a new sync pair and download all the mail from the IMAP server again.**

The new `utf8foldernames` is an option that will in no case be enabled automatically by updating the software, so I think worries about users reading changelogs aren't necessary. IMO it's sufficient to put all necessary explanations and warnings, especially regarding side-effects to existing sync pairs in the documentation of the new function. 

It would be good if someone could confirm or challenge this consideration.

**Comment by nicolas33** [comment]
> I think that anyone who wants to make use of a new utf-8 option for bidirectional sync will have to create a new sync pair and download all the mail from the IMAP server again.

Yes.

> The new utf8foldernames is an option that will in no case be enabled automatically by updating the software, so I think worries about users reading changelogs aren't necessary. IMO it's sufficient to put all necessary explanations and warnings, especially regarding side-effects to existing sync pairs in the documentation of the new function.

Ok.

**Comment by nicolas33** [comment]
> I'm not sure about that.

To make it clear, you're right that FMD5 won't be broken because the Maildir in UTF-8 is not the same.

**Comment by nicolas33** [comment]
@uliska Thanks for your PR. Since it's merged, I'm closing this issue. I guess the best will be to open new issues if needed.
