### ISSUE TITLE
first time merely running "offlineimap", python errors ...

### ISSUE THREAD

**Issue by evanescente-ondine** [OfflineIMAP/offlineimap#511]
It's my first time runnning offlineimap. I am working toward fetching some of my mail from an IMAP server, look into their bodies, and feed a database with infos from them.
But: I know nothing about python, so I don't get a line of anything below.

offlineimap v7.0.12, imaplib2 v2.55 (system), Python 
Linux debian 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
- Python version: how ?
- CLI options: none

=> offlineimap
Traceback (most recent call last):
  File "/usr/bin/offlineimap", line 23, in <module>
    oi.run()
  File "/usr/share/offlineimap/offlineimap/init.py", line 78, in run
    options, args = self.__parse_cmd_options()
  File "/usr/share/offlineimap/offlineimap/init.py", line 255, in __parse_cmd_options
    config.set_if_not_exists('general', 'dry-run', 'False')
  File "/usr/share/offlineimap/offlineimap/CustomConfig.py", line 135, in set_if_not_exists
    self.set(section, option, value)
  File "/usr/lib/python2.7/ConfigParser.py", line 753, in set
    ConfigParser.set(self, section, option, value)
  File "/usr/lib/python2.7/ConfigParser.py", line 396, in set
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'general'

**Comment by nicolas33** [comment]
> Python version: how ?

`python --version`



> ConfigParser.NoSectionError: No section: 'general'

You have to create a configuration file that offlineimap will read to know your accounts and options. There are good kick starter like https://wiki.archlinux.org/index.php/OfflineIMAP .

**Comment by mimi1vx** [comment]
/usr/lib/python2.7 - so something from python-2.7.x , in general problem with missing config --> needs catch raise NoSectionError(section) and print to USER: you dont have any config, please configure me

**Comment by nicolas33** [comment]
Please, share your configuration file here (remove private data).
