### ISSUE TITLE
Syncing data from local to remote fails when maxage is set

### ISSUE THREAD

**Issue by shubhamkrm** [OfflineIMAP/offlineimap#512]
#### General informations

- system/distribution (with version): ubuntu 17.10
- offlineimap version (`offlineimap -V`): offlineimap v7.1.2, imaplib2 v2.57 (system), Python v2.7.14, OpenSSL 1.0.2g  1 Mar 2016
- Python version: 2.7.14
- server name or domain: Gmail 
- CLI options: none

#### Configuration file offlineimaprc
```
[general]
#list of accounts, comma separated
ui = TTYUI
accounts = krmshubham
fsync = False
pythonfile = ~/.config/offlineimap/gnome-keyring_helper.py

[Account krmshubham]
localrepository = krmshubham-local
remoterepository = krmshubham-remote
postsynchook = notmuch new
maxage = 2017-11-19

[Repository krmshubham-local]
type = Maildir
localfolders = ~/mail/krmshubham
nametrans = lambda folder: {'drafts': '[Gmail]/Drafts',
			 'sent'	: '[Gmail]/Sent Mail',
         		'flagged':'[Gmail]/Starred',
			'trash'	: '[Gmail]/Trash',
			'archive':'[Gmail]/All Mail',
			'spam'	: '[Gmail]/Spam',
			'important' : '[Gmail]/Important'
			}.get(folder, folder)

[Repository krmshubham-remote]
type = Gmail
remoteusereval = get_username("krmshubham-gmail")
remotepasseval = get_password("krmshubham-gmail")
realdelete=no
maxconnections=3
nametrans = lambda folder: {'[Gmail]/Drafts':    'drafts',
                            '[Gmail]/Sent Mail': 'sent',
                            '[Gmail]/Starred':   'flagged',
                            '[Gmail]/Trash':     'trash',
                            '[Gmail]/All Mail':  'archive',
			    '[Gmail]/Spam' :	 'spam',
	   		    '[Gmail]/Important' : 'important'
                            }.get(folder, folder)
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
```
#### pythonfile (if any)

A python file copied from https://blog.lertsenem.com/command_line_mail_setup_with_offlineimap_notmuch_and_alot.html#sf-command_line_mail_setup_with_offlineimap_notmuch_and_alot-8 to get passwords from gnome-keyring. I think that's not relevant here.

#### Logs, error

```
2017-12-19 23:15:36 DEBUG: [imap]:   15:36.40 Folder NSIT [acc: krmshubham] last 20 log messages:
2017-12-19 23:15:36 ERROR: ERROR: ERROR in syncfolder for krmshubham folder NSIT: Traceback (most recent call last):
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 594, in syncfolder
    cachemessagelists_upto_date(maxage)
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 506, in cachemessagelists_upto_date
    remotefolder.cachemessagelist(min_uid=min(uids))
  File "/usr/share/offlineimap/offlineimap/folder/Gmail.py", line 122, in cachemessagelist
    min_date=min_date, min_uid=min_uid)
  File "/usr/share/offlineimap/offlineimap/folder/IMAP.py", line 255, in cachemessagelist
    imapobj, min_date=min_date, min_uid=min_uid)
  File "/usr/share/offlineimap/offlineimap/folder/IMAP.py", line 236, in _msgs_to_fetch
    search_result = search(search_cond)
  File "/usr/share/offlineimap/offlineimap/folder/IMAP.py", line 198, in search
    res_type, res_data = imapobj.search(None, search_conditions)
  File "/usr/lib/python2.7/dist-packages/imaplib2.py", line 1079, in search
    return self._simple_command(name, *criteria, **kw)
  File "/usr/lib/python2.7/dist-packages/imaplib2.py", line 1740, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/lib/python2.7/dist-packages/imaplib2.py", line 1493, in _command_complete
    raise self.error('%s command error: %s %s. Data: %.100s' % (rqb.name, typ, dat, rqb.data))
error: SEARCH command error: BAD ['Could not parse command']. Data: FMAO19 SEARCH (UID -4:*)


  SEARCH command error: BAD ['Could not parse command']. Data: FMAO19 SEARCH (UID -4:*)
```

#### Steps to reproduce the error

- Copy or move an email from INBOX to another folder in the local copy using mutt  
- Try to sync the repositories.

#### Workaround

Removing `maxage` from the offlineimaprc file solved the problem, but it'd be better if there's some better solution.

**Comment by nicolas33** [comment]
Could you try the above version with imap debug log enabled, please?

**Comment by shubhamkrm** [comment]
Sorry, the error went away after I deleted the cache from ~/.offlineimap folder, and now I'm unable to reproduce the issue.

**Comment by nicolas33** [comment]
That's good news. A corrupted cache can do weird things. I have no idea how this could lead to this issue, though.

**Comment by shubhamkrm** [comment]
Hi, the error happened again. I'm attaching the debug log from the version you asked. I noticed that when I run the installed version, there's an error in syncing just one folder, whereas in the modified version, there's an exception in every version. I'm attaching logs for both of them. The one for the original is in imap_old.log, where the log for the modified version is in imap.log.
[imap.log](https://github.com/OfflineIMAP/offlineimap/files/1582377/imap.log
[imap_old.log](https://github.com/OfflineIMAP/offlineimap/files/1582386/imap_old.log)
)

**Comment by nicolas33** [comment]
My patch was wrong, sorry. Please, try this latest version above.

**Comment by nicolas33** [comment]
Notice the current log (`imap_old.log`, without the patch) does not help. I need to know what's wrong in the command and this was not logged.

**Comment by shubhamkrm** [comment]
What ui should I use? For now, instead of the command, I get `AttributeError: 'TTYUI' object has no attribute 'exception'`

**Comment by nicolas33** [comment]
Ouch! I forgot there's no wrapper for logger.exception. I did yet another patch.

**Comment by shubhamkrm** [comment]
No problem. Let me try now.

**Comment by shubhamkrm** [comment]
[imap.log](https://github.com/OfflineIMAP/offlineimap/files/1582685/imap.log)

**Comment by nicolas33** [comment]
There's no unexpected search conditions. The IMAP server is reporting the full IMAP command: `SEARCH (UID -4:*)`. 

So, I think the issue is that we have a negative value as starting UID. I'll check why we can have this negative integer.

**Comment by shubhamkrm** [comment]
Thanks for checking. I have noticed that this happens only if I move some message, which is older than maxage, from inbox to another folder . This issue doesn't arise if the moved message is newer than the maxage.

**Comment by nicolas33** [comment]
Good report. This will help.

**Comment by nicolas33** [comment]
I did a quick fix to check my assumption. Does this patch the issue? (it's another git branch).

**Comment by shubhamkrm** [comment]
Yes, it did!

**Comment by nicolas33** [comment]
Ok, great. You can run with this patch for now. It's safe.

I'll try to fix the root cause and I'll request you to check the new version. I'm not sure I'll have time before Christmas, though.

**Comment by shubhamkrm** [comment]
It's okay! Enjoy your holidays :)

**Comment by nicolas33** [comment]
Thank you. Here is a new patch.

**Comment by shubhamkrm** [comment]
Thanks. It works perfectly.

**Comment by nicolas33** [comment]
Thank you much. Patch applied into the 'next' branch. I think I'll make a new release during January.
