### ISSUE TITLE
docs: add full list of .offlineimaprc options somewhere

### ISSUE THREAD

**Issue by Unip0rn** [OfflineIMAP/offlineimap#513]
not a bug report, but a feature request on the documentation from a total newbie.
I'd like a list of all options I have in .offlineimaprc with an explanation what they do.
This is to have a single place to look at, when thinking of "there should be an option for that" as well as starting up with the project and asking oneselves what one can achieve by using offlineimap.

If there are questions on this request or I made it at the wrong place I wish to be told so.

Thanks in advance.

**Comment by chris001** [comment]
Easily solution, add comments inside the `.offlineimaprc` file, next to each config option of an example config + add a `--help` command line option which explains each option fully.

**Comment by nicolas33** [comment]
That's what we have here: https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf

I agree this could be easier to find on the website.

**Comment by Unip0rn** [comment]
It is PR 12 on OfflineIMAP/offlineimap.github.io now

**Comment by nicolas33** [comment]
Thank you much. Applied.
