### ISSUE TITLE
Cannot APPEND to a SPAM folder

### ISSUE THREAD

**Issue by Quintus** [OfflineIMAP/offlineimap#514]
Hi everyone,

I'm currently configuring my mail server for SpamAssassin and auto-learning using Dovecot's `antispam` plugin. I've set everything set up successfully now, just offlineimap doesn't want to play the game:

~~~~~
OfflineImapError: Saving msg in folder 'Junk', repository 'Privat-remote' failed (abort).
Server responded: NO ['[CANNOT] Cannot APPEND to a SPAM folder
(0.103 + 0.030 + 0.132 secs).']
~~~~~

Referring to dovecot-antispam(7):

> ALLOWING APPENDS?
>
> You should be careful with allowing APPENDs to SPAM folders. The reason for  possibly
> allowing  it is to allow not-SPAM --> SPAM transitions to work with offlineimap. How‐
> ever, because with APPEND the plugin cannot know the source of the message,  multiple
>  bad scenarios can happen:
>
> 1. SPAM --> SPAM transitions cannot be recognised and are trained
> 2. the same holds for Trash --> SPAM transitions
>
> Additionally,  because  we  cannot  recognise SPAM --> not-SPAM transitions, training
> good messages will never work with APPEND.

The compelling reason to not allow APPENDs is actually the last sentence after the enumeration. Thus, I've no intention to enable `APPEND` on a spam folder. How can I get offlineimap to not use `APPEND` on those folders, but do things differently?

#### General informations

- system/distribution (with version): Gentoo Linux
- offlineimap version (`offlineimap -V`): 6.5.5
- Python version: 2.7.14
- server name or domain: my own server, actually
- CLI options: none

#### Configuration file offlineimaprc

```
[general]
metadata = ~/.cache/offlineimap
accounts = Privat

[Account Privat]
localrepository = Privat-local
remoterepository = Privat-remote
status_backend = sqlite

[Repository Privat-local]
type = Maildir
localfolders = ~/.local/share/mail/privat

[Repository Privat-remote]
type = IMAP
remotehost = (redacted)
remoteuser = (redacted)
ssl = yes
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
remotepass = (redacted)
```

#### Logs, error

```
Folder Junk [acc: Privat]:
 Copy message -1 (1 of 1) Privat-local:Junk -> Privat-remote
Folder ML.colognerb [acc: Privat]:
 Syncing ML.colognerb: IMAP -> Maildir
Thread 'Folder Junk [acc: Privat]' terminated with exception:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/offlineimap/threadutil.py", line 158, in run
    Thread.run(self)
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/offlineimap/accounts.py", line 458, in syncfolder
    localfolder.syncmessagesto(remotefolder, statusfolder)
  File "/usr/lib64/python2.7/site-packages/offlineimap/folder/Base.py", line 780, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib64/python2.7/site-packages/offlineimap/folder/Base.py", line 660, in __syncmessagesto_copy
    register = 0)
  File "/usr/lib64/python2.7/site-packages/offlineimap/folder/Base.py", line 586, in copymessageto
    new_uid = dstfolder.savemessage(uid, message, flags, rtime)
  File "/usr/lib64/python2.7/site-packages/offlineimap/folder/IMAP.py", line 574, in savemessage
    raise OfflineImapError(msg, OfflineImapError.ERROR.REPO)
OfflineImapError: Saving msg in folder 'Junk', repository 'Privat-remote' failed (abort). Server responded: NO ['[CANNOT] Cannot APPEND to a SPAM folder (0.103 + 0.030 + 0.132 secs).']



Last 15 debug messages logged for Folder Junk [acc: Privat] prior to exception:
imap: __options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '91'}
imap: __options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '92'}
imap: __options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '93'}
imap: __options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '94'}
imap: __options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '95'}
imap: __options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '96'}
imap: __options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '97'}
imap: __options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '98'}
imap: __options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '99'}
imap: __options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '100'}
imap: __options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '101'}
imap: __options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '102'}
imap: Write mail 'Junk:-1' with flags set([])
: deletemessageheaders: called to delete []
imap: savemessage: date: "29-Dec-2017 10:14:25 +0100", content: 'Return-Path: <bounce@newportcacpa.com>
Delivered-To: (redacted)
Received: from (redacted)
	by (redacted)(Dovecot...14533948_d4d116ca343d9e9579eb5bad09ed20ce_=_--

'
```

#### Steps to reproduce the error

1. Configure a dovecot IMAP server with `antispam` plugin.
2. Move a mail into the configured spam folder on your local PC.
3. Run offlineimap.
4. Observe the above error message.

**Comment by chris001** [comment]
@Quintus 
To fix this bug, speaking for myself, I'd need some backing to replace all usages of `APPEND` and in its place add support for RFC68651, automatically detect IMAP `MOVE` command capability on the server, and also add support for `COPY`/ `\Deleted` fallback procedure to support all older IMAP servers which don't have the `MOVE` command.
* https://tools.ietf.org/html/rfc6851
* https://stackoverflow.com/questions/122267/imap-how-to-move-a-message-from-one-folder-to-another

**Comment by nicolas33** [comment]
You could folderfilter this folder or never make changes to the local folder in this maildir. APPEND happens to upload new local messages.

**Comment by chris001** [comment]
* @nicolas33  You're right, for that one case, we must continue to use `APPEND` command for the one case of uploading new local email messages to the remote IMAP server.  
* However, for all other cases I can think of, when we must move a message from one folder to another folder within the same IMAP server in order to get in sync with the state of another server, instead of using the old way (download message from remote IMAP server to local machine, followed by immediately upload message to a different folder on the same remote IMAP server), we'd need to upgrade to do the new way (use IMAP `MOVE` command, or fallback to IMAP `COPY` command followed immediately by set `\Deleted` flag).

**Comment by Quintus** [comment]
> You could folderfilter this folder or never make changes to the local folder in this maildir. APPEND happens to upload new local messages.

Sure, and that's what I'm doing currently, but that defeats the purpose of Dovecot's `antispam` plugin...

**Comment by nicolas33** [comment]
@chris001 Sure. Create a feature request for the MOVE command.

@Quintus You did changes on the local side in the Junk folder. That's what the logs say: `Copy message -1 (1 of 1) Privat-local:Junk -> Privat-remote`. Remove the offending mail to go back to no error.

**Comment by nicolas33** [comment]
To be clear I'm saying that you can't do what you intend, currently.

It may be possible to workaround this by introducing another folder to train spamassassin (not sure).

**Comment by chris001** [comment]
I think the way the Dovecot `antispam` plugin works is, it detects when a client (`offlineimap` in our case) uses IMAP commands to MOVE a mail from `inbox` to `spam` or to `junk` (the plugin learns that this contents and/or headers is really from a spam sender and tries to use learning techniques to get better next time and not make the same mistake).  Same when the client (`offlineimap`) uses IMAP MOVE to move a message from `spam` or `junk` to `inbox`, the `antispam` plugin tries to train `spamassassin` to not make the same mistake again.

If offlineimap just downloads the message, and re-uploads (using `APPEND` command) a new copy of the message into `spam` or `junk`, it appears as a NEW message, so `antispam` cannot make the logical connection, it cannot conclude that the user MOVEd the message into `spam` or `junk`, and therefore cannot take this opportunity to train `spamassassin` to not make the same mistake again (the false positive or false negative).

**Comment by Quintus** [comment]
> You did changes on the local side in the Junk folder. That's what the logs say [...] To be clear I'm saying that you can't do what you intend, currently.

I understand this. So, consider this ticket as

> a feature request for the MOVE command.

Or do you really want me to create a new ticket?

Regarding:

> It may be possible to workaround this by introducing another folder to train spamassassin (not sure).

I've resolved the problem for me by means of workaround. I don't put my spam mail into that folder, but into another folder that's not marked as a SPAM folder for Dovecot's `antispam` plugin. I can then run a cronjob on the mail server that feeds that folder's contents into `sa-learn`. This lacks the ability to learn ham messages and is not a nice workaround as it renders Dovecot's `antispam` plugin pretty useless. I could have the same effect by just not using it at all.

**Comment by Quintus** [comment]
Nevermind, I've created a feature request for the `MOVE` command in #515. Discussion should probably move there.
