### ISSUE TITLE
inconsistent documentation about maxsyncaccounts

### ISSUE THREAD

**Issue by listx** [OfflineIMAP/offlineimap#520]
In `offlineimap.conf`, we are told to "set the maxsyncaccounts option accordingly" https://github.com/OfflineIMAP/offlineimap/blob/67d35dbbcbd74f03c32f278ba080135b5b98897a/offlineimap.conf#L276-L277, but in `docs/offlineimap.txt` we are told that the `maxsyncaccounts` option is deprecated because of race conditions https://github.com/OfflineIMAP/offlineimap/blob/67d35dbbcbd74f03c32f278ba080135b5b98897a/docs/offlineimap.txt#L214-L215.

So, is it supported or not?

**Comment by nicolas33** [comment]
Oh, good catch. max syncaccounts is supported in the case you want one instance of offlineimap syncing more than one account. Later, support for running more than one instance was added in offlineimap with a lock file at the account level. So, it's better to run as many offlineimap instances as there are accounts.

However, maxsyncaccounts is not always optionnal. It's required for autorefresh to work. If you have systemd on your system it's better to replace autorefresh with the systemd timeout service. 

More on this here:

https://github.com/OfflineIMAP/offlineimap/tree/master/contrib/systemd
http://www.offlineimap.org/configuration/2016/01/29/why-i-m-not-using-maxconnctions.html

I'll fix this.

**Comment by nicolas33** [comment]
Please, let me know if the above patch looks OK to you.

**Comment by nicolas33** [comment]
Here we go. I think this version is clear enough for all the cases.

**Comment by listx** [comment]
Thanks, LGTM.

**Comment by nicolas33** [comment]
Applied. Thank you.
