### ISSUE TITLE
Emails with edited X-Label header are deleted

### ISSUE THREAD

**Issue by frnsys** [OfflineIMAP/offlineimap#523]
#### General informations

- system/distribution (with version): 
Ubuntu 16.04 (Linux 4.4.0-112-generic (x86_64))

- offlineimap version (`offlineimap -V`): 
6.6.1

- Python version: 
2.7 and 3.5

- server name or domain: 
- CLI options: none

#### Configuration file offlineimaprc

```
[general]
accounts = main


[Account main]
localrepository = main-local
remoterepository = main-remote

# full refresh, in min
autorefresh = 0.2

# quick refreshs between each full refresh
quick = 10

# update notmuch index after sync
postsynchook = notmuch new


[Repository main-local]
type = Maildir
localfolders = ~/.mail

# delete remote mails that were deleted locally
sync_deletes = yes


[Repository main-remote]
type = IMAP
remoteport = 1143
remotehost = 127.0.0.1
remoteuser = <my email>
remotepasseval = open('/home/me/docs/keys/mail').read().split('\n')[-1].split('=')[-1]
keepalive = 60
holdconnectionopen = yes

# delete local mails that were deleted on the remote server
expunge = yes

# sync only these
folderfilter = lambda foldername: foldername in ['INBOX', 'Archive', 'Sent']
```

#### Steps to reproduce the error
- Use `<edit-label>` function in `neomutt` to edit `X-Label` header of an email
- On next refresh, offlineimap deletes the changed email

I brought this up here <https://github.com/neomutt/neomutt/issues/1053> but it seems like this has more to do with offlineimap. What seems to be happening is when the `X-Label` header is added, offlineimap sees it as a new email that somehow ends with it being deleted (I don't fully understand why though).

Is there a configuration option that prevents this behavior?

**Comment by nicolas33** [comment]
> I brought this up here neomutt/neomutt#1053 but it seems like this has more to do with offlineimap. What seems to be happening is when the X-Label header is added, offlineimap sees it as a new email that somehow ends with it being deleted (I don't fully understand why though).
> 
> Is there a configuration option that prevents this behavior?

I've quickly checked the code and I don't understand what's going on, here. The X-Label header seems to be only used for Gmail repositories while there's only one IMAP repository in your configuration file. It is used to locally store the labels of Gmail.

I wonder something else is happening. Could you check the filename before the edition and after that (don't forget to sync on disk from neomutt)?

The email is deleted in the maildir on next sync, right? Is it deleted on the remote after that?

Notice we don't support the v6 series. You might like to upgrade to the latest v7.1.5.

**Comment by frnsys** [comment]
Oh thanks, I just upgraded to 7.1.5!

Yes, the email is deleted in the maildir on the next sync and also deleted on remote, here's what is output:

```
Folder INBOX [acc: main]:        
 Syncing INBOX: IMAP -> Maildir
 Copy message UID -1 (1/1) main-local:INBOX -> main-remote       
Folder Archive [acc: main]:  
 Syncing Archive: IMAP -> Maildir
Folder INBOX [acc: main]:      
 savemessage: Searching mails for new Message-ID failed. Could not determine new UID on INBOX.                                         Folder Archive [acc: main]:                                      
 Skipping Archive (not changed)
Folder INBOX [acc: main]:     
 Deleting 1 messages (88) in IMAP[INBOX]
Folder Sent [acc: main]:
 Syncing Sent: IMAP -> Maildir
 Skipping Sent (not changed)                 
Account sync main:
 Calling hook: notmuch new
 Hook stdout: No new mail. Removed 1 message.
```

And yes, it does look like the filename is changing:

- Original: `1518309163_0.22338.anarres,U=89,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S`
- After editing the label: `1518309228.R61549665121590429.anarres:2,S`

**Comment by chris001** [comment]
Looks like a bug. Filename shouldn't really matter to the point where a different filename causes the system to see it as a unique different message. The content of the headers should matter more. Questions:
1. When `X-Label` header content changes, does `Message-ID` header content change, in reality?
2. Should `Message-ID` change, when `X-Label` changes?

**Comment by frnsys** [comment]
When `neomutt` writes the `X-Label` change, the `Message-ID` header doesn't change (I feel like it shouldn't anyways). It seems to also add these headers:

```
Status: RO
Content-Length: 712
```

Is there any reason why that would cause a deletion?

**Comment by chris001** [comment]
In theory, changes to the headers shouldn't cause deletion.  The reality, it looks like this is a bug in the code that decides about what to do based on the headers, and that's why the deletion is happening, but it shouldn't happen.

**Comment by nicolas33** [comment]
> And yes, it does look like the filename is changing:
> 
> Original: 1518309163_0.22338.anarres,U=89,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S
> After editing the label: 1518309228.R61549665121590429.anarres:2,S

So, here is what's happening. The rename of the filename is expected. It's a way to know that the content was changed.
On next sync, offlineimap sees email with UID number 89 as deleted AND a new email. Those changes are synced on remote.

There's a deletion and a new upload for this email in order to keep the remote synced.

I see no issue, here.

**Comment by frnsys** [comment]
The new email is deleted as well, presumably because it's not on remote? So I end up losing the email entirely.

Is it up to neomutt then to implement this label change so that it preserves the UID, or is that not possible?

**Comment by nicolas33** [comment]
> The new email is deleted as well, presumably because it's not on remote? So I end up losing the email entirely.

The logs suggest the email was uploaded successfully. The email should stand on the remote. However, offlineimap could not determine the UID:
`savemessage: Searching mails for new Message-ID failed. Could not determine new UID on INBOX.`

This happens when there's no UIDPLUS on the IMAP server and when our search method based on the X-Offlineimap header fails. Maybe a run with debug mode enabled could help (-dimap CLI option).

Offlineimap does NOT remove the edited email locally. However, I see your postsync hook pretends to remove emails. Why?

> Is it up to neomutt then to implement this label change so that it preserves the UID, or is that not possible?

No, preserving the filename (and the UID) would be wrong. We have to propagate the label changes on the remote.

**Comment by frnsys** [comment]
Thanks for explaining. I will try it with the debug option.

The edited email doesn't show up on the remote server (at least, it's not listed when I load the inbox in my email provider's site). So perhaps what's happening is: my email provider isn't registering the edited email, so when offlineimap syncs, it sees that it's gone from remote and it's deleted locally? I'm trying to figure out what's deleting it if it's not offlineimap.

That postsynchook is notmuch removing the original email from it's database, I think. I will try it without that as well.

**Comment by nicolas33** [comment]
The edited email doesn't show up on the remote server (at least, it's not listed when I load the inbox in my email provider's site). So perhaps what's happening is: my email provider isn't registering the edited email, so when offlineimap syncs, it sees that it's gone from remote and it's deleted locally?

offlineimap only removes emails having UID (and missing from the UID list provided by the server). When offlineimap can't assign a UID to a newly uploaded email it will be re-uploaded on next run.

**Comment by nicolas33** [comment]
Notice: editing a mail means "remove the old one and create a new email".

**Comment by frnsys** [comment]
After some more experimentation, it seems like it may be something on my email provider's end. In any case, I managed to skirt the issue entirely by using notmuch's tagging system, which doesn't modify emails directly (if anyone is interested, [my muttrc showing the setup is here](https://github.com/frnsys/dippindots/blob/fa19ba6b905a3da18b3f064e82462096e3a8d580/dots/email/muttrc#L9)].

thanks again

**Comment by nicolas33** [comment]
Happy to hear you could get this working.
Thanks for your feedback!
