### ISSUE TITLE
Mapping INBOX to a folder fails

### ISSUE THREAD

**Issue by Musashi69** [OfflineIMAP/offlineimap#524]
Tried to file the mails from INBOX of host1 account into folder Job/Klinik of host2 account. nametrans succeeded in python shell with the lambda rules I used in the .offlineimaprc. Making the regex less trict didn't change a thing :-/

#### General informations

- system/distribution (with version): Debian 9
- offlineimap version (`offlineimap -V`): v7.1.5
- Python version: v2.7.13
- server name or domain: cardhu
- CLI options: none

#### Configuration file offlineimaprc
[general]
accounts = KLS

[Account KLS]
localrepository = host2
remoterepository = host1

[Repository host1]
type = IMAP
ssl = yes
cert_fingerprint = keykeykey
folderfilter = lambda folder: folder in ['INBOX']
readonly = true

[Repository host2]
type = IMAP
ssl = yes
cert_fingerprint = keykeykey
createfolders = False
nametrans = lambda folder: re.sub( '^INBOX$', 'Job/Klinik', folder)

#### Logs, error

user at host:~$ offlineimap --info
OfflineIMAP 7.1.5
   Licensed under the GNU GPL v2 or any later version (with an OpenSSL 
exception)
imaplib2 v2.57 (system), Python v2.7.13, OpenSSL 1.1.0f  25 May 2017
   imaplib2: 2.57 (system)
Remote repository 'host1': type 'IMAP'
Host: host1 Port: None SSL: True
Establishing connection to host1:993 (host1)
Server supports ID extension.
Server welcome string: * OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE 
AUTH=LOGIN AUTH=PLAIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5 SASL-IR] host server 
ready
Server capabilities: ('IMAP4REV1', 'LITERAL+', 'ID', 'ENABLE', 'ACL', 
'RIGHTS=KXTE', 'QUOTA', 'MAILBOX-REFERRALS', 'NAMESPACE', 'UIDPLUS', 
'NO_ATOMIC_RENAME', 'UNSELECT', 'CHILDREN', 'MULTIAPPEND', 'BINARY', 
'CATENATE', 'CONDSTORE', 'ESEARCH', 'SORT', 'SORT=MODSEQ', 
'SORT=DISPLAY', 'THREAD=ORDEREDSUBJECT', 'THREAD=REFERENCES', 
'ANNOTATEMORE', 'LIST-EXTENDED', 'WITHIN', 'QRESYNC', 'SCAN', 'XLIST', 
'URLAUTH', 'URLAUTH=BINARY', 'X-NETSCAPE', 'X-INTRANATOR-SETTINGS-UI', 
'X-INTRANATOR-FREEBUSY-TRIGGER', 'X-SHAREDSEEN-ANNOTATION', 
'LOGINDISABLED', 'COMPRESS=DEFLATE', 'IDLE')

folderfilter= lambda folder: folder in ['INBOX']

Folderlist:
  INBOX
  INBOX/Aufgaben (disabled)
  INBOX/Drafts (disabled)
  INBOX/Entw&APw-rfe (disabled)
  INBOX/Gel&APY-schte Elemente (disabled)
  INBOX/Gesendete Elemente (disabled)
  INBOX/Junk (disabled)
  INBOX/Kalender (disabled)
  INBOX/Kontakte (disabled)
  INBOX/Notizen (disabled)
  INBOX/privat (disabled)
  INBOX/Sent (disabled)
  INBOX/Trash (disabled)

Local repository 'host2': type 'MappedIMAP'
Host: host2 Port: None SSL: True
Establishing connection to host2:993 (host2)
Server supports ID extension.
Server welcome string: * OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE 
AUTH=PLAIN AUTH=LOGIN SASL-IR] host Cyrus IMAP 
2.5.11-41-gd53406f3f-Debian-2.5.11.41-0~kolab2 server ready
Server capabilities: ('IMAP4REV1', 'LITERAL+', 'ID', 'ENABLE', 'ACL', 
'RIGHTS=KXTEN', 'QUOTA', 'MAILBOX-REFERRALS', 'NAMESPACE', 'UIDPLUS', 
'NO_ATOMIC_RENAME', 'UNSELECT', 'CHILDREN', 'MULTIAPPEND', 'BINARY', 
'CATENATE', 'CONDSTORE', 'ESEARCH', 'SORT', 'SORT=MODSEQ', 
'SORT=DISPLAY', 'SORT=UID', 'THREAD=ORDEREDSUBJECT', 
'THREAD=REFERENCES', 'ANNOTATEMORE', 'ANNOTATE-EXPERIMENT-1', 
'METADATA', 'LIST-EXTENDED', 'LIST-STATUS', 'LIST-MYRIGHTS', 'WITHIN', 
'QRESYNC', 'SCAN', 'XLIST', 'XMOVE', 'MOVE', 'SPECIAL-USE', 
'CREATE-SPECIAL-USE', 'URLAUTH', 'URLAUTH=BINARY', 'LOGINDISABLED', 
'X-QUOTA=STORAGE', 'X-QUOTA=MESSAGE', 'X-QUOTA=X-ANNOTATION-STORAGE', 
'X-QUOTA=X-NUM-FOLDERS', 'IDLE')

nametrans= lambda folder: re.sub( '^INBOX$', 'Job/Klinik', folder)

Folderlist:
    [ ... ]
  Hobby/Status
  Hobby/Status/Monit
  Job
  Job/Arbeitsangebote
  Job/Arbeitsangebote/Uebernommen
  INBOX -> Job/Klinik
  Job/Klinik
  Journal
  Notes
    [ ... ]

#### Steps to reproduce the error

Nothing special - set up the .offlineimaprc, tried the --info and the --dry run before invoking the actual run

**Comment by Musashi69** [comment]
Addendum:
When performing the actual run the output reads like this:

> Folder INBOX [acc: KLS]:
>  Syncing INBOX: IMAP -> MappedIMAP
>  Copy message UID 10 (1/934) host1:INBOX -> host2
>  Copy message UID 11 (2/934) host1:INBOX -> host2
>  Copy message UID 12 (3/934) host1:INBOX -> host2
>  Copy message UID 13 (4/934) host1:INBOX -> host2
>  Copy message UID 14 (5/934) host1:INBOX -> host2
>  Copy message UID 15 (6/934) host1:INBOX -> host2
>  Copy message UID 16 (7/934) host1:INBOX -> host2
> ^CTerminating NOW (this may take a few seconds)...

Should the part after `->` show more info if the mapping succeeded?
One more question - is it important which host is defined as local and which as remote?

**Comment by nicolas33** [comment]
The nametrans rule must stand in the host1 section where you have the folderfilter rule.

> Should the part after -> show more info if the mapping succeeded?

I agree. Please, open a new issue for this feature request.

> One more question - is it important which host is defined as local and which as remote?

No it's not. However, once it's defined you must never swap them.

**Comment by Musashi69** [comment]
Thanks for checking and finding the error we missed on the mailinglist. Opened issue like requested and closing this as SOLVED

**Comment by nicolas33** [comment]
Thank you for the feedback!
