### ISSUE TITLE
Feature request: Make sync output more verbose, show mapping

### ISSUE THREAD

**Issue by Musashi69** [OfflineIMAP/offlineimap#525]
When performing the actual run the output reads like this:

> Folder INBOX [acc: test]:
> Syncing INBOX: IMAP -> MappedIMAP
> Copy message UID 10 (1/934) host1:INBOX -> host2
> Copy message UID 11 (2/934) host1:INBOX -> host2
> Copy message UID 12 (3/934) host1:INBOX -> host2
> Copy message UID 13 (4/934) host1:INBOX -> host2
> Copy message UID 14 (5/934) host1:INBOX -> host2
> Copy message UID 15 (6/934) host1:INBOX -> host2
> Copy message UID 16 (7/934) host1:INBOX -> host2

The program reports which folder on host1 is synced - but doesn't show which folder on host2 receives the mails. This might lead to a vast number of mails synced to the wrong folder (and having to sort them out manually)
So I'd like to suggest to make the program output more verbose on the host2 part - ideally to make it look e.g. like this:
When performing the actual run the output reads like this:

> Folder INBOX [acc: test]:
> Syncing INBOX: IMAP -> MappedIMAP
> Copy message UID 10 (1/934) host1:INBOX -> host2:targetfolder
> Copy message UID 11 (2/934) host1:INBOX -> host2:targetfolder
> Copy message UID 12 (3/934) host1:INBOX -> host2:targetfolder
> Copy message UID 13 (4/934) host1:INBOX -> host2:targetfolder
> Copy message UID 14 (5/934) host1:INBOX -> host2:targetfolder
> Copy message UID 15 (6/934) host1:INBOX -> host2:targetfolder
> Copy message UID 16 (7/934) host1:INBOX -> host2:targetfolder

**General informations**
- system/distribution (with version): Debian 9
- offlineimap version (offlineimap -V): v7.1.5
- Python version: v2.7.13

**Comment by Musashi69** [comment]
Pull request created , works for me on my local copy. Please feel free to use it in the official codebase.

**Comment by nicolas33** [comment]
Thank you much @Musashi69 ; applied. :-)
