### ISSUE TITLE
status_backend replacement?

### ISSUE THREAD

**Issue by schiessle** [OfflineIMAP/offlineimap#527]
I read in the changelog that the config switch "status_backend" was removed for OffineIMAP 7.1.0 but no reason was given and no replacement was mentioned: https://github.com/OfflineIMAP/offlineimap/blob/master/Changelog.md

As far as I understood it, the default was a plain text and optional a sqlite backend could be used, mainly for performance reasons on large mail boxes. So what does the removal of this config switch effectively means? Are the performance problems of the plain text file no longer an issue? Does OfflineIMAP now always uses a sqlite database? Is there any new config switch which replaces the old one?

**Comment by nicolas33** [comment]
The switch was removed because only sqlite is supported. This move has been decided after a long time with sqlite set by default.

**Comment by schiessle** [comment]
> This move has been decided after a long time with sqlite set by default.

So it uses now always sqlite? On debian i could install Offineimap without sqlite, see the dependency settings:

````
$ apt show offlineimap
Package: offlineimap
Version: 7.1.5+dfsg1-1
Priority: optional
Section: mail
Maintainer: Ilias Tsitsimpis <iliastsi@debian.org>
Installed-Size: 595 kB
Depends: python-imaplib2 (>= 2.57), python-six, python:any (>= 2.7.5-5~)
Recommends: python-socks
Suggests: python-kerberos
Homepage: http://offlineimap.org/
Tag: implemented-in::python, interface::commandline, interface::text-mode,
 mail::imap, network::client, protocol::imap, protocol::ssl,
 role::program, scope::utility, use::synchronizing, works-with::mail
Download-Size: 173 kB
APT-Manual-Installed: yes
APT-Sources: http://ftp2.de.debian.org/debian sid/main amd64 Packages
````

How can I verify that sqlite is used?

**Comment by nicolas33** [comment]
You can check the file format in the cache directory ("metadata" path):
`find ~/.offlineimap/* -type f -exec file '{}' \+ `

**Comment by nicolas33** [comment]
Forgot to say that the Python SQLite driver in part of the Python core libraries. It's installed with Python itself. No need to install the package providing the command 'sqlite3'.

**Comment by schiessle** [comment]
Thanks for clarification. I checked my setup and, as you said, sqlite is used. :smiley:
