### ISSUE TITLE
not working with brew python on macOS

### ISSUE THREAD

**Issue by chew-z** [OfflineIMAP/offlineimap#530]
#### General informations

I have noticed this morning that `brew update && brew upgrade` changed/linked 'python' to 'python3'. This is good perhaps but it resulted in offlineimap not working anymore on my system because 'commands' had been removed from python3.

#### Logs, error

```
$ offlineimap
OfflineIMAP 7.1.5
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v3.6.4, OpenSSL 1.0.2n  7 Dec 2017
ERROR: No module named 'commands'
ERROR: Exceptions occurred during the run!
ERROR: No module named 'commands'

$ python --version
Python 3.6.4
```

**Comment by nicolas33** [comment]
Yes, the support for Py3 is not ready and stalled. I have no idea why these brew commands are changing python to python3. Is there something we can do?

**Comment by arolle** [comment]
Could it be an option to change the header in `libexec/offlineimap.py` to `#!/usr/bin/env python2`?
One fix is to issue

     ln -sf "$(which python2)" "$(which python)"

**Comment by chris001** [comment]
* https://pythonclock.org

I'm nearly complete building the first real automatic tests of live email sync to run here on github for `offlineimap`, including support to test on MacOS, and `python3`.  This makes updating to compatible with `python3` much easier because the new code changes are verified in just 1-2 minutes on linux, macos, python 2.7 and python 3.6.

**Comment by nicolas33** [comment]
The idea of fixing the shebang is nice. Change applied on the current "next" branch. Hope this will help. Other than that I don't see what we could do, though.

Thank you all.

**Comment by sjktje** [comment]
Anyone know how to fix this temporarily until the next offlineimap release?

**Comment by chris001** [comment]
@sjktje 
* You just need to edit 2 files, `bin/offlineimap` and `offlineimap.py`.
* Edit the first line in each file, from `#!/usr/bin/env python`, to `#!/usr/bin env python2`.  Save each file and that's it!

**Comment by nicolas33** [comment]
@chris001 Good point. I forgot this second file in my previous patch. Fixed for offlineimap.py, too.
