### ISSUE TITLE
REQ: Add Automated Tests. Start to build a better quality OfflineIMAP app today.

### ISSUE THREAD

**Issue by chris001** [OfflineIMAP/offlineimap#531]
Very pleased to announce that Automated Testing is now working, at substantial coverage level.

* Live sync test with real commercial IMAP mail servers: Microsoft **Outlook.com** , and **GMail.com**.
* `Linux Ubuntu 14.04 Trusty` and `Mac OSX High Sierra 10.13` operating systems.
* Python 2.7 and Python 3.6.
* LOGIN, PLAIN, and XOAUTH2 authentication mechanisms.
* Strong TLS security, on IMAPS port 993, using one of the latest versions of OpenSSL available.

There's more to add:
* Update the unit tests, which were contributed a while ago by @spaetz  and crew, to use the actual existing secure encrypted login methods inside OfflineIMAP, not try to login directly over cleartext (!!).
* Adjust some settings, to let the tests to run on the Mac OSX's Python 3.6 environment.
* Another IMAP account, maybe **Dovecot**, so that the rest of the authentication mechanisms could be tested: `GSSAPI`, and `CRAM-MD5`.
* Functional tests: Create (send/store)/Read/Update (modify)/Delete mail, CRUD GMail labels, CRUD message flags, 7-bit and UTF-8, International, and Emoji charset tests, date tests, sync mailbox, move mail from one folder to another folder on the same account, etc.

**Comment by nicolas33** [comment]
PR applied on the temporary trytravis branch. I'll merge it into 'next' when you drop me the info on gitter so the tests pass.

**Comment by chris001** [comment]
Private script shared!  It's easy to run, adds encrypted info to `.travis.yml`!

**Comment by nicolas33** [comment]
Applied into next.
Thank you much!
