### ISSUE TITLE
Release vs Tag (error with metadata)

### ISSUE THREAD

**Issue by chris001** [OfflineIMAP/offlineimap#533]
This is a subtle, yet serious, release metadata bug.
When you visit https://github.com/OfflineIMAP/offlineimap/releases/latest it shows the latest release as May 2014. 
**v6.5.6 (25 May 2014) is a "Release", whereas v7.1.5 (13 Jan 2018) is a "Tag", but confusingly, GitHub uses these terms slightly differently in the web front-end and the API, which causes great confusion.**
Version 7.1.5 and all others since 6.5.6, show "tag".
**It's important to make "Release" because this is the metadata which is automatically retrieved by external software distribution systems.**

**Comment by nicolas33** [comment]
Release deleted. Thanks.

**Comment by chris001** [comment]
Now, it shows 6.5.5
https://github.com/OfflineIMAP/offlineimap/releases/latest
The good solution is, for the next release 7.1.6, it must be a "release", not a "tag", then, it will be the one that appears when all externally metadata tools query for "what's the latest release of offlineimap" by visiting this github URL.

**Comment by chris001** [comment]
https://help.github.com/articles/creating-releases/
How to create the "release" by referring to the version in the git tag.  
Either from web interface, or using command line!

**Comment by chris001** [comment]
New "release" for v7.1.5 drafted @nicolas33 for you to have a look, and click Publish.
This would solve the bug of the internet seeing "latest release date: october 2013".
https://github.com/OfflineIMAP/offlineimap/releases
Contents of Release are copied from `Changelog.md`.

**Comment by nicolas33** [comment]
> The good solution is, for the next release 7.1.6, it must be a "release", not a "tag",

I sightly disagree. Making a release is a git thing, not a github thing. With git we create a release by creating an annotated tag.

If github can't comply with git, this is yet another github issue. I don't want to consume my time on github by micro-managing each of my git command. I want to spend my time on the software tracked with git and made public with github.

Github is strongly broken in many ways. Follow the github way just because it's github is pure non-sense because this tool makes you fight our core tool which is git.

**Comment by nicolas33** [comment]
> Now, it shows 6.5.5

So, there is a new issue with github. When I've deleted the previous release **note** the web UI was showing the tags. Later, github has changed the UI for another release note. Github is not reliable.

**Comment by chris001** [comment]
I've figured it out.  I made a new release note.  This fixes the problem, so that v7.1.5 will show as the newest one.

**Comment by chris001** [comment]
So this link https://github.com/OfflineIMAP/offlineimap/releases shows the Release Note (created in github) of the newest "release" (github).  This is the metadata seen by the entire public internet.  When there is no Release Note (github), the internet sees an error message something like "invalid repo or no release ever made".  I realize it might seem not perfect in line with `git` on some level, but for the internet to see accurate information, we can easily fix this, by doing as most all other repos on github do, and make draft Release Notes, on the command line, or in the github web interface, containing the content of the `Changelog.md` for the relevant release.  At least, for the next release 7.1.6.

**Comment by chris001** [comment]
* This:
https://www.barrykooij.com/create-github-releases-via-command-line/
```
API_JSON=$(printf '{"tag_name": "v%s","target_commitish": "master","name": "v%s","body": "Release of version %s","draft": false,"prerelease": false}' $VERSION $VERSION $VERSION)
curl --data "$API_JSON" https://api.github.com/repos/:owner/:repository/releases?access_token=:access_token
```
* Get your own personal Access Token here: https://github.com/settings/applications

**Comment by nicolas33** [comment]
Please, don't get confused by github. It can offer a lot of features, this does not mean we should use all of them. We have our own official website for the changelog with the release notes.

github is so confusing that it's a good reason **not** to use it. Actually, I think we should move to another provider like gitlab which is not perfect but is much less confusing and more git compliant.

**Comment by chris001** [comment]
I love github it's really awesome, and it doesn't derange me at all to make a "Release" object, from the command line, or from the web interface.

I've searched far, and found a really nice badge to automatically show the newest version available, from the existing OfflineIMAP github metadata [![Github Tag](https://img.shields.io/github/tag/OfflineIMAP/offlineimap.svg)](https://github.com/OfflineIMAP/offlineimap/releases)

**Comment by nicolas33** [comment]
Contributors to the project have access to some features for maintainers because github sucks at properly handling rights. It's not good to split the release job into different hands.

The current releases page is fine so feel free to make a PR for the badge.
