### ISSUE TITLE
Github pull request mailer to mailing list!

### ISSUE THREAD

**Issue by chris001** [OfflineIMAP/offlineimap#534]
https://github.com/google/pull-request-mailer

"Optionally, it's possible to run the tool in daemon mode, **let it receive GitHub webooks** and automatically process them."

We should setup our WebHooks to get a URL on the website, at every pull request, and that code (Haskell code running on the website) will transmit email message to the mailing list email address.

**Comment by nicolas33** [comment]
We don't have the infra to run this kind of tool.

**Comment by chris001** [comment]
It's no worry, my org has infra to lend to run this tool, until we raise the funds to rent our own proper server cheap $40/year.

**Comment by nicolas33** [comment]
Nobody ever requested to read the github PR in the mailing list. I agree this would be best but I'm not sure we really need this.

**Comment by chris001** [comment]
I create this pull request because of blog post you wrote, about the need for github to mail notification of pull request to project mailing list, to engage the users who subscribe only to the mailing list, so they can review code, test, and participate more often and more easily.
* "**PR by email**
What about hooks? I know so many organizations and maintainers out-there would love to get the patches from pull requests automatically sent to their mailing list. This would FIX almost all of the above issues in ONE SHOT!"
* http://blog.wikichoon.com/2014/04/github-doesnt-support-pull-request.html
* "Apparently the anaconda team has one too:" https://github.com/rhinstaller/github-email-hook/
Let's just do it!  Host this little `pull-request-mailer` or `github-email-hook` on the infra and give it a try.

**Comment by nicolas33** [comment]
> I create this pull request because of blog post you wrote, about the need for github to mail notification of pull request to project mailing list, to engage the users who subscribe only to the mailing list, so they can review code, test, and participate more often and more easily.

At this time we had to handle the github migration. Guess what! The migration worked. By doing so, we lost almost all our best and long time contributors.

**Comment by nicolas33** [comment]
Feel free to host a service if you think it worth.

**Comment by chris001** [comment]
Sure. It's just a simple `https` web server, that receives a request from github containing the body of the pull request notifcation in email format, and sends that html in an email to the mailing list email address.  With luck, this will bring back most of the best and long time contributors, because they're still online, and probably most or all still subscribed to the mailing list.

**Comment by nicolas33** [comment]
Ok. :-)

I'll have to know the URL, the POST format and the events while creating the webhook.

**Comment by chris001** [comment]
Is it interesting enough to start small with this pull request notifier, have it simply send a notification email to the mailing list, something like, "From: Pull Request Notifier. Date: ____ Subject: New pull request: ____.  Text of pull request: ____.  Link back to pull request on github: _____" ?

**Comment by nicolas33** [comment]
The script must be installed and the service running so we can check it is responding from the net.
Next, we'll enable the webhook and check the emails are sent.
Easy.

**Comment by nicolas33** [comment]
Should we close this issue?

**Comment by chris001** [comment]
Was busy for some time, sorry.  Let's keep it open and get it done.  Infra server is running with secure https.  Need time this weekend to config connection from nginx web server `uwsgi` gateway to python app `github-email-hook`, then will be ready to test.

**Comment by nicolas33** [comment]
Oh that's fine. We have time. We didn't have a MR for a long long time!

**Comment by nicolas33** [comment]
I'm closing this one. MRs do not come with high rate, BTW.
