### ISSUE TITLE
Make it more clear that three ctrl-c presses will actually kill offlineimap

### ISSUE THREAD

**Issue by amandabee** [OfflineIMAP/offlineimap#539]
I'm currently running OfflineIMAP 7.1.5 -- if I try to kill a stalled process with <kbd>ctrl</kbd><kbd>c</kbd> it just hangs indefinititely: 

    ^CTerminating NOW (this may take a few seconds)...

I recently learned ([via issue 537 ](https://github.com/OfflineIMAP/offlineimap/issues/537) that pressing  <kbd>ctrl</kbd><kbd>c</kbd> three times will actually force a hard kill. But there's no outward clue that that will work, though it does: 

    ^CTerminating NOW (this may take a few seconds)...
    ^CTerminating NOW (this may take a few seconds)...
    ^CTerminating NOW (this may take a few seconds)...
    Signaled thrice. Aborting!

The text in that `Terminating NOW` message should / could make it more clear that if it doesn't terminate within two or three minutes, a user could try hitting <kbd>ctrl</kbd><kbd>c</kbd> two more times

**Comment by chris001** [comment]
Yes, this is a good idea.  That one message should be updated to clearly say if it doesn't terminate to press `ctrl c` two more times.

**Comment by nicolas33** [comment]
Fixed.
