### ISSUE TITLE
Documentation of UID validity problems is confusing

### ISSUE THREAD

**Issue by amandabee** [OfflineIMAP/offlineimap#542]
In the section of the documentation that addresses UID validity problems (<http://www.offlineimap.org/doc/FAQ.html#what-is-the-uid-validity-problem-for-folder>) there are instructions for addressing UID validity problems by clearing the cache. Those instructions are followed by a note:

> If you’re using the plain text backend, change the above LocalStatus-sqlite to LocalStatus.   Of course, replace AccountName and RemoteRepositoryName with the names as specified in ~/.offlineimaprc.   The reason is that moving it like this means like “I’ve never synced this folder before, do a full sync the next time”.

However `LocalStatus` doesn't appear anywhere else on the entire page, and it certainly doesn't appear in the directions preceding that note. So either the instructions are incomplete or the note is inaccurate.

**Comment by nicolas33** [comment]
Fixed. Thank you.
