### ISSUE TITLE
Offlineimap hangs on first sync action after upgrading from 6.7.0 to 7.1.5

### ISSUE THREAD

**Issue by nickurak** [OfflineIMAP/offlineimap#546]
#### General informations

- system/distribution (with version): Fedora 28 (regression on upgrade from Fedora 27)
- offlineimap version (`offlineimap -V`): 7.1.5 (regression on upgrade from 6.7.0)
- Python version: 2.7.14
- server name or domain: (private corporate server -- exchange)
- CLI options: none

#### Configuration file offlineimaprc

```
[general]
accounts = MyCorp
pythonfile = ~/notes/keyring-util.py
socktimemout=30

[Account MyCorp]
localrepository = LocalMyCorp
remoterepository = MyCorpExchange
autorefresh = 2

[Repository LocalMyCorp]
type = Maildir
localfolders = ~/MyCorpMail

[Repository MyCorpExchange]
type = IMAP
remotehost = outlook.<myemployer>.com
remoteuser = nickuj
remotepass = get_password("<mycorp>", "nickuj")
folderfilter = lambda foldername: foldername in ['INBOX', 'INBOX/Announcements', 'INBOX/Forums', 'INBOX/VPSplitter', 'INBOX/sent', 'Sent Items', 'INBOX/GreaseMonkeys']
ssl=yes
maxconnections = 1
holdconnectionopen = yes
keepalive = 60
cert_fingerprint = 4928945d3b776f08f6749cf9e9488220a3e8048e
cert_fingerprint = f30acac2d985c7a17fe4dee254418eddab0a7ba2
```

#### pythonfile (if any)

```
#!/usr/bin/python

import keyring
import sys
import getpass

def get_password(service, user):
    pw = keyring.get_password(service, user)
    assert pw is not None
    return keyring.get_password(service, user)

def set_password(service, user, password):
    keyring.set_password(service, user, password)

if __name__ == "__main__":
    if len(sys.argv) > 1:
        if sys.argv[1] == "p":
            print get_password(sys.argv[2], sys.argv[3])
        elif sys.argv[1] == "sc":
            set_password(sys.argv[2], sys.argv[3], sys.argv[4])
        else:
            print "error, unknown command %s" % sys.argv[1]
            sys.exit(1)
```

#### Logs, error

```
OfflineIMAP 7.1.5
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.14, OpenSSL 1.1.0h-fips  27 Mar 2018
Account sync MyCorp:
 *** Processing account MyCorp
 Establishing connection to outlook.<myemployer>.com:993 (MyCorpExchange)
 GSSAPI authentication failed: The AUTH protocol exchange was canceled by the client.
Folder INBOX [acc: MyCorp]:
 Syncing INBOX: IMAP -> Maildir
<hangs here>

```

#### Steps to reproduce the error

- Upgrade from 6.7.0, where things are working correctly, to 7.15
- Run offlineimap, and observe the hang (above)
- Downgrade back to 6.7.0, observe things resume working, mail syncs appropriately, etc.

I just upgraded from Fedora 27 to 28, which bumped offlineimap from 6.7.0 up to 7.1.5, and now offlineimap appears to hang on "Syncing INBOX/Forums: IMAP -> Maildir". 

7.0.14 seems to have the same issue, but downgrading to 6.7.0 makes everything work again.

**Comment by nicolas33** [comment]
Could try offlineimap v7.2.0, please?

It's weird there's a GSSAPI authentication attempt in the logs but nothing about this in the conf. I guess you've removed the related lines and I wonder this issue is related to kerberos. Could you confirm you're using kerberos, please? If so, you'll need to install the gssapi Python module for v7.2.0 to work.

**Comment by nickurak** [comment]
Nope, not using Kerberos. I *believe* I have that error whether I'm on 6.7.0 where it's working, or on 7.1.x where I'm having problems.

**Comment by nicolas33** [comment]
> Nope, not using Kerberos. I believe I have that error whether I'm on 6.7.0 where it's working, or on 7.1.x where I'm having problems.

Weird.

Anyway, could you [git bisect](http://www.offlineimap.org/doc/git-bisect.html) this issue, please? (make sure to have this hang to mark as bad)

**Comment by nicolas33** [comment]
BTW, I don't understand why it tries to sync `INBOX/Forums` while it's in folderfilter.

**Comment by nickurak** [comment]
41e275e has the issue consistently, 41e275e^ consistently does not.

```
commit 41e275e9a288fa7a58c09f9f4951a4b184446d9f (refs/bisect/bad)
Author: Nicolas Sebrecht <nicolas.s-dev@laposte.net>
Date:   Sat Apr 9 21:06:38 2016 +0200

    make sqlite status cache the default
    
    Signed-off-by: Nicolas Sebrecht <nicolas.s-dev@laposte.net>

```

**Comment by nickurak** [comment]
I'm observing that while it's "hung" it is making changes in LocalStatus-sqlite.

I'm trying again with eatmydata -- on an 11gig mailbox, is there a guideline of minutes/hours/days for this operation, or a guess as to how large the sqlite files would end up?

Addendum: It's working now, it looks like this was just the initial sqlite sync being very slow, and once that was done with, it's back to a reasonable performance.

Maybe the better UX issue here would be "Long-running operations (like an initial sqlity sync) can happen without user feedback to indicate progress is ongoing"?

That said -- thanks for your pointers helping get this figured out.

**Comment by nicolas33** [comment]
Yes, we've changed of backend so offlineimap has to convert the cache data. We have this message currently:

```
   75             # If backend contains data, import it to folder.                                                                                                                                         
>> 76             if not folderbk.isnewfolder():                                                                                                                                                           
>> 77                 self.ui._msg("Migrating LocalStatus cache from %s to %s "                                                                                                                            
   78                     "status folder for %s:%s"%                                                                                                                                                       
   79                     (bk, self._backend, self.name, folder.name))
```

Thank you much for your feedback.

**Comment by nickurak** [comment]
Interesting -- the message "Migrating LocalStatus cache" hasn't shown up anywhere in my logs.

**Comment by nicolas33** [comment]
Are you sure about that? Notice this is displayed *only once* and won't be displayed again whether the job has ended or not.

**Comment by nickurak** [comment]
Maybe if it started on an earlier invocation, and I killed it, and it continued on the next several attempts (that I also aborted after giving up waiting for); would it have logged that message once on the first try and never again? Unfortunately my logs have wrapped now, but I didn't see any sign of it.
