### ISSUE TITLE
Messages synced across hosts causes duplicates

### ISSUE THREAD

**Issue by ieure** [OfflineIMAP/offlineimap#549]
#### General informations

- system/distribution (with version): Debian 9.4 "stretch"
- offlineimap version (`offlineimap -V`): `offlineimap v7.0.12, imaplib2 v2.55 (system), Python v2.7.13`
- Python version: 2.7.13
- server name or domain: Not sure what this means.  Fastmail?
- CLI options: `-a retrospectv`

#### Configuration file offlineimaprc

```
[general]
ui = quiet
accounts = retrospectv
pythonfile = ~/dotfiles/offlineimap.py

[Account retrospectv]
localrepository = retrospectv-local
remoterepository = retrospectv-remote

[Repository retrospectv-local]
type = Maildir
localfolders = ~/Mail/retrospectv

[Repository retrospectv-remote]
type = IMAP
remotehost = imap.fastmail.com
remoteport = 993
ssl = yes
starttls = no
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
remoteuser = my@email.addr
remotepasseval = get_pass('fastmail.com/alpha')
realdelete = no
maxconnections = 3
idlefolders = ['INBOX']
holdconnectionopen = yes
```

#### pythonfile (if any)

```
from subprocess import check_output

def get_pass(account):
    return check_output("pass %s" % account, shell=True).splitlines()[0]
```

#### Steps to reproduce the error

1. Use OfflineIMAP to sync your email on host A.
2. Copy `~/Mail` (or whatever your local Maildir is), plus OfflineIMAP config to host B.
3. Run OfflineIMAP on host B.
4. Observe that host B's `~/Mail` has duplicate messages in it.

I'm using Syncthing to keep my `~/Mail` on multiple hosts, and was unhappy to see that I had a lot of duplicate files in there due to [the way OfflineIMAP generates mail filenames](https://github.com/OfflineIMAP/offlineimap/blob/01a744a/offlineimap/folder/Maildir.py#L290).  This includes multiple non-deterministic factors, such as system clock and hostname, though hostname seems to be the most troublesome.

I know [this format is mandated by the Maildir standard](http://cr.yp.to/proto/maildir.html), but it's very troublesome and I wish it weren't so.  Even more unfortunate is how Maildir uses a large number of small files.  Due to modern (large) block storage typically using a 4096 byte block size, each dupe will use at least that much, though the actual email is closer to 1-2kb.  After approximately a year of using OfflineIMAP across three machines on a brand new email account, I have 750mb of waste sitting in my `~/Mail`.

Do you have any suggestions for either making OfflineIMAP sufficiently configurable to avoid this, or an alternate setup which allows access to a local cache of my email across multiple machines?

**Comment by nicolas33** [comment]
1. About dups, please read https://github.com/OfflineIMAP/offlineimap/issues/543
2. About disk usage, you should configure your filesystem to use a smaller block size or change of filesystem.

**Comment by chris001** [comment]
Great idea @nicolas33 about the smaller block size or change filesystem to use disk space more efficiently.
* Is there any test that has been made to determine an ideal block size for an IMAP server or OfflineIMAP client app? 1KB? 512B? 2KB?
* What are the recommended linux, mac, bsd, filesystems which are more ideal for efficiently storing email message files on client and server? ZFS? ext4?
* Here's a thread about ZFS, it's very good for IMAP mail storage, and only uses available RAM memory that would otherwise be unused. https://www.dovecot.org/list/dovecot/2014-December/099157.html

**Comment by nicolas33** [comment]
The best filesystems for maildirs in Linux are those with great perf for small files with a lot of files. I don't know which ones are the best today. I use BTRFS and it's well good enough. Historically, email servers used to be on filesystems like ReiserFS because of speed.
