### ISSUE TITLE
How do I discard any local changes and take remote as source-of-truth?

### ISSUE THREAD

**Issue by ppwwyyxx** [OfflineIMAP/offlineimap#554]
#### General informations

- system/distribution (with version): archlinux latest
- offlineimap version (`offlineimap -V`): offlineimap v7.2.0, imaplib2 v2.57 (bundled), Python v2.7.15, OpenSSL 1.1.0h  27 Mar 2018
- Python version: 
- server name or domain: gmail

#### Configuration file offlineimaprc

```
[general]
ui = ttyui
accounts = personal
socktimeout = 10

[Account personal]
localrepository = GmailLocal
remoterepository = GmailRemote
autorefresh = 5
#quick = 10
quick = 0

[Repository GmailLocal]
type = GmailMaildir
localfolders = /Mail/Maildir

[Repository GmailRemote]
type = Gmail
ipv6 = False
ssl = yes
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
starttls = no
maxconnections = 1
readonly = true
remoteuser = 
createfolders = false
```

#### Steps to reproduce the error

I've been using "readonly=true" on remote for a long time, and now I want to switch to "readonly=false".

When "readonly=true" on remote, running `offlineimap -o` does not do any syncing. The two repo appear in sync.
After I switched to "readonly=false" and run `offlineimap --dry-run -o`, I saw things like:
```
Folder XXX [acc: personal]:
 Syncing XXX: Gmail -> GmailMaildir
 [DRYRUN] Copy 1 messages from XXX[GmailLocal] to GmailRemote
Folder YYY [acc: personal]:
 Syncing YYY: Gmail -> GmailMaildir
 [DRYRUN] Copy 38 messages from YYY[GmailLocal] to GmailRemote
 Deleting flag S from 1 messages on YYY
 Deleting flag R from 2 messages on YYY
```
So it seems like there are local changes that are different from remote. I don't know what those local changes are and wanted to discard them completely and take the remote as source of truth. What's the best way to do that?

**Comment by nicolas33** [comment]
Restore a backup : http://www.offlineimap.org/documentation.html#make-backups-of-a-mailbox
It's the only way to do this.

**Comment by ppwwyyxx** [comment]
Do you mean I have to make a fresh sync?

**Comment by nicolas33** [comment]
No. A new sync will update to the current state. "Discarding" changes as requested refers to "restoring a backup" to a previous state.

**Comment by ppwwyyxx** [comment]
Thanks for the explanation. But in this case I wanted to restore to the state of remote (i.e. discarding local changes and trust the current state of remote). 
And in order to "restore a backup" I'll need to first make a backup. And making a backup of remote means I need to make a fresh sync of remote.
Isn't this right?

**Comment by nicolas33** [comment]
> in order to "restore a backup" I'll need to first make a backup. And making a backup of remote means I need to make a fresh sync of remote.
> Isn't this right?

Yes, or restore from any previous existing backup.



> But in this case I wanted to restore to the state of remote (i.e. discarding local changes and trust the current state of remote).

A new sync updates the remote. If you want a two way sync discarding local changes there's no other way than removing the local cache and maildir to restart a sync from scratch.
