### ISSUE TITLE
Maildir cur, new, tmp for intermediate nested folders

### ISSUE THREAD

**Issue by mkamensky** [OfflineIMAP/offlineimap#561]
When the IMAP has nested folders, say Foo/{Bar,Baz}, syncing will create Foo/{new,cur,tmp} even if Foo is just a container for the two nested folders, and no mail is ever stored there. The result of this is that mutt (and possibly other programs) treats Foo as a mailbox, and ignores the nested folders within.

My suggestion: to create cur,tmp,new only when they are needed, i.e., when trying to save a message. If this is a bad idea, will be happy to get other suggestions how to solve this issue.

Thanks

**Comment by nicolas33** [comment]
As a syncer, we should apply the maildir format where applicable.

For the issue with mutt, you might like to check the [mbnames] configuration section. This feature was introduced exactly for such use case.

**Comment by mkamensky** [comment]
Thanks. The issue is not with detecting new mail, but with listing folders in the directory browser, as explained [here](https://gitlab.com/muttmua/mutt/wikis/MuttFaq/Maildir#2-custom-layout-of-separate-maildirs). As far as I understand, mbnames cannot help here.

**Comment by mkamensky** [comment]
I guess this is more reasonable to classify as an issue with mutt, but still, is it mandated by the Maildir spec that such intermediate folders have the new,cur,tmp structure, in addition to the nested folders?

**Comment by nicolas33** [comment]
> is it mandated by the Maildir spec that such intermediate folders have the new,cur,tmp structure, in addition to the nested folders?

This is more subtle. If it could be then we must apply.





> The issue is not with detecting new mail, but with listing folders in the directory browser, as explained here. As far as I understand, mbnames cannot help here.

I think you misunderstood mbnames or the "mailboxes" feature of mutt.

**Comment by mkamensky** [comment]
Seems to work, thanks and sorry for the noise
