### ISSUE TITLE
sync_deletes = no is not working

### ISSUE THREAD

**Issue by arunkumar4534** [OfflineIMAP/offlineimap#563]
Hiiii.I am new to offline imap.If i sync after deleting some mails in remote means, its automatically deleting in local folder also.I want to remove this option.Thanks in advance.
My conf file as below
---------------------------------------------------------------------------------------------------------------------------------
[general]
accounts = yukthi

[Account yukthi]
localrepository = yukthi-Local
remoterepository = yukthi-Remote

[Repository yukthi-Local]
type = Maildir
localfolders = /home/vmail/yukthi.com/yukthi
sync_deletes = no

[Repository yukthi-Remote]
type = IMAP
remotehost = imap.gmail.com
remoteuser = ************************
remotepass = ************
readonly = True
ssl = yes

-----------------------------------------------------------------------------------------------------------------------------

**Comment by nicolas33** [comment]
`sync_deletes = no` goes in the remote section.

**Comment by arunkumar4534** [comment]
@nicolas33 , there is no change happened after inserted `sync_deletes = no` in remote section

**Comment by nicolas33** [comment]
It's applicable for the next syncs. This won't resurrect already deleted emails.

**Comment by arunkumar4534** [comment]
No , it's not working for the next sync also.

**Comment by arunkumar4534** [comment]
Shall i need to change the files like `accounts.py` and `base.py`?

**Comment by arunkumar4534** [comment]
And i am getting these errors while i am trying to install new version?
```root@arun:~/offlineimap-7.2.1# ./offlineimap.py
Traceback (most recent call last):
  File "./offlineimap.py", line 22, in <module>
    from offlineimap import OfflineImap
  File "/root/offlineimap-7.2.1/offlineimap/__init__.py", line 20, in <module>
    from offlineimap.init import OfflineImap
  File "/root/offlineimap-7.2.1/offlineimap/init.py", line 34, in <module>
    from offlineimap import threadutil, accounts, folder, mbnames
  File "/root/offlineimap-7.2.1/offlineimap/accounts.py", line 23, in <module>
    import six
ImportError: No module named six
```

**Comment by nicolas33** [comment]
Installing offlineimap with root is rarely a good idea.
How did you install offlineimap? See http://www.offlineimap.org/doc/installation.html

**Comment by nicolas33** [comment]
Hmm, I realize our doc is obsolete. It's lacking the dependencies installation step...

**Comment by nicolas33** [comment]
Great. Thanks for your feedback.
