### ISSUE TITLE
offlineimap will only sync INBOX (offlineimap + mutt + own server with dovecot)

### ISSUE THREAD

**Issue by DickSteelOy** [OfflineIMAP/offlineimap#564]
#### General informations

- 4.17.4-1-MANJARO
- offlineimap v7.2.1
- Python v2.7.15
- server name or domain: dovecot
- CLI options: none

#### Configuration file offlineimaprc
```
[mbnames]
enabled = yes
filename = ~/.mutt/mailboxes
header = "mailboxes "
peritem = "+%(accountname)s/%(foldername)s"
sep = " "
footer = "\n"

[general]
accounts = Dick
maxsyncaccounts = 1

[Account Dick]
localrepository = Local
remoterepository = Remote
autorefresh = 0.5
quick = 10

[Repository Local]
type = Maildir
localfolders = ~/Mail/Dick/

[Repository Remote]
keepalive = 60
holdconnectionopen = yes
type = IMAP
remotehost = host
remoteuser = user
ssl = yes
sslcacertfile = we have
```

####  ./mutt/muttrc
```
# IMAP: offlineimap
set folder = "~/Mail"
source ~/.mutt/mailboxes
set spoolfile = "+Dick/INBOX"
set record = "+Dick/Sent"
set postponed = "+Dick/Drafts"
```
#### ./mutt/mailboxes
```
Mailboxes "+Dick/INBOX"
```

#### offlineimap --info

```
OfflineIMAP 7.2.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.15, OpenSSL 1.1.0h  27 Mar 2018
  imaplib2: 2.57 (bundled)
Remote repository 'Remote': type 'IMAP'
Host: adress Port: None SSL: True
Establishing connection to host
Server supports ID extension.
Server welcome string: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
Server capabilities: ('IMAP4REV1', 'LITERAL+', 'SASL-IR', 'LOGIN-REFERRALS', 'ID', 'ENABLE', 'IDLE', 'SORT', 'SORT=DISPLAY', 'THREAD=REFERENCES', 'THREAD=REFS', 'THREAD=ORDEREDSUBJECT', 'MULTIAPPEND', 'URL-PARTIAL', 'CATENATE', 'UNSELECT', 'CHILDREN', 'NAMESPACE', 'UIDPLUS', 'LIST-EXTENDED', 'I18NLEVEL=1', 'CONDSTORE', 'QRESYNC', 'ESEARCH', 'ESORT', 'SEARCHRES', 'WITHIN', 'CONTEXT=SEARCH', 'LIST-STATUS', 'BINARY', 'MOVE', 'SPECIAL-USE')

Folderlist:
 INBOX

Local repository 'Local': type 'Maildir'
Folderlist:
 INBOX

```

#### Why is only INBOX being synced when mutt will create Sent and Drafts?

I guess I am missing something very basic in the configuration. So if I delete all local files, offlineimap will only get INBOX from the server and add that to .mutt/mailboxes. If I manually add folders to .mutt/mailboxes, they will disappear from the file when offlineimap runs. If I add folders to my maildir, they do not get uploaded to remote.

**Comment by nicolas33** [comment]
> I guess I am missing something very basic in the configuration.

The configuration looks correct.



> So if I delete all local files, offlineimap will only get INBOX from the server and add that to .mutt/mailboxes.

Yes. Be care with deletions, though. It's better remove the whole maildir and the local cache (in 'metadatadir': ~/.offlineimap) to restart from scratch.

> If I manually add folders to .mutt/mailboxes, they will disappear from the file when offlineimap runs.

Correct. It's possible to manually add folders to the mbnames file but not directly in this file. You shall manually write a new "intermediate" json file manually in ~/.offlineimap/mbnames/. The intermediate files are created/updated here by offlineimap to produce the final mbnames file intended for mutt on each run.

> If I add folders to my maildir, they do not get uploaded to remote.

Unless you disable this feature, local folders are created and synced to the remote.

**Comment by nicolas33** [comment]
About deletions: 

1. "removing the files in the maildir" means the emails are removed so they are deleted on the remote.
2. "removing the maildir" (IOW, the directory of the folder) should mean "re-download". However, there are some edge cases where this won't work as expected and behave as per (1).
