### ISSUE TITLE
multiple sslcacertfile accross linux/osx

### ISSUE THREAD

**Issue by x4m3** [OfflineIMAP/offlineimap#568]
hi, i use offlineimap on osx and linux, and i keep the same configuration in git to make my life easier.

however, i have an issue with the ssl certfiles, osx uses one at `/usr/local/etc/openssl/cert.pem`, while linux uses one at `/etc/ssl/certs/ca-certificates.crt`.

i added both files to my offlineimaprc, on osx offlineimap works just fine, using the correct certfile, but on linux offlineimap tells me that it couldn't find the osx certfile ,but doesnt use the linux certfile (even if its before the osx certfile)!

if someone has a fix for this issue or a workaround, i would love to see it. thank you.

#### Configuration file offlineimaprc

```
ssl = true
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
sslcacertfile = /usr/local/etc/openssl/cert.pem
```

**Comment by nicolas33** [comment]
I'm afraid what you intend is not possible unless `OS-DEFAULT` can find the certificate for both systems (the values can be found in https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap/utils/distro.py#L14).

The usual workaround is to write a small script to generate the configuration files from a common skeleton.

**Comment by x4m3** [comment]
if i add the certfile path into https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap/utils/distro.py#L14 and make a pull request, would it be good for you ? 

for osx/darwin there is one already, but it is for macports, and i use openssl from homebrew, i think it would be useful for people who also use homebrew.

**Comment by nicolas33** [comment]
Sure, please do!

**Comment by chris001** [comment]
This might help:
https://stackoverflow.com/questions/26921605/detect-homebrew-vs-osx-python

**Comment by x4m3** [comment]
thank you @chris001 

while im at it, im going to make another pull request to add archlinux.

i'm going to make the osx pull request later, im not on the mac for now.

**Comment by nicolas33** [comment]
@x4m3 Both PR applied. Thank you!

**Comment by x4m3** [comment]
i'm happy to help! when can we see the next release? can't wait to try it and see the fixes !

Отправлено с iPhone

**Comment by nicolas33** [comment]
I can't say. We don't have a roadmap. If other @OfflineIMAP/offlineimap-contributors want one I'll release it.

**Comment by nicolas33** [comment]
Should we close this issue, now?

**Comment by x4m3** [comment]
yeah sure!

**Comment by x4m3** [comment]
hi @nicolas33, i tried to run offlineimap from the `next` branch with the patches that i sent, and i removed the `sslcacertfile` in my offlineimap config (since they are now in the https://github.com/OfflineIMAP/offlineimap/blob/next/offlineimap/utils/distro.py file), but i get the error `No CA certificates and no server fingerprints configured.  You must configure at least something, otherwise having SSL helps nothing.`. did i miss something ?

**Comment by nicolas33** [comment]
@x4m3 You're not supposed to remove the `sslcacertfile` configuration option.
Set `sslcacertfile = OS-DEFAULT` as explained here:
https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L748

**Comment by x4m3** [comment]
@nicolas33 ohhh thank you!! now it works on osx, but not on archlinux: i get the error `Default CA bundle was requested, but OfflineIMAP doesn't know any for your current operating system.` yet in `offlineimap/utils/distro.py` file the certfile is specified.

i modified the distro.py file to print the distro in `get_os_name()`, and when i run it, the function returns `linux-arch`, so the certfile path **and** the distro name is correct, what can be wrong ?

**Comment by nicolas33** [comment]
That's weird.

Do you have offlineimap installed twice?
No blank somewhere in the name?
The file exists? (file /etc/ssl/certs/ca-certificates.crt)

Finally, you might check in a debug session:
```
> python2
>>> import offlineimap.utils.distro as d
>>> d.get_os_sslcertfile()
'/etc/ssl/certs/ca-certificates.crt'
>>>
```

**Comment by x4m3** [comment]
@nicolas33 
* i have the latest offlineimap release (from the arch package), i tested off the git repo on the `next` branch (i dont think that counts as being installed)
* no, there's no blanks in the name, i checked.
* the file exists (i can `cat` the file)

i opened a debug session, ran the commands, but nothing showed
```
Python 2.7.15 (default, Jun 27 2018, 13:05:28) 
[GCC 8.1.1 20180531] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import offlineimap.utils.distro as d
>>> d.get_os_sslcertfile()
>>>
```

but something that is even weirder:
```
>>> import offlineimap.utils.distro as d
>>> d.get_os_name()
'linux'
>>>
```

but when i edited the python function in `distro.py` to print `OS` in the function `get_os_name()`, i got `linux-arch` ...

im sorry if it is confusing, because it doesnt make any sense to me...

**Comment by nicolas33** [comment]
> i have the latest offlineimap release (from the arch package), i tested off the git repo on the next branch (i dont think that counts as being installed)

This counts because of how python loads imports. Usually there's no issue but sometimes there are. You might need to remove the offlineimap version you don't test while hacking.

Then, try this so we can understand what's happening:
```
> python2
>>> import platform as p
>>> p.system()
>>> p.linux_distribution()
```

**Comment by x4m3** [comment]
i removed the offlineimap arch package, and here are the results:
```
╭─ ~/wk/offlineimap x4m3;x1-arch
╰─ $ python2                                                                                                                                                next * 01:43:55
Python 2.7.15 (default, Jun 27 2018, 13:05:28) 
[GCC 8.1.1 20180531] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform as p
>>> p.system()
'Linux'
>>> p.linux_distribution()
('', '', '')
>>> 
```

**Comment by nicolas33** [comment]
So, the latest call returns nothing. Do you have the [lsb-release](https://www.archlinux.org/packages/community/any/lsb-release/) package installed?

**Comment by x4m3** [comment]
i didnt have that package installed. i installed it, ran the same thing, but still nothing :/

```
╭─ ~/wk/offlineimap x4m3;x1-arch
╰─ $ python2                                                                                                                                                next * 12:23:38
Python 2.7.15 (default, Jun 27 2018, 13:05:28) 
[GCC 8.1.1 20180531] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform as p
>>> p.system()
'Linux'
>>> p.linux_distribution()
('', '', '')
>>> 
```

**Comment by x4m3** [comment]
oh okay i see, apparently that bug is fixed in python3.3, but python2 doesnt have it .... sucks

**Comment by nicolas33** [comment]
offlineimap won't be ported to py3 and there won't be a nice fix in the standard library for python2. Hence, I'm fine with a "dirty" hack to correctly detect archlinux as showed in the link. This is a small change and this can't be very offending for other use cases. Feel free!

**Comment by nicolas33** [comment]
@x4m3 Nice job! PR applied. Thank you much!

**Comment by x4m3** [comment]
no problems! happy to help, and happy to see that a new release will be soon! i'm getting tired of having to run offlineimap from the git repo haha :)
