### ISSUE TITLE
Invalid literal for int error - on latest version for Debian

### ISSUE THREAD

**Issue by shankargopal** [OfflineIMAP/offlineimap#576]
#### General informations

System/version: Linux debian 4.15.0-2-686-pae #1 SMP Debian 4.15.11-1 (2018-03-20) i686 GNU/Linux
Offlineimap -V: offlineimap v7.2.1, imaplib2 v2.57 (system), Python v2.7.15, OpenSSL 1.1.0h  27 Mar 2018
- server name or domain: Gmail
- CLI options: none

#### Configuration file offlineimaprc

[general]
metadata = /var/mail/offlineimap
accounts = Gmail-New
ui=blinkenlights

[Account Gmail-New]
localrepository = Gmail-Local
remoterepository = Gmail-Remote
autorefresh = 1
quick = 10

[Repository Gmail-Local]
type = IMAP
remotehost = 127.0.0.1
remoteuser = xxx
remotepass = xxx
auth_mechanisms = PLAIN
ssl = no
starttls = no

[Repository Gmail-Remote]
type = Gmail
remoteuser = xxx
remotepass = xxx
folderfilter = lambda foldername: foldername in ['INBOX','[Gmail]/Spam', '[Gmail]/Trash','sgscript']
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
maxconnections = 3
auth_mechanisms = LOGIN

#### Logs, error

*** Processing account Gmail-New
Establishing connection to imap.gmail.com:993 (Gmail-Remote)
Establishing connection to 127.0.0.1:143 (Gmail-Local)
ERROR: While attempting to sync account 'Gmail-New'
  invalid literal for int() with base 10: "34142\xdc'R"
*** Finished account 'Gmail-New' in 0:14
Next sync in 1:00

#### Steps to reproduce the error

Run offlineimap

Thank you for all your hard work!
This simply started happening one day.  No intervention that I know of beforehand - it just started.

**Comment by nicolas33** [comment]
This email has a character we can't handle. I would manually check this email. You should have the UID of the email in the logs. You might like to [ignore the sync for this UID](https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L1376).

To know more about this email you need to try a [manual session](http://www.offlineimap.org/server/imap/error/2016/01/27/error-no-such-number.html).

**Comment by shankargopal** [comment]
Thank you! However, I cannot locate any UID in the logs, and insofar as I
can understand them the error is occurring prior to any fetch.  This is an
excerpt from the logs with the `-d ALL` option on the command line:

2018-09-17 08:20:13 INFO: OfflineImap 7.2.1 starting...
  Python: 2.7.15 Platform: linux2
  Args: /usr/bin/offlineimap -l /tmp/oimap.log -d ALL
2018-09-17 08:20:13 INFO: OfflineIMAP 7.2.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL
exception)
2018-09-17 08:20:13 INFO: imaplib2 v2.57 (system), Python v2.7.15, OpenSSL
1.1.0h  27 Mar 2018
2018-09-17 08:20:13 DEBUG: Now debugging for imap: IMAP protocol debugging
2018-09-17 08:20:13 DEBUG: Now debugging for maildir: Maildir repository
debugging
2018-09-17 08:20:13 DEBUG: Now debugging for thread: Threading debugging
2018-09-17 08:20:13 DEBUG: Now debugging for : Other offlineimap related
sync messages
2018-09-17 08:20:13 DEBUG: [thread]: Register new thread 'Account sync
Gmail-New' (account 'Gmail-New')
2018-09-17 08:20:13 DEBUG: [imap]: Using authentication mechanisms ['LOGIN']
2018-09-17 08:20:13 DEBUG: [imap]: Using authentication mechanisms ['PLAIN']
2018-09-17 08:20:13 INFO: *** Processing account Gmail-New
2018-09-17 08:20:13 INFO: Establishing connection to imap.gmail.com:993
(Gmail-Remote)
2018-09-17 08:20:13 DEBUG: [imap]: Gmail-Remote: level 'tls_compat',
version 'None'
2018-09-17 08:20:15 DEBUG: [imap]: Attempting LOGIN authentication
2018-09-17 08:20:15 DEBUG: [imap]: Attempting IMAP LOGIN authentication
2018-09-17 08:20:17 DEBUG: []: Filtering out 'Archive'[Gmail-Remote] due to
folderfilter
2018-09-17 08:20:17 INFO: Establishing connection to 127.0.0.1:143
(Gmail-Local)
2018-09-17 08:20:17 DEBUG: [imap]: Attempting PLAIN authentication
2018-09-17 08:20:18 ERROR: ERROR: While attempting to sync account
'Gmail-New'
  str,attr
2018-09-17 08:20:18 ERROR: ['  File
"/usr/share/offlineimap/offlineimap/accounts.py", line 283, in
syncrunner\n    self.__sync()\n', '  File
"/usr/share/offlineimap/offlineimap/accounts.py", line 360, in __sync\n
localrepos.getfolders()\n', '  File
"/usr/share/offlineimap/offlineimap/repository/IMAP.py", line 452, in
getfolders\n    imapobj = self.imapserver.acquireconnection()\n', '  File
"/usr/share/offlineimap/offlineimap/imapserver.py", line 561, in
acquireconnection\n    self.__authn_helper(imapobj)\n', '  File
"/usr/share/offlineimap/offlineimap/imapserver.py", line 425, in
__authn_helper\n    if func(imapobj):\n', '  File
"/usr/share/offlineimap/offlineimap/imapserver.py", line 351, in
__authn_plain\n    imapobj.authenticate(\'PLAIN\', self.__plainhandler)\n',
'  File "/usr/lib/python2.7/dist-packages/imaplib2.py", line 734, in
authenticate\n    typ, dat = self._simple_command(\'AUTHENTICATE\',
mechanism.upper())\n', '  File
"/usr/lib/python2.7/dist-packages/imaplib2.py", line 1740, in
_simple_command\n    return self._command_complete(self._command(name,
*args), kw)\n', '  File "/usr/lib/python2.7/dist-packages/imaplib2.py",
line 1466, in _command\n    literal = literator(data, rqb)\n', '  File
"/usr/lib/python2.7/dist-packages/imaplib2.py", line 2331, in process\n
ret = self.mech(self.decode(data))\n', '  File
"/usr/share/offlineimap/offlineimap/imapserver.py", line 212, in
__plainhandler\n    self.ui.debug(\'imap\', \'__plainhandler: returning
%s\'% logsafe_retval)\n', '  File
"/usr/share/offlineimap/offlineimap/ui/UIBase.py", line 223, in debug\n
self.logger.debug("[%s]: %s" % (debugtype, msg))\n', '  File
"/usr/lib/python2.7/logging/__init__.py", line 1162, in debug\n
self._log(DEBUG, msg, args, **kwargs)\n', '  File
"/usr/lib/python2.7/logging/__init__.py", line 1293, in _log\n
self.handle(record)\n', '  File "/usr/lib/python2.7/logging/__init__.py",
line 1303, in handle\n    self.callHandlers(record)\n', '  File
"/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers\n
hdlr.handle(record)\n', '  File "/usr/lib/python2.7/logging/__init__.py",
line 766, in handle\n    self.emit(record)\n', '  File
"/usr/share/offlineimap/offlineimap/ui/Curses.py", line 317, in emit\n
self.ui.logwin.addstr(log_str, color)\n']
2018-09-17 08:20:18 INFO: *** Finished account 'Gmail-New' in 0:05
2018-09-17 08:20:18 INFO: Next sync in 1:00
2018-09-17 08:20:33 WARNING: Preparing to shutdown after sync (this may
take some time), press CTRL-C three times to shutdown immediately

**Comment by nicolas33** [comment]
AFAICT offlineimap can't log the issue because of this unexpected encoding. It's hard to say where it's coming from but I guess this character could be in the configuration file.

**Comment by shankargopal** [comment]
Thanks.  The config file is copied in the first post.  The only parts that
have been removed are the passwords and some folder names, and both are
entirely alphabetical in English (not even any special characters).

Could there be corruption in the database?

I managed to get longer tracebacks for the error here.  Might these help?

Traceback:
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 283, in
syncrunner
    self.__sync()
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 360, in __sync
    localrepos.getfolders()
  File "/usr/share/offlineimap/offlineimap/repository/IMAP.py", line 484,
in getfolders
    self))
  File "/usr/share/offlineimap/offlineimap/folder/UIDMaps.py", line 47, in
__init__
    self.diskr2l, self.diskl2r = self._loadmaps()
  File "/usr/share/offlineimap/offlineimap/folder/UIDMaps.py", line 91, in
_loadmaps
    rem = int(str2)

ERROR: While attempting to sync account 'Gmail-New'
  invalid literal for int() with base 10: "34142\xdc'R"

Traceback:
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 283, in
syncrunner
    self.__sync()
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 360, in __sync
    localrepos.getfolders()
  File "/usr/share/offlineimap/offlineimap/repository/IMAP.py", line 484,
in getfolders
    self))
  File "/usr/share/offlineimap/offlineimap/folder/UIDMaps.py", line 47, in
__init__
    self.diskr2l, self.diskl2r = self._loadmaps()
  File "/usr/share/offlineimap/offlineimap/folder/UIDMaps.py", line 91, in
_loadmaps
    rem = int(str2)

**Comment by nicolas33** [comment]
This new log seems to indicate that the UID map file is broken for a foldername. This is a plain text file in the metadatadir. You can remove the offending line(s) if any (be aware this might create duplicates).

**Comment by shankargopal** [comment]
How would I identify which one is broken?

**Comment by shankargopal** [comment]
Sorry, found it.  The INBOX file in UIDMapping in Repository-Gmail-Local
has gibberish at the end - starting with the number 34142 (as in the error
message).  And removing that line appears to have fixed it (at least it's
syncing now)!  Thank you very much.

For reference the second log I sent you is the traceback I got when I
pressed "Ctrl-C" to end offlineimap after the error occurred.  This
traceback was not in the offlineimap logs.

**Comment by nicolas33** [comment]
> For reference the second log I sent you is the traceback I got when I pressed "Ctrl-C" to end offlineimap after the error occurred. This traceback was not in the offlineimap logs.

I didn't expect this. Thanks for the feedback!
Happy syncing!
