### ISSUE TITLE
Deleted folder gets "re-downloaded" although non-existent

### ISSUE THREAD

**Issue by mrossinek** [OfflineIMAP/offlineimap#580]
#### General informations

- system/distribution (with version): Arch Linux (4.18.16-arch1-1-ARCH)
- offlineimap version (`offlineimap -V`): v7.2.1
- Python version: for offlineimap: v2.7.15 (i.e. output inside offlineimap -V)
- server name or domain: uni related server
- CLI options: none

#### Configuration file offlineimaprc

```
[general]
accounts = uni
# load python code for get_pass method
pythonfile = ~/.offlineimap.py

[Account uni]
localrepository  = local
remoterepository = remote

[Repository local]
type = Maildir
localfolders = ~/.mail/uni

[Repository remote]
type             = IMAP
remotehost       = domain
remoteport       = 993
remoteuser       = username
remotepasseval   = get_pass("domain","user@domain")
auth_mechanism   = GSSAPI
starttls         = yes
ssl              = yes
cert_fingerprint = fingerprint
subscribedonly   = yes

# lets mutt read the Maildir correctly
[mbnames]
enabled  = yes
filename = ~/.config/neomutt/uni.mailboxes
header   = "mailboxes "
peritem  = "+%(accountname)s/%(foldername)s"
sep      = " "
footer   = "\n"
```

#### pythonfile (if any)

```
#! /usr/bin/env python2
from subprocess import check_output


def get_pass(hostdomain, username):
    return check_output("pass " + hostdomain + "/" + username, shell=True).splitlines()[0]
```

#### Logs, error

```
ERROR: Exceptions occurred during the run!
ERROR: Aborting sync, folder 'INBOX.Sonstiges.Vortraege' [acc: 'uni']
  Error SELECTing mailbox 'INBOX/Sonstiges/Vortraege', server reply:
('NO', ["INBOX/Sonstiges/Vortraege doesn't exist."])

Traceback:
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 632, in syncfolder
    check_uid_validity()
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 504, in check_uid_validity
    remotefolder.save_uidvalidity()
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 261, in save_uidvalidity
    newval = self.get_uidvalidity()
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/IMAP.py", line 142, in get_uidvalidity
    self.__selectro(imapobj)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/IMAP.py", line 89, in __selectro
    imapobj.select(self.getfullIMAPname(), force=force)
  File "/usr/lib/python2.7/site-packages/offlineimap/imaplibutil.py", line 70, in select
    raise OfflineImapError(errstr, severity)
```

#### Steps to reproduce the error

- sync using offlineimap and basic setup
- delete folder either on remote directly or using --delete-folder option
- delete local maildir folder of corresponding folder
- delete all related entries in cache directory
- even delete all entries regarding this specific folder in json file with mailbox names etc.
- sync again with offlineimap
-> it creates a local folder for the deleted folder and then complains of not being able to find it (obviously because it was deleted...)

My question is therefore: why does it even create a local version of this folder in the first place? I.e. where is it getting the information from regarding this folder?

**Comment by ardumont** [comment]
Hello,

I have the same annoyance on my box(es).

The setup is mostly similar (including [offlineimap's configuration](https://github.com/ardumont/dot-files/blob/master/.offlineimaprc)).

The distribution is debian:
```
$ dpkg -l offlineimap | grep offlineimap
ii  offlineimap    7.2.1+dfsg1-1 all          IMAP/Maildir synchronization and reader support
```

Finally after:
- checking ~/.offlineimap and see files with tag name that should no longer be there
- removed the ~/.offlineimap/ (i considered this folder a cache) [2]
- and sync back

Everything is now fine ;)
The noise is no longer coming back after a sync \m/

[2] I was a tad brutal and removed it entirely, maybe pinpointing the right files should be enough 

Cheers,

**Comment by mrossinek** [comment]
Thx for the tip!

I tried your procedure as well and also went as far as removing the whole caching folder (~/.offlinimap/) but to no avail..

I am starting to suspect that the option
```
subscribedonly = yes
```
is causing me the trouble but I don't understand how or why.
Where does offlineimap query the "subscription" status?
Because it might be the case that the actually removed folders are still set to subscribed as of now.
But I would rather not set this option to `no` because I believe this will start downloading all the archived folders as well (which is not what I want).
However, if this seems to be causing the trouble, I guess I could try disabling the option and adding a lambda function to filter all the folders I don't want to download (but I rather had this done automagically rather than setting up a filter like this manually for all my boxes).

Cheers

**Comment by mrossinek** [comment]
> It's a request to the remote.

Okay, that is what I thought.

It is really weird. I double checked everything (deleting local folder, validating correct removal of remote folder, removing all caching entries and any mentions of the folder).
I also went to talk to the IT administration to make sure that removing a folder from within the webmail client actually removes it properly and instantly (which is the case).
And I went ahead and set up the whole system for testing on a different computer and it still wanted to create the aforementioned deleted folder for a local copy..

I am at a loss here but do not think that this problem lies on the side of offlineimap but I guess this is rather a bug on the side of my uni which they are not willing to look into because its such a niche user group..

I will be closing this. Thanks anyway for your time!

**Comment by mrossinek** [comment]
Okay.. last but not least I figured it out. I will add this here in case anybody else ever happens to run into this or a similar problem:

The trouble is indeed caused by the setting `subscribedonly = yes`.
Somehow, the subscription status of a folder is not removed upon the removal of the folder itself (at least not in my case). Thus, when offlineimap queries the server for the list of subscribed folders, the apparently removed folder is still included, resulting in the above problem.
The way to resolve this problem is therefore to unsubscribe from the folders that were deleted.

This is probably straight forward in mail clients like Thunderbird, Outlook and the like, because you can right-click on a folder and unsubscribe from it.
If one does not use one of the above clients (or a similar one) like me, but uses (neo)mutt instead, the way to resolve the problem is as follows:

1. recreate the deleted folder on the server
2. connect to the imap server directly via mutt (i.e. not to the local mailboxes created by offlineimap)
  a. example config: https://gist.github.com/mrossinek/eb0224016a454e8aaab26bed9ee74c27
3. list mailboxes and change subscription status of the folder to be deleted to "unsubscribed"
4. now delete the folder on the server for real
5. finally sync offlineimap and be happy that it works :smile:

Hope this helps! Cheers

**Comment by nicolas33** [comment]
Thank you for the report. I guess the issue is the IMAP server which is exposing non-existent folders as subscribed.
