### ISSUE TITLE
"ctrl +c" hangs on "terminating NOW"

### ISSUE THREAD

**Issue by ildar** [OfflineIMAP/offlineimap#60]
The program doesn't react on signals. E.g. if I press Ctrl+C, it says:
> ^CTerminating NOW (this may take a few seconds)...

and goes on running. This happens during the FETCH phase.

**Comment by nicolas33** [comment]
We tend to have too much feedbacks about that. I wonder if it would make sense to bind the SIGTERM to SIGQUIT after a first catched signal of SIGTERM.

**Comment by nicolas33** [comment]
Agressive stop on several `ctrl+c` is now implemented. Expected for upcoming v6.7.0-rc2.
Not being able to gracefully abort is still a bug, though.

**Comment by dolohow** [comment]
I would close this issue.  If someone want gracefull support it should create another issue.  This one is solved by doing `ctr+c` three times.

**Comment by nicolas33** [comment]
@dolohow Feel free. Don't you have the rights to close issues and assign labels?

**Comment by dolohow** [comment]
No, I don't have.
