### ISSUE TITLE
Copying from gmail to another gmail hack

### ISSUE THREAD

**Issue by leolara** [OfflineIMAP/offlineimap#600]
I have been trying to copy from a gmail account to another gmail account. 

In line https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap/repository/__init__.py#L51

I added to the dictionary ```'Gmail': GmailRepository``` . Then I have an account with the local repository being one of the gmails.

It seems to work, is this ok? Can I cause harm? Why is this not implemented this way?

What is the correct way to copy from a gmail to another?

**Comment by leolara** [comment]
I am seeing this type of error:

```ERROR: IMAP backend cannot change a messages UID from 972 to 904```

**Comment by nicolas33** [comment]
> In line https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap/repository/__init__.py#L51
> 
> I added to the dictionary `'Gmail': GmailRepository` . Then I have an account with the local repository being one of the gmails.

Why did you do this?

**Comment by nicolas33** [comment]
> Why is this not implemented this way?

This is all about implementation design/details.

> What is the correct way to copy from a gmail to another?

Create one account with two repositories. If both are of _remote_ type, offlineimap does the necessary to handle this case (basically this enables the UIDMaps feature rather than trying to change UIDs).

**Comment by leolara** [comment]
Ok, what is the syntax for an account with two remotes? Is it documented?

I tried:

```
[Account tworemotes]
remoterepository = source
remoterepository = destination
```

and

```
[Account tworemotes]
remoterepository = source, destination
```

where both source and destination are well configured gmail repositories, and I got errors in both cases.

Thanks :-)

**Comment by leolara** [comment]
If I do 

```
[Account tworemotes]
remoterepository = source
localrepository = destination
```

I get an error, unless I do the change in the code I mentioned. Hence, I do not know how to have an account with two Gmail type repos. Please let me know how

**Comment by nicolas33** [comment]
```
[Account tworemotes]
remoterepository = nameForFirstRemote
localrepository = nameForSecondRemote
```

Whether a repo is actually local or remote depends on the `type` you define in the repository section, eg:
```
[Respository nameForFirstRemote]
type = Gmail
```
```
[Respository nameForSecondRemote]
type = IMAP
```

Basically, the Account section always expects one "local" and one "remote". We define the *real type* of each repo in the corresponding Respository section. You could think "remoterepository" as "firstrepository" and "localrepository" as "secondrepository". This might be a bit confusing but that's historical inheritance (offlineimap was initially thought to have one real local backend and one remote backend).

**Comment by nicolas33** [comment]
> I get an error, unless I do the change in the code I mentioned. Hence, I do not know how to have an account with two Gmail type repos. Please let me know how

Did you remove all the cache in the metadatadir?

**Comment by nicolas33** [comment]
Sorry, I didn't mention that the locarepository must be of IMAP type.

**Comment by leolara** [comment]
Yes, removing Maildir, if both remote and local are of Gmail type I get the following error:

```ERROR: 'Gmail' repository not supported for 'local' repositories.```

Unless I do the change I did.

According to you this work if I mark one of the Gmails as IMAP. Why?

More importantly: Don't I lose features like preserving the labels and stars if I change from Gmail type to IMAP type?

**Comment by nicolas33** [comment]
Gmail type was introduced to help the translation of labels into folders (IOW, fake the Google oddities into standard IMAP behaviour). The reversed translation (folders -> labels) is handled by Gmail.

Other Gmail specific settings have been added to Gmail later (e.g. helpers for OAUTH). You can still have a Gmail account defined as IMAP but you won't have the automatic helpers for this one. Why don't we support the Gmail type for the local side? I don't know. This would require some digging.

**Comment by leolara** [comment]
@nicolas33  So, then currently if I do not use OAUTH i get the same effect using IMAP instead of Gmail. I am using password auth, not oauth.

Will labels get preserved?

**Comment by nicolas33** [comment]
I think so while I don't remember I've had feedabcks on this use case.
