### ISSUE TITLE
[Question] Could offlineimap somehow co-exist with another synchronization program

### ISSUE THREAD

**Issue by D4N** [OfflineIMAP/offlineimap#601]
Hi, first and foremost thanks for offlineimap, I have been using it in conjunction with notmuch for the past years and it has served me very well.

Unfortunately due to some recent changes, I now need to synchronize my notmuch tags across multiple machines. The only tool that fit my needs is muchsync, which works very well, but is made for a slightly different use case: it also synchronizes the contents of Maildirs, not only notmuch tags.

Due to way I'd like my setup to work, I don't want a "central" machine and would like to use offlineimap on all my replicas, which creates a nasty problem: when I run muchsync, it drops files into the maildir, that offlineimap does not know about. Offlineimap then of course re-downloads those messages, since it did not sync those (and thus did not write them into the uuidvalidity database).

Now for my actual question: Could offlineimap somehow work in such a setup, i.e. when it is not the only tool that syncs the email into a Maildir? Is this even possible?

Thanks in advance for any pointers/replies,

Dan

**Comment by nicolas33** [comment]
> Now for my actual question: Could offlineimap somehow work in such a setup, i.e. when it is not the only tool that syncs the email into a Maildir? Is this even possible?

I'm afraid it's not possible. Offlineimap relies on its own database to keep track on what is synced and this is not shared across tools.

**Comment by nicolas33** [comment]
BTW, why do you need offlineimap where you're syncing the emails with another tool?

**Comment by D4N** [comment]
> I'm afraid it's not possible. Offlineimap relies on its own database to keep track on what is synced and this is not shared across tools.

I thought that this would be the case, so monkey patching offlineimap's database would be the only option, right? (Don't worry I am not crazy enough to try that).

> BTW, why do you need offlineimap where you're syncing the emails with another tool?

The major reason is that muchsync has been build for the use case where your email resides on a single server (that receives it e.g. via SMTP) and you replicate the Maildir + notmuch tags via muchsync to your clients. This however doesn't really reflect my environment: I have multiple email accounts residing on different servers, which are collected on my machine. But I don't want to have a single machine that is running and reachable 24/7, so that I can fetch the Maildir via muchsync. Ideally, I'd like each of my machines to fetch my email via offlineimap and sync the tags via muchsync, but muchsync doesn't support tag only syncing (that is by design and probably impossible) and breaks offlineimap's ability to sync without duplicating email. Hope this makes sense (that's a very notmuch specific problem).

Also, offlineimap has served me very well in the past and never destroyed email, so I really don't want to let it go for another tool that could cause problems (although I haven't heard of any, on the contrary). 

Anyway, thanks for your answers & your time!

**Comment by nicolas33** [comment]
> I thought that this would be the case, so monkey patching offlineimap's database would be the only option, right?

Sorry, there's nothing we/you could do in the code to fix this.

**Comment by D4N** [comment]
> Sorry, there's nothing we/you could do in the code to fix this.

No problem at all, this is really something far beyond the scope of offlineimap.
