### ISSUE TITLE
Get datetime of last refresh when using autorefresh

### ISSUE THREAD

**Issue by edi9999** [OfflineIMAP/offlineimap#603]
#### General informations

- system/distribution (with version): ubuntu 18.04
- offlineimap version (`offlineimap -V`):  7.2.3
- Python version: 2.7.15
- server name or domain: 
- CLI options: 

##### Feature Request

I would like to be able to add an indicator to my bar to know when the last synchronisation took place. For example, show something like (10 minutes ago). 

I use : 

```
autorefresh = 20
```

so that the email is automatically refetched every 20 minutes, but I would like to know if there is a way to know when the last refresh took place.

**Comment by nicolas33** [comment]
Related to #367

**Comment by edi9999** [comment]
It is a bit related, but in my case I would like to know when a refresh has finished, not only when there is new mail. But a notification system that is more "general" would indeed be what I need.

**Comment by nicolas33** [comment]
Sure.

BTW, you could do what you want with a post sync hook.

**Comment by edi9999** [comment]
Thanks for the suggestion, Indeed I have just achieved that with a post sync hook !

I'm closing this issue since it is a practical way to address my issue.
