### ISSUE TITLE
too much traffic

### ISSUE THREAD

**Issue by eschulte** [OfflineIMAP/offlineimap#61]
Running offline imap with `-d ALL` resulting in a log file of almost 1G in size.  In this file it looks like offlineimap recieves a reply line for *every* email in any of my inboxes.

     $ offlineimap -o -d ALL -a gmail 2>&1|grep -a "imap.gmail.com reader <"|wc -l
     97512

This seems excessive and would explain why offlineimap spins up my CPU so significantly and takes so long to run.  Does the IMAP protocol not provide a way to avoid this exhaustic re-pulling of entire mailboxes on every sync?  It looks like there may be a RECENT flag to the EXAMINE command which appears to be causing these huge responses from the server (see http://tools.ietf.org/html/rfc1730#page-16).

**Comment by nicolas33** [comment]
I guess there are 2 different issues, here. If I'm right, this issue should be splitted.

* The first is about excessive IMAP requests and still needs analysis and confirmation.
* The second is about using the RECENT flag.

For the latter I wonder if the requested feature would not go against the whole syncing logic implemented in OfflineIMAP which is based on UIDs only.

I'd like inputs from the other maintainers on this to know if it would worth the trouble.
@xnox , @konvpalto , @spaetz , @X-Ryl669 , what's your opinion?

**Comment by simplygood** [comment]
I was also wondering why offlineimap uses a lot of network traffic as well as CPU when compared to other imap clients. It will be really great if this can be changed.

**Comment by nicolas33** [comment]
The string pointed out is imaplib2 debug option. I don't think there's any excessive IMAP requests.
