### ISSUE TITLE
Generating mailboxes, but filter out Drafts/Spam/Bin

### ISSUE THREAD

**Issue by ZaxonXP** [OfflineIMAP/offlineimap#610]
#### General informations

- system/distribution (with version):  Debian GNU/Linux 9.8 (stretch)
- offlineimap version (`offlineimap -V`):  offlineimap v7.2.3, imaplib2 v2.57 (bundled), Python v2.7.13, OpenSSL 1.1.0j  20 Nov 2018
- Python version: Python 2.7.13
- server name or domain: n/a
- CLI options: n/a

#### Configuration file offlineimaprc

```
[mbnames]
enabled = yes
filename = ~/.mutt/mailboxes
header = "mailboxes \\ \n"
peritem = "+%(foldername)s"
sep = " \\ \n"
footer = "\n"

mbnames_folderfilter = lambda foldername: foldername not in ['[Gmail].Drafts', '[Gmail].Spam', '[Gmail].Bin']

incremental = no

[general]
accounts = GMail
maxsyncaccounts = 1
ui = basic

[Account GMail]
localrepository = Gmail-Local
remoterepository = Gmail-Remote

[Repository Gmail-Local]
type = Maildir
localfolders = ~/Mail/GMail/

[Repository Gmail-Remote]
type = Gmail
remotehost = imap.gmail.com
remoteuser = <edited_out>
remotepass = <edited_out>
maxconnections = 3

sslcacertfile = /etc/ssl/certs/ca-certificates.crt
```

#### Steps to reproduce the error
just run `offlineimap`

The problem is that the `~/.mutt/mailboxes` file also contains the following:
```
"+[Gmail].Bin" \ 
"+[Gmail].Drafts" \ 
"+[Gmail].Spam" \ 
```
How to do this correctly?

Kind regards,
Piotr

**Comment by nicolas33** [comment]
mbnames filters apply on the translated names. Check the translated names with `offlineimap --info`.

**Comment by ZaxonXP** [comment]
Indeed, the result is different when using `offlineimap --info`. Thank you for the help.
