### ISSUE TITLE
Gmail messages from "All mail" are not deleted. 

### ISSUE THREAD

**Issue by ZaxonXP** [OfflineIMAP/offlineimap#611]
#### General informations

- system/distribution (with version): Debian GNU/Linux 9.8 (stretch)
- offlineimap version (`offlineimap -V`): offlineimap v7.2.3, imaplib2 v2.57 (bundled), Python v2.7.13, OpenSSL 1.1.0j 20 Nov 2018
- Python version: Python 2.7.13
- server name or domain: n/a
- CLI options: n/a

#### Configuration file offlineimaprc

```
[mbnames]
enabled = yes
filename = ~/.mutt/mailboxes
header = "mailboxes \\ \n"
peritem = "+%(foldername)s"
sep = " \\ \n"
footer = "\n"

mbnames_folderfilter = lambda foldername: foldername not in ['[Gmail].Drafts', '[Gmail].Spam', '[Gmail].Bin']

incremental = no

[general]
accounts = GMail
maxsyncaccounts = 1
ui = basic

[Account GMail]
localrepository = Gmail-Local
remoterepository = Gmail-Remote

[Repository Gmail-Local]
type = Maildir
localfolders = ~/Mail/GMail/

[Repository Gmail-Remote]
type = Gmail
remotehost = imap.gmail.com
remoteuser = <edited_out>
remotepass = <edited_out>
maxconnections = 3

sslcacertfile = /etc/ssl/certs/ca-certificates.crt
```

#### pythonfile (if any)

```
n/a
```

#### Logs, error

```
n/a
```

#### Steps to reproduce the error
**Scenatio 1:**
1. In the GMail settings unselect "All mail" from IMAP visibility.
2. Have some emails in GMail INBOX.
3. Sync all the folders with `offlineimap -f INBOX,"[Gmail]/Bin","[Gmail]/Spam"`.
4. In the Mutt go to inbox, open new e-mail then delete it (`d`) and refresh the mailbox (`$`).
5. Go to the Bin mailbox and delete all the e-mails then refresh the mailbox.
6. Sync all the folders with `offlineimap -f INBOX,"[Gmail]/Bin","[Gmail]/Spam"`.
7. Open the GMail from the web app and go to the `All mail` folder.

Result: The new e-mail which was deleted from both INBOX and the Bin is not deleted from the `All Mail` folder.

**Scenario 2:**
1. In the GMail settings unselect "All mail" from IMAP visibility.
2. Have some emails in GMail INBOX.
3. Sync all the folders with `offlineimap -f INBOX,"[Gmail]/Bin","[Gmail]/Spam"`.
4. In the Mutt go to inbox, open new e-mail then delete it (`d`) and refresh the mailbox (`$`).
5. Sync all the folders with `offlineimap -f INBOX,"[Gmail]/Bin","[Gmail]/Spam"`.
6. Go to the Bin mailbox and delete all the e-mails then refresh the mailbox.
7. Sync all the folders with `offlineimap -f INBOX,"[Gmail]/Bin","[Gmail]/Spam"`.
8. Open the GMail from the web app and go to the `All mail` folder.

Result: In the GMail web app the `All mail` folder will not have the deleted e-mails. Also Bin is cleaned.

The problem in the scenario 1 is that the e-mails are still in the `All Mail` folder instead to be deleted as in the scenario 2.

Is any way possible to have these e-mails always deleted?

Kind regards,
Piotr

**Comment by nicolas33** [comment]
This is all Gmail specific and not standard IMAP, AFAIK. So, no I think it's not possible to achieve what you want.

The "All mail" Gmail folder can be quite surprinsing.
