### ISSUE TITLE
sync stuck on a specific UID ends with "Killed"

### ISSUE THREAD

**Issue by dliessi** [OfflineIMAP/offlineimap#614]
#### General informations

- system/distribution (with version): FreeBSD 11.0-ALPHA5 on Raspberry Pi
- offlineimap version (`offlineimap -V`): offlineimap v7.2.1, imaplib2 v2.57 (bundled), Python v2.7.11, OpenSSL 1.0.2h-freebsd  3 May 2016
- server name or domain: imap.gmail.com
- CLI options: -c /PATH/TO/offlineimaprc -1 -o -u basic -a ACCOUNT_NAME

#### Configuration file offlineimaprc

```
[DEFAULT]
gmailtrashfolder = [Gmail]/Cestino
auth_mechanisms = LOGIN
sslcacertfile = /etc/ssl/cert.pem
ssl = yes

[general]
accounts = ACCOUNT_NAME
socktimeout = 120
metadata = /PATH/TO/offlineimap-metadata

[Account ACCOUNT_NAME]
localrepository = ACCOUNT_NAME_Local
remoterepository = ACCOUNT_NAME_Gmail
synclabels = yes
labelsheader = X-Gmail-Labels

[Repository ACCOUNT_NAME_Local]
type = GmailMaildir
localfolders = /path/to/gmail.com/ACCOUNT_NAME

[Repository ACCOUNT_NAME_Gmail]
type = Gmail
remoteuser = ACCOUNT_NAME@gmail.com
remotepass = ACCOUNT_PASSWORD
trashfolder = %(gmailtrashfolder)s
readonly = True
createfolders = False
folderfilter = lambda folder: folder in ['[Gmail]/Tutti i messaggi', '[Gmail]/Cestino', '[Gmail]/Spam']
```

#### Logs, error

The following is the output of two subsequent runs of offlineimap.
The `Syncing [Gmail]/Tutti i messaggi: Gmail -> GmailMaildir` and `Collecting data from messages on [Gmail]/Tutti i messaggi` phases last a long time (in one of the runs they were respectively about 20 minutes and about 13 minutes long), but this is probably normal since I have many tens of thousands of messages.
Then it seems to get stuck, again for a long time (in one of the runs about 10 minutes), on the message with UID 296103.
There is no user intervention during the runs, so the `Killed` message is not due to pressing `ctrl-C` or sending a signal to the process.

```
# offlineimap -c /PATH/TO/offlineimaprc -1 -o -u basic -a ACCOUNT_NAME
OfflineIMAP 7.2.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.11, OpenSSL 1.0.2h-freebsd  3 May 2016
*** Processing account ACCOUNT_NAME
Establishing connection to imap.gmail.com:993 (ACCOUNT_NAME_Gmail)
Syncing [Gmail]/Cestino: Gmail -> GmailMaildir
Collecting data from messages on [Gmail]/Cestino
Copy message UID 53074 (1/1) ACCOUNT_NAME_Gmail:[Gmail]/Cestino -> ACCOUNT_NAME_Local:[Gmail].Cestino
Syncing [Gmail]/Spam: Gmail -> GmailMaildir
Collecting data from messages on [Gmail]/Spam
Syncing [Gmail]/Tutti i messaggi: Gmail -> GmailMaildir
Collecting data from messages on [Gmail]/Tutti i messaggi
Copy message UID 296103 (1/3285) ACCOUNT_NAME_Gmail:[Gmail]/Tutti i messaggi -> ACCOUNT_NAME_Local:[Gmail].Tutti i messaggi
Killed

# offlineimap -c /PATH/TO/offlineimaprc -1 -o -u basic -a ACCOUNT_NAME
OfflineIMAP 7.2.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.11, OpenSSL 1.0.2h-freebsd  3 May 2016
*** Processing account ACCOUNT_NAME
Establishing connection to imap.gmail.com:993 (ACCOUNT_NAME_Gmail)
Syncing [Gmail]/Cestino: Gmail -> GmailMaildir
Collecting data from messages on [Gmail]/Cestino
Syncing [Gmail]/Spam: Gmail -> GmailMaildir
Collecting data from messages on [Gmail]/Spam
Syncing [Gmail]/Tutti i messaggi: Gmail -> GmailMaildir
Collecting data from messages on [Gmail]/Tutti i messaggi
Copy message UID 296103 (1/3288) ACCOUNT_NAME_Gmail:[Gmail]/Tutti i messaggi -> ACCOUNT_NAME_Local:[Gmail].Tutti i messaggi
Killed
```

How can I determine which message corresponds to UID 296103 (to check if there anything strange with that specific message)?
Can I tell offlineimap to skip that UID?
Can I get more information on why it fails?

**Comment by nicolas33** [comment]
"Killed" is not a literal existing in our code. It looks like offlineimap is killed by something else. Perhaps the OOM Killer? How many RAM do you have?

> How can I determine which message corresponds to UID 296103 (to check if there anything strange with that specific message)?

This requires a manual search via IMAP: http://www.offlineimap.org/server/imap/error/2016/01/27/error-no-such-number.html

> Can I tell offlineimap to skip that UID?

Yes. http://www.offlineimap.org/configuration/2016/07/18/ignoring-UIDs.html

> Can I get more information on why it fails?

I would first try to understand where this "Killed" log message comes from and why offlineimap gets killed.

**Comment by dliessi** [comment]
> How many RAM do you have?

512 MB (Raspberry Pi 1 model B)

I monitored the RAM usage during a further run with the same command line: the last time I checked before the process was killed (less than 30 s before), the RAM usage was about 40 %.

> This requires a manual search via IMAP

I did it and I found out that the message has a big attachment (about 18 MB).
I excluded with `copy_ignore_eval` and ran again offlineimap, which completed without errors.

Then I commented out the `copy_ignore_eval` line and run again offlineimap adding also the `-q` option.
It failed with the following output:

```
# offlineimap -c /PATH/TO/offlineimaprc -1 -o -u basic -a ACCOUNT_NAME -q
OfflineIMAP 7.2.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.11, OpenSSL 1.0.2h-freebsd  3 May 2016
*** Processing account ACCOUNT_NAME
Establishing connection to imap.gmail.com:993 (ACCOUNT_NAME_Gmail)
Syncing [Gmail]/Cestino: Gmail -> GmailMaildir
Collecting data from messages on [Gmail]/Cestino
Copy message UID 53082 (1/1) ACCOUNT_NAME_Gmail:[Gmail]/Cestino -> ACCOUNT_NAME_Local:[Gmail].Cestino
Syncing [Gmail]/Spam: Gmail -> GmailMaildir
Skipping [Gmail]/Spam (not changed)
Syncing [Gmail]/Tutti i messaggi: Gmail -> GmailMaildir
ERROR: Aborting sync, folder '[Gmail].Tutti i messaggi' [acc: 'ACCOUNT_NAME']
  Server 'imap.gmail.com' closed connection, error on SELECT '[Gmail]/Tutti i messaggi'. Server said: connection closed
*** Finished account 'ACCOUNT_NAME' in 34:49
ERROR: Exceptions occurred during the run!
ERROR: Aborting sync, folder '[Gmail].Tutti i messaggi' [acc: 'ACCOUNT_NAME']
  Server 'imap.gmail.com' closed connection, error on SELECT '[Gmail]/Tutti i messaggi'. Server said: connection closed

Traceback:
  File "/usr/local/lib/python2.7/site-packages/offlineimap/accounts.py", line 632, in syncfolder
    check_uid_validity()
  File "/usr/local/lib/python2.7/site-packages/offlineimap/accounts.py", line 497, in check_uid_validity
    if not remotefolder.check_uidvalidity():
  File "/usr/local/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 227, in check_uidvalidity
    return self.get_saveduidvalidity() == self.get_uidvalidity()
  File "/usr/local/lib/python2.7/site-packages/offlineimap/folder/IMAP.py", line 142, in get_uidvalidity
    self.__selectro(imapobj)
  File "/usr/local/lib/python2.7/site-packages/offlineimap/folder/IMAP.py", line 89, in __selectro
    imapobj.select(self.getfullIMAPname(), force=force)
  File "/usr/local/lib/python2.7/site-packages/offlineimap/imaplibutil.py", line 64, in select
    exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/offlineimap/imaplibutil.py", line 53, in select
    result = super(UsefulIMAPMixIn, self).select(mailbox, readonly)
  File "/usr/local/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 1097, in select
    rqb = self._command(name, mailbox)
  File "/usr/local/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 1418, in _command
    raise self.abort('connection closed')
```

Any ideas?

> I would first try to understand where this "Killed" log message comes from and why offlineimap gets killed.

Where should I look?

**Comment by nicolas33** [comment]
> Any ideas?

I don't know why this failed. Is this reproducible?

**Comment by dliessi** [comment]
> Is this reproducible?

I tried again and got the same error.

**Comment by nicolas33** [comment]
It might be that the copy thread gets killed. How is RAM usage during the sync?

**Comment by dliessi** [comment]
> How is RAM usage during the sync?

Lowest amount of free RAM during the run is 195 MB, so it is not running out of RAM.

**Comment by nicolas33** [comment]
Do you still have the "Killed" issue?

**Comment by dliessi** [comment]
> Do you still have the "Killed" issue?

Yes: without `-q` I get the "Killed" message, with `-q` I get the error in https://github.com/OfflineIMAP/offlineimap/issues/614#issuecomment-487285075 (RAM usage is very similar in both).

**Comment by nicolas33** [comment]
If the RAM usage is low, is it possible that python makes illegal RAM access? Is there anything in the system logs?

**Comment by dliessi** [comment]
I find nothing in the log files. Is there anything specific I should check?

Do you want me to send you the offending message?

(It is ok for me to permanently exclude that message, or even just delete it, since I have already downloaded and backed up the attachment, but offlineimap shouldn't fail anyway, so I would like to keep investigating the issue.)

**Comment by nicolas33** [comment]
Yes, you can ignore offending UIDs:

http://www.offlineimap.org/configuration/2016/07/18/ignoring-UIDs.html

Yes, you may send me the offending email.

**Comment by dliessi** [comment]
> Yes, you may send me the offending email.

Just a double check: do you remember that it has an 18 MB attachment? Is it ok for you?
Shall I send it to the address listed in your GitHub profile?

**Comment by nicolas33** [comment]
> Just a double check: do you remember that it has an 18 MB attachment? Is it ok for you?
> Shall I send it to the address listed in your GitHub profile?

That's fine.

**Comment by nicolas33** [comment]
File downloaded. The email is malformed but it's because of the eml format (vs raw IMAP). I could upload it via offlineimap on one of my account (not Gmail, though).

If you want to dig into this more, you may send this offending email (to yourself) as attachement to a new email and see how it goes. This check will help to understand if the issue is related to the size or something else. However, if it's something else, it might be hard to get the root cause.

**Comment by dliessi** [comment]
Sorry for the huge delay.

> If you want to dig into this more, you may send this offending email (to yourself) as attachement to a new email and see how it goes. This check will help to understand if the issue is related to the size or something else. However, if it's something else, it might be hard to get the root cause.

Before sending you the eml file via wetransfer, I tried to send you the attachment of my original offending email: the outgoing message, which was saved in the sent messages, raised the same error as the original one in offlineimap.
Can we draw any conclusion from this or do you want me to send some other very big file to myself?

**Comment by nicolas33** [comment]
I don't need to dig into this more there are a lot of possible issues and this could take a lot of time to find the root cause. If it's ok on your side I think we can keep this issue closed.

**Comment by dliessi** [comment]
Ok. Given the possibility to exclude individual UIDs (which I did), I have no need to investigate the issue further, except to satisfy my curiosity. You can keep the issue closed. Thanks for your help!

**Comment by nicolas33** [comment]
Thank you for the feedback.

**Comment by dliessi** [comment]
This happened again with another message. It is again a message with a large attachment. Any ideas?

**Comment by chris001** [comment]
I suspect out of memory.  To prove or disprove this:
* Would you run the same sync, on a different machine, with multiple times as much as your RPi's 512MB RAM, for example on a PC computer in a VirtualBox virtual machine running linux (freebsd if that's your preferred distro) with 2GB RAM.  
* To rule out the OS, would you also run the sync in a virtualbox virtual machine running ubuntu 18.04 and 2GB RAM.

**Comment by dliessi** [comment]
The previous time I monitored the RAM usage and found that

> Lowest amount of free RAM during the run is 195 MB

(see comments above).

However I will do both tests, limiting the sync to the offending message(s) and a few succeeding messages.
