### ISSUE TITLE
offlineimap ignores ssl = none

### ISSUE THREAD

**Issue by alexwms** [OfflineIMAP/offlineimap#620]
#### General informations

- system/distribution (with version): macOS 10.14.2
- offlineimap version (`offlineimap -V`): 7.2.3, installed with brew
- Python version: 2.7.6, anaconda
- server name or domain: protonmail bridge, 127.0.0.1:1143
- CLI options: none

#### Configuration file offlineimaprc

[general]
accounts = main

[Account main]
localrepository = main-local
remoterepository = main-remote
autorefresh = 0.2
quick = 10
postsynchook = notmuch new

[Repository main-local]
type = Maildir
localfolders = ~/.mail
sync_deletes = yes

[Repository main-remote]
type = IMAP
remoteport = 1143
remotehost = 127.0.0.1
remoteuser = <email>
remotepass = <password>
keepalive = 60
holdconnectionopen = yes
expunge = yes
folderfilter = lambda foldername: foldername in ['INBOX', 'Archive', 'Sent']
ssl = no

#### Logs, error
acBook-Air:~ alex$ offlineimap
OfflineIMAP 7.2.3
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.6, OpenSSL 0.9.7l 28 Sep 2006
Account sync main:
 *** Processing account main
 Establishing connection to 127.0.0.1:1143 (main-remote)
 ERROR: Could not connect via SSL to host '127.0.0.1' and non-standard ssl port 1143 configured. Make sure you connect to the correct port. Got: [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
 *** Finished account 'main' in 0:00
 Next refresh in 0.0 minutes
 *** Processing account main
 Establishing connection to 127.0.0.1:1143 (main-remote)
 ERROR: Could not connect via SSL to host '127.0.0.1' and non-standard ssl port 1143 configured. Make sure you connect to the correct port. Got: [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
 *** Finished account 'main' in 0:00
 Next refresh in 0.0 minutes
 *** Processing account main
 Establishing connection to 127.0.0.1:1143 (main-remote)
 ERROR: Could not connect via SSL to host '127.0.0.1' and non-standard ssl port 1143 configured. Make sure you connect to the correct port. Got: [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
 *** Finished account 'main' in 0:00
ERROR: Exceptions occurred during the run!
ERROR: Could not connect via SSL to host '127.0.0.1' and non-standard ssl port 1143 configured. Make sure you connect to the correct port. Got: [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

Traceback:
  File "/usr/local/Cellar/offlineimap/7.2.3/libexec/offlineimap/accounts.py", line 283, in syncrunner
    self.__sync()
  File "/usr/local/Cellar/offlineimap/7.2.3/libexec/offlineimap/accounts.py", line 359, in __sync
    remoterepos.getfolders()
  File "/usr/local/Cellar/offlineimap/7.2.3/libexec/offlineimap/repository/IMAP.py", line 452, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/usr/local/Cellar/offlineimap/7.2.3/libexec/offlineimap/imapserver.py", line 658, in acquireconnection
    exc_info()[2])
  File "/usr/local/Cellar/offlineimap/7.2.3/libexec/offlineimap/imapserver.py", line 586, in acquireconnection
    self.__authn_helper(imapobj)
  File "/usr/local/Cellar/offlineimap/7.2.3/libexec/offlineimap/imapserver.py", line 439, in __authn_helper
    self.__start_tls(imapobj)
  File "/usr/local/Cellar/offlineimap/7.2.3/libexec/offlineimap/imapserver.py", line 331, in __start_tls
    imapobj.starttls()
  File "/usr/local/Cellar/offlineimap/7.2.3/libexec/offlineimap/bundled_imaplib2.py", line 1198, in starttls
    self.ssl_wrap_socket()
  File "/usr/local/Cellar/offlineimap/7.2.3/libexec/offlineimap/bundled_imaplib2.py", line 548, in ssl_wrap_socket
    self.sock = ssl.wrap_socket(self.sock, self.keyfile, self.certfile, ca_certs=self.ca_certs, cert_reqs=cert_reqs, ssl_version=ssl_version)
  File "/Users/alex/anaconda/lib/python2.7/ssl.py", line 387, in wrap_socket
    ciphers=ciphers)
  File "/Users/alex/anaconda/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/Users/alex/anaconda/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()

#### Steps to reproduce the error
I am connecting to the server run by Protonmail Bridge on my laptop. The above error occurs after simply running the command `offlineimap`. I have specified `ssl = no` in the config, but for some reason offlineimap is still attempting to use SSL (see the logs).

**Comment by nicolas33** [comment]
The log is clear: it's starting with starttls. Try adding `starttls = no`. Make sure you won't change of remote without updating this option because no data will be encrypted.

**Comment by alexwms** [comment]
That did the trick. Thanks.
