### ISSUE TITLE
corrupt mail resulting from use of IDLE (IMAP->Maildir)

### ISSUE THREAD

**Issue by davebiffuk** [OfflineIMAP/offlineimap#63]
I've been happily using offlineimap 6.5.5 to do IMAP->Maildir for weeks. Just today, I configured it to do IDLE by adding:

idlefolders = ['INBOX']

The next run of offlineimap told me:

Account sync SangerZuul:
 *** Finished account 'SangerZuul' in 0:05
 Next refresh in 5.0 minutes
Thread-9:
 Syncing INBOX: IMAP -> Maildir
 Copy message 771539 (1 of 1) SangerZuul-remote:INBOX -> SangerZuul-local

And now mutt is showing me a message at the top of my inbox, apparently dated Jan 01, no subject, 0K size. This is what the message actually looks like in the Maildir:

````
9dh3@no:~/offlineimap/sanger.ac.uk/INBOX/new$ ls -l 
-rw-rw-r-- 1 dh3 dh3 1 Nov 13 14:25 1384352744_0.25906.no,U=771540,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,
dh3@no:~/offlineimap/sanger.ac.uk/INBOX/new$ cat 1384352744_0.25906.no,U=771540,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,
9dh3@no:~/offlineimap/sanger.ac.uk/INBOX/new$ 
````

(i.e. the file contains a single digit "9", not a properly-formatted message)

It looks like quite a coincidence that the thread number in the sync output is the same as the errant digit that's ended up in the message file.

I'll take a look but I've never examined the offlineimap source before, and I'm no IMAP expert...

Cheers,
Dave

**Comment by nicolas33** [comment]
Looks more like a RAM failure to me. Anyway, you might want to use another IMAP client to compare the results and see what happens with this offending mail.

I'm closing because it's old. If you want to dig into it, please re-open.
