### ISSUE TITLE
OpenSSL connection failure

### ISSUE THREAD

**Issue by jankara** [OfflineIMAP/offlineimap#631]
I'm using openSUSE Leap 15.0 with offlineimap version:

offlineimap v7.2.3, imaplib2 v2.57 (bundled), Python v2.7.14, OpenSSL 1.1.0i-fips  14 Aug 2018

I'm trying to connect to IMAP server jabberwock.ucw.cz. Openssl seems to be just fine connecting to it:

openssl s_client -CApath /etc/ssl/certs -connect jabberwock.ucw.cz:imaps -showcerts | perl -ne 'print if /BEGIN/../END/; print STDERR if /return/' >~/.jabberwock_cacert.pem

Stores certificates to  ~/.jabberwock_cacert.pem while outputting:

depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = www.ucw.cz
verify return:1
    Verify return code: 0 (ok)
DONE

So it seems SSL certificates are fine. Similarly, also mutt is trusting the certificate just fine when I'm using it to connect to that server directly. However offlineimap complains:

offlineimap -c ~/.offlineimaprc2 -d imap
OfflineIMAP 7.2.3
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.14, OpenSSL 1.1.0i-fips  14 Aug 2018
Debug mode: Forcing to singlethreaded.
Now debugging for imap: IMAP protocol debugging
Now debugging for : Other offlineimap related sync messages
Account sync UCW:
 [imap]: Using authentication mechanisms ['GSSAPI', 'XOAUTH2', 'CRAM-MD5', 'PLAIN', 'LOGIN']
 *** Processing account UCW
 Establishing connection to jabberwock.ucw.cz:993 (jabberwock)
 [imap]: jabberwock: level 'tls_compat', version 'tls1_2'
 ERROR: Unknown SSL protocol connecting to host 'jabberwock.ucw.cz' for repository 'jabberwock'. OpenSSL responded:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
 ['  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 283, in syncrunner\n    self.__sync()\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 359, in __sync\n    remoterepos.getfolders()\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/repository/IMAP.py", line 452, in getfolders\n    imapobj = self.imapserver.acquireconnection()\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 658, in acquireconnection\n    exc_info()[2])\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 572, in acquireconnection\n    af=self.af,\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/imaplibutil.py", line 194, in __init__\n    super(WrappedIMAP4_SSL, self).__init__(*args, **kwargs)\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 2182, in __init__\n    IMAP4.__init__(self, host, port, debug, debug_file, identifier, timeout, debug_buf_lvl)\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 360, in __init__\n    self.open(host, port)\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/imaplibutil.py", line 202, in open\n    super(WrappedIMAP4_SSL, self).open(host, port)\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 2195, in open\n    self.ssl_wrap_socket()\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 547, in ssl_wrap_socket\n    self.sock = ssl.wrap_socket(self.sock, self.keyfile, self.certfile, ca_certs=self.ca_certs, cert_reqs=cert_reqs, ssl_version=ssl_version)\n', '  File "/usr/lib64/python2.7/ssl.py", line 951, in wrap_socket\n    ciphers=ciphers)\n', '  File "/usr/lib64/python2.7/ssl.py", line 619, in __init__\n    self.do_handshake()\n', '  File "/usr/lib64/python2.7/ssl.py", line 848, in do_handshake\n    self._sslobj.do_handshake()\n']

My .offlineimaprc2 looks like:

[general]
accounts = UCW

[Account UCW]
localrepository = Local2
remoterepository = jabberwock
autorefresh = 2
quick = 10

[Repository Local2]
type = Maildir
localfolders = ~/MailUCW/

[Repository jabberwock]
type = IMAP
remotehost = jabberwock.ucw.cz
remoteuser = <my_user_name>
remotepassfile = ~/.jabberwockpass
ssl=yes
ssl_version = tls1_2
sslcacertfile = ~/.jabberwock_cacert.pem
maxconnections = 1
holdconnectionopen = no

I've added ssl_version=tls1_2 after seeing some similar issues being resolved by it but it didn't change anything for me.

Any idea what is wrong or how to debug this further?

**Comment by nicolas33** [comment]
I guess the server requires SNI. If so, you must upgrade to offlineimap v7.3.0.
