### ISSUE TITLE
"Killed" at big attachment download - not enough ram - fixed

### ISSUE THREAD

**Issue by andi-at-1** [OfflineIMAP/offlineimap#637]
Problem: Running out of memory (512mb virtual box)
Solution: Give the virtual box more RAM, 1GB and it syncs like a charm again!

#### General informations

- system/distribution (with version): 
Ubuntu 19.10
- offlineimap version (`offlineimap -V`): 
offlineimap v7.2.3, imaplib2 v2.57 (system), , OpenSSL 1.1.1c  28 May 2019
- Python version: Python v2.7.17rc1
- server name or domain: 
- CLI options: 

#### Configuration file offlineimaprc
[general]
metadata = ~/.offlineimap.IMAP
maxsyncaccounts = 1
ignore-readonly = no
# ui = Quiet

[Account mail]
localrepository=mail-local
remoterepository=mail-remote

[Repository mail-local]
type = IMAP
ssl=no
maxconnections = 1

[Repository mail-remote]
type=IMAP
ssl=yes
maxconnections = 1
folderfilter = lambda foldername: foldername not in ['Trash', 'Junk', 'Deleted Items']

#### Logs, error
Copy message UID 25 (2/30) xxx-remote:xxxx -> xxx-local:xxx
Killed

#### Steps to reproduce the error

Put a relative big File (30-70MB) on the remote Mail server
use a relative slow internet connection (i think a timeout happens)
try to sync that, it will abort after around 70-90sec the sync with no error message except "killed"

I think that´s a watchdog problem when the download lasts too long. After deleing the file from the mail server the sync continues without problems.

I´ve already tried to set socktimeout = 200 but did not help

Please fix that or point me to the file where the timeout happens, I know it´s not good practice to send that big files and i could use the file limit, but I want to have a consistent backup...

**Comment by chris001** [comment]
I suspect it's caused by either a timeout, or an out of RAM memory condition.  Because the code downloads attachments to a string in RAM, doesn't it??

**Comment by nicolas33** [comment]
"killed" means offlineimap was OOM killed, I think. Is this really happening for a 90MB attachement?
How is RAM comsumption for offlineimap during the sync?

**Comment by andi-at-1** [comment]
oh man that was a great tip! The error was thrown because we are running out of memory, I´m running the VM with just the default 512mb ram, 

During the start of the sync the used ram grows steady but slowly while indexing, at the start of the real sync of the message it grews up rapidly and got killed. 

Giving the VM 1gig of RAM solved the problem. Maby it would be nice to add some verification if there is enough ram before download. But I think if anyone else is running in that problem he now will find the solution here, sounds good enough to me.

Thanks!!

**Comment by nicolas33** [comment]
Glad we could help you!

**Comment by chris001** [comment]
Notes for improvement in terms of performance/memory usage: 
1. Download each full email message directly to disk as a file without using any RAM (instead of full email message to RAM).  
2. Access the raw headers by reading from the memory-mammed file to create strings/arrays, for processing/comparison...
