### ISSUE TITLE
IDLE working only once per sync

### ISSUE THREAD

**Issue by jonlauer** [OfflineIMAP/offlineimap#65]
With the idlefolders setting on, IDLE only retrieves one new message in between full syncs.  Subsequent messages are not retrieved by IDLE until the next full sync.

I'm using offlineimap 6.5.5 on arch linux, installed from the official repositories (https://www.archlinux.org/packages/community/any/offlineimap/) and connecting to a corporate exchange server.

EDIT: After toying around with the offlineimap sources, it appears that the issue lies in the acquireconnection() method of imapserver.py.  I am able to successfully receive multiple IDLE updates if I create the connection directly in the IdleThread class using offlineimap.imaplib2.IMAP4_SSL(servername) and logging in via imapobj.login(user, pass).  I'm going to take a bit more in depth look at the acquireconnection() code tomorrow.

**Comment by nicolas33** [comment]
Is this issue still valid with lastest stable (v6.6.1) and latest rc (v6.7.0-rc1)?

**Comment by jonlauer** [comment]
Let me check.  It’s been a while since I have looked at the code , but I recall this being a threading issue.  I’ll grab the release candidate and see if it’s still an issue.

Thanks for following up.

Jon Lauer

JMT Technology Group
"An Employee Owned Company"

Follow us on Twitter<http://twitter.com/JMTTG> & LinkedIn<http://www.linkedin.com/companies/880675/JMT+Technology+Group?trk=pro_other_cmpy>!
P Please consider the environment before printing this e-mail

**Comment by nicolas33** [comment]
@jonlauer Your mail client does horrible things when you reply:
* citations are missing `> `
* signature marker must be `-- ` (dash, dash, space)
As a consequence, nice formatting at github fails.

**Comment by jonlauer** [comment]
I apologize.  We're forced to use outlook here... not my first choice in email clients.

I'll keep in touch via github.com instead of using email.

To partially answer your question, this still appears to be an issue in 6.6.1.  I'll let you know the results of the release candidate.

**Comment by nicolas33** [comment]
What do you mean by "until the next full sync"?

**Comment by jonlauer** [comment]
Essentially, the full synchronization works great.  If I configure offlineimap to poll every ~5 minutes or so, it works as expected.

If I specify the configuration `idlefolders = ['INBOX']`, offlineimap continues to poll for new email, however if, for example, Microsoft Exchange receives an email delivered to me in between the full syncs, it is not retrieved by offlineimap until the next full sync.

**Comment by jonlauer** [comment]
It appears that the release candidate has the same issue.  I can do some further debugging and try to pinpoint the exact location of the issue.  Let me know if there's any information/configs/screenshots that i can provide that will help you troubleshoot this issue further.

**Comment by kainz** [comment]
This still occurs in v6.7.0.

**Comment by nicolas33** [comment]
Provide debug logs with IMAP enabled, please.

**Comment by nicolas33** [comment]
Closing because of no feedback.
