### ISSUE TITLE
with -a CLI option, mbnames must not erase the entries of other accounts

### ISSUE THREAD

**Issue by lahwaacz** [OfflineIMAP/offlineimap#66]
The current behaviour is that `mbnames` are constructed when an account is synchronized. When using the `-a` command line option to override the accounts from config file, `mbnames` are constructed only for the accounts specified on command line. It would be much more useful if the `-a` option caused that `mbnames` were constructed for all accounts from the config file.

Intended setup: I want to have [imapfilter](https://github.com/lefcha/imapfilter) running in an infinite loop, which would then run offlineimap only for specific account when a new mail is delivered. Currently it is needed to synchronize all accounts to have correct `mbnames`.

**Comment by nicolas33** [comment]
I'm not using mbnames myself but I agree that having this outside any account section or outside the general section is wrong.

Is it possible to workaround this issue by using the `sort_keyfunc`?

**Comment by nicolas33** [comment]
I don't get why mbnames would have to be constructed for accounts not being synced.

**Comment by lahwaacz** [comment]
Because mailbox names are __global__ file (as expected by e.g. mutt), so running offlineimap should always produce the same file, regardless of the configured and specified (with `-a`) accounts. I strongly recommend to reopen this bug.

**Comment by nicolas33** [comment]
Please, provide a sample of the current behaviour and what you would expect.

**Comment by lahwaacz** [comment]
offlineimap's config snippet:

```ini
[mbnames]
enabled = yes
filename = ~/mailboxes
header = "mailboxes "
peritem = "+%(accountname)s/%(foldername)s"
sep = " "
footer = "\n"

[Account foo]
...

[Account bar]
...
```

Testing current behaviour:

```
$ offlineimap -o -u quiet -a foo
$ cat ~/mailboxes 
mailboxes "+foo/INBOX" "+foo/drafts" "+foo/sent" "+foo/spam" "+foo/trash"
$ offlineimap -o -u quiet -a bar
$ cat ~/mailboxes 
mailboxes "+bar/INBOX" "+bar/drafts" "+bar/sent" "+bar/spam" "+bar/trash"
```

Expected result for both cases:

```
mailboxes "+bar/INBOX" "+bar/drafts" "+bar/sent" "+bar/spam" "+bar/trash" "+foo/INBOX" "+foo/drafts" "+foo/sent" "+foo/spam" "+foo/trash"
```

**Comment by nicolas33** [comment]
Why not run `offlineimap -o -u quiet`?

**Comment by nicolas33** [comment]
Actually, this would be wrong to make any wite for accounts not requested at CLI.

**Comment by lahwaacz** [comment]
> Why not run `offlineimap -o -u quiet`?

For the same reason why quick specificaton of accounts on the command-line exists in the first place - to focus on doing the most important task as fast as possible. Syncing all accounts at once might take a long time, while users might need to quickly sync one specific account, for example via hooks for currently open mailbox in mutt.

> Actually, this would be wrong to make any wite for accounts not requested at CLI.

I could understand a problem with not respecting the `accounts` list in the `[general]` section of the config, but I don't see a problem with taking all `accounts` from the config regardless of the CLI options. Please elaborate why this is such a big problem.

**Comment by nicolas33** [comment]
As soon as we would implement writes for accounts not requested at CLI, users will complain about unexpected directory creations.

I still don't get exactly why you need the creation of (empty) folders for maildirs you're not going to sync.

I wonder this use case is too much specific and does not worth the code complexity to be added for this edge-case feature.

Please, don't get me wrong. I'm not offending you and I'm not invalidating your use case. I'm pointing out that this specific use case is marginal enough and would introduce unexpected behaviour for most users to worth the change.

**Comment by lahwaacz** [comment]
The expected behaviour is not that all the directories would be created, but they would be written to the mailbox names file (set with the `filename` option in `[mbnames]`). It is the client's responsibility to handle non-existent directories in a sane way; in my use case all directories already exist due to previous sync of all the accounts.

**Comment by nicolas33** [comment]
Yes, sorry for not being clear. Writing mbnames to the filename for non-synced accounts is wrong because entries would be created for non-existing folders. `mbnames` is supposed to map to the local maildir of the synced folders.

We are NOT supposed to connect to a remote account if we are not requested to sync it.

> in my use case all directories already exist due to previous sync of all the accounts.

So, should be the mbnames entries.

**Comment by lahwaacz** [comment]
> `mbnames` is supposed to map to the local maildir of the synced folders.

I think this is where we'll disagree. From the clients' point of view, e.g. Mutt reading the mbnames file, it expects _all folders that currently exist locally_, even if they are not synced most recently. Now it's up to offlineimap to ensure that this expectation is fulfilled in all its operation.

> We are NOT supposed to connect to a remote account if we are not requested to sync it.

Now I can see why the implementation seems too complex to you. I agree that connecting to remote accounts that are not being synced is wrong, but you don't have to do that for this functionality. For example, the last-synced folders are already cached in the `Repository-<name>-local/FolderValidity/<folder name>` files. For accounts that are not being synced, this is a read-only operation.

**Comment by dolohow** [comment]
What about switch `--create-mbnames`?

And also I agree with @nicolas33, we should not create directories of other accounts when syncing only specific with `-a` switch.

**Comment by nicolas33** [comment]
> From the clients' point of view, e.g. Mutt reading the mbnames file, it expects all folders that currently exist locally, even if they are not synced most recently.

At the end of the sync, the mapping is updated. We can't write the mbnames **before** we know the local maildirs to create. We know this at sync time.

> the last-synced folders are already cached in the Repository-<name>-local/FolderValidity/<folder name> files. For accounts that are not being synced, this is a read-only operation.

I don't get why it is required to update the mbnames **after** the lastest sync since it was already updated **at the end** of the latest sync.

If it's only required to read the local cache, I think a little shell/lua/whatever script can easily do the job. Hence, I'm still not convince we should implement this in offlineimap. I'd be delighted that any user request us to add such a script in the `contrib/` directory of the official sources. Even if I don't get how it's usefull.

**Comment by nicolas33** [comment]
Hmm, I guess I'm getting your issue. Is offlineimap **erasing or clearing** the entries of the other accounts when used with `-a`?

**Comment by lahwaacz** [comment]
> Hmm, I guess I'm getting your issue. Is offlineimap **erasing or clearing** the entries of the other accounts when used with `-a`?

Yes! Exactly this. Please take a look at [this post](https://github.com/OfflineIMAP/offlineimap/issues/66#issuecomment-227464856) again, it's all there: after `offlineimap -o -u quiet -a foo` the mbnames file contains entries only for the `foo` account, regardless of the previous content, sync or anything. That means that you can't effectively use the `-a` option with different accounts along with the `[mbnames]` section enabled, because the writes to the mbnames file will overwrite each other.

When you've finally got it, can this issue be finally reopened to acknowledge it as a valid bug?

**Comment by nicolas33** [comment]
> Yes! Exactly this.

Ok, thanks for your insistence. I did not understood your point soon because I was focused on how the file is *constructed*. It's obvious that `-a` **must not** erase the entries of the other accounts. The solving is easy but we definetely won't connect to the other remotes.

So, mbnames should build intermediate mbnames in `<metadata>/mbnames` in a per-account basis. At the end of the sync of each account, the intermediate file is updated.

Then, the real target can be built by concatenation of all the intermediate mbnames. This operation is triggered at the end of the full sync if `incremental` option is disabled and at the end of the sync of each account otherwise.

We might want to add a `purge` option in the mbnames section to remove any intermediate file not in the `accounts` list.

**Comment by nicolas33** [comment]
@lahwaacz Could you test https://github.com/nicolas33/offlineimap/tree/ns/mbnames please?

**Comment by nicolas33** [comment]
I did some basic tests, here.

Notice you don't need to create folders to check updates are done right. Instead, you might want to check the date and content of the files in the cache (`<metadata>/mbnames`) and the content of your mbnames target file.

**Comment by lahwaacz** [comment]
I think that will fix the issue. Is there a specific reason to use yaml and require a 3rd party module instead of using e.g. [json](https://docs.python.org/2/library/json.html) from the standard library?

**Comment by dolohow** [comment]
> Is there a specific reason to use yaml and require a 3rd party module instead of using e.g. json from the standard library?

That is a good question.

**Comment by nicolas33** [comment]
>> Is there a specific reason to use yaml and require a 3rd party module instead of using e.g. json from the standard library?

> That is a good question.

I second that. I didn't know json was in the standard library. Will change that soon. Good catch!

**Comment by nicolas33** [comment]
https://github.com/nicolas33/offlineimap/tree/ns/mbnames-2

**Comment by nicolas33** [comment]
Fixed.
