### ISSUE TITLE
Save mail dir with specified ownership?

### ISSUE THREAD

**Issue by mikekgr** [OfflineIMAP/offlineimap#674]
#### General informations

- system/distribution (with version): Ubuntu server 20.04
- offlineimap version (`offlineimap -V`): offlineimap v7.2.3, imaplib2 v2.57 (system), Python v2.7.18rc1, OpenSSL 1.1.1f  31 Mar 2020

Dear Sirs,
Is there any supporting / suggesting way to set user:group ownership deferent that root user, in order to save the maildir in the local repository using these pre-specified? I don't want to have root ownership, even if I run the offlineIMAP as root, also I don't want to create separate user.
Thanks.

**Comment by chris001** [comment]
If you're trying to run as `root` user, yet, set user/group ownership of files that `OfflineIMAP` creates to a given user/group, then the user and group has to have been already created!

Why can't you just run `OfflineIMAP` from the user's account?  Then, `OfflineIMAP` will create all files as the correct user and group!

**Comment by mikekgr** [comment]
Ok understood. Also I got the tip to use su so that did the trick.
Many thanks for your answer.
