### ISSUE TITLE
How to use the collected budget 

### ISSUE THREAD

**Issue by nicolas33** [OfflineIMAP/offlineimap#679]
@chris001: I'm opening the discussion here because I think it's easier to discuss here for most people and contributors.

I think it's time to discuss how to use the collected money. The offlineimap project is currently on a good shape with @thekix working on the py3 version of offlineimap at https://github.com/OfflineIMAP/offlineimap3. That's the beginning but it's starting very well.

It is clear we always wanted this funds raising to give a kick to python3 for offlineimap. This is now happening and I'm delighted about this. My POV is the following:

1. We should actively support the current efforts.
2. We should promote "long time" contributions (for some months, at least).

So, I'm in favour to offer financial help to the active contributors of offlineimap3 every month with a rate which is still to be defined.
(BTW, I don't aim to get a penny.)

Comments are welcome.

**Comment by chris001** [comment]
@nicolas33 Sounds good.  Meritocracy + compensate Sebastian @spaetz for our project domain name since 2010 (10 years) x ($15/year) = $150.  https://whois.domaintools.com/offlineimap.org

**Comment by spaetz** [comment]
Thanks, I am flattered, but that is my donation offlineimap. So no need to compensate me.

**Comment by nicolas33** [comment]
Ok. Thank you very much Sebastian!

**Comment by chris001** [comment]
Thank you, Sebastian! 👍  😄 🤜 🤛 🤗

**Comment by nicolas33** [comment]
We've decided to retribute @thekix for his work on offlineimap3. The last steps to get this done is under way.
Thanks to all the contributors!
