### ISSUE TITLE
Location of local status db

### ISSUE THREAD

**Issue by mb720** [OfflineIMAP/offlineimap#683]
Hi and thanks a lot for OfflineIMAP!

I was wondering whether the location of the [local status databases](https://github.com/OfflineIMAP/offlineimap/blob/11313a9b9c684ee23d631db9fec1a615ec6bc76a/offlineimap/folder/LocalStatusSQLite.py#L220) can be changed. Currently, they are in `~/.offlineimap/`.

Is there an option to set the location to somewhere else or maybe make OfflineIMAP use `XDG_DATA_HOME` for it?

---

I'm using OfflineIMAP 7.3.3 on Arch Linux 5.9.2.

**Comment by nicolas33** [comment]
I think you're looking for [the metadata configuration option](https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L59).

**Comment by mb720** [comment]
Exactly what I needed, thanks!

I put this in my OfflineIMAP config:

    metadata = $XDG_DATA_HOME/offlineimap
