### ISSUE TITLE
Send a desktop notification when receiving new mail

### ISSUE THREAD

**Issue by deadbeef2000** [OfflineIMAP/offlineimap#689]
#### General informations

- system/distribution (with version): Arch Linux
- offlineimap version (`offlineimap -V`): 7.3.3
- Python version: 2.7.18
- server name or domain: -
- CLI options: -

I'd like to be able to get a desktop notification for new mails and I'd like to be able to customize that notification (e.g. the title of the notification being the subject of the mail and the body being the senders mail address)

**Comment by nicolas33** [comment]
See the postsynchook command: https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L317
