### ISSUE TITLE
remotepasseval broken with recent upgrade? 'a bytes-like object is required, not 'str''

### ISSUE THREAD

**Issue by nllz** [OfflineIMAP/offlineimap#697]
A recent upgrade to Ubuntu 21.04 from 20.04 seems to have broken my offineimap with GPG setup. Have tried trawling through old issues but could not determine the fix. All help appreciated.

PS Most likely a Python versioning thing, something which I run into a lot lately...

#### General informations
- system/distribution (with version): 
$ uname -a            
Linux kosmos 5.11.0-17-generic #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- offlineimap version (`offlineimap -V`): 
$ /usr/share/offlineimap3/run -V  
offlineimap v7.3.0, imaplib2 v3.05, Python v3.9.4, OpenSSL 1.1.1j  16 Feb 2021
- Python version: 
$ python -V
Python 3.8.5

- server name or domain: 
- CLI options: 

#### Configuration file offlineimaprc

```
# Path to file with arbitrary Python code to be loaded
pythonfile = ~/.offlineimap.py
# Decrypt and read the encrypted password
remotepasseval = get_passnielsddg()

```

#### pythonfile (if any)

```
#! /usr/bin/env python3
from subprocess import check_output

def get_passnielsddg():
    return check_output("gpg -dq ~/.secret/.passwdnielsddg.gpg", shell=True).strip("\n")
```

#### Logs, error

```
#### Steps to reproduce the error
$ /usr/share/offlineimap3/run
OfflineIMAP 7.3.0
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v3.05, Python v3.9.4, OpenSSL 1.1.1j  16 Feb 2021
Account sync nielsddg:
 *** Processing account nielsddg
 Establishing connection to ********* (nielsddg-remote)
 ERROR: While attempting to sync account 'nielsddg'
  a bytes-like object is required, not 'str'
 *** Finished account 'nielsddg' in 0:00
 a bytes-like object is required, not 'str' *** Processing account nielsddg
 Establishing connection to mail.greenhost.nl:993 (nielsddg-remote)
 ERROR: While attempting to sync account 'nielsddg'
  a bytes-like object is required, not 'str'
 *** Finished account 'nielsddg' in 0:00
```

**Comment by nllz** [comment]
Probably linked to [this issue](https://github.com/OfflineIMAP/offlineimap/issues/354) - but weirdly enough this occurs in offlineimap3, which should not happen because it is a python2 - 3 versioning issue.

**Comment by sebastianschauenburg** [comment]
Have the same issue here, but the offlineimap development apparently happens in offlineimap3 and [they also have a corresponding issue report](https://github.com/OfflineIMAP/offlineimap3/issues/57). I'd suggest following that one.

**Comment by nicolas33** [comment]
offlineimap won't support python3. Please, check offlineimap3 as mentioned.
