### ISSUE TITLE
Getting error in process filter ... No such file or directory.

### ISSUE THREAD

**Issue by simurgh9** [OfflineIMAP/offlineimap#700]
**Describe the issue**

Sometimes when I send mail in emacs using `mu4e`, I get these kinds of errors,

```
error in process filter: cond:
    Error 70: cannot read file /home/username/Maildir/Drafts/cur/1630476890.84dde0cb4899f5c6.smrgh:2,DS:
        No such file or directory
error in process filter:
    Error 70: cannot read file /home/username/Maildir/Drafts/cur/5310278690.84dde0cb4899f5c6.smrgh:2,DS:
        No such file or directory
```

The email still goes through. It is just annoying to see these, I get these especially when I take too long to type in an email. After it is sent, I see a draft of it saved even though the email was sent. 

Could it be due to the fact that I move the backups (of files being currently edited that) emacs makes to a directory somewhere else?

**Environment**

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
I initially posted this over at the [Mu's github](https://github.com/djcb/mu/issues/2011) but was told that it maybe an offlineimap issue. Offlineimap is at 7.2.3.

**Comment by nicolas33** [comment]
Weird. offlineimap has nothing to do about SMTP (email sending protocol). Do you have technical reasons/reports that it's related to offlineimap?

If any file/email is added to the local mailbox 'Drafts', syncing it with offlineimap should upload the file but never delete it locally.
Anyway, you might like to folderfilter the 'Drafts' folder.

**Comment by simurgh9** [comment]
Well, it is either offlineimap or Mu. Since I am not very well-versed in email internals, I took the Mu's maintainer's word,

> Yeah, that's offlneimap working behind mu4e's back; not so much mu4e can do about that, unfortunately.

Check the thread I linked at the end of the post.

> Anyway, you might like to folderfilter the 'Drafts' folder.

Yeah that is what I am doing right now.

**Comment by nicolas33** [comment]
Got it. That's likely offlineimap renaming the files while you're writing drafts. The only correct thing to do is to folderfilter the Drafts folder.

**Comment by simurgh9** [comment]
Thanks!
