### ISSUE TITLE
offlineimap error on Pop!_OS 21.04

### ISSUE THREAD

**Issue by T-Fen** [OfflineIMAP/offlineimap#703]
#### General information

- system/distribution (with version): Pop!_OS 21.04
- offlineimap version (`offlineimap -V`): 7.3.0
- Python version: python3 3.9.5
- server name or domain: 
- CLI options: 

#### Configuration file offlineimaprc

```
REMOVE PRIVATE DATA.
```

#### pythonfile (if any)

```
REMOVE PRIVATE DATA.
```

#### Logs, error

```
REMOVE PRIVATE DATA.
```

#### Steps to reproduce the error
Run offlineimap from the terminal and get the following error:
$ offlineimap 
OfflineIMAP 7.3.0
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v3.05, Python v3.9.5, OpenSSL 1.1.1j  16 Feb 2021
ERROR: No module named 'commands'
ERROR: Exceptions occurred during the run!
ERROR: No module named 'commands'
- 
-

**Comment by nicolas33** [comment]
offlineimap is not compatible with python 3. You should try https://github.com/OfflineIMAP/offlineimap3
