### ISSUE TITLE
Delete some emails from Gmail server with offlineimap.

### ISSUE THREAD

**Issue by hongyi-zhao** [OfflineIMAP/offlineimap#704]
At present, the space used in my Gmail mailbox is close to the quota, as shown below:

![image](https://user-images.githubusercontent.com/11155854/133437927-73a05daf-43cc-4860-b0ed-aff5ee33d8dd.png)

Therefore, I have to delete some emails to free up space, but I haven't found an efficient and reliable way to do this based on specific filtering conditions. I'm not sure if `offlineimap` can do this tedious job for me. Any tips would be greatly appreciated.

Regards,
HZ

**Comment by nicolas33** [comment]
Offlineimap can sync the emails from the server to a local imap directory and sync back changes.

So, this could help to filter your emails if you aim at filtering them locally.
