### ISSUE TITLE
Please take over the offlineimap.org domain

### ISSUE THREAD

**Issue by spaetz** [OfflineIMAP/offlineimap#713]
Hi, I have been keeping the stewardship of the offlineimap.org domain for a few years now. But as I am changing my hosting I will not be able to keep an .org domain as part of the package any longer. Please do take back the offlineimap.org domain, I would be happy to transfer it to somewhat who represents the offlineimap project or has been authorized by one of the maintainers.
I am sorry for putting the burden back to you.

**Comment by nicolas33** [comment]
@thekix : I'm sorry, I won't have time to handle this.

**Comment by spaetz** [comment]
The domain has been paid until 27.11.2023 now, so now urgent action is required. But it does cost me 15€/year now. If nothing happens until then the domain will expire. But again, happy to transfer the domain to anybody from the project.

**Comment by pabs3** [comment]
Perhaps the site should redirect to offlineimap.github.io, since that will exist after the domain is expired?

**Comment by nicolas33** [comment]
First of all, thank you very much for the domain offered to the community for all these years. Thank you.

With python2 dying, the offlineimap project is now forked to offlineimap3. The new offlineimap3 is maintained by new contributors. I don't have time anymore to actively contribute. AFAICT, there's no official maintained website for offlineimap3.

So, I think that's fine to free the domain name and fallback to the github.io alternative.

**Comment by spaetz** [comment]
Ok, thanks for letting me know.

**Comment by chris001** [comment]
I don't mind at all taking it over and redirect it to the io pages.
