### ISSUE TITLE
Why store the pid + hostname in the filename?

### ISSUE THREAD

**Issue by vHanda** [OfflineIMAP/offlineimap#716]
Hello.

I noticed that the pid and hostname is being stored in the filename - https://github.com/OfflineIMAP/offlineimap/blob/7531ac4640aff8477b0893c55c99c9fe4a9bbcfc/offlineimap/folder/Maildir.py#L294 . I went back through the git history and I could trace it back to 5b5e6d0ef8cbb9f397c4d9df204c1d1d13572609 from 20 years ago, sadly the commit message doesn't really explain.

Is there any particular reason they are needed?

I have backups of old email accounts, and the filenames' reflect the different hostnames I've chosen over the years, I'm not sure if it matters that my hostname is now again different.

**Comment by nicolas33** [comment]
I think there's no need for the hostname in the first place.

**Comment by vHanda** [comment]
@me-and Thank you for the wonderful explanation.

I'm closing this issue as I now understand.
