### ISSUE TITLE
offlineimap is not terminated properly 

### ISSUE THREAD

**Issue by liangguo** [OfflineIMAP/offlineimap#77]
Hi, 

I'm using offlineimap in Debian SID, after run offlineimap, all input will not be echoed, and the command output endline becomes fuzzy: this is a simple output:

  liang@guoliangc:/z/src/offlineimap/offlineimap(master) $ akonadi-liang.X20Cgy  gpg-LSpLDX        kde-liangYH651W  liang        offlineimap_6.5.5-0.1.diff.9cydkl  orbit-liang
                                         a.svg                 hsperfdata_liang  ksocket-kdm      mp.log       oi.log                             ssh-kppxVIMeUtcQ
                     fcitx-socket-:0       kde-kdm           ksocket-liang    offlineimap  ol.log
                                                                                                 liang@guoliangc:/z/src/offlineimap/offlineimap(master) $ 

After some dig, I found tty properties have been chaned, with a normal console, the stty shows:
speed 38400 baud; line = 0;
-brkint ixoff -imaxbel iutf8

with offlineimap runned console, the stty shows:
speed 38400 baud; line = 0;
                                        -brkint ixoff -imaxbel iutf8
                                                                    -onlcr
                                                                          -echo 
-onlcr and -echo are added.  

-onlcr and -echo is seted in init_banner() and should be removed in terminate(), but when exit normally, terminate() is not called. 

Thanks,

**Comment by nicolas33** [comment]
Should be fixed in next release.
