### ISSUE TITLE
Crashes, when IMAP folder already exists at destination

### ISSUE THREAD

**Issue by manuelRiel** [OfflineIMAP/offlineimap#79]
I was syncing some accounts with complex IMAP folders. After about 20 folders the script would crash with the error. "Folder already exists."

I only used one connection at a time. So no sync issues, I suggest. Expected behavior would be NOT to creat the folder and just accept that it already exists.

**Comment by nicolas33** [comment]
Please read this: http://offlineimap.org/doc/FAQ.html#i-get-a-mailbox-already-exists-error
