### ISSUE TITLE
Zoho Mail: Local repository isn't syncing properly with the remote

### ISSUE THREAD

**Issue by notfoss** [OfflineIMAP/offlineimap#93]
With Zoho Mail, when syncing local messages not present on the remote, the following message is generated.

`Can't parse FETCH response, can't find UID: %s`

The message(s) still get copied to the remote server, but the X-OfflineIMAP header isn't stripped off, and this breaks parsing of the message.

**Comment by nicolas33** [comment]
No response from OP. Feel free to re-open.

**Comment by notfoss** [comment]
Sorry for the late reply, I haven't been using offlineimap since some months. But sometime in the future I'll try to reproduce the problem and re-open the bug if required.

Thanks.
